/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* Includes */
#include "fsl_reset.h"
#include "fsl_device_registers.h"

/* Local Defines */

/* Local Types */

/* Local Functions */

/* Local Variables */

/* Global Variables */
/* TODO:  Individual resets not in current CRR */
rst_line_info_t const g_rstLineInfo[RST_NUM_LINE] =
{
    [RST_LINE_A55C0_NCPUPORESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_A55C0_NCPUPORESET].lineReg =
        &SRC_XSPR_CORTEXMIX_CORE0->IRST_REQ_CTRL,
    [RST_LINE_A55C0_NCPUPORESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_A55C0_NCPUPORESET].statReg =
            &SRC_XSPR_CORTEXMIX_CORE0->IRST_REQ_CTRL,
    [RST_LINE_A55C0_NCPUPORESET].assertLow = false,
    [RST_LINE_A55C0_NCPUPORESET].toggleUsec = 10U,

    [RST_LINE_A55C0_NCORERESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_A55C0_NCORERESET].lineReg =
        &SRC_XSPR_CORTEXMIX_CORE0->IRST_REQ_CTRL,
    [RST_LINE_A55C0_NCORERESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_A55C0_NCORERESET].statReg =
        &SRC_XSPR_CORTEXMIX_CORE0->IRST_REQ_CTRL,
    [RST_LINE_A55C0_NCORERESET].assertLow = false,
    [RST_LINE_A55C0_NCORERESET].toggleUsec = 10U,

    [RST_LINE_A55C1_NCPUPORESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_A55C1_NCPUPORESET].lineReg =
        &SRC_XSPR_CORTEXMIX_CORE1->IRST_REQ_CTRL,
    [RST_LINE_A55C1_NCPUPORESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_A55C1_NCPUPORESET].statReg =
        &SRC_XSPR_CORTEXMIX_CORE1->IRST_REQ_CTRL,
    [RST_LINE_A55C1_NCPUPORESET].assertLow = false,
    [RST_LINE_A55C1_NCPUPORESET].toggleUsec = 10U,

    [RST_LINE_A55C1_NCORERESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_A55C1_NCORERESET].lineReg =
        &SRC_XSPR_CORTEXMIX_CORE1->IRST_REQ_CTRL,
    [RST_LINE_A55C1_NCORERESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_A55C1_NCORERESET].statReg =
        &SRC_XSPR_CORTEXMIX_CORE1->IRST_REQ_CTRL,
    [RST_LINE_A55C1_NCORERESET].assertLow = false,
    [RST_LINE_A55C1_NCORERESET].toggleUsec = 10U,

    [RST_LINE_A55C2_NCPUPORESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_A55C2_NCPUPORESET].lineReg =
        &SRC_XSPR_CORTEXMIX_CORE2->IRST_REQ_CTRL,
    [RST_LINE_A55C2_NCPUPORESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_A55C2_NCPUPORESET].statReg =
        &SRC_XSPR_CORTEXMIX_CORE2->IRST_REQ_CTRL,
    [RST_LINE_A55C2_NCPUPORESET].assertLow = false,
    [RST_LINE_A55C2_NCPUPORESET].toggleUsec = 10U,

    [RST_LINE_A55C2_NCORERESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_A55C2_NCORERESET].lineReg =
        &SRC_XSPR_CORTEXMIX_CORE2->IRST_REQ_CTRL,
    [RST_LINE_A55C2_NCORERESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_A55C2_NCORERESET].statReg =
        &SRC_XSPR_CORTEXMIX_CORE2->IRST_REQ_CTRL,
    [RST_LINE_A55C2_NCORERESET].assertLow = false,
    [RST_LINE_A55C2_NCORERESET].toggleUsec = 10U,

    [RST_LINE_A55C3_NCPUPORESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_A55C3_NCPUPORESET].lineReg =
        &SRC_XSPR_CORTEXMIX_CORE3->IRST_REQ_CTRL,
    [RST_LINE_A55C3_NCPUPORESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_A55C3_NCPUPORESET].statReg =
        &SRC_XSPR_CORTEXMIX_CORE3->IRST_REQ_CTRL,
    [RST_LINE_A55C3_NCPUPORESET].assertLow = false,
    [RST_LINE_A55C3_NCPUPORESET].toggleUsec = 10U,

    [RST_LINE_A55C3_NCORERESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_A55C3_NCORERESET].lineReg =
        &SRC_XSPR_CORTEXMIX_CORE3->IRST_REQ_CTRL,
    [RST_LINE_A55C3_NCORERESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_A55C3_NCORERESET].statReg =
        &SRC_XSPR_CORTEXMIX_CORE3->IRST_REQ_CTRL,
    [RST_LINE_A55C3_NCORERESET].assertLow = false,
    [RST_LINE_A55C3_NCORERESET].toggleUsec = 10U,

    [RST_LINE_A55P_NPRESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_A55P_NPRESET].lineReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NPRESET].assertLow = false,
    [RST_LINE_A55P_NPRESET].toggleUsec = 10U,

    [RST_LINE_A55P_NSPORESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_A55P_NSPORESET].lineReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NSPORESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_A55P_NSPORESET].statReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NSPORESET].assertLow = false,
    [RST_LINE_A55P_NSPORESET].toggleUsec = 10U,

    [RST_LINE_A55P_NSRESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_2_MASK,
    [RST_LINE_A55P_NSRESET].lineReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NSRESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_2_MASK,
    [RST_LINE_A55P_NSRESET].statReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NSRESET].assertLow = false,
    [RST_LINE_A55P_NSRESET].toggleUsec = 10U,

    [RST_LINE_A55P_NATRESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_3_MASK,
    [RST_LINE_A55P_NATRESET].lineReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NATRESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_3_MASK,
    [RST_LINE_A55P_NATRESET].statReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NATRESET].assertLow = false,
    [RST_LINE_A55P_NATRESET].toggleUsec = 10U,

    [RST_LINE_A55P_NGICRESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_4_MASK,
    [RST_LINE_A55P_NGICRESET].lineReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NGICRESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_4_MASK,
    [RST_LINE_A55P_NGICRESET].statReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NGICRESET].assertLow = false,
    [RST_LINE_A55P_NGICRESET].toggleUsec = 10U,

    [RST_LINE_A55P_NPERIPHRESET].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_5_MASK,
    [RST_LINE_A55P_NPERIPHRESET].lineReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NPERIPHRESET].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_5_MASK,
    [RST_LINE_A55P_NPERIPHRESET].statReg =
        &SRC_XSPR_CORTEXMIX_PLATFORM->IRST_REQ_CTRL,
    [RST_LINE_A55P_NPERIPHRESET].assertLow = false,
    [RST_LINE_A55P_NPERIPHRESET].toggleUsec = 10U,

    [RST_LINE_DDRPHY_PRESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_DDRPHY_PRESETN].lineReg =
        &SRC_XSPR_DDRMIX->IRST_REQ_CTRL,
    [RST_LINE_DDRPHY_PRESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_DDRPHY_PRESETN].statReg =
        &SRC_XSPR_DDRMIX->IRST_REQ_CTRL,
    [RST_LINE_DDRPHY_PRESETN].assertLow = false,
    [RST_LINE_DDRPHY_PRESETN].toggleUsec = 10U,

    [RST_LINE_DDRPHY_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_DDRPHY_RESETN].lineReg =
        &SRC_XSPR_DDRMIX->IRST_REQ_CTRL,
    [RST_LINE_DDRPHY_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_DDRPHY_RESETN].statReg =
        &SRC_XSPR_DDRMIX->IRST_REQ_CTRL,
    [RST_LINE_DDRPHY_RESETN].assertLow = false,
    [RST_LINE_DDRPHY_RESETN].toggleUsec = 10U,

    [RST_LINE_DISP0_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_DISP0_RESETN].lineReg =
        &SRC_XSPR_DISPLAYMIX->IRST_REQ_CTRL,
    [RST_LINE_DISP0_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_DISP0_RESETN].statReg =
        &SRC_XSPR_DISPLAYMIX->IRST_REQ_CTRL,
    [RST_LINE_DISP0_RESETN].assertLow = false,
    [RST_LINE_DISP0_RESETN].toggleUsec = 10U,

    [RST_LINE_DISP1_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_DISP1_RESETN].lineReg =
        &SRC_XSPR_DISPLAYMIX->IRST_REQ_CTRL,
    [RST_LINE_DISP1_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_DISP1_RESETN].statReg =
        &SRC_XSPR_DISPLAYMIX->IRST_REQ_CTRL,
    [RST_LINE_DISP1_RESETN].assertLow = false,
    [RST_LINE_DISP1_RESETN].toggleUsec = 10U,
        
    [RST_LINE_LVDS_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_2_MASK,
    [RST_LINE_LVDS_RESETN].lineReg =
        &SRC_XSPR_DISPLAYMIX->IRST_REQ_CTRL,
    [RST_LINE_LVDS_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_2_MASK,
    [RST_LINE_LVDS_RESETN].statReg =
        &SRC_XSPR_DISPLAYMIX->IRST_REQ_CTRL,
    [RST_LINE_LVDS_RESETN].assertLow = false,
    [RST_LINE_LVDS_RESETN].toggleUsec = 10U,

    [RST_LINE_USB1PHY_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_USB1PHY_RESETN].lineReg =
        &SRC_XSPR_HSIOMIX_TOP->IRST_REQ_CTRL,
    [RST_LINE_USB1PHY_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_USB1PHY_RESETN].statReg =
        &SRC_XSPR_HSIOMIX_TOP->IRST_REQ_CTRL,
    [RST_LINE_USB1PHY_RESETN].assertLow = false,
    [RST_LINE_USB1PHY_RESETN].toggleUsec = 10U,

    [RST_LINE_USB2PHY_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_USB2PHY_RESETN].lineReg =
        &SRC_XSPR_HSIOMIX_TOP->IRST_REQ_CTRL,
    [RST_LINE_USB2PHY_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_USB2PHY_RESETN].statReg =
        &SRC_XSPR_HSIOMIX_TOP->IRST_REQ_CTRL,
    [RST_LINE_USB2PHY_RESETN].assertLow = false,
    [RST_LINE_USB2PHY_RESETN].toggleUsec = 10U,

    [RST_LINE_PCIE1PHY_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_2_MASK,
    [RST_LINE_PCIE1PHY_RESETN].lineReg =
        &SRC_XSPR_HSIOMIX_TOP->IRST_REQ_CTRL,
    [RST_LINE_PCIE1PHY_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_2_MASK,
    [RST_LINE_PCIE1PHY_RESETN].statReg =
        &SRC_XSPR_HSIOMIX_TOP->IRST_REQ_CTRL,
    [RST_LINE_PCIE1PHY_RESETN].assertLow = false,
    [RST_LINE_PCIE1PHY_RESETN].toggleUsec = 10U,

    [RST_LINE_PCIE2PHY_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_3_MASK,
    [RST_LINE_PCIE2PHY_RESETN].lineReg =
        &SRC_XSPR_HSIOMIX_TOP->IRST_REQ_CTRL,
    [RST_LINE_PCIE2PHY_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_3_MASK,
    [RST_LINE_PCIE2PHY_RESETN].statReg =
        &SRC_XSPR_HSIOMIX_TOP->IRST_REQ_CTRL,
    [RST_LINE_PCIE2PHY_RESETN].assertLow = false,
    [RST_LINE_PCIE2PHY_RESETN].toggleUsec = 10U,

    [RST_LINE_ENETPHY_PCS_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_ENETPHY_PCS_RESETN].lineReg =
        &SRC_XSPR_NETCMIX->IRST_REQ_CTRL,
    [RST_LINE_ENETPHY_PCS_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_ENETPHY_PCS_RESETN].statReg =
        &SRC_XSPR_NETCMIX->IRST_REQ_CTRL,
    [RST_LINE_ENETPHY_PCS_RESETN].assertLow = false,
    [RST_LINE_ENETPHY_PCS_RESETN].toggleUsec = 10U,

    [RST_LINE_ECAT_IP_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_ECAT_IP_RESETN].lineReg =
        &SRC_XSPR_NETCMIX->IRST_REQ_CTRL,
    [RST_LINE_ECAT_IP_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_ECAT_IP_RESETN].statReg =
        &SRC_XSPR_NETCMIX->IRST_REQ_CTRL,
    [RST_LINE_ECAT_IP_RESETN].assertLow = false,
    [RST_LINE_ECAT_IP_RESETN].toggleUsec = 10U,

    [RST_LINE_V2X_RESETB].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_V2X_RESETB].lineReg =
        &SRC_XSPR_WAKEUPMIX->IRST_REQ_CTRL,
    [RST_LINE_V2X_RESETB].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_0_MASK,
    [RST_LINE_V2X_RESETB].statReg =
        &SRC_XSPR_WAKEUPMIX->IRST_REQ_CTRL,
    [RST_LINE_V2X_RESETB].assertLow = false,
    [RST_LINE_V2X_RESETB].toggleUsec = 10U,

    [RST_LINE_BISS_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_BISS_RESETN].lineReg =
        &SRC_XSPR_WAKEUPMIX->IRST_REQ_CTRL,
    [RST_LINE_BISS_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_1_MASK,
    [RST_LINE_BISS_RESETN].statReg =
        &SRC_XSPR_WAKEUPMIX->IRST_REQ_CTRL,
    [RST_LINE_BISS_RESETN].assertLow = false,
    [RST_LINE_BISS_RESETN].toggleUsec = 10U,

    [RST_LINE_ENDAT3_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_2_MASK,
    [RST_LINE_ENDAT3_RESETN].lineReg =
        &SRC_XSPR_WAKEUPMIX->IRST_REQ_CTRL,
    [RST_LINE_ENDAT3_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_2_MASK,
    [RST_LINE_ENDAT3_RESETN].statReg =
        &SRC_XSPR_WAKEUPMIX->IRST_REQ_CTRL,
    [RST_LINE_ENDAT3_RESETN].assertLow = false,
    [RST_LINE_ENDAT3_RESETN].toggleUsec = 10U,

    [RST_LINE_ENDAT2_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_3_MASK,
    [RST_LINE_ENDAT2_RESETN].lineReg =
        &SRC_XSPR_WAKEUPMIX->IRST_REQ_CTRL,
    [RST_LINE_ENDAT2_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_3_MASK,
    [RST_LINE_ENDAT2_RESETN].statReg =
        &SRC_XSPR_WAKEUPMIX->IRST_REQ_CTRL,
    [RST_LINE_ENDAT2_RESETN].assertLow = false,
    [RST_LINE_ENDAT2_RESETN].toggleUsec = 10U,

    [RST_LINE_HIPERFACE_RESETN].lineMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_4_MASK,
    [RST_LINE_HIPERFACE_RESETN].lineReg =
        &SRC_XSPR_WAKEUPMIX->IRST_REQ_CTRL,
    [RST_LINE_HIPERFACE_RESETN].statMask =
        SRC_XSPR_IRST_REQ_CTRL_RSTR_0_IRST_4_MASK,
    [RST_LINE_HIPERFACE_RESETN].statReg =
        &SRC_XSPR_WAKEUPMIX->IRST_REQ_CTRL,
    [RST_LINE_HIPERFACE_RESETN].assertLow = false,
    [RST_LINE_HIPERFACE_RESETN].toggleUsec = 10U,

    /* RSTR */
    [RST_LINE_ANAMIX].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_ANAMIX].lineReg = &SRC_XSPR_ANAMIX->SLICE_SW_CTRL,
    [RST_LINE_ANAMIX].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_ANAMIX].statReg = &SRC_XSPR_ANAMIX->RSTR_STAT,
    [RST_LINE_ANAMIX].assertLow = false,
    [RST_LINE_ANAMIX].toggleUsec = 10U,

    [RST_LINE_AONMIX_TOP].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_AONMIX_TOP].lineReg = &SRC_XSPR_AONMIX->SLICE_SW_CTRL,
    [RST_LINE_AONMIX_TOP].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
        [RST_LINE_AONMIX_TOP].statReg = &SRC_XSPR_AONMIX->RSTR_STAT,
    [RST_LINE_AONMIX_TOP].assertLow = false,
    [RST_LINE_AONMIX_TOP].toggleUsec = 10U,

    [RST_LINE_AONMIX_M33].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_1_MASK,
    [RST_LINE_AONMIX_M33].lineReg = &SRC_XSPR_AONMIX->SLICE_SW_CTRL,
    [RST_LINE_AONMIX_M33].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_1_RST_STAT_MASK,
    [RST_LINE_AONMIX_M33].statReg = &SRC_XSPR_AONMIX->RSTR_STAT,
    [RST_LINE_AONMIX_M33].assertLow = false,
    [RST_LINE_AONMIX_M33].toggleUsec = 10U,

    [RST_LINE_AONMIX_ELE].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_2_MASK,
    [RST_LINE_AONMIX_ELE].lineReg = &SRC_XSPR_AONMIX->SLICE_SW_CTRL,
    [RST_LINE_AONMIX_ELE].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_2_RST_STAT_MASK,
    [RST_LINE_AONMIX_ELE].statReg = &SRC_XSPR_AONMIX->RSTR_STAT,
    [RST_LINE_AONMIX_ELE].assertLow = false,
    [RST_LINE_AONMIX_ELE].toggleUsec = 10U,

    [RST_LINE_BBSMMIX].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_BBSMMIX].lineReg = &SRC_XSPR_BBSMMIX->SLICE_SW_CTRL,
    [RST_LINE_BBSMMIX].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_BBSMMIX].statReg = &SRC_XSPR_BBSMMIX->RSTR_STAT,
    [RST_LINE_BBSMMIX].assertLow = false,
    [RST_LINE_BBSMMIX].toggleUsec = 10U,
    
    [RST_LINE_M71MIX].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_M71MIX].lineReg = &SRC_XSPR_M71MIX->SLICE_SW_CTRL,
    [RST_LINE_M71MIX].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_M71MIX].statReg = &SRC_XSPR_M71MIX->RSTR_STAT,
    [RST_LINE_M71MIX].assertLow = false,
    [RST_LINE_M71MIX].toggleUsec = 10U,

    [RST_LINE_CCMSRCGPCMIX].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_CCMSRCGPCMIX].lineReg = &SRC_XSPR_CCMSRCGPCMIX->SLICE_SW_CTRL,
    [RST_LINE_CCMSRCGPCMIX].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_CCMSRCGPCMIX].statReg = &SRC_XSPR_CCMSRCGPCMIX->RSTR_STAT,
    [RST_LINE_CCMSRCGPCMIX].assertLow = false,
    [RST_LINE_CCMSRCGPCMIX].toggleUsec = 10U,
        
    [RST_LINE_CORTEXAMIX_CORE0].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_CORTEXAMIX_CORE0].lineReg = &SRC_XSPR_CORTEXMIX_CORE0->SLICE_SW_CTRL,
    [RST_LINE_CORTEXAMIX_CORE0].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_CORTEXAMIX_CORE0].statReg = &SRC_XSPR_CORTEXMIX_CORE0->RSTR_STAT,
    [RST_LINE_CORTEXAMIX_CORE0].assertLow = false,
    [RST_LINE_CORTEXAMIX_CORE0].toggleUsec = 10U,

    [RST_LINE_CORTEXAMIX_CORE1].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_CORTEXAMIX_CORE1].lineReg = &SRC_XSPR_CORTEXMIX_CORE1->SLICE_SW_CTRL,
    [RST_LINE_CORTEXAMIX_CORE1].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_CORTEXAMIX_CORE1].statReg = &SRC_XSPR_CORTEXMIX_CORE1->RSTR_STAT,
    [RST_LINE_CORTEXAMIX_CORE1].assertLow = false,
    [RST_LINE_CORTEXAMIX_CORE1].toggleUsec = 10U,

    [RST_LINE_CORTEXAMIX_CORE2].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_CORTEXAMIX_CORE2].lineReg = &SRC_XSPR_CORTEXMIX_CORE2->SLICE_SW_CTRL,
    [RST_LINE_CORTEXAMIX_CORE2].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_CORTEXAMIX_CORE2].statReg = &SRC_XSPR_CORTEXMIX_CORE2->RSTR_STAT,
    [RST_LINE_CORTEXAMIX_CORE2].assertLow = false,
    [RST_LINE_CORTEXAMIX_CORE2].toggleUsec = 10U,

    [RST_LINE_CORTEXAMIX_CORE3].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_CORTEXAMIX_CORE3].lineReg = &SRC_XSPR_CORTEXMIX_CORE3->SLICE_SW_CTRL,
    [RST_LINE_CORTEXAMIX_CORE3].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_CORTEXAMIX_CORE3].statReg = &SRC_XSPR_CORTEXMIX_CORE3->RSTR_STAT,
    [RST_LINE_CORTEXAMIX_CORE3].assertLow = false,
    [RST_LINE_CORTEXAMIX_CORE3].toggleUsec = 10U,

    [RST_LINE_CORTEXAMIX_PLATFORM].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_CORTEXAMIX_PLATFORM].lineReg = &SRC_XSPR_CORTEXMIX_PLATFORM->SLICE_SW_CTRL,
    [RST_LINE_CORTEXAMIX_PLATFORM].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_CORTEXAMIX_PLATFORM].statReg = &SRC_XSPR_CORTEXMIX_PLATFORM->RSTR_STAT,
    [RST_LINE_CORTEXAMIX_PLATFORM].assertLow = false,
    [RST_LINE_CORTEXAMIX_PLATFORM].toggleUsec = 10U,

    /* TODO: WDOG3/4 reset line */

    [RST_LINE_DDRMIX_TOP].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_DDRMIX_TOP].lineReg = &SRC_XSPR_DDRMIX->SLICE_SW_CTRL,
    [RST_LINE_DDRMIX_TOP].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_DDRMIX_TOP].statReg = &SRC_XSPR_DDRMIX->RSTR_STAT,
    [RST_LINE_DDRMIX_TOP].assertLow = false,
    [RST_LINE_DDRMIX_TOP].toggleUsec = 10U,

    [RST_LINE_DDRMIX_PHY].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_1_MASK,
    [RST_LINE_DDRMIX_PHY].lineReg = &SRC_XSPR_DDRMIX->SLICE_SW_CTRL,
    [RST_LINE_DDRMIX_PHY].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_1_RST_STAT_MASK,
    [RST_LINE_DDRMIX_PHY].statReg = &SRC_XSPR_DDRMIX->RSTR_STAT,
    [RST_LINE_DDRMIX_PHY].assertLow = false,
    [RST_LINE_DDRMIX_PHY].toggleUsec = 10U,

    [RST_LINE_DISPLAYMIX].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_DISPLAYMIX].lineReg = &SRC_XSPR_DISPLAYMIX->SLICE_SW_CTRL,
    [RST_LINE_DISPLAYMIX].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_DISPLAYMIX].statReg = &SRC_XSPR_DISPLAYMIX->RSTR_STAT,
    [RST_LINE_DISPLAYMIX].assertLow = false,
    [RST_LINE_DISPLAYMIX].toggleUsec = 10U,

    [RST_LINE_M70MIX].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_M70MIX].lineReg = &SRC_XSPR_M70MIX->SLICE_SW_CTRL,
    [RST_LINE_M70MIX].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_M70MIX].statReg = &SRC_XSPR_M70MIX->RSTR_STAT,
    [RST_LINE_M70MIX].assertLow = false,
    [RST_LINE_M70MIX].toggleUsec = 10U,

    [RST_LINE_HSIOMIX_TOP].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_HSIOMIX_TOP].lineReg = &SRC_XSPR_HSIOMIX_TOP->SLICE_SW_CTRL,
    [RST_LINE_HSIOMIX_TOP].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_HSIOMIX_TOP].statReg = &SRC_XSPR_HSIOMIX_TOP->RSTR_STAT,
    [RST_LINE_HSIOMIX_TOP].assertLow = false,
    [RST_LINE_HSIOMIX_TOP].toggleUsec = 10U,

    [RST_LINE_HSIOMIX_WAON].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_HSIOMIX_WAON].lineReg = &SRC_XSPR_HSIOMIX_WAON->SLICE_SW_CTRL,
    [RST_LINE_HSIOMIX_WAON].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_HSIOMIX_WAON].statReg = &SRC_XSPR_HSIOMIX_WAON->RSTR_STAT,
    [RST_LINE_HSIOMIX_WAON].assertLow = false,
    [RST_LINE_HSIOMIX_WAON].toggleUsec = 10U,

    [RST_LINE_NETCMIX].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_NETCMIX].lineReg = &SRC_XSPR_NETCMIX->SLICE_SW_CTRL,
    [RST_LINE_NETCMIX].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_NETCMIX].statReg = &SRC_XSPR_NETCMIX->RSTR_STAT,
    [RST_LINE_NETCMIX].assertLow = false,
    [RST_LINE_NETCMIX].toggleUsec = 10U,

    [RST_LINE_NETCMIX_M33].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_1_MASK,
    [RST_LINE_NETCMIX_M33].lineReg = &SRC_XSPR_NETCMIX->SLICE_SW_CTRL,
    [RST_LINE_NETCMIX_M33].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_1_RST_STAT_MASK,
    [RST_LINE_NETCMIX_M33].statReg = &SRC_XSPR_NETCMIX->RSTR_STAT,
    [RST_LINE_NETCMIX_M33].assertLow = false,
    [RST_LINE_NETCMIX_M33].toggleUsec = 10U,

    [RST_LINE_NETCMIX_WDOG_7_8].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_2_MASK,
    [RST_LINE_NETCMIX_WDOG_7_8].lineReg = &SRC_XSPR_NETCMIX->SLICE_SW_CTRL,
    [RST_LINE_NETCMIX_WDOG_7_8].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_2_RST_STAT_MASK,
    [RST_LINE_NETCMIX_WDOG_7_8].statReg = &SRC_XSPR_NETCMIX->RSTR_STAT,
    [RST_LINE_NETCMIX_WDOG_7_8].assertLow = false,
    [RST_LINE_NETCMIX_WDOG_7_8].toggleUsec = 10U,

    [RST_LINE_NOCMIX].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_NOCMIX].lineReg = &SRC_XSPR_NOCMIX->SLICE_SW_CTRL,
    [RST_LINE_NOCMIX].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_NOCMIX].statReg = &SRC_XSPR_NOCMIX->RSTR_STAT,
    [RST_LINE_NOCMIX].assertLow = false,
    [RST_LINE_NOCMIX].toggleUsec = 10U,

    [RST_LINE_NPUMIX].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_NPUMIX].lineReg = &SRC_XSPR_NPUMIX->SLICE_SW_CTRL,
    [RST_LINE_NPUMIX].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_NPUMIX].statReg = &SRC_XSPR_NPUMIX->RSTR_STAT,
    [RST_LINE_NPUMIX].assertLow = false,
    [RST_LINE_NPUMIX].toggleUsec = 10U,

    [RST_LINE_WAKEUPMIX_TOP].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_0_MASK,
    [RST_LINE_WAKEUPMIX_TOP].lineReg = &SRC_XSPR_WAKEUPMIX->SLICE_SW_CTRL,
    [RST_LINE_WAKEUPMIX_TOP].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_WAKEUPMIX_TOP].statReg = &SRC_XSPR_WAKEUPMIX->RSTR_STAT,
    [RST_LINE_WAKEUPMIX_TOP].assertLow = false,
    [RST_LINE_WAKEUPMIX_TOP].toggleUsec = 10U,

    [RST_LINE_WAKEUPMIX_JTAG].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_1_MASK,
    [RST_LINE_WAKEUPMIX_JTAG].lineReg = &SRC_XSPR_WAKEUPMIX->SLICE_SW_CTRL,
    [RST_LINE_WAKEUPMIX_JTAG].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_0_RST_STAT_MASK,
    [RST_LINE_WAKEUPMIX_JTAG].statReg = &SRC_XSPR_WAKEUPMIX->RSTR_STAT,
    [RST_LINE_WAKEUPMIX_JTAG].assertLow = false,
    [RST_LINE_WAKEUPMIX_JTAG].toggleUsec = 10U,

    [RST_LINE_WAKEUPMIX_WDOG_5].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_2_MASK,
    [RST_LINE_WAKEUPMIX_WDOG_5].lineReg = &SRC_XSPR_WAKEUPMIX->SLICE_SW_CTRL,
    [RST_LINE_WAKEUPMIX_WDOG_5].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_2_RST_STAT_MASK,
    [RST_LINE_WAKEUPMIX_WDOG_5].statReg = &SRC_XSPR_WAKEUPMIX->RSTR_STAT,
    [RST_LINE_WAKEUPMIX_WDOG_5].assertLow = false,
    [RST_LINE_WAKEUPMIX_WDOG_5].toggleUsec = 10U,

    [RST_LINE_WAKEUPMIX_WDOG_6].lineMask =
        SRC_XSPR_SLICE_SW_CTRL_RST_RSTR_3_MASK,
    [RST_LINE_WAKEUPMIX_WDOG_6].lineReg = &SRC_XSPR_WAKEUPMIX->SLICE_SW_CTRL,
    [RST_LINE_WAKEUPMIX_WDOG_6].statMask =
        SRC_XSPR_RSTR_STAT_RSTR_3_RST_STAT_MASK,
    [RST_LINE_WAKEUPMIX_WDOG_6].statReg = &SRC_XSPR_WAKEUPMIX->RSTR_STAT,
    [RST_LINE_WAKEUPMIX_WDOG_6].assertLow = false,
    [RST_LINE_WAKEUPMIX_WDOG_6].toggleUsec = 10U,
};

/*--------------------------------------------------------------------------*/
/* Query system reset reason                                                 */
/*--------------------------------------------------------------------------*/
uint32_t RST_SystemGetResetReason(void)
{
    uint32_t resetReason = RST_REASON_POR;

    /* If SRC reset status bits are cleared, reason with default to POR */
    uint32_t srsReason = SRC_GEN->SRESR;

    /* If SRC reset status is indicated, return reset source index */
    if (srsReason != 0U)
    {
        resetReason = 31UL - ((uint32_t) __CLZ(srsReason));
    }

    return resetReason; 
}

/*--------------------------------------------------------------------------*/
/* Clear system reset reason                                                 */
/*--------------------------------------------------------------------------*/
void RST_SystemClearResetReason(uint32_t resetReason)
{
    /* Use W1C to clear the specified SRC reset status bit */
    if (resetReason < RST_NUM_REASONS)
    {
        SRC_GEN->SRESR |= (1UL << resetReason);
    }
}

/*--------------------------------------------------------------------------*/
/* Request system reset                                                     */
/*--------------------------------------------------------------------------*/
void RST_SystemRequestReset(void)
{
    /* Assert CM33 SYSRESETREQ */ 
    NVIC_SystemReset();
}
