/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXE246VLQ/signal_configuration.xml
 *
 * Copyright 2025 NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXE247VLQ-pinctrl.h with this part's differences applied
 * below (114 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: a37fc56c898e6e9f
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXE246VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXE246VLQ_WRAPPER_

#include "MCXE247VLQ-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE24_PTB29
#undef ADC0_SE25_PTC19
#undef ADC0_SE26_PTC23
#undef ADC0_SE27_PTC27
#undef ADC0_SE28_PTC28
#undef ADC0_SE29_PTC29
#undef ADC0_SE30_PTC30
#undef ADC0_SE31_PTC31
#undef ADC1_SE24_PTD30
#undef ADC1_SE25_PTE19
#undef ADC1_SE26_PTE20
#undef ADC1_SE27_PTE21
#undef ADC1_SE28_PTE22
#undef ADC1_SE29_PTE23
#undef ADC1_SE30_PTE24
#undef ADC1_SE31_PTE25
#undef ENET_TMR0_PTD14
#undef ENET_TMR1_PTD13
#undef ENET_TMR2_PTD15
#undef ENET_TMR3_PTE9
#undef ETM_TRACE_CLKOUT_PTC2
#undef ETM_TRACE_CLKOUT_PTD16
#undef ETM_TRACE_D0_PTD0
#undef ETM_TRACE_D0_PTD7
#undef ETM_TRACE_D1_PTD12
#undef ETM_TRACE_D1_PTE4
#undef ETM_TRACE_D2_PTD11
#undef ETM_TRACE_D2_PTD16
#undef ETM_TRACE_D3_PTD10
#undef ETM_TRACE_D3_PTD15
#undef FTM6_CH0_PTB20
#undef FTM6_CH0_PTD19
#undef FTM6_CH1_PTB21
#undef FTM6_CH2_PTB22
#undef FTM6_CH3_PTB23
#undef FTM6_CH3_PTD22
#undef FTM6_CH4_PTD23
#undef FTM6_CH5_PTB25
#undef FTM6_CH5_PTD24
#undef FTM6_CH7_PTB27
#undef FTM6_FLT0_PTB13
#undef FTM6_FLT1_PTB12
#undef FTM6_FLT1_PTD30
#undef FTM7_CH0_PTB28
#undef FTM7_CH0_PTD27
#undef FTM7_CH1_PTB29
#undef FTM7_CH1_PTD28
#undef FTM7_CH2_PTD29
#undef FTM7_CH3_PTD30
#undef FTM7_CH5_PTC19
#undef FTM7_CH7_PTE19
#undef FTM7_FLT0_PTA15
#undef FTM7_FLT1_PTE6
#undef LPI2C1_HREQ_PTC5
#undef LPI2C1_HREQ_PTD12
#undef LPI2C1_SCLS_PTA13
#undef LPI2C1_SCLS_PTC17
#undef LPI2C1_SCLS_PTD18
#undef LPI2C1_SCL_PTD19
#undef LPI2C1_SCL_PTD9
#undef LPI2C1_SCL_PTE1
#undef LPI2C1_SDAS_PTA12
#undef LPI2C1_SDAS_PTC16
#undef LPI2C1_SDAS_PTC30
#undef LPI2C1_SDA_PTC31
#undef LPI2C1_SDA_PTD8
#undef LPI2C1_SDA_PTE0
#undef MII_COL_PTB23
#undef MII_COL_PTC14
#undef MII_CRS_PTB22
#undef MII_CRS_PTC15
#undef MII_RMII_MDC_PTB5
#undef MII_RMII_MDC_PTE8
#undef MII_RMII_MDIO_PTB4
#undef MII_RMII_RXD0_PTC0
#undef MII_RMII_RXD0_PTC1
#undef MII_RMII_RXD1_PTC0
#undef MII_RMII_RXD1_PTC1
#undef MII_RMII_RX_DV_PTC17
#undef MII_RMII_RX_ER_PTC16
#undef MII_RMII_TXD0_PTC2
#undef MII_RMII_TXD1_PTD7
#undef MII_RMII_TX_CLK_PTD11
#undef MII_RMII_TX_EN_PTD12
#undef MII_RXD2_PTD9
#undef MII_RXD3_PTD8
#undef MII_RX_CLK_PTD10
#undef MII_TXD2_PTD6
#undef MII_TXD3_PTD5
#undef MII_TX_ER_PTC3
#undef QSPI_A_CS_PTC3
#undef QSPI_A_IO0_PTD11
#undef QSPI_A_IO1_PTD7
#undef QSPI_A_IO2_PTD12
#undef QSPI_A_IO3_PTC2
#undef QSPI_A_SCK_PTD10
#undef QSPI_B_CS_PTC15
#undef QSPI_B_IO0_PTB4
#undef QSPI_B_IO1_PTD6
#undef QSPI_B_IO2_PTD5
#undef QSPI_B_IO3_PTC3
#undef QSPI_B_RWDS_PTC0
#undef QSPI_B_SCK_PTC1
#undef SAI0_BCLK_PTA12
#undef SAI0_D0_PTA13
#undef SAI0_D1_PTE1
#undef SAI0_D2_PTE0
#undef SAI0_D3_PTA14
#undef SAI0_MCLK_PTD1
#undef SAI0_SYNC_PTA11
#undef SAI1_BCLK_PTB8
#undef SAI1_D0_PTB9
#undef SAI1_MCLK_PTB10
#undef SAI1_SYNC_PTE2

#endif /* _ZEPHYR_DTS_BINDING_MCXE246VLQ_WRAPPER_ */
