/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA557BVPN/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA557VPN-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 4d477bf4a04e5cda
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA557BVPN_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA557BVPN_WRAPPER_

#include "MCXA557VPN-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA557BVPN_WRAPPER_ */
