/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA142VLF/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA153VLF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 318f528b38629f52
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA142VLF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA142VLF_WRAPPER_

#include "MCXA153VLF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA142VLF_WRAPPER_ */
