/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA365VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA366VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 011ef572d22de35a
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA365VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA365VLL_WRAPPER_

#include "MCXA366VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA365VLL_WRAPPER_ */
