/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA366VPN/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA366VLQ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: ee22aa6d28c1f247
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA366VPN_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA366VPN_WRAPPER_

#include "MCXA366VLQ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA366VPN_WRAPPER_ */
