/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA456VASR/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA457VASR-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 203abc09e69095bd
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA456VASR_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA456VASR_WRAPPER_

#include "MCXA457VASR-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA456VASR_WRAPPER_ */
