/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA155VLH/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA156VLH-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: ed91edea20c414f3
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA155VLH_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA155VLH_WRAPPER_

#include "MCXA156VLH-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA155VLH_WRAPPER_ */
