/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA346VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA366VLL-pinctrl.h with this part's differences applied
 * below (143 removed, 0 changed,
 * 140 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: a0f6521a5e7a64e3
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA346VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA346VLQ_WRAPPER_

#include "MCXA366VLL-pinctrl.h"

/* Signals not present on this part */
#undef CAN1_RXD_P1_0
#undef CAN1_RXD_P1_12
#undef CAN1_RXD_P1_7
#undef CAN1_RXD_P2_0
#undef CAN1_RXD_P2_15
#undef CAN1_TXD_P1_1
#undef CAN1_TXD_P1_13
#undef CAN1_TXD_P1_6
#undef CAN1_TXD_P2_1
#undef CAN1_TXD_P2_16
#undef FLEXIO0_D0_P0_0
#undef FLEXIO0_D0_P0_16
#undef FLEXIO0_D10_P1_2
#undef FLEXIO0_D10_P2_2
#undef FLEXIO0_D10_P4_2
#undef FLEXIO0_D11_P1_3
#undef FLEXIO0_D11_P2_3
#undef FLEXIO0_D11_P4_3
#undef FLEXIO0_D12_P1_4
#undef FLEXIO0_D12_P2_4
#undef FLEXIO0_D12_P4_4
#undef FLEXIO0_D13_P1_5
#undef FLEXIO0_D13_P2_5
#undef FLEXIO0_D13_P4_5
#undef FLEXIO0_D14_P1_6
#undef FLEXIO0_D14_P2_6
#undef FLEXIO0_D14_P3_6
#undef FLEXIO0_D14_P4_6
#undef FLEXIO0_D15_P1_7
#undef FLEXIO0_D15_P2_7
#undef FLEXIO0_D15_P3_7
#undef FLEXIO0_D15_P4_7
#undef FLEXIO0_D16_P1_8
#undef FLEXIO0_D16_P3_8
#undef FLEXIO0_D17_P1_9
#undef FLEXIO0_D17_P3_9
#undef FLEXIO0_D18_P1_10
#undef FLEXIO0_D18_P2_10
#undef FLEXIO0_D18_P3_10
#undef FLEXIO0_D19_P1_11
#undef FLEXIO0_D19_P2_11
#undef FLEXIO0_D19_P3_11
#undef FLEXIO0_D1_P0_1
#undef FLEXIO0_D1_P0_17
#undef FLEXIO0_D20_P1_12
#undef FLEXIO0_D20_P2_12
#undef FLEXIO0_D20_P3_12
#undef FLEXIO0_D21_P1_13
#undef FLEXIO0_D21_P2_13
#undef FLEXIO0_D21_P3_13
#undef FLEXIO0_D22_P1_14
#undef FLEXIO0_D22_P3_14
#undef FLEXIO0_D23_P1_15
#undef FLEXIO0_D23_P2_15
#undef FLEXIO0_D23_P3_15
#undef FLEXIO0_D24_P2_16
#undef FLEXIO0_D24_P3_16
#undef FLEXIO0_D25_P2_17
#undef FLEXIO0_D25_P3_17
#undef FLEXIO0_D26_P3_18
#undef FLEXIO0_D27_P2_19
#undef FLEXIO0_D27_P3_19
#undef FLEXIO0_D27_P3_27
#undef FLEXIO0_D28_P2_20
#undef FLEXIO0_D28_P3_20
#undef FLEXIO0_D28_P3_28
#undef FLEXIO0_D29_P2_21
#undef FLEXIO0_D29_P3_21
#undef FLEXIO0_D29_P3_29
#undef FLEXIO0_D2_P0_18
#undef FLEXIO0_D2_P0_2
#undef FLEXIO0_D30_P1_30
#undef FLEXIO0_D30_P3_22
#undef FLEXIO0_D30_P3_30
#undef FLEXIO0_D31_P1_31
#undef FLEXIO0_D31_P2_23
#undef FLEXIO0_D31_P3_31
#undef FLEXIO0_D3_P0_19
#undef FLEXIO0_D3_P0_3
#undef FLEXIO0_D4_P0_20
#undef FLEXIO0_D5_P0_21
#undef FLEXIO0_D6_P0_14
#undef FLEXIO0_D6_P0_22
#undef FLEXIO0_D6_P0_6
#undef FLEXIO0_D7_P0_15
#undef FLEXIO0_D7_P0_23
#undef FLEXIO0_D8_P1_0
#undef FLEXIO0_D8_P2_0
#undef FLEXIO0_D8_P3_0
#undef FLEXIO0_D9_P1_1
#undef FLEXIO0_D9_P2_1
#undef FLEXIO0_D9_P3_1
#undef I3C0_PUR_P0_2
#undef I3C0_PUR_P1_11
#undef I3C0_SCL_P0_17
#undef I3C0_SCL_P1_31
#undef I3C0_SCL_P1_9
#undef I3C0_SDA_P0_16
#undef I3C0_SDA_P1_30
#undef I3C0_SDA_P1_8
#undef LCD_P0_P1_0
#undef LCD_P10_P1_12
#undef LCD_P11_P1_13
#undef LCD_P12_P1_14
#undef LCD_P13_P1_15
#undef LCD_P18_P0_14
#undef LCD_P19_P0_15
#undef LCD_P1_P1_1
#undef LCD_P20_P0_16
#undef LCD_P21_P0_17
#undef LCD_P22_P0_18
#undef LCD_P23_P0_19
#undef LCD_P24_P0_20
#undef LCD_P25_P0_21
#undef LCD_P26_P0_22
#undef LCD_P27_P0_23
#undef LCD_P2_P1_2
#undef LCD_P32_P3_0
#undef LCD_P33_P3_1
#undef LCD_P34_P3_6
#undef LCD_P35_P3_7
#undef LCD_P36_P3_8
#undef LCD_P37_P3_9
#undef LCD_P38_P3_10
#undef LCD_P39_P3_11
#undef LCD_P3_P1_3
#undef LCD_P40_P3_12
#undef LCD_P41_P3_13
#undef LCD_P42_P3_14
#undef LCD_P43_P3_15
#undef LCD_P44_P3_16
#undef LCD_P45_P3_17
#undef LCD_P46_P3_18
#undef LCD_P47_P3_19
#undef LCD_P4_P1_6
#undef LCD_P5_P1_7
#undef LCD_P6_P1_8
#undef LCD_P7_P1_9
#undef LCD_P8_P1_10
#undef LCD_P9_P1_11
#undef LCD_VLL1_P1_5
#undef LCD_VLL2_P1_4
#undef USB0_VBUS_DET_P2_12

/* Signals specific to this part */
#define ADC1_A14_P1_16 A15X_MUX('1',16,0)
#define ADC1_A15_P1_17 A15X_MUX('1',17,0)
#define ADC1_A16_P1_18 A15X_MUX('1',18,0)
#define ADC1_A17_P1_19 A15X_MUX('1',19,0)
#define ADC2_A10_P0_5 A15X_MUX('0',5,0)
#define ADC2_A11_P0_7 A15X_MUX('0',7,0)
#define ADC2_A12_P0_12 A15X_MUX('0',12,0)
#define ADC2_A13_P0_13 A15X_MUX('0',13,0)
#define ADC2_A16_P4_0 A15X_MUX('4',0,0)
#define ADC2_A17_P4_1 A15X_MUX('4',1,0)
#define ADC2_A3_P2_24 A15X_MUX('2',24,0)
#define ADC2_A9_P0_4 A15X_MUX('0',4,0)
#define ADC3_A10_P3_4 A15X_MUX('3',4,0)
#define ADC3_A11_P3_5 A15X_MUX('3',5,0)
#define ADC3_A21_P3_23 A15X_MUX('3',23,0)
#define ADC3_A22_P3_24 A15X_MUX('3',24,0)
#define ADC3_A23_P3_25 A15X_MUX('3',25,0)
#define ADC3_A3_P2_25 A15X_MUX('2',25,0)
#define ADC3_A8_P3_2 A15X_MUX('3',2,0)
#define ADC3_A9_P3_3 A15X_MUX('3',3,0)
#define CAN0_RXD_P1_19 A15X_MUX('1',19,11)
#define CAN0_TXD_P1_18 A15X_MUX('1',18,11)
#define CMP1_OUT_P0_4 A15X_MUX('0',4,8)
#define CMP2_IN1_P0_7 A15X_MUX('0',7,0)
#define CMP2_OUT_P0_5 A15X_MUX('0',5,8)
#define CT0_MAT0_P0_24 A15X_MUX('0',24,4)
#define CT0_MAT1_P0_25 A15X_MUX('0',25,4)
#define CT0_MAT2_P0_12 A15X_MUX('0',12,4)
#define CT0_MAT2_P0_26 A15X_MUX('0',26,4)
#define CT0_MAT2_P0_4 A15X_MUX('0',4,4)
#define CT0_MAT3_P0_13 A15X_MUX('0',13,4)
#define CT0_MAT3_P0_27 A15X_MUX('0',27,4)
#define CT0_MAT3_P0_5 A15X_MUX('0',5,4)
#define CT2_MAT2_P2_22 A15X_MUX('2',22,4)
#define CT3_MAT0_P1_18 A15X_MUX('1',18,4)
#define CT3_MAT0_P2_8 A15X_MUX('2',8,4)
#define CT3_MAT1_P1_19 A15X_MUX('1',19,4)
#define CT3_MAT1_P2_9 A15X_MUX('2',9,4)
#define CT3_MAT2_P2_18 A15X_MUX('2',18,4)
#define CT4_MAT0_P3_2 A15X_MUX('3',2,4)
#define CT4_MAT1_P3_3 A15X_MUX('3',3,4)
#define CT4_MAT2_P2_14 A15X_MUX('2',14,4)
#define CT_INP10_P2_26 A15X_MUX('2',26,4)
#define CT_INP11_P3_23 A15X_MUX('3',23,4)
#define CT_INP12_P1_16 A15X_MUX('1',16,4)
#define CT_INP13_P1_17 A15X_MUX('1',17,4)
#define CT_INP14_P3_26 A15X_MUX('3',26,4)
#define CT_INP15_P3_25 A15X_MUX('3',25,4)
#define CT_INP16_P3_24 A15X_MUX('3',24,4)
#define CT_INP18_P3_4 A15X_MUX('3',4,4)
#define CT_INP19_P3_5 A15X_MUX('3',5,4)
#define CT_INP3_P0_7 A15X_MUX('0',7,4)
#define CT_INP8_P2_24 A15X_MUX('2',24,4)
#define CT_INP9_P2_25 A15X_MUX('2',25,4)
#define FREQME_CLK_IN0_P1_18 A15X_MUX('1',18,1)
#define FREQME_CLK_IN1_P1_19 A15X_MUX('1',19,1)
#define ISPMODE_N_P3_29 A15X_MUX('3',29,1)
#define LPSPI1_PCS1_P3_2 A15X_MUX('3',2,2)
#define LPUART1_CTS_B_P3_23 A15X_MUX('3',23,3)
#define LPUART5_CTS_B_P0_27 A15X_MUX('0',27,8)
#define LPUART5_CTS_B_P1_19 A15X_MUX('1',19,8)
#define LPUART5_RTS_B_P0_26 A15X_MUX('0',26,8)
#define LPUART5_RTS_B_P1_18 A15X_MUX('1',18,8)
#define LPUART5_RXD_P0_24 A15X_MUX('0',24,8)
#define LPUART5_RXD_P1_16 A15X_MUX('1',16,8)
#define LPUART5_TXD_P0_25 A15X_MUX('0',25,8)
#define LPUART5_TXD_P1_17 A15X_MUX('1',17,8)
#define P0_12 A15X_MUX('0',12,0)
#define P0_13 A15X_MUX('0',13,0)
#define P0_24 A15X_MUX('0',24,0)
#define P0_25 A15X_MUX('0',25,0)
#define P0_26 A15X_MUX('0',26,0)
#define P0_27 A15X_MUX('0',27,0)
#define P0_4 A15X_MUX('0',4,0)
#define P0_5 A15X_MUX('0',5,0)
#define P0_7 A15X_MUX('0',7,0)
#define P1_16 A15X_MUX('1',16,0)
#define P1_17 A15X_MUX('1',17,0)
#define P1_18 A15X_MUX('1',18,0)
#define P1_19 A15X_MUX('1',19,0)
#define P2_14 A15X_MUX('2',14,0)
#define P2_18 A15X_MUX('2',18,0)
#define P2_22 A15X_MUX('2',22,0)
#define P2_24 A15X_MUX('2',24,0)
#define P2_25 A15X_MUX('2',25,0)
#define P2_26 A15X_MUX('2',26,0)
#define P2_8 A15X_MUX('2',8,0)
#define P2_9 A15X_MUX('2',9,0)
#define P3_2 A15X_MUX('3',2,0)
#define P3_23 A15X_MUX('3',23,0)
#define P3_24 A15X_MUX('3',24,0)
#define P3_25 A15X_MUX('3',25,0)
#define P3_26 A15X_MUX('3',26,0)
#define P3_3 A15X_MUX('3',3,0)
#define P3_4 A15X_MUX('3',4,0)
#define P3_5 A15X_MUX('3',5,0)
#define P4_0 A15X_MUX('4',0,0)
#define P4_1 A15X_MUX('4',1,0)
#define PWM0_A3_P4_0 A15X_MUX('4',0,5)
#define PWM0_B3_P4_1 A15X_MUX('4',1,5)
#define PWM0_X0_P3_2 A15X_MUX('3',2,5)
#define PWM0_X1_P3_3 A15X_MUX('3',3,5)
#define PWM0_X2_P3_4 A15X_MUX('3',4,5)
#define PWM0_X3_P3_5 A15X_MUX('3',5,5)
#define PWM1_X2_P3_2 A15X_MUX('3',2,7)
#define PWM1_X3_P3_23 A15X_MUX('3',23,7)
#define PWM1_X3_P3_3 A15X_MUX('3',3,7)
#define SmartDMA_PIO0_P0_4 A15X_MUX('0',4,7)
#define SmartDMA_PIO12_P1_16 A15X_MUX('1',16,7)
#define SmartDMA_PIO13_P1_17 A15X_MUX('1',17,7)
#define SmartDMA_PIO14_P1_18 A15X_MUX('1',18,7)
#define SmartDMA_PIO15_P1_19 A15X_MUX('1',19,7)
#define SmartDMA_PIO1_P0_5 A15X_MUX('0',5,7)
#define SmartDMA_PIO20_P4_0 A15X_MUX('4',0,7)
#define SmartDMA_PIO21_P4_1 A15X_MUX('4',1,7)
#define SmartDMA_PIO23_P3_23 A15X_MUX('3',23,10)
#define SmartDMA_PIO24_P3_24 A15X_MUX('3',24,10)
#define SmartDMA_PIO25_P3_25 A15X_MUX('3',25,10)
#define SmartDMA_PIO26_P3_26 A15X_MUX('3',26,10)
#define SmartDMA_PIO2_P3_2 A15X_MUX('3',2,10)
#define SmartDMA_PIO3_P0_7 A15X_MUX('0',7,7)
#define SmartDMA_PIO3_P3_3 A15X_MUX('3',3,10)
#define SmartDMA_PIO4_P3_4 A15X_MUX('3',4,10)
#define SmartDMA_PIO5_P3_5 A15X_MUX('3',5,10)
#define TRIG_IN10/CT_INP14_P3_26_P3_26 A15X_MUX('3',26,4)
#define TRIG_IN10_P3_26 A15X_MUX('3',26,1)
#define TRIG_IN11_P3_24 A15X_MUX('3',24,1)
#define TRIG_IN4_P2_9 A15X_MUX('2',9,1)
#define TRIG_IN5_P2_26 A15X_MUX('2',26,1)
#define TRIG_IN5_P4_0 A15X_MUX('4',0,1)
#define TRIG_OUT3_P2_8 A15X_MUX('2',8,1)
#define TRIG_OUT6_P2_24 A15X_MUX('2',24,1)
#define TRIG_OUT6_P3_25 A15X_MUX('3',25,1)
#define TRIG_OUT7_P2_25 A15X_MUX('2',25,1)
#define UTICK_CAP2_P0_4 A15X_MUX('0',4,5)
#define UTICK_CAP3_P0_5 A15X_MUX('0',5,5)
#define WUU0_IN0_P0_4 A15X_MUX('0',4,0)
#define WUU0_IN14_P1_16 A15X_MUX('1',16,0)
#define WUU0_IN15_P1_19 A15X_MUX('1',19,0)
#define WUU0_IN1_P0_7 A15X_MUX('0',7,0)

#endif /* _ZEPHYR_DTS_BINDING_MCXA346VLQ_WRAPPER_ */
