/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA174VLH/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA344VLH-pinctrl.h with this part's differences applied
 * below (10 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 796e143b40c94355
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA174VLH_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA174VLH_WRAPPER_

#include "MCXA344VLH-pinctrl.h"

/* Signals not present on this part */
#undef CMP2_IN0_P2_4
#undef CMP2_IN3_P1_2
#undef CMP2_INN4_P2_2
#undef CMP2_INP4_P2_6
#undef OPAMP1_INN_P2_17
#undef OPAMP1_INP_P2_16
#undef OPAMP1_OUT_P2_19
#undef OPAMP2_INN_P2_1
#undef OPAMP2_INP_P2_0
#undef OPAMP2_OUT_P2_6

#endif /* _ZEPHYR_DTS_BINDING_MCXA174VLH_WRAPPER_ */
