/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA346VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA356VLQ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 106afdbc67ee90f1
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA346VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA346VLQ_WRAPPER_

#include "MCXA356VLQ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA346VLQ_WRAPPER_ */
