/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA153VLH/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA344VLH-pinctrl.h with this part's differences applied
 * below (142 removed, 0 changed,
 * 27 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 796e143b40c94355
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA153VLH_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA153VLH_WRAPPER_

#include "MCXA344VLH-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_A14_P0_3
#undef ADC0_A1_P2_4
#undef ADC0_A2_P2_15
#undef ADC0_A3_P2_3
#undef ADC1_A0_P2_1
#undef ADC1_A10_P1_12
#undef ADC1_A11_P1_13
#undef ADC1_A1_P2_5
#undef ADC1_A20_P3_31
#undef ADC1_A21_P3_30
#undef ADC1_A22_P3_29
#undef ADC1_A2_P2_19
#undef ADC1_A3_P2_6
#undef ADC1_A4_P2_3
#undef ADC1_A5_P2_13
#undef ADC1_A6_P2_17
#undef ADC1_A7_P2_7
#undef ADC1_A8_P1_10
#undef ADC1_A9_P1_11
#undef CAN0_RXD_P1_11
#undef CAN0_RXD_P1_12
#undef CAN0_RXD_P1_3
#undef CAN0_RXD_P1_7
#undef CAN0_RXD_P2_12
#undef CAN0_TXD_P1_10
#undef CAN0_TXD_P1_13
#undef CAN0_TXD_P1_2
#undef CAN0_TXD_P1_6
#undef CAN0_TXD_P2_13
#undef CMP0_INP4_P2_15
#undef CMP1_INN4_P2_2
#undef CMP1_INP4_P2_19
#undef CMP2_IN0_P2_4
#undef CMP2_IN3_P1_2
#undef CMP2_INN4_P2_2
#undef CMP2_INP4_P2_6
#undef CT0_MAT2_P2_15
#undef CT0_MAT3_P2_17
#undef FREQME_CLK_IN0_P1_8
#undef FREQME_CLK_IN1_P1_9
#undef ISPMODE_N_P0_6
#undef LPI2C1_HREQ_P3_29
#undef LPI2C1_SCLS_P1_3
#undef LPI2C1_SCLS_P3_30
#undef LPI2C1_SCL_P1_1
#undef LPI2C1_SCL_P1_13
#undef LPI2C1_SCL_P3_27
#undef LPI2C1_SDAS_P1_2
#undef LPI2C1_SDAS_P3_31
#undef LPI2C1_SDA_P1_0
#undef LPI2C1_SDA_P1_12
#undef LPI2C1_SDA_P3_28
#undef LPSPI1_PCS0_P2_17
#undef LPSPI1_SDI_P2_15
#undef LPUART1_CTS_B_P2_17
#undef LPUART1_RTS_B_P2_15
#undef LPUART2_CTS_B_P2_4
#undef LPUART2_RTS_B_P2_5
#undef LPUART3_CTS_B_P3_14
#undef LPUART3_CTS_B_P3_7
#undef LPUART3_RTS_B_P3_15
#undef LPUART3_RTS_B_P3_6
#undef LPUART3_RXD_P3_0
#undef LPUART3_RXD_P3_13
#undef LPUART3_TXD_P3_1
#undef LPUART3_TXD_P3_12
#undef OPAMP0_INN_P2_13
#undef OPAMP0_INP_P2_12
#undef OPAMP0_OUT_P2_15
#undef OPAMP1_INN_P2_17
#undef OPAMP1_INP_P2_16
#undef OPAMP1_OUT_P2_19
#undef OPAMP2_INN_P2_1
#undef OPAMP2_INP_P2_0
#undef OPAMP2_OUT_P2_6
#undef P2_15
#undef P2_17
#undef P2_19
#undef PWM0_A3_P3_6
#undef PWM0_B3_P3_7
#undef PWM0_X3_P3_15
#undef PWM1_A0_P3_30
#undef PWM1_A0_P3_6
#undef PWM1_A1_P3_14
#undef PWM1_A2_P3_12
#undef PWM1_A3_P3_27
#undef PWM1_B0_P3_31
#undef PWM1_B0_P3_7
#undef PWM1_B1_P3_15
#undef PWM1_B2_P3_13
#undef PWM1_B3_P3_28
#undef PWM1_X0_P3_0
#undef PWM1_X1_P3_1
#undef SMARTDMA_PIO0_P1_4
#undef SMARTDMA_PIO0_P3_0
#undef SMARTDMA_PIO10_P3_10
#undef SMARTDMA_PIO11_P3_11
#undef SMARTDMA_PIO12_P3_12
#undef SMARTDMA_PIO13_P3_13
#undef SMARTDMA_PIO14_P3_14
#undef SMARTDMA_PIO15_P3_15
#undef SMARTDMA_PIO16_P2_12
#undef SMARTDMA_PIO17_P2_13
#undef SMARTDMA_PIO18_P2_15
#undef SMARTDMA_PIO19_P2_16
#undef SMARTDMA_PIO1_P1_5
#undef SMARTDMA_PIO1_P3_1
#undef SMARTDMA_PIO20_P2_17
#undef SMARTDMA_PIO21_P2_19
#undef SMARTDMA_PIO24_P2_0
#undef SMARTDMA_PIO25_P2_1
#undef SMARTDMA_PIO26_P2_2
#undef SMARTDMA_PIO27_P2_3
#undef SMARTDMA_PIO27_P3_27
#undef SMARTDMA_PIO28_P2_4
#undef SMARTDMA_PIO28_P3_28
#undef SMARTDMA_PIO29_P2_5
#undef SMARTDMA_PIO29_P3_29
#undef SMARTDMA_PIO2_P0_6
#undef SMARTDMA_PIO2_P1_6
#undef SMARTDMA_PIO30_P2_6
#undef SMARTDMA_PIO30_P3_30
#undef SMARTDMA_PIO31_P2_7
#undef SMARTDMA_PIO31_P3_31
#undef SMARTDMA_PIO3_P1_7
#undef SMARTDMA_PIO4_P1_8
#undef SMARTDMA_PIO5_P1_9
#undef SMARTDMA_PIO6_P0_16
#undef SMARTDMA_PIO6_P1_10
#undef SMARTDMA_PIO6_P3_6
#undef SMARTDMA_PIO7_P0_17
#undef SMARTDMA_PIO7_P1_11
#undef SMARTDMA_PIO7_P3_7
#undef SMARTDMA_PIO8_P1_12
#undef SMARTDMA_PIO8_P3_8
#undef SMARTDMA_PIO9_P1_13
#undef SMARTDMA_PIO9_P3_9
#undef TRIG_IN9_P2_17
#undef TRIG_OUT4_P2_15
#undef TRIG_OUT5_P2_19
#undef WUU0_IN21_P2_15
#undef WUU0_IN30_P3_27

/* Signals specific to this part */
#define ADC0_A10_P1_12 A15X_MUX('1',12,0)
#define ADC0_A11_P1_13 A15X_MUX('1',13,0)
#define ADC0_A12_P3_31 A15X_MUX('3',31,0)
#define ADC0_A13_P3_30 A15X_MUX('3',30,0)
#define ADC0_A14_P3_29 A15X_MUX('3',29,0)
#define ADC0_A1_P2_1 A15X_MUX('2',1,0)
#define ADC0_A2_P2_3 A15X_MUX('2',3,0)
#define ADC0_A3_P2_6 A15X_MUX('2',6,0)
#define ADC0_A8_P1_10 A15X_MUX('1',10,0)
#define ADC0_A9_P1_11 A15X_MUX('1',11,0)
#define I3C0_PUR_P0_2 A15X_MUX('0',2,10)
#define I3C0_PUR_P1_11 A15X_MUX('1',11,10)
#define I3C0_SCL_P0_17 A15X_MUX('0',17,10)
#define I3C0_SCL_P1_31 A15X_MUX('1',31,10)
#define I3C0_SCL_P1_9 A15X_MUX('1',9,10)
#define I3C0_SDA_P0_16 A15X_MUX('0',16,10)
#define I3C0_SDA_P1_30 A15X_MUX('1',30,10)
#define I3C0_SDA_P1_8 A15X_MUX('1',8,10)
#define LPI2C0_SCLS_P1_3 A15X_MUX('1',3,3)
#define LPI2C0_SCL_P1_1 A15X_MUX('1',1,3)
#define LPI2C0_SCL_P3_27 A15X_MUX('3',27,2)
#define LPI2C0_SDAS_P1_2 A15X_MUX('1',2,3)
#define LPI2C0_SDA_P1_0 A15X_MUX('1',0,3)
#define LPI2C0_SDA_P3_28 A15X_MUX('3',28,2)
#define PWM0_A0_P3_6 A15X_MUX('3',6,5)
#define PWM0_B0_P3_7 A15X_MUX('3',7,5)
#define USB0_VBUS_DET_P2_12 A15X_MUX('2',12,1)

#endif /* _ZEPHYR_DTS_BINDING_MCXA153VLH_WRAPPER_ */
