/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA132VFM/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA133VFM-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 640b19435aec4551
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA132VFM_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA132VFM_WRAPPER_

#include "MCXA133VFM-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA132VFM_WRAPPER_ */
