/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA173VLH/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA174VLH-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 668b79a31f94cd37
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA173VLH_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA173VLH_WRAPPER_

#include "MCXA174VLH-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA173VLH_WRAPPER_ */
