/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA256VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA366VLL-pinctrl.h with this part's differences applied
 * below (105 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 011ef572d22de35a
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA256VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA256VLL_WRAPPER_

#include "MCXA366VLL-pinctrl.h"

/* Signals not present on this part */
#undef ADC2_A0_P2_4
#undef ADC2_A14_P0_14
#undef ADC2_A15_P0_15
#undef ADC2_A18_P4_2
#undef ADC2_A19_P4_3
#undef ADC2_A1_P2_10
#undef ADC2_A20_P4_4
#undef ADC2_A21_P4_5
#undef ADC2_A22_P4_6
#undef ADC2_A23_P4_7
#undef ADC2_A2_P2_6
#undef ADC2_A4_P2_16
#undef ADC2_A5_P2_12
#undef ADC2_A6_P2_20
#undef ADC2_A7_P2_7
#undef ADC2_A8_P0_2
#undef ADC3_A0_P2_5
#undef ADC3_A12_P3_6
#undef ADC3_A13_P3_7
#undef ADC3_A14_P3_12
#undef ADC3_A15_P3_13
#undef ADC3_A16_P3_14
#undef ADC3_A17_P3_15
#undef ADC3_A18_P3_20
#undef ADC3_A19_P3_21
#undef ADC3_A1_P2_11
#undef ADC3_A20_P3_22
#undef ADC3_A2_P2_23
#undef ADC3_A4_P2_17
#undef ADC3_A5_P2_13
#undef ADC3_A6_P2_21
#undef ADC3_A7_P2_7
#undef CAN1_RXD_P1_0
#undef CAN1_RXD_P1_12
#undef CAN1_RXD_P1_7
#undef CAN1_RXD_P2_0
#undef CAN1_RXD_P2_15
#undef CAN1_TXD_P1_1
#undef CAN1_TXD_P1_13
#undef CAN1_TXD_P1_6
#undef CAN1_TXD_P2_1
#undef CAN1_TXD_P2_16
#undef CMP2_IN0_P2_4
#undef CMP2_IN2_P0_23
#undef CMP2_IN3_P1_2
#undef CMP2_OUT_P0_20
#undef LCD_P0_P1_0
#undef LCD_P10_P1_12
#undef LCD_P11_P1_13
#undef LCD_P12_P1_14
#undef LCD_P13_P1_15
#undef LCD_P18_P0_14
#undef LCD_P19_P0_15
#undef LCD_P1_P1_1
#undef LCD_P20_P0_16
#undef LCD_P21_P0_17
#undef LCD_P22_P0_18
#undef LCD_P23_P0_19
#undef LCD_P24_P0_20
#undef LCD_P25_P0_21
#undef LCD_P26_P0_22
#undef LCD_P27_P0_23
#undef LCD_P2_P1_2
#undef LCD_P32_P3_0
#undef LCD_P33_P3_1
#undef LCD_P34_P3_6
#undef LCD_P35_P3_7
#undef LCD_P36_P3_8
#undef LCD_P37_P3_9
#undef LCD_P38_P3_10
#undef LCD_P39_P3_11
#undef LCD_P3_P1_3
#undef LCD_P40_P3_12
#undef LCD_P41_P3_13
#undef LCD_P42_P3_14
#undef LCD_P43_P3_15
#undef LCD_P44_P3_16
#undef LCD_P45_P3_17
#undef LCD_P46_P3_18
#undef LCD_P47_P3_19
#undef LCD_P4_P1_6
#undef LCD_P5_P1_7
#undef LCD_P6_P1_8
#undef LCD_P7_P1_9
#undef LCD_P8_P1_10
#undef LCD_P9_P1_11
#undef LCD_VLL1_P1_5
#undef LCD_VLL2_P1_4
#undef LPUART5_CTS_B_P1_12
#undef LPUART5_CTS_B_P3_8
#undef LPUART5_RTS_B_P1_13
#undef LPUART5_RTS_B_P3_9
#undef LPUART5_RXD_P1_11
#undef LPUART5_RXD_P3_11
#undef LPUART5_TXD_P1_10
#undef LPUART5_TXD_P3_10
#undef OPAMP1_INN_P2_17
#undef OPAMP1_INP_P2_16
#undef OPAMP1_OUT_P2_19
#undef OPAMP2_INN_P2_1
#undef OPAMP2_INP_P2_0
#undef OPAMP2_OUT_P2_6
#undef OPAMP3_INN_P2_21
#undef OPAMP3_INP_P2_20
#undef OPAMP3_OUT_P2_23

#endif /* _ZEPHYR_DTS_BINDING_MCXA256VLL_WRAPPER_ */
