/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA146VPJ/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA366VLL-pinctrl.h with this part's differences applied
 * below (229 removed, 0 changed,
 * 18 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: a0f6521a5e7a64e3
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA146VPJ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA146VPJ_WRAPPER_

#include "MCXA366VLL-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_A1_P2_4
#undef ADC0_A3_P2_3
#undef ADC1_A0_P2_1
#undef ADC2_A0_P2_4
#undef ADC2_A14_P0_14
#undef ADC2_A15_P0_15
#undef ADC2_A18_P4_2
#undef ADC2_A19_P4_3
#undef ADC2_A1_P2_10
#undef ADC2_A20_P4_4
#undef ADC2_A21_P4_5
#undef ADC2_A22_P4_6
#undef ADC2_A23_P4_7
#undef ADC2_A2_P2_6
#undef ADC2_A4_P2_16
#undef ADC2_A5_P2_12
#undef ADC2_A6_P2_20
#undef ADC2_A7_P2_7
#undef ADC2_A8_P0_2
#undef ADC3_A0_P2_5
#undef ADC3_A12_P3_6
#undef ADC3_A13_P3_7
#undef ADC3_A14_P3_12
#undef ADC3_A15_P3_13
#undef ADC3_A16_P3_14
#undef ADC3_A17_P3_15
#undef ADC3_A18_P3_20
#undef ADC3_A19_P3_21
#undef ADC3_A1_P2_11
#undef ADC3_A20_P3_22
#undef ADC3_A2_P2_23
#undef ADC3_A4_P2_17
#undef ADC3_A5_P2_13
#undef ADC3_A6_P2_21
#undef ADC3_A7_P2_7
#undef CAN1_RXD_P1_0
#undef CAN1_RXD_P1_12
#undef CAN1_RXD_P1_7
#undef CAN1_RXD_P2_0
#undef CAN1_RXD_P2_15
#undef CAN1_TXD_P1_1
#undef CAN1_TXD_P1_13
#undef CAN1_TXD_P1_6
#undef CAN1_TXD_P2_1
#undef CAN1_TXD_P2_16
#undef CMP2_IN0_P2_4
#undef CMP2_IN2_P0_23
#undef CMP2_IN3_P1_2
#undef CMP2_OUT_P0_20
#undef CT_INP2_P0_14
#undef CT_INP3_P0_15
#undef DAC0_OUT_P2_2
#undef FLEXIO0_D6_P0_14
#undef FLEXIO0_D7_P0_15
#undef LCD_P0_P1_0
#undef LCD_P10_P1_12
#undef LCD_P11_P1_13
#undef LCD_P12_P1_14
#undef LCD_P13_P1_15
#undef LCD_P18_P0_14
#undef LCD_P19_P0_15
#undef LCD_P1_P1_1
#undef LCD_P20_P0_16
#undef LCD_P21_P0_17
#undef LCD_P22_P0_18
#undef LCD_P23_P0_19
#undef LCD_P24_P0_20
#undef LCD_P25_P0_21
#undef LCD_P26_P0_22
#undef LCD_P27_P0_23
#undef LCD_P2_P1_2
#undef LCD_P32_P3_0
#undef LCD_P33_P3_1
#undef LCD_P34_P3_6
#undef LCD_P35_P3_7
#undef LCD_P36_P3_8
#undef LCD_P37_P3_9
#undef LCD_P38_P3_10
#undef LCD_P39_P3_11
#undef LCD_P3_P1_3
#undef LCD_P40_P3_12
#undef LCD_P41_P3_13
#undef LCD_P42_P3_14
#undef LCD_P43_P3_15
#undef LCD_P44_P3_16
#undef LCD_P45_P3_17
#undef LCD_P46_P3_18
#undef LCD_P47_P3_19
#undef LCD_P4_P1_6
#undef LCD_P5_P1_7
#undef LCD_P6_P1_8
#undef LCD_P7_P1_9
#undef LCD_P8_P1_10
#undef LCD_P9_P1_11
#undef LCD_VLL1_P1_5
#undef LCD_VLL2_P1_4
#undef LPUART5_CTS_B_P1_12
#undef LPUART5_CTS_B_P3_8
#undef LPUART5_RTS_B_P1_13
#undef LPUART5_RTS_B_P3_9
#undef LPUART5_RXD_P1_11
#undef LPUART5_RXD_P3_11
#undef LPUART5_TXD_P1_10
#undef LPUART5_TXD_P3_10
#undef OPAMP0_INN_P2_13
#undef OPAMP0_INP_P2_12
#undef OPAMP0_OUT_P2_15
#undef OPAMP1_INN_P2_17
#undef OPAMP1_INP_P2_16
#undef OPAMP1_OUT_P2_19
#undef OPAMP2_INN_P2_1
#undef OPAMP2_INP_P2_0
#undef OPAMP2_OUT_P2_6
#undef OPAMP3_INN_P2_21
#undef OPAMP3_INP_P2_20
#undef OPAMP3_OUT_P2_23
#undef P0_14
#undef P0_15
#undef PWM0_A3_P3_6
#undef PWM0_B3_P3_7
#undef PWM0_X3_P3_15
#undef PWM0_X3_P3_21
#undef PWM1_A0_P3_16
#undef PWM1_A0_P3_30
#undef PWM1_A0_P3_6
#undef PWM1_A1_P3_14
#undef PWM1_A2_P3_12
#undef PWM1_A3_P3_20
#undef PWM1_A3_P3_27
#undef PWM1_B0_P3_17
#undef PWM1_B0_P3_31
#undef PWM1_B0_P3_7
#undef PWM1_B1_P3_15
#undef PWM1_B2_P3_13
#undef PWM1_B3_P3_21
#undef PWM1_B3_P3_28
#undef PWM1_X0_P3_0
#undef PWM1_X0_P3_18
#undef PWM1_X1_P3_1
#undef PWM1_X1_P3_19
#undef PWM1_X2_P3_22
#undef SmartDMA_PIO0_P1_4
#undef SmartDMA_PIO0_P3_0
#undef SmartDMA_PIO10_P0_20
#undef SmartDMA_PIO10_P1_14
#undef SmartDMA_PIO10_P3_10
#undef SmartDMA_PIO11_P0_21
#undef SmartDMA_PIO11_P1_15
#undef SmartDMA_PIO11_P3_11
#undef SmartDMA_PIO12_P0_22
#undef SmartDMA_PIO12_P3_12
#undef SmartDMA_PIO13_P0_23
#undef SmartDMA_PIO13_P3_13
#undef SmartDMA_PIO14_P2_10
#undef SmartDMA_PIO14_P3_14
#undef SmartDMA_PIO15_P2_11
#undef SmartDMA_PIO15_P3_15
#undef SmartDMA_PIO16_P2_12
#undef SmartDMA_PIO16_P3_16
#undef SmartDMA_PIO17_P2_13
#undef SmartDMA_PIO17_P3_17
#undef SmartDMA_PIO18_P2_15
#undef SmartDMA_PIO18_P3_18
#undef SmartDMA_PIO19_P2_16
#undef SmartDMA_PIO19_P3_19
#undef SmartDMA_PIO1_P1_5
#undef SmartDMA_PIO1_P3_1
#undef SmartDMA_PIO20_P2_17
#undef SmartDMA_PIO20_P3_20
#undef SmartDMA_PIO21_P2_19
#undef SmartDMA_PIO21_P3_21
#undef SmartDMA_PIO22_P2_20
#undef SmartDMA_PIO22_P3_22
#undef SmartDMA_PIO22_P4_2
#undef SmartDMA_PIO23_P2_21
#undef SmartDMA_PIO23_P4_3
#undef SmartDMA_PIO24_P2_0
#undef SmartDMA_PIO24_P4_4
#undef SmartDMA_PIO25_P2_1
#undef SmartDMA_PIO25_P4_5
#undef SmartDMA_PIO26_P2_2
#undef SmartDMA_PIO26_P4_6
#undef SmartDMA_PIO27_P2_3
#undef SmartDMA_PIO27_P3_27
#undef SmartDMA_PIO27_P4_7
#undef SmartDMA_PIO28_P2_4
#undef SmartDMA_PIO28_P3_28
#undef SmartDMA_PIO29_P2_5
#undef SmartDMA_PIO29_P3_29
#undef SmartDMA_PIO2_P0_6
#undef SmartDMA_PIO2_P1_6
#undef SmartDMA_PIO30_P2_6
#undef SmartDMA_PIO30_P3_30
#undef SmartDMA_PIO31_P2_7
#undef SmartDMA_PIO31_P3_31
#undef SmartDMA_PIO3_P1_7
#undef SmartDMA_PIO4_P0_14
#undef SmartDMA_PIO4_P1_8
#undef SmartDMA_PIO5_P0_15
#undef SmartDMA_PIO5_P1_9
#undef SmartDMA_PIO6_P0_16
#undef SmartDMA_PIO6_P1_10
#undef SmartDMA_PIO6_P3_6
#undef SmartDMA_PIO7_P0_17
#undef SmartDMA_PIO7_P1_11
#undef SmartDMA_PIO7_P3_7
#undef SmartDMA_PIO8_P0_18
#undef SmartDMA_PIO8_P1_12
#undef SmartDMA_PIO8_P3_8
#undef SmartDMA_PIO9_P0_19
#undef SmartDMA_PIO9_P1_13
#undef SmartDMA_PIO9_P3_9
#undef TRIG_IN0
#undef TRIG_IN1
#undef TRIG_IN11
#undef TRIG_IN2
#undef TRIG_IN3
#undef TRIG_IN4
#undef TRIG_IN5
#undef TRIG_IN6
#undef TRIG_IN7
#undef UTICK_CAP0_P0_14
#undef UTICK_CAP1_P0_15
#undef WUU0_IN13_P1_15
#undef WUU0_IN17_P4_4
#undef WUU0_IN21_P2_15
#undef WUU0_IN3_P0_19
#undef WUU0_IN4_P0_20
#undef WUU0_IN5_P0_23

/* Signals specific to this part */
#define ADC0_A1_P2_1 A15X_MUX('2',1,0)
#define ADC1_A0_P2_4 A15X_MUX('2',4,0)
#define CAN0_RXD_P1_12 A15X_MUX('1',12,11)
#define CAN0_RXD_P1_7 A15X_MUX('1',7,11)
#define CAN0_TXD_P1_13 A15X_MUX('1',13,11)
#define CAN0_TXD_P1_6 A15X_MUX('1',6,11)
#define CT4_MAT0_P3_2 A15X_MUX('3',2,4)
#define CT_INP10_P1_14 A15X_MUX('1',14,4)
#define CT_INP11_P1_15 A15X_MUX('1',15,4)
#define FLEXIO0_D10_P3_2 A15X_MUX('3',2,6)
#define ISPMODE_N_P3_29 A15X_MUX('3',29,1)
#define LPSPI1_PCS1_P3_2 A15X_MUX('3',2,2)
#define P3_2 A15X_MUX('3',2,0)
#define PWM0_A0_P3_6 A15X_MUX('3',6,5)
#define PWM0_B0_P3_7 A15X_MUX('3',7,5)
#define WUU0_IN17_P4_6 A15X_MUX('4',6,0)
#define WUU0_IN31_P0_19 A15X_MUX('0',19,8)
#define WUU0_IN31_P0_6 A15X_MUX('0',6,8)

#endif /* _ZEPHYR_DTS_BINDING_MCXA146VPJ_WRAPPER_ */
