/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA365VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA366VLQ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 040f8c207631f8cd
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA365VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA365VLQ_WRAPPER_

#include "MCXA366VLQ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA365VLQ_WRAPPER_ */
