/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA173VFM/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA174VFM-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 5a7a33f05449bab9
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA173VFM_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA173VFM_WRAPPER_

#include "MCXA174VFM-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA173VFM_WRAPPER_ */
