/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA255VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA256VLQ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 821d50bf6c462c6b
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA255VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA255VLQ_WRAPPER_

#include "MCXA256VLQ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA255VLQ_WRAPPER_ */
