/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA133VFM/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA153VFM-pinctrl.h with this part's differences applied
 * below (1 removed, 0 changed,
 * 15 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: d61c6eaf169ed581
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA133VFM_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA133VFM_WRAPPER_

#include "MCXA153VFM-pinctrl.h"

/* Signals not present on this part */
#undef USB0_VBUS_DET_P2_12

/* Signals specific to this part */
#define ADC0_A6_P2_16 A15X_MUX('2',16,0)
#define CT0_MAT1_P2_13 A15X_MUX('2',13,5)
#define CT0_MAT2_P2_16 A15X_MUX('2',16,5)
#define CT0_MAT3_P2_17 A15X_MUX('2',17,5)
#define LPSPI1_PCS0_P2_17 A15X_MUX('2',17,2)
#define LPSPI1_SDI_P2_16 A15X_MUX('2',16,2)
#define LPSPI1_SDO_P2_13 A15X_MUX('2',13,2)
#define LPUART1_CTS_B_P2_17 A15X_MUX('2',17,3)
#define LPUART1_RTS_B_P2_16 A15X_MUX('2',16,3)
#define LPUART1_TXD_P2_13 A15X_MUX('2',13,3)
#define P2_13 A15X_MUX('2',13,0)
#define P2_16 A15X_MUX('2',16,0)
#define P2_17 A15X_MUX('2',17,0)
#define TRIG_IN8_P2_13 A15X_MUX('2',13,1)
#define TRIG_IN9_P2_17 A15X_MUX('2',17,1)

#endif /* _ZEPHYR_DTS_BINDING_MCXA133VFM_WRAPPER_ */
