/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA343VLH/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA344VLH-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 796e143b40c94355
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA343VLH_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA343VLH_WRAPPER_

#include "MCXA344VLH-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA343VLH_WRAPPER_ */
