/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA155VFT/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA156VFT-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: d11da2b0665754d9
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA155VFT_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA155VFT_WRAPPER_

#include "MCXA156VFT-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA155VFT_WRAPPER_ */
