/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA345VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA356VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: aa58a236e71c2066
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA345VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA345VLL_WRAPPER_

#include "MCXA356VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA345VLL_WRAPPER_ */
