/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA144VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA146VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 4113e9bd3a857cd9
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA144VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA144VLL_WRAPPER_

#include "MCXA146VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA144VLL_WRAPPER_ */
