/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA255VLH/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA256VLH-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 55372236a2f4a920
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA255VLH_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA255VLH_WRAPPER_

#include "MCXA256VLH-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA255VLH_WRAPPER_ */
