/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA145VPJ/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA146VPJ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 05214de8fd4a9c93
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA145VPJ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA145VPJ_WRAPPER_

#include "MCXA146VPJ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA145VPJ_WRAPPER_ */
