/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA536VPN/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA537VPN-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 56b58020b57aa4e0
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA536VPN_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA536VPN_WRAPPER_

#include "MCXA537VPN-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA536VPN_WRAPPER_ */
