/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA343VLF/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA344VLF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 274475298b343e90
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA343VLF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA343VLF_WRAPPER_

#include "MCXA344VLF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA343VLF_WRAPPER_ */
