/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA175VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA256VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: ddd2948b0645ffd6
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA175VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA175VLL_WRAPPER_

#include "MCXA256VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA175VLL_WRAPPER_ */
