/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA173VLF/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA174VLF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: ca2913b96703c66b
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA173VLF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA173VLF_WRAPPER_

#include "MCXA174VLF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA173VLF_WRAPPER_ */
