/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA132VFT/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA133VFT-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 5174930f7f0e676f
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA132VFT_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA132VFT_WRAPPER_

#include "MCXA133VFT-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA132VFT_WRAPPER_ */
