/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA154VPJ/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA156VPJ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 578e2406c13f9b32
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA154VPJ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA154VPJ_WRAPPER_

#include "MCXA156VPJ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA154VPJ_WRAPPER_ */
