/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA144VFT/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA146VFT-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: e8b6b48cc97289ed
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA144VFT_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA144VFT_WRAPPER_

#include "MCXA146VFT-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA144VFT_WRAPPER_ */
