/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA133VFT/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA153VFM-pinctrl.h with this part's differences applied
 * below (1 removed, 0 changed,
 * 97 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: d61c6eaf169ed581
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA133VFT_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA133VFT_WRAPPER_

#include "MCXA153VFM-pinctrl.h"

/* Signals not present on this part */
#undef USB0_VBUS_DET_P2_12

/* Signals specific to this part */
#define ADC0_A0_P2_0 A15X_MUX('2',0,0)
#define ADC0_A12_P3_31 A15X_MUX('3',31,0)
#define ADC0_A13_P3_30 A15X_MUX('3',30,0)
#define ADC0_A15_P0_6 A15X_MUX('0',6,0)
#define ADC0_A1_P2_1 A15X_MUX('2',1,0)
#define ADC0_A3_P2_6 A15X_MUX('2',6,0)
#define ADC0_A6_P2_16 A15X_MUX('2',16,0)
#define ADC0_A8_P1_10 A15X_MUX('1',10,0)
#define ADC0_A9_P1_11 A15X_MUX('1',11,0)
#define CLKOUT_P0_6 A15X_MUX('0',6,12)
#define CMP1_OUT_P0_6 A15X_MUX('0',6,8)
#define CT0_MAT0_P0_16 A15X_MUX('0',16,4)
#define CT0_MAT1_P0_17 A15X_MUX('0',17,4)
#define CT0_MAT1_P2_13 A15X_MUX('2',13,5)
#define CT0_MAT2_P2_16 A15X_MUX('2',16,5)
#define CT0_MAT2_P3_30 A15X_MUX('3',30,4)
#define CT0_MAT3_P2_17 A15X_MUX('2',17,5)
#define CT0_MAT3_P3_31 A15X_MUX('3',31,4)
#define CT1_MAT2_P2_6 A15X_MUX('2',6,5)
#define CT1_MAT2_P3_12 A15X_MUX('3',12,4)
#define CT1_MAT3_P3_13 A15X_MUX('3',13,4)
#define CT2_MAT0_P1_10 A15X_MUX('1',10,4)
#define CT2_MAT0_P2_0 A15X_MUX('2',0,5)
#define CT2_MAT0_P2_20 A15X_MUX('2',20,4)
#define CT2_MAT1_P1_11 A15X_MUX('1',11,4)
#define CT2_MAT1_P2_1 A15X_MUX('2',1,5)
#define CT2_MAT1_P2_21 A15X_MUX('2',21,4)
#define CT_INP16_P2_0 A15X_MUX('2',0,4)
#define CT_INP17_P2_1 A15X_MUX('2',1,4)
#define CT_INP18_P2_6 A15X_MUX('2',6,4)
#define CT_INP2_P0_6 A15X_MUX('0',6,4)
#define CT_INP6_P3_14 A15X_MUX('3',14,4)
#define I3C0_PUR_P1_11 A15X_MUX('1',11,10)
#define I3C0_SCL_P0_17 A15X_MUX('0',17,10)
#define I3C0_SDA_P0_16 A15X_MUX('0',16,10)
#define LPI2C0_HREQ_P0_6 A15X_MUX('0',6,2)
#define LPI2C0_SCLS_P1_11 A15X_MUX('1',11,3)
#define LPI2C0_SCL_P0_17 A15X_MUX('0',17,2)
#define LPI2C0_SDAS_P1_10 A15X_MUX('1',10,3)
#define LPI2C0_SDA_P0_16 A15X_MUX('0',16,2)
#define LPSPI0_PCS1_P0_6 A15X_MUX('0',6,3)
#define LPSPI0_PCS2_P0_16 A15X_MUX('0',16,3)
#define LPSPI0_PCS3_P0_17 A15X_MUX('0',17,3)
#define LPSPI1_PCS0_P2_17 A15X_MUX('2',17,2)
#define LPSPI1_PCS1_P2_6 A15X_MUX('2',6,2)
#define LPSPI1_PCS2_P2_20 A15X_MUX('2',20,2)
#define LPSPI1_PCS3_P2_21 A15X_MUX('2',21,2)
#define LPSPI1_SDI_P2_16 A15X_MUX('2',16,2)
#define LPSPI1_SDO_P2_13 A15X_MUX('2',13,2)
#define LPTMR0_ALT2_P3_31 A15X_MUX('3',31,0)
#define LPUART0_RXD_P2_0 A15X_MUX('2',0,2)
#define LPUART0_TXD_P2_1 A15X_MUX('2',1,2)
#define LPUART1_CTS_B_P1_11 A15X_MUX('1',11,2)
#define LPUART1_CTS_B_P2_17 A15X_MUX('2',17,3)
#define LPUART1_RTS_B_P1_10 A15X_MUX('1',10,2)
#define LPUART1_RTS_B_P2_16 A15X_MUX('2',16,3)
#define LPUART1_TXD_P2_13 A15X_MUX('2',13,3)
#define LPUART2_CTS_B_P3_13 A15X_MUX('3',13,2)
#define LPUART2_RTS_B_P3_12 A15X_MUX('3',12,2)
#define LPUART2_RXD_P3_14 A15X_MUX('3',14,2)
#define P0_16 A15X_MUX('0',16,0)
#define P0_17 A15X_MUX('0',17,0)
#define P0_6 A15X_MUX('0',6,0)
#define P1_10 A15X_MUX('1',10,0)
#define P1_11 A15X_MUX('1',11,0)
#define P2_0 A15X_MUX('2',0,0)
#define P2_1 A15X_MUX('2',1,0)
#define P2_13 A15X_MUX('2',13,0)
#define P2_16 A15X_MUX('2',16,0)
#define P2_17 A15X_MUX('2',17,0)
#define P2_20 A15X_MUX('2',20,0)
#define P2_21 A15X_MUX('2',21,0)
#define P2_6 A15X_MUX('2',6,0)
#define P3_12 A15X_MUX('3',12,0)
#define P3_13 A15X_MUX('3',13,0)
#define P3_14 A15X_MUX('3',14,0)
#define P3_30 A15X_MUX('3',30,0)
#define P3_31 A15X_MUX('3',31,0)
#define PWM0_X0_P3_12 A15X_MUX('3',12,5)
#define PWM0_X1_P3_13 A15X_MUX('3',13,5)
#define PWM0_X2_P3_14 A15X_MUX('3',14,5)
#define TRIG_IN10_P3_31 A15X_MUX('3',31,1)
#define TRIG_IN6_P2_0 A15X_MUX('2',0,1)
#define TRIG_IN7_P2_1 A15X_MUX('2',1,1)
#define TRIG_IN8_P2_13 A15X_MUX('2',13,1)
#define TRIG_IN8_P2_20 A15X_MUX('2',20,1)
#define TRIG_IN9_P2_17 A15X_MUX('2',17,1)
#define TRIG_IN9_P2_21 A15X_MUX('2',21,1)
#define TRIG_OUT2_P1_11 A15X_MUX('1',11,1)
#define TRIG_OUT4_P2_6 A15X_MUX('2',6,1)
#define TRIG_OUT6_P3_30 A15X_MUX('3',30,1)
#define UTICK_CAP2_P0_16 A15X_MUX('0',16,5)
#define UTICK_CAP3_P0_17 A15X_MUX('0',17,5)
#define WUU0_IN11_P1_11 A15X_MUX('1',11,0)
#define WUU0_IN18_P2_0 A15X_MUX('2',0,0)
#define WUU0_IN25_P3_14 A15X_MUX('3',14,0)
#define WUU0_IN2_P0_16 A15X_MUX('0',16,0)

#endif /* _ZEPHYR_DTS_BINDING_MCXA133VFT_WRAPPER_ */
