/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA186VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA266VLQ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 19899132eb5b49d5
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA186VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA186VLQ_WRAPPER_

#include "MCXA266VLQ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA186VLQ_WRAPPER_ */
