/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA343VFM/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA344VFM-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 783e6fa8c7b9a767
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA343VFM_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA343VFM_WRAPPER_

#include "MCXA344VFM-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA343VFM_WRAPPER_ */
