/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA365VLH/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA366VLH-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 32c05025efab9b57
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA365VLH_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA365VLH_WRAPPER_

#include "MCXA366VLH-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA365VLH_WRAPPER_ */
