/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA256VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA366VLL-pinctrl.h with this part's differences applied
 * below (105 removed, 0 changed,
 * 139 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 011ef572d22de35a
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA256VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA256VLQ_WRAPPER_

#include "MCXA366VLL-pinctrl.h"

/* Signals not present on this part */
#undef ADC2_A0_P2_4
#undef ADC2_A14_P0_14
#undef ADC2_A15_P0_15
#undef ADC2_A18_P4_2
#undef ADC2_A19_P4_3
#undef ADC2_A1_P2_10
#undef ADC2_A20_P4_4
#undef ADC2_A21_P4_5
#undef ADC2_A22_P4_6
#undef ADC2_A23_P4_7
#undef ADC2_A2_P2_6
#undef ADC2_A4_P2_16
#undef ADC2_A5_P2_12
#undef ADC2_A6_P2_20
#undef ADC2_A7_P2_7
#undef ADC2_A8_P0_2
#undef ADC3_A0_P2_5
#undef ADC3_A12_P3_6
#undef ADC3_A13_P3_7
#undef ADC3_A14_P3_12
#undef ADC3_A15_P3_13
#undef ADC3_A16_P3_14
#undef ADC3_A17_P3_15
#undef ADC3_A18_P3_20
#undef ADC3_A19_P3_21
#undef ADC3_A1_P2_11
#undef ADC3_A20_P3_22
#undef ADC3_A2_P2_23
#undef ADC3_A4_P2_17
#undef ADC3_A5_P2_13
#undef ADC3_A6_P2_21
#undef ADC3_A7_P2_7
#undef CAN1_RXD_P1_0
#undef CAN1_RXD_P1_12
#undef CAN1_RXD_P1_7
#undef CAN1_RXD_P2_0
#undef CAN1_RXD_P2_15
#undef CAN1_TXD_P1_1
#undef CAN1_TXD_P1_13
#undef CAN1_TXD_P1_6
#undef CAN1_TXD_P2_1
#undef CAN1_TXD_P2_16
#undef CMP2_IN0_P2_4
#undef CMP2_IN2_P0_23
#undef CMP2_IN3_P1_2
#undef CMP2_OUT_P0_20
#undef LCD_P0_P1_0
#undef LCD_P10_P1_12
#undef LCD_P11_P1_13
#undef LCD_P12_P1_14
#undef LCD_P13_P1_15
#undef LCD_P18_P0_14
#undef LCD_P19_P0_15
#undef LCD_P1_P1_1
#undef LCD_P20_P0_16
#undef LCD_P21_P0_17
#undef LCD_P22_P0_18
#undef LCD_P23_P0_19
#undef LCD_P24_P0_20
#undef LCD_P25_P0_21
#undef LCD_P26_P0_22
#undef LCD_P27_P0_23
#undef LCD_P2_P1_2
#undef LCD_P32_P3_0
#undef LCD_P33_P3_1
#undef LCD_P34_P3_6
#undef LCD_P35_P3_7
#undef LCD_P36_P3_8
#undef LCD_P37_P3_9
#undef LCD_P38_P3_10
#undef LCD_P39_P3_11
#undef LCD_P3_P1_3
#undef LCD_P40_P3_12
#undef LCD_P41_P3_13
#undef LCD_P42_P3_14
#undef LCD_P43_P3_15
#undef LCD_P44_P3_16
#undef LCD_P45_P3_17
#undef LCD_P46_P3_18
#undef LCD_P47_P3_19
#undef LCD_P4_P1_6
#undef LCD_P5_P1_7
#undef LCD_P6_P1_8
#undef LCD_P7_P1_9
#undef LCD_P8_P1_10
#undef LCD_P9_P1_11
#undef LCD_VLL1_P1_5
#undef LCD_VLL2_P1_4
#undef LPUART5_CTS_B_P1_12
#undef LPUART5_CTS_B_P3_8
#undef LPUART5_RTS_B_P1_13
#undef LPUART5_RTS_B_P3_9
#undef LPUART5_RXD_P1_11
#undef LPUART5_RXD_P3_11
#undef LPUART5_TXD_P1_10
#undef LPUART5_TXD_P3_10
#undef OPAMP1_INN_P2_17
#undef OPAMP1_INP_P2_16
#undef OPAMP1_OUT_P2_19
#undef OPAMP2_INN_P2_1
#undef OPAMP2_INP_P2_0
#undef OPAMP2_OUT_P2_6
#undef OPAMP3_INN_P2_21
#undef OPAMP3_INP_P2_20
#undef OPAMP3_OUT_P2_23

/* Signals specific to this part */
#define ADC1_A14_P1_16 A15X_MUX('1',16,0)
#define ADC1_A15_P1_17 A15X_MUX('1',17,0)
#define ADC1_A16_P1_18 A15X_MUX('1',18,0)
#define ADC1_A17_P1_19 A15X_MUX('1',19,0)
#define CAN0_RXD_P1_19 A15X_MUX('1',19,11)
#define CAN0_TXD_P1_18 A15X_MUX('1',18,11)
#define CMP1_OUT_P0_4 A15X_MUX('0',4,8)
#define CT0_MAT0_P0_24 A15X_MUX('0',24,4)
#define CT0_MAT1_P0_25 A15X_MUX('0',25,4)
#define CT0_MAT2_P0_12 A15X_MUX('0',12,4)
#define CT0_MAT2_P0_26 A15X_MUX('0',26,4)
#define CT0_MAT2_P0_4 A15X_MUX('0',4,4)
#define CT0_MAT3_P0_13 A15X_MUX('0',13,4)
#define CT0_MAT3_P0_27 A15X_MUX('0',27,4)
#define CT0_MAT3_P0_5 A15X_MUX('0',5,4)
#define CT2_MAT2_P2_22 A15X_MUX('2',22,4)
#define CT3_MAT0_P1_18 A15X_MUX('1',18,4)
#define CT3_MAT0_P2_8 A15X_MUX('2',8,4)
#define CT3_MAT1_P1_19 A15X_MUX('1',19,4)
#define CT3_MAT1_P2_9 A15X_MUX('2',9,4)
#define CT3_MAT2_P2_18 A15X_MUX('2',18,4)
#define CT4_MAT0_P3_2 A15X_MUX('3',2,4)
#define CT4_MAT1_P3_3 A15X_MUX('3',3,4)
#define CT4_MAT2_P2_14 A15X_MUX('2',14,4)
#define CT_INP10_P2_26 A15X_MUX('2',26,4)
#define CT_INP11_P3_23 A15X_MUX('3',23,4)
#define CT_INP12_P1_16 A15X_MUX('1',16,4)
#define CT_INP13_P1_17 A15X_MUX('1',17,4)
#define CT_INP14_P3_26 A15X_MUX('3',26,4)
#define CT_INP15_P3_25 A15X_MUX('3',25,4)
#define CT_INP16_P3_24 A15X_MUX('3',24,4)
#define CT_INP18_P3_4 A15X_MUX('3',4,4)
#define CT_INP19_P3_5 A15X_MUX('3',5,4)
#define CT_INP3_P0_7 A15X_MUX('0',7,4)
#define CT_INP8_P2_24 A15X_MUX('2',24,4)
#define CT_INP9_P2_25 A15X_MUX('2',25,4)
#define FLEXIO0_D10_P3_2 A15X_MUX('3',2,6)
#define FLEXIO0_D11_P3_3 A15X_MUX('3',3,6)
#define FLEXIO0_D12_P3_4 A15X_MUX('3',4,6)
#define FLEXIO0_D13_P3_5 A15X_MUX('3',5,6)
#define FLEXIO0_D16_P2_8 A15X_MUX('2',8,6)
#define FLEXIO0_D17_P2_9 A15X_MUX('2',9,6)
#define FLEXIO0_D22_P2_14 A15X_MUX('2',14,6)
#define FLEXIO0_D24_P1_16 A15X_MUX('1',16,6)
#define FLEXIO0_D24_P3_24 A15X_MUX('3',24,6)
#define FLEXIO0_D25_P1_17 A15X_MUX('1',17,6)
#define FLEXIO0_D25_P3_25 A15X_MUX('3',25,6)
#define FLEXIO0_D26_P1_18 A15X_MUX('1',18,6)
#define FLEXIO0_D26_P2_18 A15X_MUX('2',18,6)
#define FLEXIO0_D26_P3_26 A15X_MUX('3',26,6)
#define FLEXIO0_D27_P1_19 A15X_MUX('1',19,6)
#define FLEXIO0_D30_P2_22 A15X_MUX('2',22,6)
#define FLEXIO0_D31_P3_23 A15X_MUX('3',23,6)
#define FLEXIO0_D4_P0_12 A15X_MUX('0',12,6)
#define FLEXIO0_D4_P0_4 A15X_MUX('0',4,6)
#define FLEXIO0_D5_P0_13 A15X_MUX('0',13,6)
#define FLEXIO0_D5_P0_5 A15X_MUX('0',5,6)
#define FLEXIO0_D7_P0_7 A15X_MUX('0',7,6)
#define FLEXIO0_D8_P4_0 A15X_MUX('4',0,6)
#define FLEXIO0_D9_P4_1 A15X_MUX('4',1,6)
#define FREQME_CLK_IN0_P1_18 A15X_MUX('1',18,1)
#define FREQME_CLK_IN1_P1_19 A15X_MUX('1',19,1)
#define LPSPI1_PCS1_P3_2 A15X_MUX('3',2,2)
#define LPUART1_CTS_B_P3_23 A15X_MUX('3',23,3)
#define P0_12 A15X_MUX('0',12,0)
#define P0_13 A15X_MUX('0',13,0)
#define P0_24 A15X_MUX('0',24,0)
#define P0_25 A15X_MUX('0',25,0)
#define P0_26 A15X_MUX('0',26,0)
#define P0_27 A15X_MUX('0',27,0)
#define P0_4 A15X_MUX('0',4,0)
#define P0_5 A15X_MUX('0',5,0)
#define P0_7 A15X_MUX('0',7,0)
#define P1_16 A15X_MUX('1',16,0)
#define P1_17 A15X_MUX('1',17,0)
#define P1_18 A15X_MUX('1',18,0)
#define P1_19 A15X_MUX('1',19,0)
#define P2_14 A15X_MUX('2',14,0)
#define P2_18 A15X_MUX('2',18,0)
#define P2_22 A15X_MUX('2',22,0)
#define P2_24 A15X_MUX('2',24,0)
#define P2_25 A15X_MUX('2',25,0)
#define P2_26 A15X_MUX('2',26,0)
#define P2_8 A15X_MUX('2',8,0)
#define P2_9 A15X_MUX('2',9,0)
#define P3_2 A15X_MUX('3',2,0)
#define P3_23 A15X_MUX('3',23,0)
#define P3_24 A15X_MUX('3',24,0)
#define P3_25 A15X_MUX('3',25,0)
#define P3_26 A15X_MUX('3',26,0)
#define P3_3 A15X_MUX('3',3,0)
#define P3_4 A15X_MUX('3',4,0)
#define P3_5 A15X_MUX('3',5,0)
#define P4_0 A15X_MUX('4',0,0)
#define P4_1 A15X_MUX('4',1,0)
#define PWM0_A3_P4_0 A15X_MUX('4',0,5)
#define PWM0_B3_P4_1 A15X_MUX('4',1,5)
#define PWM0_X0_P3_2 A15X_MUX('3',2,5)
#define PWM0_X1_P3_3 A15X_MUX('3',3,5)
#define PWM0_X2_P3_4 A15X_MUX('3',4,5)
#define PWM0_X3_P3_5 A15X_MUX('3',5,5)
#define PWM1_X2_P3_2 A15X_MUX('3',2,7)
#define PWM1_X3_P3_23 A15X_MUX('3',23,7)
#define PWM1_X3_P3_3 A15X_MUX('3',3,7)
#define SmartDMA_PIO0_P0_4 A15X_MUX('0',4,7)
#define SmartDMA_PIO12_P1_16 A15X_MUX('1',16,7)
#define SmartDMA_PIO13_P1_17 A15X_MUX('1',17,7)
#define SmartDMA_PIO14_P1_18 A15X_MUX('1',18,7)
#define SmartDMA_PIO15_P1_19 A15X_MUX('1',19,7)
#define SmartDMA_PIO1_P0_5 A15X_MUX('0',5,7)
#define SmartDMA_PIO20_P4_0 A15X_MUX('4',0,7)
#define SmartDMA_PIO21_P4_1 A15X_MUX('4',1,7)
#define SmartDMA_PIO23_P3_23 A15X_MUX('3',23,10)
#define SmartDMA_PIO24_P3_24 A15X_MUX('3',24,10)
#define SmartDMA_PIO25_P3_25 A15X_MUX('3',25,10)
#define SmartDMA_PIO26_P3_26 A15X_MUX('3',26,10)
#define SmartDMA_PIO2_P3_2 A15X_MUX('3',2,10)
#define SmartDMA_PIO3_P0_7 A15X_MUX('0',7,7)
#define SmartDMA_PIO3_P3_3 A15X_MUX('3',3,10)
#define SmartDMA_PIO4_P3_4 A15X_MUX('3',4,10)
#define SmartDMA_PIO5_P3_5 A15X_MUX('3',5,10)
#define TAMPER2_P3_26 A15X_MUX('3',26,0)
#define TAMPER3_P3_25 A15X_MUX('3',25,0)
#define TRIG_IN10/CT_INP14_P3_26_P3_26 A15X_MUX('3',26,4)
#define TRIG_IN10_P3_26 A15X_MUX('3',26,1)
#define TRIG_IN11_P3_24 A15X_MUX('3',24,1)
#define TRIG_IN4_P2_9 A15X_MUX('2',9,1)
#define TRIG_IN5_P2_26 A15X_MUX('2',26,1)
#define TRIG_IN5_P4_0 A15X_MUX('4',0,1)
#define TRIG_OUT3_P2_8 A15X_MUX('2',8,1)
#define TRIG_OUT6_P2_24 A15X_MUX('2',24,1)
#define TRIG_OUT6_P3_25 A15X_MUX('3',25,1)
#define TRIG_OUT7_P2_25 A15X_MUX('2',25,1)
#define UTICK_CAP2_P0_4 A15X_MUX('0',4,5)
#define UTICK_CAP3_P0_5 A15X_MUX('0',5,5)
#define WUU0_IN0_P0_4 A15X_MUX('0',4,0)
#define WUU0_IN14_P1_16 A15X_MUX('1',16,0)
#define WUU0_IN15_P1_19 A15X_MUX('1',19,0)
#define WUU0_IN1_P0_7 A15X_MUX('0',7,0)

#endif /* _ZEPHYR_DTS_BINDING_MCXA256VLQ_WRAPPER_ */
