/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA144VPJ/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA146VPJ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: b8d1459fea450864
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA144VPJ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA144VPJ_WRAPPER_

#include "MCXA146VPJ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA144VPJ_WRAPPER_ */
