/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA266VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA366VLL-pinctrl.h with this part's differences applied
 * below (45 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: a0f6521a5e7a64e3
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA266VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA266VLL_WRAPPER_

#include "MCXA366VLL-pinctrl.h"

/* Signals not present on this part */
#undef ADC2_A0_P2_4
#undef ADC2_A14_P0_14
#undef ADC2_A15_P0_15
#undef ADC2_A18_P4_2
#undef ADC2_A19_P4_3
#undef ADC2_A1_P2_10
#undef ADC2_A20_P4_4
#undef ADC2_A21_P4_5
#undef ADC2_A22_P4_6
#undef ADC2_A23_P4_7
#undef ADC2_A2_P2_6
#undef ADC2_A4_P2_16
#undef ADC2_A5_P2_12
#undef ADC2_A6_P2_20
#undef ADC2_A7_P2_7
#undef ADC2_A8_P0_2
#undef ADC3_A0_P2_5
#undef ADC3_A12_P3_6
#undef ADC3_A13_P3_7
#undef ADC3_A14_P3_12
#undef ADC3_A15_P3_13
#undef ADC3_A16_P3_14
#undef ADC3_A17_P3_15
#undef ADC3_A18_P3_20
#undef ADC3_A19_P3_21
#undef ADC3_A1_P2_11
#undef ADC3_A20_P3_22
#undef ADC3_A2_P2_23
#undef ADC3_A4_P2_17
#undef ADC3_A5_P2_13
#undef ADC3_A6_P2_21
#undef ADC3_A7_P2_7
#undef CMP2_IN0_P2_4
#undef CMP2_IN2_P0_23
#undef CMP2_IN3_P1_2
#undef CMP2_OUT_P0_20
#undef OPAMP1_INN_P2_17
#undef OPAMP1_INP_P2_16
#undef OPAMP1_OUT_P2_19
#undef OPAMP2_INN_P2_1
#undef OPAMP2_INP_P2_0
#undef OPAMP2_OUT_P2_6
#undef OPAMP3_INN_P2_21
#undef OPAMP3_INP_P2_20
#undef OPAMP3_OUT_P2_23

#endif /* _ZEPHYR_DTS_BINDING_MCXA266VLL_WRAPPER_ */
