/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA142VLH/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA153VLH-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 2a82dc0544d0e713
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA142VLH_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA142VLH_WRAPPER_

#include "MCXA153VLH-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA142VLH_WRAPPER_ */
