/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA355VLH/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA356VLH-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 4b8010832bd470a2
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA355VLH_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA355VLH_WRAPPER_

#include "MCXA356VLH-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA355VLH_WRAPPER_ */
