/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA145VLL/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA146VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: bee9950356f4d812
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA145VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA145VLL_WRAPPER_

#include "MCXA146VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA145VLL_WRAPPER_ */
