/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA185VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA266VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: af60d1cfde924550
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA185VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA185VLL_WRAPPER_

#include "MCXA266VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA185VLL_WRAPPER_ */
