/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA144VMP/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA146VMP-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 1f7fc2412e2f692d
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA144VMP_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA144VMP_WRAPPER_

#include "MCXA146VMP-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA144VMP_WRAPPER_ */
