/*
 * Copyright 2022-2024 NXP
 * SPDX-License-Identifier: Apache-2.0
 *
 * Note: File generated by parse_iomux.py
 * for RW610
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to RW612-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: b3a0019f24066054
 */

#ifndef _ZEPHYR_DTS_BINDING_RW610_WRAPPER_
#define _ZEPHYR_DTS_BINDING_RW610_WRAPPER_

#include "RW612-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_RW610_WRAPPER_ */
