/*
 * NOTE: Autogenerated file by kinetis_cfg_utils.py
 * for S32K142W_LQFP48/signal_configuration.xml
 *
 * Copyright 2023, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to S32K144W_LQFP48-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 5d2a626aceab0128
 */

#ifndef _ZEPHYR_DTS_BINDING_S32K142W_LQFP48_WRAPPER_
#define _ZEPHYR_DTS_BINDING_S32K142W_LQFP48_WRAPPER_

#include "S32K144W_LQFP48-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_S32K142W_LQFP48_WRAPPER_ */
