/*
 * NOTE: Autogenerated file by kinetis_cfg_utils.py
 * for S32K146_LQFP100/signal_configuration.xml
 *
 * Copyright 2023, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to S32K146_BGA100-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 4dd60ce533fd777b
 */

#ifndef _ZEPHYR_DTS_BINDING_S32K146_LQFP100_WRAPPER_
#define _ZEPHYR_DTS_BINDING_S32K146_LQFP100_WRAPPER_

#include "S32K146_BGA100-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_S32K146_LQFP100_WRAPPER_ */
