/*
 * NOTE: Autogenerated file by kinetis_cfg_utils.py
 * for S32K148_LQFP144/signal_configuration.xml
 *
 * Copyright 2023, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on S32K148_LQFP176-pinctrl.h with this part's differences applied
 * below (74 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: c2dcaaa324fdbc4b
 */

#ifndef _ZEPHYR_DTS_BINDING_S32K148_LQFP144_WRAPPER_
#define _ZEPHYR_DTS_BINDING_S32K148_LQFP144_WRAPPER_

#include "S32K148_LQFP176-pinctrl.h"

/* Signals not present on this part */
#undef FTM4_CH0_PTA18
#undef FTM4_CH0_PTC24
#undef FTM4_CH1_PTA19
#undef FTM4_CH1_PTC25
#undef FTM4_CH2_PTA20
#undef FTM4_CH3_PTA21
#undef FTM4_CH3_PTC26
#undef FTM4_CH4_PTA22
#undef FTM4_CH6_PTA23
#undef FTM4_CH6_PTE26
#undef FTM4_CH7_PTA24
#undef FTM4_CH7_PTE27
#undef FTM5_CH7_PTB19
#undef FTM6_CH0_PTA18
#undef FTM6_CH1_PTD20
#undef FTM6_CH2_PTD21
#undef FTM6_CH4_PTB24
#undef FTM6_CH6_PTB26
#undef FTM6_CH6_PTD25
#undef FTM6_CH7_PTD26
#undef FTM6_FLT0_PTD31
#undef FTM7_CH2_PTB30
#undef FTM7_CH3_PTB31
#undef FTM7_CH4_PTC18
#undef FTM7_CH4_PTD31
#undef FTM7_CH5_PTE17
#undef FTM7_CH6_PTC20
#undef FTM7_CH6_PTE18
#undef FTM7_CH7_PTC21
#undef FTM7_FLT0_PTC21
#undef FTM7_FLT1_PTC22
#undef FXIO_D0_PTA21
#undef FXIO_D1_PTA22
#undef FXIO_D2_PTA23
#undef FXIO_D3_PTA24
#undef FXIO_D4_PTE18
#undef FXIO_D5_PTE17
#undef FXIO_D6_PTD31
#undef FXIO_D7_PTD26
#undef LPSPI1_PCS0_PTA21
#undef LPSPI1_PCS1_PTA22
#undef LPSPI1_SCK_PTA19
#undef LPSPI1_SIN_PTA20
#undef LPSPI1_SOUT_PTA18
#undef LPUART1_RX_PTA19
#undef LPUART1_TX_PTA18
#undef PTA18
#undef PTA19
#undef PTA20
#undef PTA21
#undef PTA22
#undef PTA23
#undef PTA24
#undef PTB19
#undef PTB24
#undef PTB26
#undef PTB30
#undef PTB31
#undef PTC18
#undef PTC20
#undef PTC21
#undef PTC22
#undef PTC24
#undef PTC25
#undef PTC26
#undef PTD20
#undef PTD21
#undef PTD25
#undef PTD26
#undef PTD31
#undef PTE17
#undef PTE18
#undef PTE26
#undef PTE27

#endif /* _ZEPHYR_DTS_BINDING_S32K148_LQFP144_WRAPPER_ */
