/*
 * NOTE: Autogenerated file by kinetis_cfg_utils.py
 * for S32K142_LQFP48/signal_configuration.xml
 *
 * Copyright 2023, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on S32K146_LQFP64-pinctrl.h with this part's differences applied
 * below (85 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 7d1b1be1e8f1c84f
 */

#ifndef _ZEPHYR_DTS_BINDING_S32K142_LQFP48_WRAPPER_
#define _ZEPHYR_DTS_BINDING_S32K142_LQFP48_WRAPPER_

#include "S32K146_LQFP64-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE15_PTC17
#undef ADC0_SE2_PTA6
#undef ADC0_SE8_PTC0
#undef ADC1_SE10_PTE2
#undef ADC1_SE11_PTE6
#undef ADC1_SE6_PTD4
#undef ADC1_SE7_PTB12
#undef CAN2_RX_PTB12
#undef CAN2_RX_PTC16
#undef CAN2_TX_PTB13
#undef CAN2_TX_PTC17
#undef CLKOUT_PTE10
#undef CMP0_IN6_PTD7
#undef CMP0_IN7_PTD6
#undef CMP0_OUT_PTE3
#undef FTM0_CH0_PTB12
#undef FTM0_CH0_PTC0
#undef FTM0_CH7_PTE7
#undef FTM0_FLT0_PTE3
#undef FTM0_FLT1_PTA6
#undef FTM0_FLT3_PTD4
#undef FTM1_CH6_PTC0
#undef FTM1_FLT1_PTE1
#undef FTM1_FLT2_PTE0
#undef FTM1_FLT3_PTC17
#undef FTM2_CH4_PTE10
#undef FTM2_CH5_PTE11
#undef FTM2_FLT0_PTE3
#undef FTM2_FLT2_PTD6
#undef FTM2_FLT3_PTD7
#undef FTM3_CH6_PTE2
#undef FTM3_CH7_PTE6
#undef FTM3_FLT0_PTE7
#undef FTM3_FLT2_PTB12
#undef FTM3_FLT3_PTD4
#undef FTM4_CH5_PTB1
#undef FTM4_CH6_PTB0
#undef FTM5_CH0_PTC9
#undef FTM5_CH1_PTC8
#undef FTM5_CH3_PTA7
#undef FTM5_CH5_PTA6
#undef FXIO_D4_PTE10
#undef FXIO_D5_PTE11
#undef LPI2C0_HREQ_PTE1
#undef LPSPI0_PCS2_PTE6
#undef LPSPI0_SCK_PTE0
#undef LPSPI0_SIN_PTE1
#undef LPSPI0_SOUT_PTE2
#undef LPSPI1_PCS0_PTE1
#undef LPSPI1_PCS1_PTA6
#undef LPSPI1_SOUT_PTE0
#undef LPSPI2_PCS0_PTC14
#undef LPSPI2_PCS0_PTE11
#undef LPSPI2_PCS1_PTE10
#undef LPSPI2_SCK_PTC15
#undef LPSPI2_SIN_PTC0
#undef LPSPI2_SOUT_PTC1
#undef LPTMR0_ALT1_PTE11
#undef LPTMR0_ALT3_PTE2
#undef LPUART1_CTS_PTA6
#undef LPUART1_CTS_PTE2
#undef LPUART1_RTS_PTE6
#undef LPUART2_CTS_PTE9
#undef LPUART2_RTS_PTE3
#undef LPUART2_RX_PTD6
#undef LPUART2_TX_PTD7
#undef PTA6
#undef PTB12
#undef PTC0
#undef PTC17
#undef PTD4
#undef PTD6
#undef PTD7
#undef PTE0
#undef PTE1
#undef PTE10
#undef PTE11
#undef PTE2
#undef PTE3
#undef PTE6
#undef PTE7
#undef TCLK1_PTE0
#undef TRGMUX_IN6_PTE3
#undef TRGMUX_OUT4_PTE10
#undef TRGMUX_OUT5_PTE11

#endif /* _ZEPHYR_DTS_BINDING_S32K142_LQFP48_WRAPPER_ */
