/*
 * NOTE: Autogenerated file by kinetis_cfg_utils.py
 * for S32K144_LQFP64/signal_configuration.xml
 *
 * Copyright 2023, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on S32K146_LQFP64-pinctrl.h with this part's differences applied
 * below (6 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 7d1b1be1e8f1c84f
 */

#ifndef _ZEPHYR_DTS_BINDING_S32K144_LQFP64_WRAPPER_
#define _ZEPHYR_DTS_BINDING_S32K144_LQFP64_WRAPPER_

#include "S32K146_LQFP64-pinctrl.h"

/* Signals not present on this part */
#undef FTM4_CH5_PTB1
#undef FTM4_CH6_PTB0
#undef FTM5_CH0_PTC9
#undef FTM5_CH1_PTC8
#undef FTM5_CH3_PTA7
#undef FTM5_CH5_PTA6

#endif /* _ZEPHYR_DTS_BINDING_S32K144_LQFP64_WRAPPER_ */
