/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * Copyright 2020 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _STARTUP_CLOCK_MODE_CONFIG_H_
#define _STARTUP_CLOCK_MODE_CONFIG_H_

/* Choose if set the MCU to fast mode at startup phase 
 * NOTE: Pay attention that if there is macro definition 
 * _SWITCH_TO_FAST_MODE_AT_STARTUP in project build option, 
 * since it has higher priority than the macro definition 
 * in this file.
 */
#ifndef _SWITCH_TO_FAST_MODE_AT_STARTUP
#define _SWITCH_TO_FAST_MODE_AT_STARTUP 0U
#endif  /* _SWITCH_TO_FAST_MODE_AT_STARTUP */

#endif /* _STARTUP_CLOCK_MODE_CONFIG_H_ */
