/*!
 * Copyright 2025 NXP
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * \file SecLib_psa_config.h
 * \brief Config file used as MBEDTLS_CONFIG_FILE for SecLib PSA port
 *
 */

#ifndef PSA_CRYPTO_CONFIG_H
#define PSA_CRYPTO_CONFIG_H

#include "mcux_mbedtls_accelerator_config.h"

/* undef all previous definitions from MBEDTLS_CONFIG_FILE="mcux_mbedtls_psa_crypto_config.h" for memory optimization*/
#undef MBEDTLS_HAVE_ASM
#undef MBEDTLS_CIPHER_MODE_CBC
#undef MBEDTLS_CIPHER_MODE_CFB
#undef MBEDTLS_CIPHER_MODE_CTR
#undef MBEDTLS_CIPHER_MODE_OFB
#undef MBEDTLS_CIPHER_MODE_XTS
#undef MBEDTLS_CIPHER_PADDING_PKCS7
#undef MBEDTLS_CIPHER_PADDING_ONE_AND_ZEROS
#undef MBEDTLS_CIPHER_PADDING_ZEROS_AND_LEN
#undef MBEDTLS_CIPHER_PADDING_ZEROS
#undef MBEDTLS_ECP_DP_SECP192R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP256R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP384R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP521R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP192K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP256K1_ENABLED
#undef MBEDTLS_ECP_DP_BP256R1_ENABLED
#undef MBEDTLS_ECP_DP_BP384R1_ENABLED
#undef MBEDTLS_ECP_DP_BP512R1_ENABLED
#undef MBEDTLS_ECP_DP_CURVE25519_ENABLED
#undef MBEDTLS_ECP_DP_CURVE448_ENABLED
#undef MBEDTLS_ECP_NIST_OPTIM
#undef MBEDTLS_ECDSA_DETERMINISTIC
#undef MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED
#undef MBEDTLS_PK_PARSE_EC_EXTENDED
#undef MBEDTLS_PK_PARSE_EC_COMPRESSED
#undef MBEDTLS_ERROR_STRERROR_DUMMY
#undef MBEDTLS_GENPRIME
#undef MBEDTLS_NO_PLATFORM_ENTROPY
#undef MBEDTLS_PK_RSA_ALT_SUPPORT
#undef MBEDTLS_PKCS1_V15
#undef MBEDTLS_PKCS1_V21
#undef MBEDTLS_SELF_TEST
#undef MBEDTLS_USE_PSA_CRYPTO
#undef MBEDTLS_X509_RSASSA_PSS_SUPPORT
#undef MBEDTLS_AESNI_C
#undef MBEDTLS_AESCE_C
#undef MBEDTLS_AES_C
#undef MBEDTLS_ASN1_PARSE_C
#undef MBEDTLS_ASN1_WRITE_C
#undef MBEDTLS_BASE64_C
#undef MBEDTLS_BIGNUM_C
#undef MBEDTLS_CCM_C
#undef MBEDTLS_CIPHER_C
#undef MBEDTLS_CMAC_C
#undef MBEDTLS_CTR_DRBG_C
#undef MBEDTLS_DES_C
#undef MBEDTLS_DHM_C
#undef MBEDTLS_ECDH_C
#undef MBEDTLS_ECDSA_C
#undef MBEDTLS_ECP_C
#undef MBEDTLS_ENTROPY_C
#undef MBEDTLS_GCM_C
#undef MBEDTLS_HKDF_C
#undef MBEDTLS_HMAC_DRBG_C
#undef MBEDTLS_MD_C
#undef MBEDTLS_MD5_C
#undef MBEDTLS_OID_C
#undef MBEDTLS_PADLOCK_C
#undef MBEDTLS_PEM_PARSE_C
#undef MBEDTLS_PEM_WRITE_C
#undef MBEDTLS_PK_C
#undef MBEDTLS_PK_PARSE_C
#undef MBEDTLS_PK_WRITE_C
#undef MBEDTLS_PKCS5_C
#undef MBEDTLS_PKCS12_C
#undef MBEDTLS_PLATFORM_C
#undef MBEDTLS_POLY1305_C
#undef MBEDTLS_PSA_CRYPTO_C
#undef MBEDTLS_RSA_C
#undef MBEDTLS_SHA1_C
#undef MBEDTLS_SHA224_C
#undef MBEDTLS_SHA256_C
#undef MBEDTLS_SHA384_C
#undef MBEDTLS_SHA512_C
#undef MBEDTLS_SHA3_C
#undef MBEDTLS_VERSION_C

/* Optimized PSA configuration */
#define MBEDTLS_PSA_CRYPTO_C            1
#define MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG 1
#define MBEDTLS_PSA_CRYPTO_CONFIG       1

#define MBEDTLS_PLATFORM_C      1
#define MBEDTLS_PLATFORM_MEMORY 1

#ifdef MBEDTLS_PLATFORM_MEMORY
#include "fsl_component_mem_manager.h"
#endif

#define MBEDTLS_PLATFORM_CALLOC_MACRO (void *)MEM_CallocAlt
#define MBEDTLS_PLATFORM_FREE_MACRO   MEM_BufferFree

#define MBEDTLS_PSA_ACCEL_ALG_SHA_256                    1
#define MBEDTLS_PSA_ACCEL_ALG_SHA_512                    1
#define MBEDTLS_PSA_ACCEL_ALG_ECB_NO_PADDING             1
#define MBEDTLS_PSA_ACCEL_ALG_CCM                        1
#define MBEDTLS_PSA_ACCEL_ALG_GCM                        1
#define MBEDTLS_PSA_ACCEL_ALG_CMAC                       1
#define MBEDTLS_PSA_ACCEL_KEY_TYPE_AES                   1
#define MBEDTLS_PSA_ACCEL_KEY_TYPE_ECC_KEY_PAIR_GENERATE 1

#define PSA_WANT_ALG_SHA_256        1
#define PSA_WANT_ALG_SHA_512        1
#define PSA_WANT_ALG_ECB_NO_PADDING 1
#define PSA_WANT_ALG_CCM            1
#define PSA_WANT_ALG_GCM            1
#define PSA_WANT_ALG_CMAC           1

#define PSA_WANT_KEY_TYPE_AES                   1
#define PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_GENERATE 1
#define PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_EXPORT   1
#define PSA_WANT_KEY_TYPE_HMAC                  1

#define PSA_WANT_ECC_MONTGOMERY_255 1
#define PSA_WANT_ECC_SECP_R1_256    1

/*
 * The following symbols extend and deprecate the legacy
 * PSA_WANT_KEY_TYPE_xxx_KEY_PAIR ones. They include the usage of that key in
 * the name's suffix. "_USE" is the most generic and it can be used to describe
 * a generic suport, whereas other ones add more features on top of that and
 * they are more specific.
 */

#endif /* PSA_CRYPTO_CONFIG_H */