# The west manifest file (west.yml) for MCUXpresso SDK overall delivery.
#
# The per-workspace west configuration file, ${workspace_path}/.west/config,
# specifies the path of the project containing this manifest file, the
# path is relative to the workspace location ${workspace_path}.
#
#     [manifest]
#     path = core
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html

manifest:
  
  remotes:
    - name: nxpmicro
      url-base: https://github.com/NXPmicro
    - name: nxp
      url-base: https://github.com/NXP

  defaults:
    remote: nxpmicro

  projects:
    - name: mcux-sdk-examples
      revision: 07dfa7fda416cf01e525df1ebbfccc60f956f260
      path: examples
    - name: FreeRTOS-Kernel
      revision: MCUX_2.11.0
      path: rtos/freertos/freertos_kernel
    - name: mcux-sdk-middleware-sdmmc
      revision: MCUX_2.11.0
      path: middleware/sdmmc
    - name: mcux-sdk-middleware-multicore
      path: middleware/multicore
      revision: MCUX_2.11.0
    - name: rpmsg-lite
      path: middleware/multicore/rpmsg_lite
      url:  https://github.com/NXPmicro/rpmsg-lite
      revision: v3.2.0
    - name: erpc
      path: middleware/multicore/erpc
      url:  https://github.com/EmbeddedRPC/erpc
      revision: 1.9.0
    - name: mcux-soc-svd
      revision: 5946ee393984e3708b8df7cc8ced836bf69c324a
      path: svd
    - name: fatfs
      path: middleware/fatfs
      revision: MCUX_2.11.0
    - name: mcux-sdk-middleware-eiq
      revision: MCUX_2.11.0
      path: middleware/eiq
    - name: mcux-sdk-middleware-deepviewrt
      revision: MCUX_2.11.0
      path: middleware/eiq/deepviewrt
    - name: mcux-sdk-middleware-glow
      revision: MCUX_2.11.0
      path: middleware/eiq/glow
    - name: mcux-sdk-middleware-tensorflow
      revision: MCUX_2.11.0
      path: middleware/eiq/tensorflow-lite
    - name: mcux-sdk-middleware-usb
      path: middleware/usb
      revision: MCUX_2.11.0
    - name: mcux-sdk-middleware-edgefast-bluetooth
      path: middleware/edgefast_bluetooth
      revision: MCUX_2.11.0
    - name: mcux-sdk-middleware-ethermind
      path: middleware/wireless/ethermind
      revision: MCUX_2.11.0
    - name: azure-rtos
      path: rtos/azure-rtos
      revision: MCUX_2.11.0
      remote: nxp
    - name: threadx
      path: rtos/azure-rtos/threadx
      revision: MCUX_2.11.0
      remote: nxp
    - name: filex
      path: rtos/azure-rtos/filex
      revision: MCUX_2.11.0
      remote: nxp
    - name: levelx
      path: rtos/azure-rtos/levelx
      revision: MCUX_2.11.0
      remote: nxp
    - name: netxduo
      path: rtos/azure-rtos/netxduo
      revision: MCUX_2.11.0
      remote: nxp
    - name: usbx
      path: rtos/azure-rtos/usbx
      revision: MCUX_2.11.0
      remote: nxp
    - name: guix
      path: rtos/azure-rtos/guix
      revision: MCUX_2.11.0
      remote: nxp
  self:
    path: core
