# The west manifest file (west.yml) for MCUXpresso SDK overall delivery.
#
# The per-workspace west configuration file, ${workspace_path}/.west/config,
# specifies the path of the project containing this manifest file, the
# path is relative to the workspace location ${workspace_path}.
#
#     [manifest]
#     path = core
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  remotes:
  - name: nxpmicro
    url-base: https://github.com/NXPmicro
  - name: nxp
    url-base: https://github.com/NXP
  defaults:
    remote: nxpmicro
  projects:
  - name: mcux-sdk-examples
    revision: MCUX_2.12.0_UPDATE
    path: examples
  - name: FreeRTOS-Kernel
    revision: MCUX_2.12.0
    path: rtos/freertos/freertos_kernel
  - name: mcux-sdk-middleware-sdmmc
    revision: MCUX_2.12.0
    path: middleware/sdmmc
  - name: mcux-sdk-middleware-multicore
    path: middleware/multicore
    revision: MCUX_2.12.0
  - name: rpmsg-lite
    path: middleware/multicore/rpmsg_lite
    url: https://github.com/NXPmicro/rpmsg-lite
    revision: v4.0.0
  - name: erpc
    path: middleware/multicore/erpc
    url: https://github.com/EmbeddedRPC/erpc
    revision: 1.9.1
  - name: mcux-soc-svd
    revision: bbcf98332cafaa8e9200ebfc53b08e9634b94e6c
    path: svd
  - name: fatfs
    path: middleware/fatfs
    revision: MCUX_2.12.0
  - name: mcux-sdk-middleware-eiq
    revision: MCUX_2.12.0
    path: middleware/eiq
  - name: mcux-sdk-middleware-deepviewrt
    revision: MCUX_2.12.0
    path: middleware/eiq/deepviewrt
  - name: mcux-sdk-middleware-glow
    revision: MCUX_2.12.0
    path: middleware/eiq/glow
  - name: mcux-sdk-middleware-tensorflow
    revision: MCUX_2.12.0
    path: middleware/eiq/tensorflow-lite
  - name: mcux-sdk-middleware-usb
    path: middleware/usb
    revision: MCUX_2.12.0
  - name: mcux-sdk-middleware-edgefast-bluetooth
    path: middleware/edgefast_bluetooth
    revision: MCUX_2.12.0
  - name: mcux-sdk-middleware-ethermind
    path: middleware/wireless/ethermind
    revision: MCUX_2.12.0
    remote: nxp
  - name: azure-rtos
    path: rtos/azure-rtos
    revision: MCUX_2.12.0
    remote: nxp
  - name: threadx
    path: rtos/azure-rtos/threadx
    revision: MCUX_2.12.0
    remote: nxp
  - name: filex
    path: rtos/azure-rtos/filex
    revision: MCUX_2.12.0
    remote: nxp
  - name: levelx
    path: rtos/azure-rtos/levelx
    revision: MCUX_2.12.0
    remote: nxp
  - name: netxduo
    path: rtos/azure-rtos/netxduo
    revision: MCUX_2.12.0
    remote: nxp
  - name: usbx
    path: rtos/azure-rtos/usbx
    revision: MCUX_2.12.0
    remote: nxp
  - name: guix
    path: rtos/azure-rtos/guix
    revision: MCUX_2.12.0
    remote: nxp
  - name: mbedtls
    path: middleware/mbedtls
    revision: MCUX_2.12.0
  - name: wifi_nxp
    path: middleware/wifi_nxp
    revision: MCUX_2.12.0
    remote: nxp
  - name: lwip
    path: middleware/lwip
    revision: a9b2406ad87c00cb2228ddbbc89085e8130963bd
  - name: littlefs
    path: middleware/littlefs
    revision: 40f28b24a0c9e0087d4641601f4c1f391e21d7d5

  self:
    path: core
