/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MK64FN1M0VMD12/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MK64FN1M0VLQ12-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 2d8eea352d5c8b96
 */

#ifndef _ZEPHYR_DTS_BINDING_MK64FN1M0VMD12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK64FN1M0VMD12_WRAPPER_

#include "MK64FN1M0VLQ12-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK64FN1M0VMD12_WRAPPER_ */
