/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK64FX512VMD12/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MK64FX512VLQ12-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 05c4b096a0287829
 */

#ifndef _ZEPHYR_DTS_BINDING_MK64FX512VMD12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK64FX512VMD12_WRAPPER_

#include "MK64FX512VLQ12-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK64FX512VMD12_WRAPPER_ */
