/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK65FX1M0CAC18/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MK65FN2M0CAC18-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 4c68b846255b82cd
 */

#ifndef _ZEPHYR_DTS_BINDING_MK65FX1M0CAC18_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK65FX1M0CAC18_WRAPPER_

#include "MK65FN2M0CAC18-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK65FX1M0CAC18_WRAPPER_ */
