/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MKE18F256VLL16/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MKE18F512VLL16-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: f219a321f9d17b88
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE18F256VLL16_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE18F256VLL16_WRAPPER_

#include "MKE18F512VLL16-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MKE18F256VLL16_WRAPPER_ */
