/*
 * NOTE: File generated by gen_soc_headers.py
 * from MIMXRT555SFAWC/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MIMXRT595SFAWC-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: ec1683e6b2d53d0b
 */

#ifndef _ZEPHYR_DTS_BINDING_MIMXRT555SFAWC_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MIMXRT555SFAWC_WRAPPER_

#include "MIMXRT595SFAWC-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MIMXRT555SFAWC_WRAPPER_ */
