/*
 * NOTE: File generated by gen_soc_headers.py
 * from MIMXRT735SGFOB/signal_configuration.xml
 *
 * Copyright 2025, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MIMXRT798SGFOB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 0f2d163db779bb12
 */

#ifndef _ZEPHYR_DTS_BINDING_MIMXRT735SGFOB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MIMXRT735SGFOB_WRAPPER_

#include "MIMXRT798SGFOB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MIMXRT735SGFOB_WRAPPER_ */
