/*
 * NOTE: File generated by gen_soc_headers.py
 * from MIMXRT633SFFOB/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MIMXRT685SFFOB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 432faede1015baa3
 */

#ifndef _ZEPHYR_DTS_BINDING_MIMXRT633SFFOB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MIMXRT633SFFOB_WRAPPER_

#include "MIMXRT685SFFOB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MIMXRT633SFFOB_WRAPPER_ */
