/*
 * NOTE: File generated by gen_soc_headers.py
 * from MIMXRT555SFFOC/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MIMXRT595SFFOC-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 4797d670b5ae1356
 */

#ifndef _ZEPHYR_DTS_BINDING_MIMXRT555SFFOC_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MIMXRT555SFFOC_WRAPPER_

#include "MIMXRT595SFFOC-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MIMXRT555SFFOC_WRAPPER_ */
