/*
 * Copyright 1997-2016 Freescale Semiconductor, Inc.
 * Copyright 2016-2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*!
 * @file S32Z2_PMC.h
 * @version 2.3
 * @date 2024-05-03
 * @brief Peripheral Access Layer for S32Z2_PMC
 *
 * This file contains register definitions and macros for easy access to their
 * bit fields.
 *
 * This file assumes LITTLE endian system.
 */

/**
* @page misra_violations MISRA-C:2012 violations
*
* @section [global]
* Violates MISRA 2012 Advisory Rule 2.3, local typedef not referenced
* The SoC header defines typedef for all modules.
*
* @section [global]
* Violates MISRA 2012 Advisory Rule 2.5, local macro not referenced
* The SoC header defines macros for all modules and registers.
*
* @section [global]
* Violates MISRA 2012 Advisory Directive 4.9, Function-like macro
* These are generated macros used for accessing the bit-fields from registers.
*
* @section [global]
* Violates MISRA 2012 Required Rule 5.1, identifier clash
* The supported compilers use more than 31 significant characters for identifiers.
*
* @section [global]
* Violates MISRA 2012 Required Rule 5.2, identifier clash
* The supported compilers use more than 31 significant characters for identifiers.
*
* @section [global]
* Violates MISRA 2012 Required Rule 5.4, identifier clash
* The supported compilers use more than 31 significant characters for identifiers.
*
* @section [global]
* Violates MISRA 2012 Required Rule 5.5, identifier clash
* The supported compilers use more than 31 significant characters for identifiers.
*
* @section [global]
* Violates MISRA 2012 Required Rule 21.1, defined macro '__I' is reserved to the compiler
* This type qualifier is needed to ensure correct I/O access and addressing.
*/

/* Prevention from multiple including the same memory map */
#if !defined(S32Z2_PMC_H_)  /* Check if memory map has not been already included */
#define S32Z2_PMC_H_

#include "S32Z2_COMMON.h"

/* ----------------------------------------------------------------------------
   -- PMC Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup PMC_Peripheral_Access_Layer PMC Peripheral Access Layer
 * @{
 */

/** PMC - Size of Registers Arrays */
#define PMC_POR_WDOG_EVENT_CAPTURE_COUNT          3u

/** PMC - Register Layout Typedef */
typedef struct {
  __IO uint32_t SSR;                               /**< Source of System Reset, offset: 0x0 */
  __IO uint32_t NCSPD_CTL;                         /**< Non-Critical Supply Presence Detector Control, offset: 0x4 */
  uint8_t RESERVED_0[4];
  __I  uint32_t NCSPD_STAT;                        /**< NCSPD Status Register, offset: 0xC */
  __IO uint32_t CSPD_EVENT_CAPTURE;                /**< CSPD Event Capture (CSPDEF), offset: 0x10 */
  __IO uint32_t NCSPD_EVENT_CAPTURE;               /**< NCSPD Event Flag (NCSPDEF), offset: 0x14 */
  uint8_t RESERVED_1[4];
  __IO uint32_t POR_WDOG_EVENT_CAPTURE[PMC_POR_WDOG_EVENT_CAPTURE_COUNT]; /**< Device Status Flag (DSF0)..Device Status Flag (DSF2), array offset: 0x1C, array step: 0x4 */
} PMC_Type, *PMC_MemMapPtr;

/** Number of instances of the PMC module. */
#define PMC_INSTANCE_COUNT                       (1u)

/* PMC - Peripheral instance base addresses */
/** Peripheral PMC base address */
#define IP_PMC_BASE                              (0x40250000u)
/** Peripheral PMC base pointer */
#define IP_PMC                                   ((PMC_Type *)IP_PMC_BASE)
/** Array initializer of PMC peripheral base addresses */
#define IP_PMC_BASE_ADDRS                        { IP_PMC_BASE }
/** Array initializer of PMC peripheral base pointers */
#define IP_PMC_BASE_PTRS                         { IP_PMC }

/* ----------------------------------------------------------------------------
   -- PMC Register Masks
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup PMC_Register_Masks PMC Register Masks
 * @{
 */

/*! @name SSR - Source of System Reset */
/*! @{ */

#define PMC_SSR_POR_SUP_MASK                     (0x1U)
#define PMC_SSR_POR_SUP_SHIFT                    (0U)
#define PMC_SSR_POR_SUP_WIDTH                    (1U)
#define PMC_SSR_POR_SUP(x)                       (((uint32_t)(((uint32_t)(x)) << PMC_SSR_POR_SUP_SHIFT)) & PMC_SSR_POR_SUP_MASK)

#define PMC_SSR_CSPD_EVENT_MASK                  (0x2U)
#define PMC_SSR_CSPD_EVENT_SHIFT                 (1U)
#define PMC_SSR_CSPD_EVENT_WIDTH                 (1U)
#define PMC_SSR_CSPD_EVENT(x)                    (((uint32_t)(((uint32_t)(x)) << PMC_SSR_CSPD_EVENT_SHIFT)) & PMC_SSR_CSPD_EVENT_MASK)

#define PMC_SSR_POR_WDOG_EVENT_MASK              (0x4U)
#define PMC_SSR_POR_WDOG_EVENT_SHIFT             (2U)
#define PMC_SSR_POR_WDOG_EVENT_WIDTH             (1U)
#define PMC_SSR_POR_WDOG_EVENT(x)                (((uint32_t)(((uint32_t)(x)) << PMC_SSR_POR_WDOG_EVENT_SHIFT)) & PMC_SSR_POR_WDOG_EVENT_MASK)
/*! @} */

/*! @name NCSPD_CTL - Non-Critical Supply Presence Detector Control */
/*! @{ */

#define PMC_NCSPD_CTL_NCSPD_CTL0_MASK            (0x1U)
#define PMC_NCSPD_CTL_NCSPD_CTL0_SHIFT           (0U)
#define PMC_NCSPD_CTL_NCSPD_CTL0_WIDTH           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL0(x)              (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL0_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL0_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL1_MASK            (0x2U)
#define PMC_NCSPD_CTL_NCSPD_CTL1_SHIFT           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL1_WIDTH           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL1(x)              (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL1_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL1_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL2_MASK            (0x4U)
#define PMC_NCSPD_CTL_NCSPD_CTL2_SHIFT           (2U)
#define PMC_NCSPD_CTL_NCSPD_CTL2_WIDTH           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL2(x)              (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL2_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL2_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL3_MASK            (0x8U)
#define PMC_NCSPD_CTL_NCSPD_CTL3_SHIFT           (3U)
#define PMC_NCSPD_CTL_NCSPD_CTL3_WIDTH           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL3(x)              (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL3_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL3_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL4_MASK            (0x10U)
#define PMC_NCSPD_CTL_NCSPD_CTL4_SHIFT           (4U)
#define PMC_NCSPD_CTL_NCSPD_CTL4_WIDTH           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL4(x)              (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL4_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL4_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL5_MASK            (0x20U)
#define PMC_NCSPD_CTL_NCSPD_CTL5_SHIFT           (5U)
#define PMC_NCSPD_CTL_NCSPD_CTL5_WIDTH           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL5(x)              (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL5_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL5_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL6_MASK            (0x40U)
#define PMC_NCSPD_CTL_NCSPD_CTL6_SHIFT           (6U)
#define PMC_NCSPD_CTL_NCSPD_CTL6_WIDTH           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL6(x)              (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL6_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL6_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL7_MASK            (0x80U)
#define PMC_NCSPD_CTL_NCSPD_CTL7_SHIFT           (7U)
#define PMC_NCSPD_CTL_NCSPD_CTL7_WIDTH           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL7(x)              (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL7_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL7_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL8_MASK            (0x100U)
#define PMC_NCSPD_CTL_NCSPD_CTL8_SHIFT           (8U)
#define PMC_NCSPD_CTL_NCSPD_CTL8_WIDTH           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL8(x)              (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL8_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL8_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL9_MASK            (0x200U)
#define PMC_NCSPD_CTL_NCSPD_CTL9_SHIFT           (9U)
#define PMC_NCSPD_CTL_NCSPD_CTL9_WIDTH           (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL9(x)              (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL9_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL9_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL10_MASK           (0x400U)
#define PMC_NCSPD_CTL_NCSPD_CTL10_SHIFT          (10U)
#define PMC_NCSPD_CTL_NCSPD_CTL10_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL10(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL10_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL10_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL11_MASK           (0x800U)
#define PMC_NCSPD_CTL_NCSPD_CTL11_SHIFT          (11U)
#define PMC_NCSPD_CTL_NCSPD_CTL11_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL11(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL11_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL11_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL12_MASK           (0x1000U)
#define PMC_NCSPD_CTL_NCSPD_CTL12_SHIFT          (12U)
#define PMC_NCSPD_CTL_NCSPD_CTL12_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL12(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL12_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL12_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL13_MASK           (0x2000U)
#define PMC_NCSPD_CTL_NCSPD_CTL13_SHIFT          (13U)
#define PMC_NCSPD_CTL_NCSPD_CTL13_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL13(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL13_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL13_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL14_MASK           (0x4000U)
#define PMC_NCSPD_CTL_NCSPD_CTL14_SHIFT          (14U)
#define PMC_NCSPD_CTL_NCSPD_CTL14_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL14(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL14_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL14_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL15_MASK           (0x8000U)
#define PMC_NCSPD_CTL_NCSPD_CTL15_SHIFT          (15U)
#define PMC_NCSPD_CTL_NCSPD_CTL15_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL15(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL15_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL15_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL16_MASK           (0x10000U)
#define PMC_NCSPD_CTL_NCSPD_CTL16_SHIFT          (16U)
#define PMC_NCSPD_CTL_NCSPD_CTL16_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL16(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL16_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL16_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL17_MASK           (0x20000U)
#define PMC_NCSPD_CTL_NCSPD_CTL17_SHIFT          (17U)
#define PMC_NCSPD_CTL_NCSPD_CTL17_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL17(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL17_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL17_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL18_MASK           (0x40000U)
#define PMC_NCSPD_CTL_NCSPD_CTL18_SHIFT          (18U)
#define PMC_NCSPD_CTL_NCSPD_CTL18_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL18(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL18_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL18_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL19_MASK           (0x80000U)
#define PMC_NCSPD_CTL_NCSPD_CTL19_SHIFT          (19U)
#define PMC_NCSPD_CTL_NCSPD_CTL19_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL19(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL19_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL19_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL20_MASK           (0x100000U)
#define PMC_NCSPD_CTL_NCSPD_CTL20_SHIFT          (20U)
#define PMC_NCSPD_CTL_NCSPD_CTL20_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL20(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL20_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL20_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL21_MASK           (0x200000U)
#define PMC_NCSPD_CTL_NCSPD_CTL21_SHIFT          (21U)
#define PMC_NCSPD_CTL_NCSPD_CTL21_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL21(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL21_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL21_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL22_MASK           (0x400000U)
#define PMC_NCSPD_CTL_NCSPD_CTL22_SHIFT          (22U)
#define PMC_NCSPD_CTL_NCSPD_CTL22_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL22(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL22_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL22_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL23_MASK           (0x800000U)
#define PMC_NCSPD_CTL_NCSPD_CTL23_SHIFT          (23U)
#define PMC_NCSPD_CTL_NCSPD_CTL23_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL23(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL23_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL23_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL24_MASK           (0x1000000U)
#define PMC_NCSPD_CTL_NCSPD_CTL24_SHIFT          (24U)
#define PMC_NCSPD_CTL_NCSPD_CTL24_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL24(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL24_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL24_MASK)

#define PMC_NCSPD_CTL_NCSPD_CTL25_MASK           (0x2000000U)
#define PMC_NCSPD_CTL_NCSPD_CTL25_SHIFT          (25U)
#define PMC_NCSPD_CTL_NCSPD_CTL25_WIDTH          (1U)
#define PMC_NCSPD_CTL_NCSPD_CTL25(x)             (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_CTL_NCSPD_CTL25_SHIFT)) & PMC_NCSPD_CTL_NCSPD_CTL25_MASK)
/*! @} */

/*! @name NCSPD_STAT - NCSPD Status Register */
/*! @{ */

#define PMC_NCSPD_STAT_NCSPD_STAT0_MASK          (0x1U)
#define PMC_NCSPD_STAT_NCSPD_STAT0_SHIFT         (0U)
#define PMC_NCSPD_STAT_NCSPD_STAT0_WIDTH         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT0(x)            (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT0_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT0_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT1_MASK          (0x2U)
#define PMC_NCSPD_STAT_NCSPD_STAT1_SHIFT         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT1_WIDTH         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT1(x)            (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT1_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT1_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT2_MASK          (0x4U)
#define PMC_NCSPD_STAT_NCSPD_STAT2_SHIFT         (2U)
#define PMC_NCSPD_STAT_NCSPD_STAT2_WIDTH         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT2(x)            (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT2_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT2_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT3_MASK          (0x8U)
#define PMC_NCSPD_STAT_NCSPD_STAT3_SHIFT         (3U)
#define PMC_NCSPD_STAT_NCSPD_STAT3_WIDTH         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT3(x)            (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT3_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT3_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT4_MASK          (0x10U)
#define PMC_NCSPD_STAT_NCSPD_STAT4_SHIFT         (4U)
#define PMC_NCSPD_STAT_NCSPD_STAT4_WIDTH         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT4(x)            (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT4_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT4_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT5_MASK          (0x20U)
#define PMC_NCSPD_STAT_NCSPD_STAT5_SHIFT         (5U)
#define PMC_NCSPD_STAT_NCSPD_STAT5_WIDTH         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT5(x)            (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT5_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT5_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT6_MASK          (0x40U)
#define PMC_NCSPD_STAT_NCSPD_STAT6_SHIFT         (6U)
#define PMC_NCSPD_STAT_NCSPD_STAT6_WIDTH         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT6(x)            (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT6_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT6_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT7_MASK          (0x80U)
#define PMC_NCSPD_STAT_NCSPD_STAT7_SHIFT         (7U)
#define PMC_NCSPD_STAT_NCSPD_STAT7_WIDTH         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT7(x)            (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT7_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT7_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT8_MASK          (0x100U)
#define PMC_NCSPD_STAT_NCSPD_STAT8_SHIFT         (8U)
#define PMC_NCSPD_STAT_NCSPD_STAT8_WIDTH         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT8(x)            (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT8_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT8_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT9_MASK          (0x200U)
#define PMC_NCSPD_STAT_NCSPD_STAT9_SHIFT         (9U)
#define PMC_NCSPD_STAT_NCSPD_STAT9_WIDTH         (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT9(x)            (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT9_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT9_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT10_MASK         (0x400U)
#define PMC_NCSPD_STAT_NCSPD_STAT10_SHIFT        (10U)
#define PMC_NCSPD_STAT_NCSPD_STAT10_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT10(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT10_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT10_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT11_MASK         (0x800U)
#define PMC_NCSPD_STAT_NCSPD_STAT11_SHIFT        (11U)
#define PMC_NCSPD_STAT_NCSPD_STAT11_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT11(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT11_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT11_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT12_MASK         (0x1000U)
#define PMC_NCSPD_STAT_NCSPD_STAT12_SHIFT        (12U)
#define PMC_NCSPD_STAT_NCSPD_STAT12_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT12(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT12_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT12_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT13_MASK         (0x2000U)
#define PMC_NCSPD_STAT_NCSPD_STAT13_SHIFT        (13U)
#define PMC_NCSPD_STAT_NCSPD_STAT13_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT13(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT13_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT13_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT14_MASK         (0x4000U)
#define PMC_NCSPD_STAT_NCSPD_STAT14_SHIFT        (14U)
#define PMC_NCSPD_STAT_NCSPD_STAT14_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT14(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT14_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT14_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT15_MASK         (0x8000U)
#define PMC_NCSPD_STAT_NCSPD_STAT15_SHIFT        (15U)
#define PMC_NCSPD_STAT_NCSPD_STAT15_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT15(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT15_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT15_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT16_MASK         (0x10000U)
#define PMC_NCSPD_STAT_NCSPD_STAT16_SHIFT        (16U)
#define PMC_NCSPD_STAT_NCSPD_STAT16_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT16(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT16_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT16_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT17_MASK         (0x20000U)
#define PMC_NCSPD_STAT_NCSPD_STAT17_SHIFT        (17U)
#define PMC_NCSPD_STAT_NCSPD_STAT17_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT17(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT17_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT17_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT18_MASK         (0x40000U)
#define PMC_NCSPD_STAT_NCSPD_STAT18_SHIFT        (18U)
#define PMC_NCSPD_STAT_NCSPD_STAT18_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT18(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT18_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT18_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT19_MASK         (0x80000U)
#define PMC_NCSPD_STAT_NCSPD_STAT19_SHIFT        (19U)
#define PMC_NCSPD_STAT_NCSPD_STAT19_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT19(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT19_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT19_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT20_MASK         (0x100000U)
#define PMC_NCSPD_STAT_NCSPD_STAT20_SHIFT        (20U)
#define PMC_NCSPD_STAT_NCSPD_STAT20_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT20(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT20_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT20_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT21_MASK         (0x200000U)
#define PMC_NCSPD_STAT_NCSPD_STAT21_SHIFT        (21U)
#define PMC_NCSPD_STAT_NCSPD_STAT21_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT21(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT21_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT21_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT22_MASK         (0x400000U)
#define PMC_NCSPD_STAT_NCSPD_STAT22_SHIFT        (22U)
#define PMC_NCSPD_STAT_NCSPD_STAT22_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT22(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT22_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT22_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT23_MASK         (0x800000U)
#define PMC_NCSPD_STAT_NCSPD_STAT23_SHIFT        (23U)
#define PMC_NCSPD_STAT_NCSPD_STAT23_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT23(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT23_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT23_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT24_MASK         (0x1000000U)
#define PMC_NCSPD_STAT_NCSPD_STAT24_SHIFT        (24U)
#define PMC_NCSPD_STAT_NCSPD_STAT24_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT24(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT24_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT24_MASK)

#define PMC_NCSPD_STAT_NCSPD_STAT25_MASK         (0x2000000U)
#define PMC_NCSPD_STAT_NCSPD_STAT25_SHIFT        (25U)
#define PMC_NCSPD_STAT_NCSPD_STAT25_WIDTH        (1U)
#define PMC_NCSPD_STAT_NCSPD_STAT25(x)           (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_STAT_NCSPD_STAT25_SHIFT)) & PMC_NCSPD_STAT_NCSPD_STAT25_MASK)
/*! @} */

/*! @name CSPD_EVENT_CAPTURE - CSPD Event Capture (CSPDEF) */
/*! @{ */

#define PMC_CSPD_EVENT_CAPTURE_HVCPOREF_MASK     (0x1U)
#define PMC_CSPD_EVENT_CAPTURE_HVCPOREF_SHIFT    (0U)
#define PMC_CSPD_EVENT_CAPTURE_HVCPOREF_WIDTH    (1U)
#define PMC_CSPD_EVENT_CAPTURE_HVCPOREF(x)       (((uint32_t)(((uint32_t)(x)) << PMC_CSPD_EVENT_CAPTURE_HVCPOREF_SHIFT)) & PMC_CSPD_EVENT_CAPTURE_HVCPOREF_MASK)

#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE0_MASK (0x2U)
#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE0_SHIFT (1U)
#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE0_WIDTH (1U)
#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE0(x) (((uint32_t)(((uint32_t)(x)) << PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE0_SHIFT)) & PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE0_MASK)

#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE1_MASK (0x4U)
#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE1_SHIFT (2U)
#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE1_WIDTH (1U)
#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE1(x) (((uint32_t)(((uint32_t)(x)) << PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE1_SHIFT)) & PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE1_MASK)

#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE2_MASK (0x8U)
#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE2_SHIFT (3U)
#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE2_WIDTH (1U)
#define PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE2(x) (((uint32_t)(((uint32_t)(x)) << PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE2_SHIFT)) & PMC_CSPD_EVENT_CAPTURE_CSPD_EVENT_CAPTURE2_MASK)
/*! @} */

/*! @name NCSPD_EVENT_CAPTURE - NCSPD Event Flag (NCSPDEF) */
/*! @{ */

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE0_MASK (0x1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE0_SHIFT (0U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE0_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE0(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE0_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE0_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE1_MASK (0x2U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE1_SHIFT (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE1_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE1(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE1_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE1_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE2_MASK (0x4U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE2_SHIFT (2U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE2_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE2(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE2_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE2_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE3_MASK (0x8U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE3_SHIFT (3U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE3_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE3(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE3_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE3_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE4_MASK (0x10U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE4_SHIFT (4U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE4_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE4(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE4_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE4_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE5_MASK (0x20U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE5_SHIFT (5U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE5_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE5(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE5_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE5_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE6_MASK (0x40U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE6_SHIFT (6U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE6_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE6(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE6_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE6_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE7_MASK (0x80U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE7_SHIFT (7U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE7_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE7(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE7_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE7_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE8_MASK (0x100U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE8_SHIFT (8U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE8_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE8(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE8_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE8_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE9_MASK (0x200U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE9_SHIFT (9U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE9_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE9(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE9_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE9_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE10_MASK (0x400U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE10_SHIFT (10U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE10_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE10(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE10_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE10_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE11_MASK (0x800U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE11_SHIFT (11U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE11_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE11(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE11_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE11_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE12_MASK (0x1000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE12_SHIFT (12U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE12_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE12(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE12_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE12_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE13_MASK (0x2000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE13_SHIFT (13U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE13_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE13(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE13_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE13_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE14_MASK (0x4000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE14_SHIFT (14U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE14_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE14(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE14_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE14_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE15_MASK (0x8000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE15_SHIFT (15U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE15_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE15(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE15_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE15_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE16_MASK (0x10000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE16_SHIFT (16U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE16_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE16(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE16_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE16_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE17_MASK (0x20000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE17_SHIFT (17U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE17_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE17(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE17_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE17_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE18_MASK (0x40000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE18_SHIFT (18U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE18_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE18(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE18_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE18_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE19_MASK (0x80000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE19_SHIFT (19U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE19_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE19(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE19_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE19_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE20_MASK (0x100000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE20_SHIFT (20U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE20_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE20(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE20_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE20_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE21_MASK (0x200000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE21_SHIFT (21U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE21_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE21(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE21_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE21_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE22_MASK (0x400000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE22_SHIFT (22U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE22_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE22(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE22_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE22_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE23_MASK (0x800000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE23_SHIFT (23U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE23_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE23(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE23_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE23_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE24_MASK (0x1000000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE24_SHIFT (24U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE24_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE24(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE24_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE24_MASK)

#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE25_MASK (0x2000000U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE25_SHIFT (25U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE25_WIDTH (1U)
#define PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE25(x) (((uint32_t)(((uint32_t)(x)) << PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE25_SHIFT)) & PMC_NCSPD_EVENT_CAPTURE_NCSPD_EVENT_CAPTURE25_MASK)
/*! @} */

/*! @name POR_WDOG_EVENT_CAPTURE - Device Status Flag (DSF0)..Device Status Flag (DSF2) */
/*! @{ */

#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT0_MASK  (0xFFFFFFFFU)
#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT0_SHIFT (0U)
#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT0_WIDTH (32U)
#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT0(x)    (((uint32_t)(((uint32_t)(x)) << PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT0_SHIFT)) & PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT0_MASK)

#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT1_MASK  (0xFFFFFFFFU)
#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT1_SHIFT (0U)
#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT1_WIDTH (32U)
#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT1(x)    (((uint32_t)(((uint32_t)(x)) << PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT1_SHIFT)) & PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT1_MASK)

#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT2_MASK  (0xFFFFFFFFU)
#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT2_SHIFT (0U)
#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT2_WIDTH (32U)
#define PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT2(x)    (((uint32_t)(((uint32_t)(x)) << PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT2_SHIFT)) & PMC_POR_WDOG_EVENT_CAPTURE_DSFBIT2_MASK)
/*! @} */

/*!
 * @}
 */ /* end of group PMC_Register_Masks */

/*!
 * @}
 */ /* end of group PMC_Peripheral_Access_Layer */

#endif  /* #if !defined(S32Z2_PMC_H_) */
