/*--------------------------------------------------------------------------*/
/* Copyright 2020-2025 NXP                                                  */
/*                                                                          */
/* SPDX-License-Identifier: BSD-3-Clause                                    */
/*                                                                          */
/* Redistribution and use in source and binary forms, with or without       */
/* modification, are permitted provided that the following conditions are   */
/* met:                                                                     */
/*                                                                          */
/* 1. Redistributions of source code must retain the above copyright        */
/*    notice, this list of conditions and the following disclaimer.         */
/*                                                                          */
/* 2. Redistributions in binary form must reproduce the above copyright     */
/*    notice, this list of conditions and the following disclaimer in the   */
/*    documentation and/or other materials provided with the distribution.  */
/*                                                                          */
/* 3. Neither the name of the copyright holder nor the names of its         */
/*    contributors may be used to endorse or promote products derived from  */
/*    this software without specific prior written permission.              */
/*                                                                          */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  */
/* IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED    */
/* TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A          */
/* PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT       */
/* HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,   */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR   */
/* PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF   */
/* LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING     */
/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS       */
/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.             */
/*--------------------------------------------------------------------------*/

/**
 * @file  mcuxClEcc_Constants.h
 * @brief Constant definitions of mcuxClEcc component
 */


#ifndef MCUXCLECC_CONSTANTS_H_
#define MCUXCLECC_CONSTANTS_H_


#include <mcuxClCore_Platform.h>

#ifdef __cplusplus
extern "C" {
#endif


/**
 * @defgroup mcuxClEcc_Constants mcuxClEcc_Constants
 * @brief Defines all Macros of @ref mcuxClEcc
 * @ingroup mcuxClEcc
 * @{
 */

/**********************************************************/
/* Return codes of mcuxClEcc                               */
/**********************************************************/

/**
 * @addtogroup mcuxClEcc_Status
 * mcuxClEcc return code definitions
 * @{ */
#define MCUXCLECC_STATUS_OK                        ((mcuxClEcc_Status_t) 0x04442E03u)  ///< Operation was successful.
#define MCUXCLECC_STATUS_INVALID_PARAMS            ((mcuxClEcc_Status_t) 0x044453F8u)  ///< Parameters are invalid.
#define MCUXCLECC_STATUS_SCALAR_ZERO               ((mcuxClEcc_Status_t) 0x04445370u)  ///< Internal scalar for point multiplication is zero (mod n).
#define MCUXCLECC_STATUS_INVALID_SIGNATURE         ((mcuxClEcc_Status_t) 0x04448930u)  ///< ECDSA Signature is invalid.
#define MCUXCLECC_STATUS_NEUTRAL_POINT             ((mcuxClEcc_Status_t) 0x04448934u)  ///< The result of the point operation is the neutral point.
#define MCUXCLECC_STATUS_FAULT_ATTACK              ((mcuxClEcc_Status_t) 0x0444F0F0u)  ///< Fault attack (unexpected behavior) is detected.

#ifdef MCUXCL_FEATURE_ECC_MONTDH
#define MCUXCLECC_STATUS_SMALL_SUBGROUP_ATTACK     ((mcuxClEcc_Status_t) 0x04445374u)  ///< MONTDH public key lies in small subgroup.
#endif /* MCUXCL_FEATURE_ECC_MONTDH */
/** @} */  /* MCUXCLECC_STATUS_ */


/**
 * @addtogroup mcuxClEcc_ParamOptions
 * mcuxClEcc options definitions
 * @{ */

/**********************************************************/
/* Options for generating custom domain parameters        */
/**********************************************************/

#define MCUXCLECC_OPTION_GENERATEPRECPOINT_YES     (0x00000001u)
#define MCUXCLECC_OPTION_GENERATEPRECPOINT_NO      (0x00000002u)
#define MCUXCLECC_OPTION_GENERATEPRECPOINT_MASK    (MCUXCLECC_OPTION_GENERATEPRECPOINT_YES | MCUXCLECC_OPTION_GENERATEPRECPOINT_NO)
#define MCUXCLECC_OPTION_GENERATEPRECPOINT_OFFSET  0u



#ifdef MCUXCL_FEATURE_ECC_EDDSA

/**********************************************************/
/* Options for EdDsa                                      */
/**********************************************************/

/* phflag values for EdDSA */
#define MCUXCLECC_EDDSA_PHFLAG_ZERO    0u
#define MCUXCLECC_EDDSA_PHFLAG_ONE     1u

#endif /* MCUXCL_FEATURE_ECC_EDDSA */
/** @} */  /* mcuxClEcc_Options */

/**
 * @}
 */ /* mcuxClEcc_Constants */


/**
 * @defgroup mcuxClEcc_ParameterSizes mcuxClEcc_ParameterSizes
 * @brief Defines domain parameter, key and signature sizes of @ref mcuxClEcc
 * @ingroup mcuxClEcc_Constants
 * @{
 */

#ifdef MCUXCL_FEATURE_ECC_MONTDH

/**
 * @addtogroup MCUXCLECC_MONTDH_CURVE25519_SIZE_
 * MontDH parameter size definitions for Curve25519
 * @{ */
#define MCUXCLECC_MONTDH_CURVE25519_SIZE_PRIMEP          (32U)
#define MCUXCLECC_MONTDH_CURVE25519_SIZE_BASEPOINTORDER  (32U)
#define MCUXCLECC_MONTDH_CURVE25519_SIZE_PRIVATEKEY      (MCUXCLECC_MONTDH_CURVE25519_SIZE_BASEPOINTORDER)
#define MCUXCLECC_MONTDH_CURVE25519_SIZE_PUBLICKEY       (MCUXCLECC_MONTDH_CURVE25519_SIZE_PRIMEP)
#define MCUXCLECC_MONTDH_CURVE25519_SIZE_SHAREDSECRET    (MCUXCLECC_MONTDH_CURVE25519_SIZE_PRIMEP)
/** @} */  /* MCUXCLECC_MONTDH_CURVE25519_SIZE_ */

/**
 * @addtogroup MCUXCLECC_MONTDH_CURVE448_SIZE_
 * MontDH parameter size definitions for Curve448
 * @{ */
#define MCUXCLECC_MONTDH_CURVE448_SIZE_PRIMEP            (56U)
#define MCUXCLECC_MONTDH_CURVE448_SIZE_BASEPOINTORDER    (56U)
#define MCUXCLECC_MONTDH_CURVE448_SIZE_PRIVATEKEY        (MCUXCLECC_MONTDH_CURVE448_SIZE_BASEPOINTORDER)
#define MCUXCLECC_MONTDH_CURVE448_SIZE_PUBLICKEY         (MCUXCLECC_MONTDH_CURVE448_SIZE_PRIMEP)
#define MCUXCLECC_MONTDH_CURVE448_SIZE_SHAREDSECRET      (MCUXCLECC_MONTDH_CURVE448_SIZE_PRIMEP)
/** @} */  /* MCUXCLECC_MONTDH_CURVE448_SIZE_ */
#endif /* MCUXCL_FEATURE_ECC_MONTDH */

#ifdef MCUXCL_FEATURE_ECC_SECPK1_CURVES

/**
 * @addtogroup MCUXCLECC_WEIERECC_SECP160K1_SIZE_
 * WeierECC parameter size definitions for secp160k1
 * @{ */
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_PRIMEP                     (20U)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_BASEPOINTORDER             (21U)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP160K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_PUBLICKEY                  (2U * MCUXCLECC_WEIERECC_SECP160K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP160K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_SIGNATURE                  (2U * MCUXCLECC_WEIERECC_SECP160K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_ENCPOINT_SEC_NEUTRAL       (1u)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_ENCPOINT_SEC_COMPRESSED    (1u + MCUXCLECC_WEIERECC_SECP160K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (1u + (2u * MCUXCLECC_WEIERECC_SECP160K1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_SECP160K1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_SECP192K1_SIZE_
 * WeierECC parameter size definitions for secp192k1
 * @{ */
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_PRIMEP                     (24U)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_BASEPOINTORDER             (24U)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP192K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_PUBLICKEY                  (2U * MCUXCLECC_WEIERECC_SECP192K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP192K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_SIGNATURE                  (2U * MCUXCLECC_WEIERECC_SECP192K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_ENCPOINT_SEC_NEUTRAL       (1u)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_ENCPOINT_SEC_COMPRESSED    (1u + MCUXCLECC_WEIERECC_SECP192K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (1u + (2u * MCUXCLECC_WEIERECC_SECP192K1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_SECP192K1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_SECP224K1_SIZE_
 * WeierECC parameter size definitions for secp224k1
 * @{ */
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIMEP                     (28U)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_BASEPOINTORDER             (29U)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP224K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_PUBLICKEY                  (2U * MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_SIGNATURE                  (2U * MCUXCLECC_WEIERECC_SECP224K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_ENCPOINT_SEC_NEUTRAL       (1u)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_ENCPOINT_SEC_COMPRESSED    (1u + MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (1u + (2u * MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_SECP224K1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_SECP256K1_SIZE_
 * WeierECC parameter size definitions for secp256k1
 * @{ */
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_PRIMEP                     (32U)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_BASEPOINTORDER             (32U)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP256K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_PUBLICKEY                  (2U * MCUXCLECC_WEIERECC_SECP256K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP256K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_SIGNATURE                  (2U * MCUXCLECC_WEIERECC_SECP256K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_ENCPOINT_SEC_NEUTRAL       (1u)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_ENCPOINT_SEC_COMPRESSED    (1u + MCUXCLECC_WEIERECC_SECP256K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (1u + (2u * MCUXCLECC_WEIERECC_SECP256K1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_SECP256K1_SIZE_ */

#endif /* MCUXCL_FEATURE_ECC_SECPK1_CURVES */

#ifdef MCUXCL_FEATURE_ECC_SECPR1_CURVES
/**
 * @addtogroup MCUXCLECC_WEIERECC_SECP192R1_SIZE_
 * WeierECC parameter size definitions for secp192r1
 * @{ */
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIMEP                     (24U)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_BASEPOINTORDER             (24U)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP192R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_PUBLICKEY                  (2U * MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_SIGNATURE                  (2U * MCUXCLECC_WEIERECC_SECP192R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_ENCPOINT_SEC_NEUTRAL       (1u)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_ENCPOINT_SEC_COMPRESSED    (1u + MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (1u + (2u * MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_SECP192R1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_SECP224R1_SIZE_
 * WeierECC parameter size definitions for secp224r1
 * @{ */
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIMEP                     (28U)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_BASEPOINTORDER             (28U)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP224R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_PUBLICKEY                  (2U * MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_SIGNATURE                  (2U * MCUXCLECC_WEIERECC_SECP224R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_ENCPOINT_SEC_NEUTRAL       (1u)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_ENCPOINT_SEC_COMPRESSED    (1u + MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (1u + (2u * MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_SECP224R1_SIZE_ */
#endif /* MCUXCL_FEATURE_ECC_SECPR1_CURVES */

#if defined(MCUXCL_FEATURE_ECC_SECPR1_CURVES)
/**
 * @addtogroup MCUXCLECC_WEIERECC_SECP256R1_SIZE_
 * WeierECC parameter size definitions for secp256r1
 * @{ */
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIMEP                     (32U)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_BASEPOINTORDER             (32U)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP256R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_PUBLICKEY                  (2U * MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_SIGNATURE                  (2U * MCUXCLECC_WEIERECC_SECP256R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_ENCPOINT_SEC_NEUTRAL       (1u)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_ENCPOINT_SEC_COMPRESSED    (1u + MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (1u + (2u * MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_SECP256R1_SIZE_ */
#endif /* defined(MCUXCL_FEATURE_ECC_SECPR1_CURVES) || defined(MCUXCL_FEATURE_ECC_ECCKI) */

#if defined(MCUXCL_FEATURE_ECC_SECPR1_CURVES)
/**
 * @addtogroup MCUXCLECC_WEIERECC_SECP384R1_SIZE_
 * WeierECC parameter size definitions for secp384r1
 * @{ */
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIMEP                     (48U)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_BASEPOINTORDER             (48U)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP384R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_PUBLICKEY                  (2U * MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_SIGNATURE                  (2U * MCUXCLECC_WEIERECC_SECP384R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_ENCPOINT_SEC_NEUTRAL       (1u)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_ENCPOINT_SEC_COMPRESSED    (1u + MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (1u + (2u * MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_SECP384R1_SIZE_ */
#endif /* defined(MCUXCL_FEATURE_ECC_SECPR1_CURVES) || defined(MCUXCL_FEATURE_ECC_ECCKI) */

#if defined(MCUXCL_FEATURE_ECC_SECPR1_CURVES)
/**
 * @addtogroup MCUXCLECC_WEIERECC_SECP521R1_SIZE_
 * WeierECC parameter size definitions for secp521r1
 * @{ */
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIMEP                     (66U)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_BASEPOINTORDER             (66U)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP521R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_PUBLICKEY                  (2U * MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_SIGNATURE                  (2U * MCUXCLECC_WEIERECC_SECP521R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_ENCPOINT_SEC_NEUTRAL       (1u)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_ENCPOINT_SEC_COMPRESSED    (1u + MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (1u + (2u * MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_SECP521R1_SIZE_ */

#endif /* MCUXCL_FEATURE_ECC_SECPR1_CURVES */

#ifdef MCUXCL_FEATURE_ECC_NISTPR1_CURVES

/**
 * @addtogroup MCUXCLECC_WEIERECC_NIST_P192_SIZE_
 * WeierECC parameter size definitions for NIST P-192
 * @{ */
#define MCUXCLECC_WEIERECC_NIST_P192_SIZE_PRIMEP                     (MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_NIST_P192_SIZE_BASEPOINTORDER             (MCUXCLECC_WEIERECC_SECP192R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_NIST_P192_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIVATEKEY)
#define MCUXCLECC_WEIERECC_NIST_P192_SIZE_PUBLICKEY                  (MCUXCLECC_WEIERECC_SECP192R1_SIZE_PUBLICKEY)
#define MCUXCLECC_WEIERECC_NIST_P192_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP192R1_SIZE_SHAREDSECRET)
#define MCUXCLECC_WEIERECC_NIST_P192_SIZE_SIGNATURE                  (MCUXCLECC_WEIERECC_SECP192R1_SIZE_SIGNATURE)
#define MCUXCLECC_WEIERECC_NIST_P192_SIZE_ENCPOINT_SEC_NEUTRAL       (MCUXCLECC_WEIERECC_SECP192R1_SIZE_ENCPOINT_SEC_NEUTRAL)
#define MCUXCLECC_WEIERECC_NIST_P192_SIZE_ENCPOINT_SEC_COMPRESSED    (MCUXCLECC_WEIERECC_SECP192R1_SIZE_ENCPOINT_SEC_COMPRESSED)
#define MCUXCLECC_WEIERECC_NIST_P192_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (MCUXCLECC_WEIERECC_SECP192R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED)
/** @} */  /* MCUXCLECC_WEIERECC_NIST_P192_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_NIST_P224_SIZE_
 * WeierECC parameter size definitions for NIST P-224
 * @{ */
#define MCUXCLECC_WEIERECC_NIST_P224_SIZE_PRIMEP                     (MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_NIST_P224_SIZE_BASEPOINTORDER             (MCUXCLECC_WEIERECC_SECP224R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_NIST_P224_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIVATEKEY)
#define MCUXCLECC_WEIERECC_NIST_P224_SIZE_PUBLICKEY                  (MCUXCLECC_WEIERECC_SECP224R1_SIZE_PUBLICKEY)
#define MCUXCLECC_WEIERECC_NIST_P224_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP224R1_SIZE_SHAREDSECRET)
#define MCUXCLECC_WEIERECC_NIST_P224_SIZE_SIGNATURE                  (MCUXCLECC_WEIERECC_SECP224R1_SIZE_SIGNATURE)
#define MCUXCLECC_WEIERECC_NIST_P224_SIZE_ENCPOINT_SEC_NEUTRAL       (MCUXCLECC_WEIERECC_SECP224R1_SIZE_ENCPOINT_SEC_NEUTRAL)
#define MCUXCLECC_WEIERECC_NIST_P224_SIZE_ENCPOINT_SEC_COMPRESSED    (MCUXCLECC_WEIERECC_SECP224R1_SIZE_ENCPOINT_SEC_COMPRESSED)
#define MCUXCLECC_WEIERECC_NIST_P224_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (MCUXCLECC_WEIERECC_SECP224R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED)
/** @} */  /* MCUXCLECC_WEIERECC_NIST_P224_SIZE_ */
#endif /* MCUXCL_FEATURE_ECC_NISTPR1_CURVES */

#if defined(MCUXCL_FEATURE_ECC_NISTPR1_CURVES)
/**
 * @addtogroup MCUXCLECC_WEIERECC_NIST_P256_SIZE_
 * WeierECC parameter size definitions for NIST P-256
 * @{ */
#define MCUXCLECC_WEIERECC_NIST_P256_SIZE_PRIMEP                     (MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_NIST_P256_SIZE_BASEPOINTORDER             (MCUXCLECC_WEIERECC_SECP256R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_NIST_P256_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIVATEKEY)
#define MCUXCLECC_WEIERECC_NIST_P256_SIZE_PUBLICKEY                  (MCUXCLECC_WEIERECC_SECP256R1_SIZE_PUBLICKEY)
#define MCUXCLECC_WEIERECC_NIST_P256_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP256R1_SIZE_SHAREDSECRET)
#define MCUXCLECC_WEIERECC_NIST_P256_SIZE_SIGNATURE                  (MCUXCLECC_WEIERECC_SECP256R1_SIZE_SIGNATURE)
#define MCUXCLECC_WEIERECC_NIST_P256_SIZE_ENCPOINT_SEC_NEUTRAL       (MCUXCLECC_WEIERECC_SECP256R1_SIZE_ENCPOINT_SEC_NEUTRAL)
#define MCUXCLECC_WEIERECC_NIST_P256_SIZE_ENCPOINT_SEC_COMPRESSED    (MCUXCLECC_WEIERECC_SECP256R1_SIZE_ENCPOINT_SEC_COMPRESSED)
#define MCUXCLECC_WEIERECC_NIST_P256_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (MCUXCLECC_WEIERECC_SECP256R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED)
/** @} */  /* MCUXCLECC_WEIERECC_NIST_P256_SIZE_ */
#endif /* defined(MCUXCL_FEATURE_ECC_NISTPR1_CURVES) || defined(MCUXCL_FEATURE_ECC_ECCKI) */

#if defined(MCUXCL_FEATURE_ECC_NISTPR1_CURVES)
/**
 * @addtogroup MCUXCLECC_WEIERECC_NIST_P384_SIZE_
 * WeierECC parameter size definitions for NIST P-384
 * @{ */
#define MCUXCLECC_WEIERECC_NIST_P384_SIZE_PRIMEP                     (MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_NIST_P384_SIZE_BASEPOINTORDER             (MCUXCLECC_WEIERECC_SECP384R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_NIST_P384_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIVATEKEY)
#define MCUXCLECC_WEIERECC_NIST_P384_SIZE_PUBLICKEY                  (MCUXCLECC_WEIERECC_SECP384R1_SIZE_PUBLICKEY)
#define MCUXCLECC_WEIERECC_NIST_P384_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP384R1_SIZE_SHAREDSECRET)
#define MCUXCLECC_WEIERECC_NIST_P384_SIZE_SIGNATURE                  (MCUXCLECC_WEIERECC_SECP384R1_SIZE_SIGNATURE)
#define MCUXCLECC_WEIERECC_NIST_P384_SIZE_ENCPOINT_SEC_NEUTRAL       (MCUXCLECC_WEIERECC_SECP384R1_SIZE_ENCPOINT_SEC_NEUTRAL)
#define MCUXCLECC_WEIERECC_NIST_P384_SIZE_ENCPOINT_SEC_COMPRESSED    (MCUXCLECC_WEIERECC_SECP384R1_SIZE_ENCPOINT_SEC_COMPRESSED)
#define MCUXCLECC_WEIERECC_NIST_P384_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (MCUXCLECC_WEIERECC_SECP384R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED)
/** @} */  /* MCUXCLECC_WEIERECC_NIST_P384_SIZE_ */
#endif /* defined(MCUXCL_FEATURE_ECC_NISTPR1_CURVES) || defined(MCUXCL_FEATURE_ECC_ECCKI) */

#if defined(MCUXCL_FEATURE_ECC_NISTPR1_CURVES)
/**
 * @addtogroup MCUXCLECC_WEIERECC_NIST_P521_SIZE_
 * WeierECC parameter size definitions for NIST P-521
 * @{ */
#define MCUXCLECC_WEIERECC_NIST_P521_SIZE_PRIMEP                     (MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_NIST_P521_SIZE_BASEPOINTORDER             (MCUXCLECC_WEIERECC_SECP521R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_NIST_P521_SIZE_PRIVATEKEY                 (MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIVATEKEY)
#define MCUXCLECC_WEIERECC_NIST_P521_SIZE_PUBLICKEY                  (MCUXCLECC_WEIERECC_SECP521R1_SIZE_PUBLICKEY)
#define MCUXCLECC_WEIERECC_NIST_P521_SIZE_SHAREDSECRET               (MCUXCLECC_WEIERECC_SECP521R1_SIZE_SHAREDSECRET)
#define MCUXCLECC_WEIERECC_NIST_P521_SIZE_SIGNATURE                  (MCUXCLECC_WEIERECC_SECP521R1_SIZE_SIGNATURE)
#define MCUXCLECC_WEIERECC_NIST_P521_SIZE_ENCPOINT_SEC_NEUTRAL       (MCUXCLECC_WEIERECC_SECP521R1_SIZE_ENCPOINT_SEC_NEUTRAL)
#define MCUXCLECC_WEIERECC_NIST_P521_SIZE_ENCPOINT_SEC_COMPRESSED    (MCUXCLECC_WEIERECC_SECP521R1_SIZE_ENCPOINT_SEC_COMPRESSED)
#define MCUXCLECC_WEIERECC_NIST_P521_SIZE_ENCPOINT_SEC_UNCOMPRESSED  (MCUXCLECC_WEIERECC_SECP521R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED)
/** @} */  /* MCUXCLECC_WEIERECC_NIST_P521_SIZE_ */

#endif /* MCUXCL_FEATURE_ECC_NISTPR1_CURVES */

#ifdef MCUXCL_FEATURE_ECC_BRAINPOOLR1_CURVES

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_
 * WeierECC parameter size definitions for brainpoolP160r1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PRIMEP                       (20U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_BASEPOINTORDER               (20U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_
 * WeierECC parameter size definitions for brainpoolP192r1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PRIMEP                       (24U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_BASEPOINTORDER               (24U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_
 * WeierECC parameter size definitions for brainpoolP224r1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PRIMEP                       (28U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_BASEPOINTORDER               (28U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_
 * WeierECC parameter size definitions for brainpoolP256r1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PRIMEP                       (32U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_BASEPOINTORDER               (32U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_
 * WeierECC parameter size definitions for brainpoolP320r1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PRIMEP                       (40U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_BASEPOINTORDER               (40U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_
 * WeierECC parameter size definitions for brainpoolP384r1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PRIMEP                       (48U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_BASEPOINTORDER               (48U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_
 * WeierECC parameter size definitions for brainpoolP512r1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PRIMEP                       (64U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_BASEPOINTORDER               (64U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_ */

#endif /* MCUXCL_FEATURE_ECC_BRAINPOOLR1_CURVES */

#ifdef MCUXCL_FEATURE_ECC_BRAINPOOLT1_CURVES

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_
 * WeierECC parameter size definitions for brainpoolP160t1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PRIMEP                       (20U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_BASEPOINTORDER               (20U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_
 * WeierECC parameter size definitions for brainpoolP192t1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PRIMEP                       (24U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_BASEPOINTORDER               (24U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_
 * WeierECC parameter size definitions for brainpoolP224t1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PRIMEP                       (28U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_BASEPOINTORDER               (28U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_
 * WeierECC parameter size definitions for brainpoolP256t1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PRIMEP                       (32U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_BASEPOINTORDER               (32U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_
 * WeierECC parameter size definitions for brainpoolP320t1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PRIMEP                       (40U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_BASEPOINTORDER               (40U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_
 * WeierECC parameter size definitions for brainpoolP384t1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PRIMEP                       (48U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_BASEPOINTORDER               (48U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_ */

/**
 * @addtogroup MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_
 * WeierECC parameter size definitions for brainpoolP512t1
 * @{ */
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PRIMEP                       (64U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_BASEPOINTORDER               (64U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_ */

#endif /* MCUXCL_FEATURE_ECC_BRAINPOOLT1_CURVES */


/** @addtogroup MCUXCLECC_WEIERECC_MIN_SIZE
 * Minimum size definitions for WeierECC parameter
 * @{ */
#define MCUXCLECC_WEIERECC_MIN_SIZE_PRIMEP                       (16U)
#define MCUXCLECC_WEIERECC_MIN_SIZE_BASEPOINTORDER               (16U)
#define MCUXCLECC_WEIERECC_MIN_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_MIN_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_MIN_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_MIN_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_MIN_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_MIN_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_MIN_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_MIN_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_MIN_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_MIN_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_MIN_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_MIN_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_MIN_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_MIN_SIZE */

/** @addtogroup MCUXCLECC_WEIERECC_MAX_SIZE
 * Maximum size definitions for WeierECC parameters (ECC component officially supports up to 640 bit Weierstrass curves)
 * @{ */
#define MCUXCLECC_WEIERECC_MAX_SIZE_PRIMEP                       (80U)
#define MCUXCLECC_WEIERECC_MAX_SIZE_BASEPOINTORDER               (80U)
#define MCUXCLECC_WEIERECC_MAX_SIZE_PRIVATEKEY                   (MCUXCLECC_WEIERECC_MAX_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_MAX_SIZE_PUBLICKEY                    (2U * MCUXCLECC_WEIERECC_MAX_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_MAX_SIZE_SHAREDSECRET                 (MCUXCLECC_WEIERECC_MAX_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_MAX_SIZE_SIGNATURE                    (2U * MCUXCLECC_WEIERECC_MAX_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_MAX_SIZE_ENCPOINT_SEC_NEUTRAL         (1u)
#define MCUXCLECC_WEIERECC_MAX_SIZE_ENCPOINT_SEC_COMPRESSED      (1u + MCUXCLECC_WEIERECC_MAX_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_MAX_SIZE_ENCPOINT_SEC_UNCOMPRESSED    (1u + (2u * MCUXCLECC_WEIERECC_MAX_SIZE_PRIMEP))
/** @} */  /* MCUXCLECC_WEIERECC_MAX_SIZE */


#ifdef MCUXCL_FEATURE_ECC_EDDSA

#define MCUXCLECC_EDDSA_SIZE_HASH_PREFIX(domPrefixLen, contextLen) ((domPrefixLen) + 2u + (contextLen)) ///< Byte length of a prefix.

/** @addtogroup MCUXCLECC_EDDSA_ED25519_SIZE_
 * EdDSA parameter size definitions for Ed25519
 * @{ */
#define MCUXCLECC_EDDSA_ED25519_SIZE_PRIMEP            (32u)   ///< Byte length of the underlying prime p used in Ed25519.
#define MCUXCLECC_EDDSA_ED25519_SIZE_BASEPOINTORDER    (32u)   ///< Byte length of the base point order n used in Ed25519.
#define MCUXCLECC_EDDSA_ED25519_SIZE_PRIVATEKEY        (32u)   ///< Byte length of an Ed25519 private key.
#define MCUXCLECC_EDDSA_ED25519_SIZE_PRIVATEKEYDATA    (96u)   ///< Byte length of an Ed25519 private key handle data buffer.
#define MCUXCLECC_EDDSA_ED25519_SIZE_PUBLICKEY         (32u)   ///< Byte length of an Ed25519 public key.
#define MCUXCLECC_EDDSA_ED25519_SIZE_SIGNATURE         (64u)   ///< Byte length of an Ed25519 signature.
#define MCUXCLECC_EDDSA_ED25519_DOMPREFIXLEN           (32u)   ///< Byte length of ED25519 domain prefix

/** @} */  /* MCUXCLECC_EDDSA_ED25519_SIZE_ */

#endif /* MCUXCL_FEATURE_ECC_EDDSA */

/**
 * @}
 */ /* mcuxClEcc_ParameterSizes */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* MCUXCLECC_CONSTANTS_H_ */
