/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKL27Z64VFT4/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKL27Z256VLH4-pinctrl.h with this part's differences applied
 * below (71 removed, 0 changed,
 * 17 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 882f4ed1150c2137
 */

#ifndef _ZEPHYR_DTS_BINDING_MKL27Z64VFT4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKL27Z64VFT4_WRAPPER_

#include "MKL27Z256VLH4-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_DM3_PTE23
#undef ADC0_DP3_PTE22
#undef ADC0_SE3_PTE22
#undef ADC0_SE7a_PTE23
#undef CLKOUT32K_PTE0
#undef CMP0_IN2_PTC8
#undef CMP0_IN3_PTC9
#undef CMP0_OUT_PTE0
#undef DAC0_OUT_PTE30
#undef FXIO0_D6_PTE22
#undef FXIO0_D7_PTE23
#undef I2C0_SCL_PTC8
#undef I2C0_SDA_PTC9
#undef I2C1_SCL_PTC10
#undef I2C1_SCL_PTE1
#undef I2C1_SDA_PTC11
#undef I2C1_SDA_PTE0
#undef I2S0_MCLK_PTC4
#undef I2S0_MCLK_PTC6
#undef I2S0_MCLK_PTC8
#undef I2S0_RXD0_PTC11
#undef I2S0_RXD0_PTC5
#undef I2S0_RX_BCLK_PTC6
#undef I2S0_RX_BCLK_PTC9
#undef I2S0_RX_FS_PTC10
#undef I2S0_RX_FS_PTC7
#undef I2S0_TXD0_PTA12
#undef I2S0_TXD0_PTC0
#undef I2S0_TXD0_PTC1
#undef I2S0_TX_BCLK_PTA5
#undef I2S0_TX_BCLK_PTB18
#undef I2S0_TX_BCLK_PTC3
#undef I2S0_TX_FS_PTA13
#undef I2S0_TX_FS_PTB19
#undef I2S0_TX_FS_PTC2
#undef LPUART1_RX_PTE1
#undef LPUART1_TX_PTE0
#undef PTA12
#undef PTA13
#undef PTA5
#undef PTB18
#undef PTB19
#undef PTC10
#undef PTC11
#undef PTC8
#undef PTC9
#undef PTE0
#undef PTE1
#undef PTE22
#undef PTE23
#undef PTE31
#undef RTC_CLKOUT_PTE0
#undef SPI0_SS_PTC4
#undef SPI0_SS_PTD0
#undef SPI1_MISO_PTE0
#undef SPI1_MISO_PTE1
#undef SPI1_MOSI_PTE1
#undef SPI1_SS_PTD4
#undef TPM0_CH2_PTA5
#undef TPM0_CH4_PTC8
#undef TPM0_CH4_PTE31
#undef TPM0_CH5_PTC9
#undef TPM1_CH0_PTA12
#undef TPM1_CH1_PTA13
#undef TPM2_CH0_PTB18
#undef TPM2_CH0_PTE22
#undef TPM2_CH1_PTB19
#undef TPM2_CH1_PTE23
#undef UART2_RX_PTE23
#undef UART2_TX_PTE22
#undef USB_CLKIN_PTA5

/* Signals specific to this part */
#define ADC0_DP1_PTE16 KINETIS_MUX('E',16,0)
#define ADC0_SE1_PTE16 KINETIS_MUX('E',16,0)
#define FXIO0_D0_PTE16 KINETIS_MUX('E',16,6)
#define I2C1_SCL_PTD7 KINETIS_MUX('D',7,4)
#define I2C1_SDA_PTD6 KINETIS_MUX('D',6,4)
#define PTE16 KINETIS_MUX('E',16,1)
#define SPI0_PCS0_PTC4 KINETIS_MUX('C',4,2)
#define SPI0_PCS0_PTD0 KINETIS_MUX('D',0,2)
#define SPI0_PCS0_PTE16 KINETIS_MUX('E',16,2)
#define SPI1_MISO_PTB0 KINETIS_MUX('B',0,5)
#define SPI1_MISO_PTB1 KINETIS_MUX('B',1,4)
#define SPI1_MOSI_PTB0 KINETIS_MUX('B',0,4)
#define SPI1_MOSI_PTB1 KINETIS_MUX('B',1,5)
#define SPI1_PCS0_PTC4 KINETIS_MUX('C',4,5)
#define SPI1_PCS0_PTD4 KINETIS_MUX('D',4,2)
#define TPM_CLKIN0_PTE16 KINETIS_MUX('E',16,4)
#define UART2_TX_PTE16 KINETIS_MUX('E',16,3)

#endif /* _ZEPHYR_DTS_BINDING_MKL27Z64VFT4_WRAPPER_ */
