/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKL27Z64VLH4/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKL27Z256VLH4-pinctrl.h with this part's differences applied
 * below (22 removed, 0 changed,
 * 17 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 882f4ed1150c2137
 */

#ifndef _ZEPHYR_DTS_BINDING_MKL27Z64VLH4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKL27Z64VLH4_WRAPPER_

#include "MKL27Z256VLH4-pinctrl.h"

/* Signals not present on this part */
#undef DAC0_OUT_PTE30
#undef I2S0_MCLK_PTC4
#undef I2S0_MCLK_PTC6
#undef I2S0_MCLK_PTC8
#undef I2S0_RXD0_PTC11
#undef I2S0_RXD0_PTC5
#undef I2S0_RX_BCLK_PTC6
#undef I2S0_RX_BCLK_PTC9
#undef I2S0_RX_FS_PTC10
#undef I2S0_RX_FS_PTC7
#undef I2S0_TXD0_PTA12
#undef I2S0_TXD0_PTC0
#undef I2S0_TXD0_PTC1
#undef I2S0_TX_BCLK_PTA5
#undef I2S0_TX_BCLK_PTB18
#undef I2S0_TX_BCLK_PTC3
#undef I2S0_TX_FS_PTA13
#undef I2S0_TX_FS_PTB19
#undef I2S0_TX_FS_PTC2
#undef SPI0_SS_PTC4
#undef SPI0_SS_PTD0
#undef SPI1_SS_PTD4

/* Signals specific to this part */
#define ADC0_DP1_PTE16 KINETIS_MUX('E',16,0)
#define ADC0_SE1_PTE16 KINETIS_MUX('E',16,0)
#define FXIO0_D0_PTE16 KINETIS_MUX('E',16,6)
#define I2C1_SCL_PTD7 KINETIS_MUX('D',7,4)
#define I2C1_SDA_PTD6 KINETIS_MUX('D',6,4)
#define PTE16 KINETIS_MUX('E',16,1)
#define SPI0_PCS0_PTC4 KINETIS_MUX('C',4,2)
#define SPI0_PCS0_PTD0 KINETIS_MUX('D',0,2)
#define SPI0_PCS0_PTE16 KINETIS_MUX('E',16,2)
#define SPI1_MISO_PTB0 KINETIS_MUX('B',0,5)
#define SPI1_MISO_PTB1 KINETIS_MUX('B',1,4)
#define SPI1_MOSI_PTB0 KINETIS_MUX('B',0,4)
#define SPI1_MOSI_PTB1 KINETIS_MUX('B',1,5)
#define SPI1_PCS0_PTC4 KINETIS_MUX('C',4,5)
#define SPI1_PCS0_PTD4 KINETIS_MUX('D',4,2)
#define TPM_CLKIN0_PTE16 KINETIS_MUX('E',16,4)
#define UART2_TX_PTE16 KINETIS_MUX('E',16,3)

#endif /* _ZEPHYR_DTS_BINDING_MKL27Z64VLH4_WRAPPER_ */
