/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA154VLL/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA156VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: e40ee201efc4ec57
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA154VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA154VLL_WRAPPER_

#include "MCXA156VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA154VLL_WRAPPER_ */
