/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA456VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA457VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 5391a76c848f53ce
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA456VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA456VLL_WRAPPER_

#include "MCXA457VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA456VLL_WRAPPER_ */
