/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA286VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA287VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 35f8910d87322d8c
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA286VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA286VLL_WRAPPER_

#include "MCXA287VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA286VLL_WRAPPER_ */
