/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA536VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA537VLQ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 2282ecd5f6b55ddd
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA536VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA536VLQ_WRAPPER_

#include "MCXA537VLQ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA536VLQ_WRAPPER_ */
