/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA577VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA577VPN-pinctrl.h with this part's differences applied
 * below (78 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 9b2c405468751680
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA577VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA577VLQ_WRAPPER_

#include "MCXA577VPN-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_A7_P2_7
#undef CT0_MAT0_P0_10
#undef CT0_MAT1_P0_11
#undef CT2_MAT0_P3_18
#undef CT2_MAT1_P3_19
#undef CT3_MAT0_P2_8
#undef CT3_MAT1_P2_9
#undef CT3_MAT1_P3_27
#undef CT3_MAT2_P2_10
#undef CT3_MAT2_P4_12
#undef CT3_MAT3_P2_11
#undef CT3_MAT3_P4_13
#undef CT_INP0_P0_8
#undef CT_INP10_P2_26
#undef CT_INP13_P3_27
#undef CT_INP14_P3_26
#undef CT_INP1_P0_9
#undef ESPI0_DATA2_P4_13
#undef ESPI0_DATA3_P4_12
#undef FLEXIO0_D0_P0_8
#undef FLEXIO0_D16_P2_8
#undef FLEXIO0_D17_P2_9
#undef FLEXIO0_D18_P2_10
#undef FLEXIO0_D19_P2_11
#undef FLEXIO0_D1_P0_9
#undef FLEXIO0_D26_P3_18
#undef FLEXIO0_D26_P3_26
#undef FLEXIO0_D27_P3_19
#undef FLEXIO0_D27_P3_27
#undef FLEXIO0_D2_P0_10
#undef FLEXIO0_D3_P0_11
#undef I3C2_PUR_P4_12
#undef I3C3_PUR_P4_13
#undef LPI2C3_SCLS_P4_12
#undef LPI2C3_SCL_P3_27
#undef LPI2C3_SDAS_P4_13
#undef LPI2C4_HREQ_P0_11
#undef LPI2C4_HREQ_P4_13
#undef LPSPI3_PCS1_P3_26
#undef LPSPI4_PCS1_P3_26
#undef LPSPI5_PCS2_P4_13
#undef LPSPI5_PCS3_P4_12
#undef LPUART2_RXD_P2_11
#undef LPUART2_TXD_P2_10
#undef LPUART4_RXD_P3_18
#undef LPUART4_TXD_P3_19
#undef LPUART4_TXD_P3_27
#undef P0_10
#undef P0_11
#undef P0_8
#undef P0_9
#undef P2_10
#undef P2_11
#undef P2_26
#undef P2_8
#undef P2_9
#undef P3_18
#undef P3_19
#undef P3_26
#undef P3_27
#undef P4_12
#undef P4_13
#undef P5_8
#undef P5_9
#undef SMARTDMA_PIO14_P2_10
#undef SMARTDMA_PIO15_P2_11
#undef SMARTDMA_PIO18_P3_18
#undef SMARTDMA_PIO19_P3_19
#undef SMARTDMA_PIO26_P3_26
#undef SMARTDMA_PIO27_P3_27
#undef TRIG_IN4_P2_11
#undef TRIG_IN4_P2_9
#undef TRIG_IN5_P2_26
#undef TRIG_OUT3_P2_8
#undef TRIG_OUT5_P2_10
#undef TSI0_CH50_P3_18
#undef TSI0_CH51_P3_19
#undef VREFI_P2_7

#endif /* _ZEPHYR_DTS_BINDING_MCXA577VLQ_WRAPPER_ */
