/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA457VPN/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA577VPN-pinctrl.h with this part's differences applied
 * below (27 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 9b2c405468751680
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA457VPN_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA457VPN_WRAPPER_

#include "MCXA577VPN-pinctrl.h"

/* Signals not present on this part */
#undef ESPI0_CLK_P3_16
#undef ESPI0_CLK_P4_10
#undef ESPI0_CSN_P3_17
#undef ESPI0_CSN_P4_11
#undef ESPI0_DATA0_P3_15
#undef ESPI0_DATA0_P4_9
#undef ESPI0_DATA1_P3_14
#undef ESPI0_DATA1_P4_8
#undef ESPI0_DATA2_P3_13
#undef ESPI0_DATA2_P4_13
#undef ESPI0_DATA3_P3_12
#undef ESPI0_DATA3_P4_12
#undef ESPI0_NOTIFY_P3_20
#undef ESPI0_NOTIFY_P4_7
#undef ESPI0_RST_P3_21
#undef ESPI0_RST_P4_6
#undef TENBASET1S_DEBUG0_P0_18
#undef TENBASET1S_DEBUG1_P0_19
#undef TENBASET1S_DEBUG2_P0_20
#undef TENBASET1S_DEBUG3_P0_21
#undef TENBASET1S_DEBUG4_P0_22
#undef TENBASET1S_ED_P1_1
#undef TENBASET1S_ED_P1_12
#undef TENBASET1S_RX_P1_0
#undef TENBASET1S_RX_P1_11
#undef TENBASET1S_TX_P1_13
#undef TENBASET1S_TX_P1_2

#endif /* _ZEPHYR_DTS_BINDING_MCXA457VPN_WRAPPER_ */
