/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA536VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA537VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 558ec3784d985fc1
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA536VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA536VLL_WRAPPER_

#include "MCXA537VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA536VLL_WRAPPER_ */
