/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA567VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA577VPN-pinctrl.h with this part's differences applied
 * below (160 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 9b2c405468751680
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA567VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA567VLQ_WRAPPER_

#include "MCXA577VPN-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_A7_P2_7
#undef CT0_MAT0_P0_10
#undef CT0_MAT1_P0_11
#undef CT2_MAT0_P3_18
#undef CT2_MAT1_P3_19
#undef CT3_MAT0_P2_8
#undef CT3_MAT1_P2_9
#undef CT3_MAT1_P3_27
#undef CT3_MAT2_P2_10
#undef CT3_MAT2_P4_12
#undef CT3_MAT3_P2_11
#undef CT3_MAT3_P4_13
#undef CT_INP0_P0_8
#undef CT_INP10_P2_26
#undef CT_INP13_P3_27
#undef CT_INP14_P3_26
#undef CT_INP1_P0_9
#undef ESPI0_CLK_P3_16
#undef ESPI0_CLK_P4_10
#undef ESPI0_CSN_P3_17
#undef ESPI0_CSN_P4_11
#undef ESPI0_DATA0_P3_15
#undef ESPI0_DATA0_P4_9
#undef ESPI0_DATA1_P3_14
#undef ESPI0_DATA1_P4_8
#undef ESPI0_DATA2_P3_13
#undef ESPI0_DATA2_P4_13
#undef ESPI0_DATA3_P3_12
#undef ESPI0_DATA3_P4_12
#undef ESPI0_NOTIFY_P3_20
#undef ESPI0_NOTIFY_P4_7
#undef ESPI0_RST_P3_21
#undef ESPI0_RST_P4_6
#undef FLEXIO0_D0_P0_8
#undef FLEXIO0_D16_P2_8
#undef FLEXIO0_D17_P2_9
#undef FLEXIO0_D18_P2_10
#undef FLEXIO0_D19_P2_11
#undef FLEXIO0_D1_P0_9
#undef FLEXIO0_D26_P3_18
#undef FLEXIO0_D26_P3_26
#undef FLEXIO0_D27_P3_19
#undef FLEXIO0_D27_P3_27
#undef FLEXIO0_D2_P0_10
#undef FLEXIO0_D3_P0_11
#undef I3C2_PUR_P4_12
#undef I3C3_PUR_P4_13
#undef LPI2C3_SCLS_P4_12
#undef LPI2C3_SCL_P3_27
#undef LPI2C3_SDAS_P4_13
#undef LPI2C4_HREQ_P0_11
#undef LPI2C4_HREQ_P4_13
#undef LPSPI3_PCS1_P3_26
#undef LPSPI4_PCS1_P3_26
#undef LPSPI5_PCS2_P4_13
#undef LPSPI5_PCS3_P4_12
#undef LPUART2_RXD_P2_11
#undef LPUART2_TXD_P2_10
#undef LPUART4_RXD_P3_18
#undef LPUART4_TXD_P3_19
#undef LPUART4_TXD_P3_27
#undef P0_10
#undef P0_11
#undef P0_8
#undef P0_9
#undef P2_10
#undef P2_11
#undef P2_26
#undef P2_8
#undef P2_9
#undef P3_18
#undef P3_19
#undef P3_26
#undef P3_27
#undef P4_12
#undef P4_13
#undef P5_8
#undef P5_9
#undef SMARTDMA_PIO14_P2_10
#undef SMARTDMA_PIO15_P2_11
#undef SMARTDMA_PIO18_P3_18
#undef SMARTDMA_PIO19_P3_19
#undef SMARTDMA_PIO26_P3_26
#undef SMARTDMA_PIO27_P3_27
#undef TRIG_IN4_P2_11
#undef TRIG_IN4_P2_9
#undef TRIG_IN5_P2_26
#undef TRIG_OUT3_P2_8
#undef TRIG_OUT5_P2_10
#undef TSI0_CH0_P5_3
#undef TSI0_CH10_P0_22
#undef TSI0_CH11_P0_23
#undef TSI0_CH12_P1_0
#undef TSI0_CH13_P1_1
#undef TSI0_CH14_P1_2
#undef TSI0_CH15_P1_3
#undef TSI0_CH16_P1_4
#undef TSI0_CH17_P1_5
#undef TSI0_CH18_P1_6
#undef TSI0_CH19_P1_7
#undef TSI0_CH1_P5_4
#undef TSI0_CH20_P1_10
#undef TSI0_CH21_P1_11
#undef TSI0_CH22_P1_12
#undef TSI0_CH23_P1_13
#undef TSI0_CH24_P1_14
#undef TSI0_CH25_P1_15
#undef TSI0_CH26_P1_16
#undef TSI0_CH27_P1_17
#undef TSI0_CH28_P1_18
#undef TSI0_CH29_P1_19
#undef TSI0_CH2_P5_5
#undef TSI0_CH30_P2_0
#undef TSI0_CH31_P2_1
#undef TSI0_CH32_P2_2
#undef TSI0_CH33_P2_3
#undef TSI0_CH34_P2_4
#undef TSI0_CH35_P2_5
#undef TSI0_CH36_P2_6
#undef TSI0_CH37_P2_7
#undef TSI0_CH38_P2_12
#undef TSI0_CH39_P2_13
#undef TSI0_CH3_P5_6
#undef TSI0_CH40_P2_15
#undef TSI0_CH41_P2_16
#undef TSI0_CH42_P2_17
#undef TSI0_CH43_P2_19
#undef TSI0_CH44_P2_20
#undef TSI0_CH45_P2_21
#undef TSI0_CH46_P3_2
#undef TSI0_CH47_P3_3
#undef TSI0_CH48_P3_4
#undef TSI0_CH49_P3_5
#undef TSI0_CH4_P0_16
#undef TSI0_CH50_P3_18
#undef TSI0_CH51_P3_19
#undef TSI0_CH52_P3_20
#undef TSI0_CH53_P3_21
#undef TSI0_CH54_P3_22
#undef TSI0_CH55_P3_23
#undef TSI0_CH56_P3_24
#undef TSI0_CH57_P3_25
#undef TSI0_CH58_P4_0
#undef TSI0_CH59_P4_1
#undef TSI0_CH5_P0_17
#undef TSI0_CH60_P4_2
#undef TSI0_CH61_P4_3
#undef TSI0_CH62_P4_4
#undef TSI0_CH63_P4_5
#undef TSI0_CH64_P4_6
#undef TSI0_CH65_P4_7
#undef TSI0_CH66_P4_8
#undef TSI0_CH67_P4_9
#undef TSI0_CH68_P4_10
#undef TSI0_CH69_P4_11
#undef TSI0_CH6_P0_18
#undef TSI0_CH7_P0_19
#undef TSI0_CH8_P0_20
#undef TSI0_CH9_P0_21
#undef VREFI_P2_7

#endif /* _ZEPHYR_DTS_BINDING_MCXA567VLQ_WRAPPER_ */
