/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA286VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA287VLQ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: e6d24bac4a99a29b
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA286VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA286VLQ_WRAPPER_

#include "MCXA287VLQ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA286VLQ_WRAPPER_ */
