/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA145VLH/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA146VLH-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: d2132efb5005c509
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA145VLH_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA145VLH_WRAPPER_

#include "MCXA146VLH-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA145VLH_WRAPPER_ */
