/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA286VPN/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA287VPN-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 9588bc9c2271fd1e
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA286VPN_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA286VPN_WRAPPER_

#include "MCXA287VPN-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA286VPN_WRAPPER_ */
