/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA556VPN/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXA577VPN-pinctrl.h with this part's differences applied
 * below (103 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 9b2c405468751680
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA556VPN_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA556VPN_WRAPPER_

#include "MCXA577VPN-pinctrl.h"

/* Signals not present on this part */
#undef CAN0_RXD_P1_11
#undef CAN0_RXD_P1_19
#undef CAN0_RXD_P1_3
#undef CAN0_RXD_P2_12
#undef CAN0_TXD_P1_10
#undef CAN0_TXD_P1_18
#undef CAN0_TXD_P1_2
#undef CAN0_TXD_P2_13
#undef CAN1_RXD_P1_0
#undef CAN1_RXD_P1_12
#undef CAN1_RXD_P1_16
#undef CAN1_RXD_P1_7
#undef CAN1_RXD_P2_0
#undef CAN1_RXD_P2_15
#undef CAN1_TXD_P1_1
#undef CAN1_TXD_P1_13
#undef CAN1_TXD_P1_17
#undef CAN1_TXD_P1_6
#undef CAN1_TXD_P2_1
#undef CAN1_TXD_P2_16
#undef DAC0_OUT_P2_2
#undef DAC1_OUT_P2_3
#undef TENBASET1S_DEBUG0_P0_18
#undef TENBASET1S_DEBUG1_P0_19
#undef TENBASET1S_DEBUG2_P0_20
#undef TENBASET1S_DEBUG3_P0_21
#undef TENBASET1S_DEBUG4_P0_22
#undef TENBASET1S_ED_P1_1
#undef TENBASET1S_ED_P1_12
#undef TENBASET1S_RX_P1_0
#undef TENBASET1S_RX_P1_11
#undef TENBASET1S_TX_P1_13
#undef TENBASET1S_TX_P1_2
#undef TSI0_CH0_P5_3
#undef TSI0_CH10_P0_22
#undef TSI0_CH11_P0_23
#undef TSI0_CH12_P1_0
#undef TSI0_CH13_P1_1
#undef TSI0_CH14_P1_2
#undef TSI0_CH15_P1_3
#undef TSI0_CH16_P1_4
#undef TSI0_CH17_P1_5
#undef TSI0_CH18_P1_6
#undef TSI0_CH19_P1_7
#undef TSI0_CH1_P5_4
#undef TSI0_CH20_P1_10
#undef TSI0_CH21_P1_11
#undef TSI0_CH22_P1_12
#undef TSI0_CH23_P1_13
#undef TSI0_CH24_P1_14
#undef TSI0_CH25_P1_15
#undef TSI0_CH26_P1_16
#undef TSI0_CH27_P1_17
#undef TSI0_CH28_P1_18
#undef TSI0_CH29_P1_19
#undef TSI0_CH2_P5_5
#undef TSI0_CH30_P2_0
#undef TSI0_CH31_P2_1
#undef TSI0_CH32_P2_2
#undef TSI0_CH33_P2_3
#undef TSI0_CH34_P2_4
#undef TSI0_CH35_P2_5
#undef TSI0_CH36_P2_6
#undef TSI0_CH37_P2_7
#undef TSI0_CH38_P2_12
#undef TSI0_CH39_P2_13
#undef TSI0_CH3_P5_6
#undef TSI0_CH40_P2_15
#undef TSI0_CH41_P2_16
#undef TSI0_CH42_P2_17
#undef TSI0_CH43_P2_19
#undef TSI0_CH44_P2_20
#undef TSI0_CH45_P2_21
#undef TSI0_CH46_P3_2
#undef TSI0_CH47_P3_3
#undef TSI0_CH48_P3_4
#undef TSI0_CH49_P3_5
#undef TSI0_CH4_P0_16
#undef TSI0_CH50_P3_18
#undef TSI0_CH51_P3_19
#undef TSI0_CH52_P3_20
#undef TSI0_CH53_P3_21
#undef TSI0_CH54_P3_22
#undef TSI0_CH55_P3_23
#undef TSI0_CH56_P3_24
#undef TSI0_CH57_P3_25
#undef TSI0_CH58_P4_0
#undef TSI0_CH59_P4_1
#undef TSI0_CH5_P0_17
#undef TSI0_CH60_P4_2
#undef TSI0_CH61_P4_3
#undef TSI0_CH62_P4_4
#undef TSI0_CH63_P4_5
#undef TSI0_CH64_P4_6
#undef TSI0_CH65_P4_7
#undef TSI0_CH66_P4_8
#undef TSI0_CH67_P4_9
#undef TSI0_CH68_P4_10
#undef TSI0_CH69_P4_11
#undef TSI0_CH6_P0_18
#undef TSI0_CH7_P0_19
#undef TSI0_CH8_P0_20
#undef TSI0_CH9_P0_21

#endif /* _ZEPHYR_DTS_BINDING_MCXA556VPN_WRAPPER_ */
