/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA456VPN/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA457VPN-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: baff60aaf1817bd2
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA456VPN_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA456VPN_WRAPPER_

#include "MCXA457VPN-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA456VPN_WRAPPER_ */
