/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA566VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA567VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: f39482aec217fa54
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA566VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA566VLL_WRAPPER_

#include "MCXA567VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA566VLL_WRAPPER_ */
