/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA152VFM/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA153VFM-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: d61c6eaf169ed581
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA152VFM_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA152VFM_WRAPPER_

#include "MCXA153VFM-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA152VFM_WRAPPER_ */
