/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXA456VLQ/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXA457VLQ-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 6c62dd5846ca5b51
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXA456VLQ_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXA456VLQ_WRAPPER_

#include "MCXA457VLQ-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXA456VLQ_WRAPPER_ */
