/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXC443VMP/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXC444VLH-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 66019fd5596e23e7
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXC443VMP_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXC443VMP_WRAPPER_

#include "MCXC444VLH-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXC443VMP_WRAPPER_ */
