/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXC141VFM/signal_configuration.xml
 *
 * Copyright 2024 NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXC142VFM-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 7f1e732a6019f65e
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXC141VFM_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXC141VFM_WRAPPER_

#include "MCXC142VFM-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXC141VFM_WRAPPER_ */
