/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXC242VFM/signal_configuration.xml
 *
 * Copyright 2024 NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXC244VFM-pinctrl.h with this part's differences applied
 * below (11 removed, 0 changed,
 * 17 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 5d6c3ebd99fe3616
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXC242VFM_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXC242VFM_WRAPPER_

#include "MCXC244VFM-pinctrl.h"

/* Signals not present on this part */
#undef DAC0_OUT_PTE30
#undef I2S0_MCLK_PTC4
#undef I2S0_MCLK_PTC6
#undef I2S0_RXD0_PTC5
#undef I2S0_RX_BCLK_PTC6
#undef I2S0_RX_FS_PTC7
#undef I2S0_TXD0_PTC1
#undef I2S0_TX_BCLK_PTC3
#undef I2S0_TX_FS_PTC2
#undef SPI0_SS_PTC4
#undef SPI1_SS_PTD4

/* Signals specific to this part */
#define ADC0_DP1_PTE16 KINETIS_MUX('E',16,0)
#define ADC0_SE1_PTE16 KINETIS_MUX('E',16,0)
#define FXIO0_D0_PTE16 KINETIS_MUX('E',16,6)
#define I2C1_SCL_PTD7 KINETIS_MUX('D',7,4)
#define I2C1_SDA_PTD6 KINETIS_MUX('D',6,4)
#define PTE16 KINETIS_MUX('E',16,1)
#define SPI0_PCS0_PTC4 KINETIS_MUX('C',4,2)
#define SPI0_PCS0_PTE16 KINETIS_MUX('E',16,2)
#define SPI1_MISO_PTB0 KINETIS_MUX('B',0,5)
#define SPI1_MISO_PTB1 KINETIS_MUX('B',1,4)
#define SPI1_MOSI_PTB0 KINETIS_MUX('B',0,4)
#define SPI1_MOSI_PTB1 KINETIS_MUX('B',1,5)
#define SPI1_PCS0_PTC4 KINETIS_MUX('C',4,5)
#define SPI1_PCS0_PTD4 KINETIS_MUX('D',4,2)
#define TPM_CLKIN0_PTE16 KINETIS_MUX('E',16,4)
#define UART2_TX_PTE16 KINETIS_MUX('E',16,3)
#define VREF_OUT_PTE30 KINETIS_MUX('E',30,0)

#endif /* _ZEPHYR_DTS_BINDING_MCXC242VFM_WRAPPER_ */
