/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXC041VFG/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXC041VFG_
#define _ZEPHYR_DTS_BINDING_MCXC041VFG_

#define KINETIS_MUX(port, pin, mux)		\
	(((((port) - 'A') & 0xF) << 28) |	\
	(((pin) & 0x3F) << 22) |		\
	(((mux) & 0x7) << 8))

#define CMP0_IN2_PTA0 KINETIS_MUX('A',0,0) /* PTA_0 */
#define ADC0_SE15_PTA0 KINETIS_MUX('A',0,0) /* PTA_0 */
#define PTA0 KINETIS_MUX('A',0,1) /* PTA_0 */
#define LLWU_P7_PTA0 KINETIS_MUX('A',0,1) /* PTA_0 */
#define TPM1_CH0_PTA0 KINETIS_MUX('A',0,2) /* PTA_0 */
#define SWD_CLK_PTA0 KINETIS_MUX('A',0,3) /* PTA_0 */
#define PTA1 KINETIS_MUX('A',1,1) /* PTA_1 */
#define LPTMR0_ALT1_PTA1 KINETIS_MUX('A',1,1) /* PTA_1 */
#define TPM_CLKIN0_PTA1 KINETIS_MUX('A',1,2) /* PTA_1 */
#define RESET_b_PTA1 KINETIS_MUX('A',1,3) /* PTA_1 */
#define PTA2 KINETIS_MUX('A',2,1) /* PTA_2 */
#define CMP0_OUT_PTA2 KINETIS_MUX('A',2,2) /* PTA_2 */
#define SWD_DIO_PTA2 KINETIS_MUX('A',2,3) /* PTA_2 */
#define EXTAL0_PTA3 KINETIS_MUX('A',3,0) /* PTA_3 */
#define PTA3 KINETIS_MUX('A',3,1) /* PTA_3 */
#define I2C0_SCL_PTA3 KINETIS_MUX('A',3,2) /* PTA_3 */
#define I2C0_SDA_PTA3 KINETIS_MUX('A',3,3) /* PTA_3 */
#define LPUART0_TX_PTA3 KINETIS_MUX('A',3,4) /* PTA_3 */
#define XTAL0_PTA4 KINETIS_MUX('A',4,0) /* PTA_4 */
#define PTA4 KINETIS_MUX('A',4,1) /* PTA_4 */
#define I2C0_SDA_PTA4 KINETIS_MUX('A',4,2) /* PTA_4 */
#define I2C0_SCL_PTA4 KINETIS_MUX('A',4,3) /* PTA_4 */
#define LPUART0_RX_PTA4 KINETIS_MUX('A',4,4) /* PTA_4 */
#define CLKOUT_PTA4 KINETIS_MUX('A',4,5) /* PTA_4 */
#define PTA5 KINETIS_MUX('A',5,1) /* PTA_5 */
#define RTC_CLKIN_PTA5 KINETIS_MUX('A',5,1) /* PTA_5 */
#define TPM0_CH1_PTA5 KINETIS_MUX('A',5,2) /* PTA_5 */
#define SPI0_SS_b_PTA5 KINETIS_MUX('A',5,3) /* PTA_5 */
#define PTA6 KINETIS_MUX('A',6,1) /* PTA_6 */
#define TPM0_CH0_PTA6 KINETIS_MUX('A',6,2) /* PTA_6 */
#define SPI0_MISO_PTA6 KINETIS_MUX('A',6,3) /* PTA_6 */
#define PTA7 KINETIS_MUX('A',7,1) /* PTA_7 */
#define SPI0_MISO_PTA7 KINETIS_MUX('A',7,2) /* PTA_7 */
#define SPI0_MOSI_PTA7 KINETIS_MUX('A',7,3) /* PTA_7 */
#define ADC0_SE9_PTB0 KINETIS_MUX('B',0,0) /* PTB_0 */
#define PTB0 KINETIS_MUX('B',0,1) /* PTB_0 */
#define LLWU_P4_PTB0 KINETIS_MUX('B',0,1) /* PTB_0 */
#define EXTRG_IN_PTB0 KINETIS_MUX('B',0,2) /* PTB_0 */
#define SPI0_SCK_PTB0 KINETIS_MUX('B',0,3) /* PTB_0 */
#define I2C0_SCL_PTB0 KINETIS_MUX('B',0,4) /* PTB_0 */
#define CMP0_IN3_PTB1 KINETIS_MUX('B',1,0) /* PTB_1 */
#define ADC0_SE8_PTB1 KINETIS_MUX('B',1,0) /* PTB_1 */
#define PTB1 KINETIS_MUX('B',1,1) /* PTB_1 */
#define LPUART0_TX_PTB1 KINETIS_MUX('B',1,2) /* PTB_1 */
#define LPUART0_RX_PTB1 KINETIS_MUX('B',1,3) /* PTB_1 */
#define I2C0_SDA_PTB1 KINETIS_MUX('B',1,4) /* PTB_1 */
#define VREF_OUT_PTB2 KINETIS_MUX('B',2,0) /* PTB_2 */
#define CMP0_IN5_PTB2 KINETIS_MUX('B',2,0) /* PTB_2 */
#define PTB2 KINETIS_MUX('B',2,1) /* PTB_2 */
#define LPUART0_RX_PTB2 KINETIS_MUX('B',2,2) /* PTB_2 */
#define LPUART0_TX_PTB2 KINETIS_MUX('B',2,3) /* PTB_2 */
#define PTB3 KINETIS_MUX('B',3,1) /* PTB_3 */
#define I2C0_SCL_PTB3 KINETIS_MUX('B',3,2) /* PTB_3 */
#define LPUART0_TX_PTB3 KINETIS_MUX('B',3,3) /* PTB_3 */
#define PTB4 KINETIS_MUX('B',4,1) /* PTB_4 */
#define I2C0_SDA_PTB4 KINETIS_MUX('B',4,2) /* PTB_4 */
#define LPUART0_RX_PTB4 KINETIS_MUX('B',4,3) /* PTB_4 */
#define ADC0_SE1_PTB5 KINETIS_MUX('B',5,0) /* PTB_5 */
#define CMP0_IN1_PTB5 KINETIS_MUX('B',5,0) /* PTB_5 */
#define PTB5 KINETIS_MUX('B',5,1) /* PTB_5 */
#define TPM1_CH1_PTB5 KINETIS_MUX('B',5,2) /* PTB_5 */
#define NMI_b_PTB5 KINETIS_MUX('B',5,3) /* PTB_5 */
#endif
