/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXE247VLL/signal_configuration.xml
 *
 * Copyright 2025 NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXE247VLQ-pinctrl.h with this part's differences applied
 * below (144 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: a37fc56c898e6e9f
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXE247VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXE247VLL_WRAPPER_

#include "MCXE247VLQ-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE16_PTB18
#undef ADC0_SE17_PTB20
#undef ADC0_SE18_PTB21
#undef ADC0_SE19_PTB22
#undef ADC0_SE20_PTB23
#undef ADC0_SE21_PTB25
#undef ADC0_SE22_PTB27
#undef ADC0_SE23_PTB28
#undef ADC0_SE24_PTB29
#undef ADC0_SE25_PTC19
#undef ADC0_SE26_PTC23
#undef ADC0_SE27_PTC27
#undef ADC0_SE28_PTC28
#undef ADC0_SE29_PTC29
#undef ADC0_SE30_PTC30
#undef ADC0_SE31_PTC31
#undef ADC1_SE16_PTD18
#undef ADC1_SE17_PTD19
#undef ADC1_SE18_PTD22
#undef ADC1_SE19_PTD23
#undef ADC1_SE20_PTD24
#undef ADC1_SE21_PTD27
#undef ADC1_SE22_PTD28
#undef ADC1_SE23_PTD29
#undef ADC1_SE24_PTD30
#undef ADC1_SE25_PTE19
#undef ADC1_SE26_PTE20
#undef ADC1_SE27_PTE21
#undef ADC1_SE28_PTE22
#undef ADC1_SE29_PTE23
#undef ADC1_SE30_PTE24
#undef ADC1_SE31_PTE25
#undef CAN0_RX_PTA28
#undef CAN0_TX_PTA27
#undef CAN2_RX_PTE25
#undef CAN2_TX_PTE24
#undef FTM4_CH0_PTE20
#undef FTM4_CH1_PTE21
#undef FTM4_CH2_PTE22
#undef FTM4_CH3_PTE23
#undef FTM4_CH4_PTC27
#undef FTM4_CH4_PTE24
#undef FTM4_CH5_PTE25
#undef FTM4_CH7_PTC28
#undef FTM5_CH0_PTA25
#undef FTM5_CH1_PTA26
#undef FTM5_CH2_PTA27
#undef FTM5_CH2_PTC29
#undef FTM5_CH3_PTA28
#undef FTM5_CH4_PTA29
#undef FTM5_CH4_PTC30
#undef FTM5_CH5_PTA30
#undef FTM5_CH6_PTA31
#undef FTM5_CH6_PTC31
#undef FTM5_CH7_PTB18
#undef FTM5_CH7_PTD18
#undef FTM6_CH0_PTB20
#undef FTM6_CH0_PTD19
#undef FTM6_CH1_PTB21
#undef FTM6_CH2_PTB22
#undef FTM6_CH3_PTB23
#undef FTM6_CH3_PTD22
#undef FTM6_CH4_PTD23
#undef FTM6_CH5_PTB25
#undef FTM6_CH5_PTD24
#undef FTM6_CH7_PTB27
#undef FTM6_FLT1_PTD30
#undef FTM7_CH0_PTB28
#undef FTM7_CH0_PTD27
#undef FTM7_CH1_PTB29
#undef FTM7_CH1_PTD28
#undef FTM7_CH2_PTD29
#undef FTM7_CH3_PTD30
#undef FTM7_CH5_PTC19
#undef FTM7_CH7_PTE19
#undef FXIO_D0_PTC30
#undef FXIO_D1_PTC31
#undef FXIO_D2_PTD18
#undef FXIO_D3_PTD19
#undef LPI2C1_SCLS_PTD18
#undef LPI2C1_SCL_PTD19
#undef LPI2C1_SDAS_PTC30
#undef LPI2C1_SDA_PTC31
#undef LPSPI0_PCS0_PTA26
#undef LPSPI0_PCS1_PTA31
#undef LPSPI0_SCK_PTC23
#undef LPSPI0_SOUT_PTA30
#undef LPSPI1_PCS0_PTA26
#undef LPSPI1_PCS1_PTB18
#undef LPSPI1_SCK_PTA28
#undef LPSPI1_SIN_PTA29
#undef LPSPI1_SOUT_PTA27
#undef LPSPI2_PCS0_PTB25
#undef LPSPI2_PCS1_PTC19
#undef LPSPI2_SCK_PTB29
#undef LPSPI2_SIN_PTB28
#undef LPSPI2_SOUT_PTB27
#undef LPUART0_RX_PTA28
#undef LPUART0_TX_PTA27
#undef LPUART1_RX_PTB23
#undef LPUART1_TX_PTB22
#undef LPUART2_RX_PTA30
#undef LPUART2_TX_PTA29
#undef MII_COL_PTB23
#undef MII_CRS_PTB22
#undef PTA25
#undef PTA26
#undef PTA27
#undef PTA28
#undef PTA29
#undef PTA30
#undef PTA31
#undef PTB18
#undef PTB20
#undef PTB21
#undef PTB22
#undef PTB23
#undef PTB25
#undef PTB27
#undef PTB28
#undef PTB29
#undef PTC19
#undef PTC23
#undef PTC27
#undef PTC28
#undef PTC29
#undef PTC30
#undef PTC31
#undef PTD18
#undef PTD19
#undef PTD22
#undef PTD23
#undef PTD24
#undef PTD27
#undef PTD28
#undef PTD29
#undef PTD30
#undef PTE19
#undef PTE20
#undef PTE21
#undef PTE22
#undef PTE23
#undef PTE24
#undef PTE25

#endif /* _ZEPHYR_DTS_BINDING_MCXE247VLL_WRAPPER_ */
