/*
 * NOTE: File generated by gen_soc_headers.py
 * from MCXW235AIHNAR/signal_configuration.xml
 *
 * Copyright 2025, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXW236AIHNAR-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 12b00ae4e7c2e496
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXW235BIHNAR_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXW235BIHNAR_WRAPPER_

#include "MCXW236AIHNAR-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXW235BIHNAR_WRAPPER_ */
