/*
 * Copyright 2024 NXP
 * SPDX-License-Identifier: Apache-2.0
 *
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXW716CMFTA/signal_configuration.xml
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXW727CMFTA-pinctrl.h with this part's differences applied
 * below (18 removed, 1 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: e4e3f244538c7f47
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXW716CMFTA_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXW716CMFTA_WRAPPER_

#include "MCXW727CMFTA-pinctrl.h"

/* Signals not present on this part */
#undef CAN1_RX_PTB0
#undef CAN1_RX_PTC2
#undef CAN1_RX_PTC6
#undef CAN1_TX_PTB1
#undef CAN1_TX_PTC3
#undef CAN1_TX_PTC7
#undef LPUART0_CTS_b_PTA21
#undef LPUART0_RTS_b_PTA20
#undef RF_GPO_7_PTD1
#undef RF_UART_CTS_b_PTC0
#undef RF_UART_CTS_b_PTD3
#undef RF_UART_RTS_b_PTC1
#undef RF_UART_RTS_b_PTD4
#undef TPM2_CH0_PTD2
#undef TPM2_CH1_PTD3
#undef WUU0_P19_PTA16
#undef WUU0_P20_PTA18
#undef WUU0_P22_PTC5

/* Signals with different mux data on this part */
#undef NMI_b_PTC7
#define NMI_b_PTC7 KINETIS_MUX('C',7,1)

#endif /* _ZEPHYR_DTS_BINDING_MCXW716CMFTA_WRAPPER_ */
