/*
** ###################################################################
**     Processors:          MIMXRT2660CHPAA
**                          MIMXRT2660CVVAA
**                          MIMXRT2660DHPAA
**                          MIMXRT2660DVVAA
**                          MIMXRT2660XHP8A
**                          MIMXRT2660XVV8A
**                          MIMXRT2661CHPAA
**                          MIMXRT2661CVVAA
**                          MIMXRT2661DHPAA
**                          MIMXRT2661DVVAA
**                          MIMXRT2661XHP8A
**                          MIMXRT2661XVV8A
**                          MIMXRT2662AHP8A
**                          MIMXRT2662AVV8A
**                          MIMXRT2662CHPAA
**                          MIMXRT2662CVVAA
**                          MIMXRT2662DHPAA
**                          MIMXRT2662DVVAA
**                          MIMXRT2662XHP8A
**                          MIMXRT2662XVV8A
**                          MIMXRT2663AHP8A
**                          MIMXRT2663AVV8A
**                          MIMXRT2663CHPAA
**                          MIMXRT2663CVVAA
**                          MIMXRT2663DHPAA
**                          MIMXRT2663DVVAA
**                          MIMXRT2663XHP8A
**                          MIMXRT2663XHPAA
**                          MIMXRT2663XVV8A
**                          MIMXRT2663XVVAA
**
**     Version:             rev. 1.0, 2024-11-05
**     Build:               b260818
**
**     Abstract:
**         CMSIS Peripheral Access Layer for MIPI_CSI2RX
**
**     Copyright 1997-2016 Freescale Semiconductor, Inc.
**     Copyright 2016-2026 NXP
**     SPDX-License-Identifier: BSD-3-Clause
**
**     http:                 www.nxp.com
**     mail:                 support@nxp.com
**
**     Revisions:
**     - rev. 1.0 (2024-11-05)
**         Initial version.
**
** ###################################################################
*/

/*!
 * @file PERI_MIPI_CSI2RX.h
 * @version 1.0
 * @date 2024-11-05
 * @brief CMSIS Peripheral Access Layer for MIPI_CSI2RX
 *
 * CMSIS Peripheral Access Layer for MIPI_CSI2RX
 */

#if !defined(PERI_MIPI_CSI2RX_H_)
#define PERI_MIPI_CSI2RX_H_                      /**< Symbol preventing repeated inclusion */

#if (defined(CPU_MIMXRT2660CHPAA) || defined(CPU_MIMXRT2660CVVAA) || defined(CPU_MIMXRT2660DHPAA) || defined(CPU_MIMXRT2660DVVAA) || defined(CPU_MIMXRT2660XHP8A) || defined(CPU_MIMXRT2660XVV8A))
#include "MIMXRT2660_COMMON.h"
#elif (defined(CPU_MIMXRT2661CHPAA) || defined(CPU_MIMXRT2661CVVAA) || defined(CPU_MIMXRT2661DHPAA) || defined(CPU_MIMXRT2661DVVAA) || defined(CPU_MIMXRT2661XHP8A) || defined(CPU_MIMXRT2661XVV8A))
#include "MIMXRT2661_COMMON.h"
#elif (defined(CPU_MIMXRT2662AHP8A) || defined(CPU_MIMXRT2662AVV8A) || defined(CPU_MIMXRT2662CHPAA) || defined(CPU_MIMXRT2662CVVAA) || defined(CPU_MIMXRT2662DHPAA) || defined(CPU_MIMXRT2662DVVAA) || defined(CPU_MIMXRT2662XHP8A) || defined(CPU_MIMXRT2662XVV8A))
#include "MIMXRT2662_COMMON.h"
#elif (defined(CPU_MIMXRT2663AHP8A) || defined(CPU_MIMXRT2663AVV8A) || defined(CPU_MIMXRT2663CHPAA) || defined(CPU_MIMXRT2663CVVAA) || defined(CPU_MIMXRT2663DHPAA) || defined(CPU_MIMXRT2663DVVAA) || defined(CPU_MIMXRT2663XHP8A) || defined(CPU_MIMXRT2663XHPAA) || defined(CPU_MIMXRT2663XVV8A) || defined(CPU_MIMXRT2663XVVAA))
#include "MIMXRT2663_COMMON.h"
#else
  #error "No valid CPU defined!"
#endif

/* ----------------------------------------------------------------------------
   -- Device Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup Peripheral_access_layer Device Peripheral Access Layer
 * @{
 */


/*
** Start of section using anonymous unions
*/

#if defined(__ARMCC_VERSION)
  #if (__ARMCC_VERSION >= 6010050)
    #pragma clang diagnostic push
  #else
    #pragma push
    #pragma anon_unions
  #endif
#elif defined(__GNUC__)
  /* anonymous unions are enabled by default */
#elif defined(__IAR_SYSTEMS_ICC__)
  #pragma language=extended
#else
  #error Not supported compiler type
#endif

/* ----------------------------------------------------------------------------
   -- MIPI_CSI2RX Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup MIPI_CSI2RX_Peripheral_Access_Layer MIPI_CSI2RX Peripheral Access Layer
 * @{
 */

/** MIPI_CSI2RX - Register Layout Typedef */
typedef struct {
  __IO uint32_t CFG_MODE;                          /**< Mode, offset: 0x0 */
  __IO uint32_t CFG_FLUSH_COUNT;                   /**< Flush Counter, offset: 0x4 */
  __IO uint32_t CFG_WATCHDOG_COUNT;                /**< Watchdog Counter, offset: 0x8 */
  __I  uint32_t BIT_ERR;                           /**< Bit Error, offset: 0xC */
  __I  uint32_t PAYLOAD_CRC;                       /**< Payload CRC, offset: 0x10 */
  __IO uint32_t IRQ_STATUS;                        /**< Interrupt Request Status, offset: 0x14 */
  __IO uint32_t IRQ_ENABLE;                        /**< Interrupt Request Enable, offset: 0x18 */
  __IO uint32_t CFG_DISABLE_PAYLOAD_0;             /**< Disable Payload 0, offset: 0x1C */
  __IO uint32_t CFG_DISABLE_PAYLOAD_1;             /**< Disable Payload 1, offset: 0x20 */
  __IO uint32_t CFG_RX_USERDEF_DT_0;               /**< Receiver User-Defined Data 0, offset: 0x24 */
  __IO uint32_t CFG_RX_USERDEF_DT_1;               /**< Receiver User-Defined Data 1, offset: 0x28 */
  __IO uint32_t CFG_RX_GENERIC_DT_MAP;             /**< Receiver Generic Data Map, offset: 0x2C */
  __IO uint32_t CLOCK_LANE;                        /**< Clock Lane, offset: 0x30 */
  __IO uint32_t LANE_0;                            /**< Lane 0, offset: 0x34 */
  __IO uint32_t LANE_1;                            /**< Lane 1, offset: 0x38 */
       uint8_t RESERVED_0[452];
  __IO uint32_t CFG_REG0;                          /**< Configuration 0, offset: 0x200 */
  __I  uint32_t CFG_REG1;                          /**< Configuration 1, offset: 0x204 */
} MIPI_CSI2RX_Type;

/* ----------------------------------------------------------------------------
   -- MIPI_CSI2RX Register Masks
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup MIPI_CSI2RX_Register_Masks MIPI_CSI2RX Register Masks
 * @{
 */

/*! @name CFG_MODE - Mode */
/*! @{ */

#define MIPI_CSI2RX_CFG_MODE_CFG_NUM_LANES_MASK  (0xFU)
#define MIPI_CSI2RX_CFG_MODE_CFG_NUM_LANES_SHIFT (0U)
/*! cfg_num_lanes
 *  0b0001..1 Lane
 *  0b0010..2 Lanes
 *  0b0011..3 Lanes
 *  0b0100..4 Lanes
 *  0b1000..8 Lanes
 */
#define MIPI_CSI2RX_CFG_MODE_CFG_NUM_LANES(x)    (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_MODE_CFG_NUM_LANES_SHIFT)) & MIPI_CSI2RX_CFG_MODE_CFG_NUM_LANES_MASK)

#define MIPI_CSI2RX_CFG_MODE_CFG_VCX_EN_MASK     (0x100U)
#define MIPI_CSI2RX_CFG_MODE_CFG_VCX_EN_SHIFT    (8U)
/*! cfg_vcx_en - Virtual Channel Extension (VCX) Enable
 *  0b0..4 Virtual Channels
 *  0b1..16 (DPHY) Virtual Channels
 */
#define MIPI_CSI2RX_CFG_MODE_CFG_VCX_EN(x)       (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_MODE_CFG_VCX_EN_SHIFT)) & MIPI_CSI2RX_CFG_MODE_CFG_VCX_EN_MASK)

#define MIPI_CSI2RX_CFG_MODE_CFG_PACKET_INTERFACE_EN_MASK (0x200U)
#define MIPI_CSI2RX_CFG_MODE_CFG_PACKET_INTERFACE_EN_SHIFT (9U)
/*! cfg_packet_interface_en
 *  0b0..Pixel Interface
 *  0b1..Packet Interface
 */
#define MIPI_CSI2RX_CFG_MODE_CFG_PACKET_INTERFACE_EN(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_MODE_CFG_PACKET_INTERFACE_EN_SHIFT)) & MIPI_CSI2RX_CFG_MODE_CFG_PACKET_INTERFACE_EN_MASK)

#define MIPI_CSI2RX_CFG_MODE_CFG_SCRAMBLE_EN_MASK (0x800U)
#define MIPI_CSI2RX_CFG_MODE_CFG_SCRAMBLE_EN_SHIFT (11U)
/*! cfg_scramble_en
 *  0b0..Scramble encryption off
 *  0b1..Scramble encryption on
 */
#define MIPI_CSI2RX_CFG_MODE_CFG_SCRAMBLE_EN(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_MODE_CFG_SCRAMBLE_EN_SHIFT)) & MIPI_CSI2RX_CFG_MODE_CFG_SCRAMBLE_EN_MASK)

#define MIPI_CSI2RX_CFG_MODE_CFG_BYTE_DATA_FORMAT_MASK (0x30000U)
#define MIPI_CSI2RX_CFG_MODE_CFG_BYTE_DATA_FORMAT_SHIFT (16U)
#define MIPI_CSI2RX_CFG_MODE_CFG_BYTE_DATA_FORMAT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_MODE_CFG_BYTE_DATA_FORMAT_SHIFT)) & MIPI_CSI2RX_CFG_MODE_CFG_BYTE_DATA_FORMAT_MASK)
/*! @} */

/*! @name CFG_FLUSH_COUNT - Flush Counter */
/*! @{ */

#define MIPI_CSI2RX_CFG_FLUSH_COUNT_CFG_FLUSH_COUNT_MASK (0xFU)
#define MIPI_CSI2RX_CFG_FLUSH_COUNT_CFG_FLUSH_COUNT_SHIFT (0U)
#define MIPI_CSI2RX_CFG_FLUSH_COUNT_CFG_FLUSH_COUNT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_FLUSH_COUNT_CFG_FLUSH_COUNT_SHIFT)) & MIPI_CSI2RX_CFG_FLUSH_COUNT_CFG_FLUSH_COUNT_MASK)
/*! @} */

/*! @name CFG_WATCHDOG_COUNT - Watchdog Counter */
/*! @{ */

#define MIPI_CSI2RX_CFG_WATCHDOG_COUNT_CFG_WATCHDOG_COUNT_MASK (0xFFFFU)
#define MIPI_CSI2RX_CFG_WATCHDOG_COUNT_CFG_WATCHDOG_COUNT_SHIFT (0U)
#define MIPI_CSI2RX_CFG_WATCHDOG_COUNT_CFG_WATCHDOG_COUNT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_WATCHDOG_COUNT_CFG_WATCHDOG_COUNT_SHIFT)) & MIPI_CSI2RX_CFG_WATCHDOG_COUNT_CFG_WATCHDOG_COUNT_MASK)

#define MIPI_CSI2RX_CFG_WATCHDOG_COUNT_CFG_WATCHDOG_EN_MASK (0x80000000U)
#define MIPI_CSI2RX_CFG_WATCHDOG_COUNT_CFG_WATCHDOG_EN_SHIFT (31U)
#define MIPI_CSI2RX_CFG_WATCHDOG_COUNT_CFG_WATCHDOG_EN(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_WATCHDOG_COUNT_CFG_WATCHDOG_EN_SHIFT)) & MIPI_CSI2RX_CFG_WATCHDOG_COUNT_CFG_WATCHDOG_EN_MASK)
/*! @} */

/*! @name BIT_ERR - Bit Error */
/*! @{ */

#define MIPI_CSI2RX_BIT_ERR_BIT_ERR_MASK         (0xFFFFU)
#define MIPI_CSI2RX_BIT_ERR_BIT_ERR_SHIFT        (0U)
#define MIPI_CSI2RX_BIT_ERR_BIT_ERR(x)           (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_BIT_ERR_BIT_ERR_SHIFT)) & MIPI_CSI2RX_BIT_ERR_BIT_ERR_MASK)

#define MIPI_CSI2RX_BIT_ERR_ECC_RECEIVED_STATUS_MASK (0x3F0000U)
#define MIPI_CSI2RX_BIT_ERR_ECC_RECEIVED_STATUS_SHIFT (16U)
#define MIPI_CSI2RX_BIT_ERR_ECC_RECEIVED_STATUS(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_BIT_ERR_ECC_RECEIVED_STATUS_SHIFT)) & MIPI_CSI2RX_BIT_ERR_ECC_RECEIVED_STATUS_MASK)

#define MIPI_CSI2RX_BIT_ERR_UNSUPPORTED_DATA_TYPE_STATUS_MASK (0x400000U)
#define MIPI_CSI2RX_BIT_ERR_UNSUPPORTED_DATA_TYPE_STATUS_SHIFT (22U)
#define MIPI_CSI2RX_BIT_ERR_UNSUPPORTED_DATA_TYPE_STATUS(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_BIT_ERR_UNSUPPORTED_DATA_TYPE_STATUS_SHIFT)) & MIPI_CSI2RX_BIT_ERR_UNSUPPORTED_DATA_TYPE_STATUS_MASK)

#define MIPI_CSI2RX_BIT_ERR_EXIT_HS_ERROR_STATUS_MASK (0x800000U)
#define MIPI_CSI2RX_BIT_ERR_EXIT_HS_ERROR_STATUS_SHIFT (23U)
#define MIPI_CSI2RX_BIT_ERR_EXIT_HS_ERROR_STATUS(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_BIT_ERR_EXIT_HS_ERROR_STATUS_SHIFT)) & MIPI_CSI2RX_BIT_ERR_EXIT_HS_ERROR_STATUS_MASK)
/*! @} */

/*! @name PAYLOAD_CRC - Payload CRC */
/*! @{ */

#define MIPI_CSI2RX_PAYLOAD_CRC_CRC_RECEIVED_MASK (0xFFFFU)
#define MIPI_CSI2RX_PAYLOAD_CRC_CRC_RECEIVED_SHIFT (0U)
#define MIPI_CSI2RX_PAYLOAD_CRC_CRC_RECEIVED(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_PAYLOAD_CRC_CRC_RECEIVED_SHIFT)) & MIPI_CSI2RX_PAYLOAD_CRC_CRC_RECEIVED_MASK)

#define MIPI_CSI2RX_PAYLOAD_CRC_CRC_CALCULATED_MASK (0xFFFF0000U)
#define MIPI_CSI2RX_PAYLOAD_CRC_CRC_CALCULATED_SHIFT (16U)
#define MIPI_CSI2RX_PAYLOAD_CRC_CRC_CALCULATED(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_PAYLOAD_CRC_CRC_CALCULATED_SHIFT)) & MIPI_CSI2RX_PAYLOAD_CRC_CRC_CALCULATED_MASK)
/*! @} */

/*! @name IRQ_STATUS - Interrupt Request Status */
/*! @{ */

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_0_MASK (0x1U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_0_SHIFT (0U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_0(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_0_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_0_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_1_MASK (0x2U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_1_SHIFT (1U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_1(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_1_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_1_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_2_MASK (0x4U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_2_SHIFT (2U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_2(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_2_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_2_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_3_MASK (0x8U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_3_SHIFT (3U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_3(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_3_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_3_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_4_MASK (0x10U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_4_SHIFT (4U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_4(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_4_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_4_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_5_MASK (0x20U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_5_SHIFT (5U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_5(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_5_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_5_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_6_MASK (0x40U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_6_SHIFT (6U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_6(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_6_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_6_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_7_MASK (0x80U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_7_SHIFT (7U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_7(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_7_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_7_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_8_MASK (0x100U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_8_SHIFT (8U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_8(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_8_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_8_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_9_MASK (0x200U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_9_SHIFT (9U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_9(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_9_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_9_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_10_MASK (0x400U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_10_SHIFT (10U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_10(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_10_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_10_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_11_MASK (0x800U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_11_SHIFT (11U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_11(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_11_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_11_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_12_MASK (0x1000U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_12_SHIFT (12U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_12(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_12_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_12_MASK)

#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_17_MASK (0x20000U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_17_SHIFT (17U)
#define MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_17(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_17_SHIFT)) & MIPI_CSI2RX_IRQ_STATUS_IRQ_STATUS_17_MASK)
/*! @} */

/*! @name IRQ_ENABLE - Interrupt Request Enable */
/*! @{ */

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_0_MASK (0x1U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_0_SHIFT (0U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_0(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_0_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_0_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_1_MASK (0x2U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_1_SHIFT (1U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_1(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_1_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_1_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_2_MASK (0x4U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_2_SHIFT (2U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_2(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_2_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_2_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_3_MASK (0x8U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_3_SHIFT (3U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_3(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_3_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_3_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_4_MASK (0x10U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_4_SHIFT (4U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_4(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_4_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_4_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_5_MASK (0x20U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_5_SHIFT (5U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_5(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_5_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_5_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_6_MASK (0x40U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_6_SHIFT (6U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_6(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_6_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_6_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_7_MASK (0x80U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_7_SHIFT (7U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_7(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_7_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_7_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_8_MASK (0x100U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_8_SHIFT (8U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_8(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_8_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_8_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_9_MASK (0x200U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_9_SHIFT (9U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_9(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_9_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_9_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_10_MASK (0x400U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_10_SHIFT (10U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_10(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_10_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_10_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_11_MASK (0x800U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_11_SHIFT (11U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_11(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_11_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_11_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_12_MASK (0x1000U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_12_SHIFT (12U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_12(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_12_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_12_MASK)

#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_17_MASK (0x20000U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_17_SHIFT (17U)
#define MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_17(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_17_SHIFT)) & MIPI_CSI2RX_IRQ_ENABLE_IRQ_ENABLE_17_MASK)
/*! @} */

/*! @name CFG_DISABLE_PAYLOAD_0 - Disable Payload 0 */
/*! @{ */

#define MIPI_CSI2RX_CFG_DISABLE_PAYLOAD_0_CFG_DISABLE_PAYLOAD_31_0_MASK (0xFFFFFFFFU)
#define MIPI_CSI2RX_CFG_DISABLE_PAYLOAD_0_CFG_DISABLE_PAYLOAD_31_0_SHIFT (0U)
#define MIPI_CSI2RX_CFG_DISABLE_PAYLOAD_0_CFG_DISABLE_PAYLOAD_31_0(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_DISABLE_PAYLOAD_0_CFG_DISABLE_PAYLOAD_31_0_SHIFT)) & MIPI_CSI2RX_CFG_DISABLE_PAYLOAD_0_CFG_DISABLE_PAYLOAD_31_0_MASK)
/*! @} */

/*! @name CFG_DISABLE_PAYLOAD_1 - Disable Payload 1 */
/*! @{ */

#define MIPI_CSI2RX_CFG_DISABLE_PAYLOAD_1_CFG_DISABLE_PAYLOAD_48_32_MASK (0x1FFFFU)
#define MIPI_CSI2RX_CFG_DISABLE_PAYLOAD_1_CFG_DISABLE_PAYLOAD_48_32_SHIFT (0U)
#define MIPI_CSI2RX_CFG_DISABLE_PAYLOAD_1_CFG_DISABLE_PAYLOAD_48_32(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_DISABLE_PAYLOAD_1_CFG_DISABLE_PAYLOAD_48_32_SHIFT)) & MIPI_CSI2RX_CFG_DISABLE_PAYLOAD_1_CFG_DISABLE_PAYLOAD_48_32_MASK)
/*! @} */

/*! @name CFG_RX_USERDEF_DT_0 - Receiver User-Defined Data 0 */
/*! @{ */

#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_30H_DT_MASK (0x3FU)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_30H_DT_SHIFT (0U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_30H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_30H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_30H_DT_MASK)

#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_31H_DT_MASK (0x3F00U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_31H_DT_SHIFT (8U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_31H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_31H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_31H_DT_MASK)

#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_32H_DT_MASK (0x3F0000U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_32H_DT_SHIFT (16U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_32H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_32H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_32H_DT_MASK)

#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_33H_DT_MASK (0x3F000000U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_33H_DT_SHIFT (24U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_33H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_33H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_USERDEF_DT_0_CFG_USERDEF_33H_DT_MASK)
/*! @} */

/*! @name CFG_RX_USERDEF_DT_1 - Receiver User-Defined Data 1 */
/*! @{ */

#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_34H_DT_MASK (0x3FU)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_34H_DT_SHIFT (0U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_34H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_34H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_34H_DT_MASK)

#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_35H_DT_MASK (0x3F00U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_35H_DT_SHIFT (8U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_35H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_35H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_35H_DT_MASK)

#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_36H_DT_MASK (0x3F0000U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_36H_DT_SHIFT (16U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_36H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_36H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_36H_DT_MASK)

#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_37H_DT_MASK (0x3F000000U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_37H_DT_SHIFT (24U)
#define MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_37H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_37H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_USERDEF_DT_1_CFG_USERDEF_37H_DT_MASK)
/*! @} */

/*! @name CFG_RX_GENERIC_DT_MAP - Receiver Generic Data Map */
/*! @{ */

#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_13H_DT_MASK (0x3FU)
#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_13H_DT_SHIFT (0U)
#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_13H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_13H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_13H_DT_MASK)

#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_14H_DT_MASK (0x3F00U)
#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_14H_DT_SHIFT (8U)
#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_14H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_14H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_14H_DT_MASK)

#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_15H_DT_MASK (0x3F0000U)
#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_15H_DT_SHIFT (16U)
#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_15H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_15H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_15H_DT_MASK)

#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_16H_DT_MASK (0x3F000000U)
#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_16H_DT_SHIFT (24U)
#define MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_16H_DT(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_16H_DT_SHIFT)) & MIPI_CSI2RX_CFG_RX_GENERIC_DT_MAP_CFG_GENERIC_16H_DT_MASK)
/*! @} */

/*! @name CLOCK_LANE - Clock Lane */
/*! @{ */

#define MIPI_CSI2RX_CLOCK_LANE_ULPS_CLK_MARK_STATUS_MASK (0x1U)
#define MIPI_CSI2RX_CLOCK_LANE_ULPS_CLK_MARK_STATUS_SHIFT (0U)
#define MIPI_CSI2RX_CLOCK_LANE_ULPS_CLK_MARK_STATUS(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CLOCK_LANE_ULPS_CLK_MARK_STATUS_SHIFT)) & MIPI_CSI2RX_CLOCK_LANE_ULPS_CLK_MARK_STATUS_MASK)

#define MIPI_CSI2RX_CLOCK_LANE_ULPS_CLK_STATUS_MASK (0x2U)
#define MIPI_CSI2RX_CLOCK_LANE_ULPS_CLK_STATUS_SHIFT (1U)
#define MIPI_CSI2RX_CLOCK_LANE_ULPS_CLK_STATUS(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CLOCK_LANE_ULPS_CLK_STATUS_SHIFT)) & MIPI_CSI2RX_CLOCK_LANE_ULPS_CLK_STATUS_MASK)

#define MIPI_CSI2RX_CLOCK_LANE_CFG_CLK_LANE_EN_MASK (0x80000000U)
#define MIPI_CSI2RX_CLOCK_LANE_CFG_CLK_LANE_EN_SHIFT (31U)
#define MIPI_CSI2RX_CLOCK_LANE_CFG_CLK_LANE_EN(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CLOCK_LANE_CFG_CLK_LANE_EN_SHIFT)) & MIPI_CSI2RX_CLOCK_LANE_CFG_CLK_LANE_EN_MASK)
/*! @} */

/*! @name LANE_0 - Lane 0 */
/*! @{ */

#define MIPI_CSI2RX_LANE_0_ULPS_MARK_STATUS_LN0_MASK (0x1U)
#define MIPI_CSI2RX_LANE_0_ULPS_MARK_STATUS_LN0_SHIFT (0U)
#define MIPI_CSI2RX_LANE_0_ULPS_MARK_STATUS_LN0(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_ULPS_MARK_STATUS_LN0_SHIFT)) & MIPI_CSI2RX_LANE_0_ULPS_MARK_STATUS_LN0_MASK)

#define MIPI_CSI2RX_LANE_0_ULPS_STATUS_LN0_MASK  (0x2U)
#define MIPI_CSI2RX_LANE_0_ULPS_STATUS_LN0_SHIFT (1U)
#define MIPI_CSI2RX_LANE_0_ULPS_STATUS_LN0(x)    (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_ULPS_STATUS_LN0_SHIFT)) & MIPI_CSI2RX_LANE_0_ULPS_STATUS_LN0_MASK)

#define MIPI_CSI2RX_LANE_0_STOPSTATE_STATUS_LN0_MASK (0x4U)
#define MIPI_CSI2RX_LANE_0_STOPSTATE_STATUS_LN0_SHIFT (2U)
#define MIPI_CSI2RX_LANE_0_STOPSTATE_STATUS_LN0(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_STOPSTATE_STATUS_LN0_SHIFT)) & MIPI_CSI2RX_LANE_0_STOPSTATE_STATUS_LN0_MASK)

#define MIPI_CSI2RX_LANE_0_SKEWCAL_STATUS_LN0_MASK (0x8U)
#define MIPI_CSI2RX_LANE_0_SKEWCAL_STATUS_LN0_SHIFT (3U)
#define MIPI_CSI2RX_LANE_0_SKEWCAL_STATUS_LN0(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_SKEWCAL_STATUS_LN0_SHIFT)) & MIPI_CSI2RX_LANE_0_SKEWCAL_STATUS_LN0_MASK)

#define MIPI_CSI2RX_LANE_0_PPI_ERRCONTROL_LN0_MASK (0x400U)
#define MIPI_CSI2RX_LANE_0_PPI_ERRCONTROL_LN0_SHIFT (10U)
#define MIPI_CSI2RX_LANE_0_PPI_ERRCONTROL_LN0(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_PPI_ERRCONTROL_LN0_SHIFT)) & MIPI_CSI2RX_LANE_0_PPI_ERRCONTROL_LN0_MASK)

#define MIPI_CSI2RX_LANE_0_PPI_ERRSYNCESC_LN0_MASK (0x800U)
#define MIPI_CSI2RX_LANE_0_PPI_ERRSYNCESC_LN0_SHIFT (11U)
#define MIPI_CSI2RX_LANE_0_PPI_ERRSYNCESC_LN0(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_PPI_ERRSYNCESC_LN0_SHIFT)) & MIPI_CSI2RX_LANE_0_PPI_ERRSYNCESC_LN0_MASK)

#define MIPI_CSI2RX_LANE_0_PPI_ERRESC_LN0_MASK   (0x1000U)
#define MIPI_CSI2RX_LANE_0_PPI_ERRESC_LN0_SHIFT  (12U)
#define MIPI_CSI2RX_LANE_0_PPI_ERRESC_LN0(x)     (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_PPI_ERRESC_LN0_SHIFT)) & MIPI_CSI2RX_LANE_0_PPI_ERRESC_LN0_MASK)

#define MIPI_CSI2RX_LANE_0_PPI_ERRSOTSYNCHS_LN0_MASK (0x2000U)
#define MIPI_CSI2RX_LANE_0_PPI_ERRSOTSYNCHS_LN0_SHIFT (13U)
#define MIPI_CSI2RX_LANE_0_PPI_ERRSOTSYNCHS_LN0(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_PPI_ERRSOTSYNCHS_LN0_SHIFT)) & MIPI_CSI2RX_LANE_0_PPI_ERRSOTSYNCHS_LN0_MASK)

#define MIPI_CSI2RX_LANE_0_PPI_ERRSOTHS_LN0_MASK (0x4000U)
#define MIPI_CSI2RX_LANE_0_PPI_ERRSOTHS_LN0_SHIFT (14U)
#define MIPI_CSI2RX_LANE_0_PPI_ERRSOTHS_LN0(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_PPI_ERRSOTHS_LN0_SHIFT)) & MIPI_CSI2RX_LANE_0_PPI_ERRSOTHS_LN0_MASK)

#define MIPI_CSI2RX_LANE_0_CFG_RX_LANE0_SEL_MASK (0x3000000U)
#define MIPI_CSI2RX_LANE_0_CFG_RX_LANE0_SEL_SHIFT (24U)
/*! cfg_rx_lane0_sel
 *  0b00..Data lane 0 on the Tx Controller gets data lane 0 on the MIPI interface
 *  0b01..Data lane 0 on the Tx Controller gets data lane 1 on the MIPI interface
 *  0b10..Data lane 0 on the Tx Controller gets data lane 2 on the MIPI interface
 *  0b11..Data lane 0 on the Tx Controller gets data lane 3 on the MIPI interface
 */
#define MIPI_CSI2RX_LANE_0_CFG_RX_LANE0_SEL(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_CFG_RX_LANE0_SEL_SHIFT)) & MIPI_CSI2RX_LANE_0_CFG_RX_LANE0_SEL_MASK)

#define MIPI_CSI2RX_LANE_0_CFG_DATA_LANE_EN_LN0_MASK (0x80000000U)
#define MIPI_CSI2RX_LANE_0_CFG_DATA_LANE_EN_LN0_SHIFT (31U)
#define MIPI_CSI2RX_LANE_0_CFG_DATA_LANE_EN_LN0(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_0_CFG_DATA_LANE_EN_LN0_SHIFT)) & MIPI_CSI2RX_LANE_0_CFG_DATA_LANE_EN_LN0_MASK)
/*! @} */

/*! @name LANE_1 - Lane 1 */
/*! @{ */

#define MIPI_CSI2RX_LANE_1_ULPS_MARK_STATUS_LN1_MASK (0x1U)
#define MIPI_CSI2RX_LANE_1_ULPS_MARK_STATUS_LN1_SHIFT (0U)
#define MIPI_CSI2RX_LANE_1_ULPS_MARK_STATUS_LN1(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_ULPS_MARK_STATUS_LN1_SHIFT)) & MIPI_CSI2RX_LANE_1_ULPS_MARK_STATUS_LN1_MASK)

#define MIPI_CSI2RX_LANE_1_ULPS_STATUS_LN1_MASK  (0x2U)
#define MIPI_CSI2RX_LANE_1_ULPS_STATUS_LN1_SHIFT (1U)
#define MIPI_CSI2RX_LANE_1_ULPS_STATUS_LN1(x)    (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_ULPS_STATUS_LN1_SHIFT)) & MIPI_CSI2RX_LANE_1_ULPS_STATUS_LN1_MASK)

#define MIPI_CSI2RX_LANE_1_STOPSTATE_STATUS_LN1_MASK (0x4U)
#define MIPI_CSI2RX_LANE_1_STOPSTATE_STATUS_LN1_SHIFT (2U)
#define MIPI_CSI2RX_LANE_1_STOPSTATE_STATUS_LN1(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_STOPSTATE_STATUS_LN1_SHIFT)) & MIPI_CSI2RX_LANE_1_STOPSTATE_STATUS_LN1_MASK)

#define MIPI_CSI2RX_LANE_1_SKEWCAL_STATUS_LN1_MASK (0x8U)
#define MIPI_CSI2RX_LANE_1_SKEWCAL_STATUS_LN1_SHIFT (3U)
#define MIPI_CSI2RX_LANE_1_SKEWCAL_STATUS_LN1(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_SKEWCAL_STATUS_LN1_SHIFT)) & MIPI_CSI2RX_LANE_1_SKEWCAL_STATUS_LN1_MASK)

#define MIPI_CSI2RX_LANE_1_PPI_ERRCONTROL_LN1_MASK (0x400U)
#define MIPI_CSI2RX_LANE_1_PPI_ERRCONTROL_LN1_SHIFT (10U)
#define MIPI_CSI2RX_LANE_1_PPI_ERRCONTROL_LN1(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_PPI_ERRCONTROL_LN1_SHIFT)) & MIPI_CSI2RX_LANE_1_PPI_ERRCONTROL_LN1_MASK)

#define MIPI_CSI2RX_LANE_1_PPI_ERRSYNCESC_LN1_MASK (0x800U)
#define MIPI_CSI2RX_LANE_1_PPI_ERRSYNCESC_LN1_SHIFT (11U)
#define MIPI_CSI2RX_LANE_1_PPI_ERRSYNCESC_LN1(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_PPI_ERRSYNCESC_LN1_SHIFT)) & MIPI_CSI2RX_LANE_1_PPI_ERRSYNCESC_LN1_MASK)

#define MIPI_CSI2RX_LANE_1_PPI_ERRESC_LN1_MASK   (0x1000U)
#define MIPI_CSI2RX_LANE_1_PPI_ERRESC_LN1_SHIFT  (12U)
#define MIPI_CSI2RX_LANE_1_PPI_ERRESC_LN1(x)     (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_PPI_ERRESC_LN1_SHIFT)) & MIPI_CSI2RX_LANE_1_PPI_ERRESC_LN1_MASK)

#define MIPI_CSI2RX_LANE_1_PPI_ERRSOTSYNCHS_LN1_MASK (0x2000U)
#define MIPI_CSI2RX_LANE_1_PPI_ERRSOTSYNCHS_LN1_SHIFT (13U)
#define MIPI_CSI2RX_LANE_1_PPI_ERRSOTSYNCHS_LN1(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_PPI_ERRSOTSYNCHS_LN1_SHIFT)) & MIPI_CSI2RX_LANE_1_PPI_ERRSOTSYNCHS_LN1_MASK)

#define MIPI_CSI2RX_LANE_1_PPI_ERRSOTHS_LN1_MASK (0x4000U)
#define MIPI_CSI2RX_LANE_1_PPI_ERRSOTHS_LN1_SHIFT (14U)
#define MIPI_CSI2RX_LANE_1_PPI_ERRSOTHS_LN1(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_PPI_ERRSOTHS_LN1_SHIFT)) & MIPI_CSI2RX_LANE_1_PPI_ERRSOTHS_LN1_MASK)

#define MIPI_CSI2RX_LANE_1_CFG_RX_LANE1_SEL_MASK (0x3000000U)
#define MIPI_CSI2RX_LANE_1_CFG_RX_LANE1_SEL_SHIFT (24U)
/*! cfg_rx_lane1_sel
 *  0b00..Data lane 1 on the Tx Controller gets data lane 0 on the MIPI interface
 *  0b01..Data lane 1 on the Tx Controller gets data lane 1 on the MIPI interface
 *  0b10..Data lane 1 on the Tx Controller gets data lane 2 on the MIPI interface
 *  0b11..Data lane 1 on the Tx Controller gets data lane 3 on the MIPI interface
 */
#define MIPI_CSI2RX_LANE_1_CFG_RX_LANE1_SEL(x)   (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_CFG_RX_LANE1_SEL_SHIFT)) & MIPI_CSI2RX_LANE_1_CFG_RX_LANE1_SEL_MASK)

#define MIPI_CSI2RX_LANE_1_CFG_DATA_LANE_EN_LN1_MASK (0x80000000U)
#define MIPI_CSI2RX_LANE_1_CFG_DATA_LANE_EN_LN1_SHIFT (31U)
#define MIPI_CSI2RX_LANE_1_CFG_DATA_LANE_EN_LN1(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_LANE_1_CFG_DATA_LANE_EN_LN1_SHIFT)) & MIPI_CSI2RX_LANE_1_CFG_DATA_LANE_EN_LN1_MASK)
/*! @} */

/*! @name CFG_REG0 - Configuration 0 */
/*! @{ */

#define MIPI_CSI2RX_CFG_REG0_CFG_TST_CLKDSKW_MASK (0x10U)
#define MIPI_CSI2RX_CFG_REG0_CFG_TST_CLKDSKW_SHIFT (4U)
#define MIPI_CSI2RX_CFG_REG0_CFG_TST_CLKDSKW(x)  (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_TST_CLKDSKW_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_TST_CLKDSKW_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_DPHY_DESKEW_EN_MASK (0x20U)
#define MIPI_CSI2RX_CFG_REG0_CFG_DPHY_DESKEW_EN_SHIFT (5U)
#define MIPI_CSI2RX_CFG_REG0_CFG_DPHY_DESKEW_EN(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_DPHY_DESKEW_EN_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_DPHY_DESKEW_EN_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_CLK_PNCH_MASK   (0x40U)
#define MIPI_CSI2RX_CFG_REG0_CFG_CLK_PNCH_SHIFT  (6U)
#define MIPI_CSI2RX_CFG_REG0_CFG_CLK_PNCH(x)     (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_CLK_PNCH_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_CLK_PNCH_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_D1_PNCH_MASK    (0x80U)
#define MIPI_CSI2RX_CFG_REG0_CFG_D1_PNCH_SHIFT   (7U)
#define MIPI_CSI2RX_CFG_REG0_CFG_D1_PNCH(x)      (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_D1_PNCH_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_D1_PNCH_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_D0_PNCH_MASK    (0x100U)
#define MIPI_CSI2RX_CFG_REG0_CFG_D0_PNCH_SHIFT   (8U)
#define MIPI_CSI2RX_CFG_REG0_CFG_D0_PNCH(x)      (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_D0_PNCH_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_D0_PNCH_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_RX_HSEL_MASK    (0x200U)
#define MIPI_CSI2RX_CFG_REG0_CFG_RX_HSEL_SHIFT   (9U)
#define MIPI_CSI2RX_CFG_REG0_CFG_RX_HSEL(x)      (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_RX_HSEL_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_RX_HSEL_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_PD_PHY_MASK     (0x400U)
#define MIPI_CSI2RX_CFG_REG0_CFG_PD_PHY_SHIFT    (10U)
#define MIPI_CSI2RX_CFG_REG0_CFG_PD_PHY(x)       (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_PD_PHY_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_PD_PHY_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_DPHY_CLK_FHS_MODE_MASK (0x800U)
#define MIPI_CSI2RX_CFG_REG0_CFG_DPHY_CLK_FHS_MODE_SHIFT (11U)
#define MIPI_CSI2RX_CFG_REG0_CFG_DPHY_CLK_FHS_MODE(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_DPHY_CLK_FHS_MODE_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_DPHY_CLK_FHS_MODE_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_LANE0_SEL_MASK  (0x2000U)
#define MIPI_CSI2RX_CFG_REG0_CFG_LANE0_SEL_SHIFT (13U)
#define MIPI_CSI2RX_CFG_REG0_CFG_LANE0_SEL(x)    (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_LANE0_SEL_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_LANE0_SEL_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_LANE1_SEL_MASK  (0x4000U)
#define MIPI_CSI2RX_CFG_REG0_CFG_LANE1_SEL_SHIFT (14U)
#define MIPI_CSI2RX_CFG_REG0_CFG_LANE1_SEL(x)    (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_LANE1_SEL_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_LANE1_SEL_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_U_PRG_RXHS_SETTLE_MASK (0x1F8000U)
#define MIPI_CSI2RX_CFG_REG0_CFG_U_PRG_RXHS_SETTLE_SHIFT (15U)
#define MIPI_CSI2RX_CFG_REG0_CFG_U_PRG_RXHS_SETTLE(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_U_PRG_RXHS_SETTLE_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_U_PRG_RXHS_SETTLE_MASK)

#define MIPI_CSI2RX_CFG_REG0_CFG_UC_PRG_RXHS_SETTLE_MASK (0xFE00000U)
#define MIPI_CSI2RX_CFG_REG0_CFG_UC_PRG_RXHS_SETTLE_SHIFT (21U)
#define MIPI_CSI2RX_CFG_REG0_CFG_UC_PRG_RXHS_SETTLE(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG0_CFG_UC_PRG_RXHS_SETTLE_SHIFT)) & MIPI_CSI2RX_CFG_REG0_CFG_UC_PRG_RXHS_SETTLE_MASK)
/*! @} */

/*! @name CFG_REG1 - Configuration 1 */
/*! @{ */

#define MIPI_CSI2RX_CFG_REG1_CFG_PHY_INIT_DONE_MASK (0x2000000U)
#define MIPI_CSI2RX_CFG_REG1_CFG_PHY_INIT_DONE_SHIFT (25U)
#define MIPI_CSI2RX_CFG_REG1_CFG_PHY_INIT_DONE(x) (((uint32_t)(((uint32_t)(x)) << MIPI_CSI2RX_CFG_REG1_CFG_PHY_INIT_DONE_SHIFT)) & MIPI_CSI2RX_CFG_REG1_CFG_PHY_INIT_DONE_MASK)
/*! @} */


/*!
 * @}
 */ /* end of group MIPI_CSI2RX_Register_Masks */


/*!
 * @}
 */ /* end of group MIPI_CSI2RX_Peripheral_Access_Layer */


/*
** End of section using anonymous unions
*/

#if defined(__ARMCC_VERSION)
  #if (__ARMCC_VERSION >= 6010050)
    #pragma clang diagnostic pop
  #else
    #pragma pop
  #endif
#elif defined(__GNUC__)
  /* leave anonymous unions enabled */
#elif defined(__IAR_SYSTEMS_ICC__)
  #pragma language=default
#else
  #error Not supported compiler type
#endif

/*!
 * @}
 */ /* end of group Peripheral_access_layer */


#endif  /* PERI_MIPI_CSI2RX_H_ */

