/*
 * NOTE: File generated by gen_soc_headers.py
 * from MIMXRT533SFFOC/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MIMXRT595SFFOC-pinctrl.h with this part's differences applied
 * below (50 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 562b080ddd1196b6
 */

#ifndef _ZEPHYR_DTS_BINDING_MIMXRT533SFFOC_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MIMXRT533SFFOC_WRAPPER_

#include "MIMXRT595SFFOC-pinctrl.h"

/* Signals not present on this part */
#undef DBI_CSX_PIO4_20
#undef DBI_DSX_PIO4_21
#undef DBI_E_PIO4_25
#undef DBI_RWDX_PIO4_23
#undef DBI_WRX_PIO4_24
#undef LCDIF_dbi_data0_PIO4_27
#undef LCDIF_dbi_data13_PIO5_8
#undef LCDIF_dbi_data1_PIO4_28
#undef LCDIF_dbi_data2_PIO4_29
#undef LCDIF_dbi_data3_PIO4_30
#undef LCDIF_dbi_data4_PIO4_31
#undef LCDIF_dbi_data5_PIO5_0
#undef LCDIF_dbi_data6_PIO5_1
#undef LCDIF_dbi_data7_PIO5_2
#undef LCDIF_dbi_data8_PIO5_3
#undef LCDIF_dbi_data9_PIO5_4
#undef LCDIF_lcdif_data0_PIO4_27
#undef LCDIF_lcdif_data10_PIO3_9
#undef LCDIF_lcdif_data11_PIO3_10
#undef LCDIF_lcdif_data12_PIO3_11
#undef LCDIF_lcdif_data13_PIO3_12
#undef LCDIF_lcdif_data13_PIO5_8
#undef LCDIF_lcdif_data14_PIO3_13
#undef LCDIF_lcdif_data15_PIO3_14
#undef LCDIF_lcdif_data16_PIO3_15
#undef LCDIF_lcdif_data17_PIO3_16
#undef LCDIF_lcdif_data18_PIO3_17
#undef LCDIF_lcdif_data19_PIO3_18
#undef LCDIF_lcdif_data1_PIO4_28
#undef LCDIF_lcdif_data20_PIO3_19
#undef LCDIF_lcdif_data20_PIO5_15
#undef LCDIF_lcdif_data21_PIO3_20
#undef LCDIF_lcdif_data21_PIO5_16
#undef LCDIF_lcdif_data22_PIO3_21
#undef LCDIF_lcdif_data22_PIO5_17
#undef LCDIF_lcdif_data23_PIO3_3
#undef LCDIF_lcdif_data23_PIO5_18
#undef LCDIF_lcdif_data2_PIO4_29
#undef LCDIF_lcdif_data3_PIO4_30
#undef LCDIF_lcdif_data4_PIO4_31
#undef LCDIF_lcdif_data5_PIO5_0
#undef LCDIF_lcdif_data6_PIO5_1
#undef LCDIF_lcdif_data7_PIO5_2
#undef LCDIF_lcdif_data8_PIO5_3
#undef LCDIF_lcdif_data9_PIO3_8
#undef LCDIF_lcdif_data9_PIO5_4
#undef LCD_DTCLK_PIO4_24
#undef LCD_ENABLE_PIO4_23
#undef LCD_HSYNC_PIO4_25
#undef LCD_VSYNC_PIO4_26

#endif /* _ZEPHYR_DTS_BINDING_MIMXRT533SFFOC_WRAPPER_ */
