/*
 *  Copyright 2023-2024 NXP
 *
 *  SPDX-License-Identifier: BSD-3-Clause
 *
 */

#ifndef __NXP_WIFI_H__
#define __NXP_WIFI_H__

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#define LWIPERF_REVERSE_MODE      1
#define CONFIG_11N                1
#define STA_SUPPORT               1
#define UAP_SUPPORT               1
#define WPA                       1
#define KEY_MATERIAL_WEP          1
#define KEY_PARAM_SET_V2          1
#define ENABLE_802_11W            1
#define ENABLE_GCMP_SUPPORT       1
#define CONFIG_STA_AMPDU_RX       1
#define CONFIG_STA_AMPDU_TX       1
#define CONFIG_ENABLE_AMSDU_RX    1
#define CONFIG_UAP_AMPDU_TX       1
#define CONFIG_UAP_AMPDU_RX       1
#define CONFIG_WIFIDRIVER_PS_LOCK 1
#define CONFIG_WNM_PS             0
#define CONFIG_SCAN_CHANNEL_GAP   1
#define CONFIG_COMBO_SCAN         1
#define CONFIG_BG_SCAN            1
#define CONFIG_HOST_MLME          1
#define UAP_HOST_MLME             1
#define CONFIG_STA_AUTO_DHCPV4    1

#if CONFIG_NXP_WIFI_SHELL
#define CONFIG_WIFI_SHELL 1
#endif

#if CONFIG_NXP_WIFI_MAX_AP_ENTRIES
#define CONFIG_MAX_AP_ENTRIES CONFIG_NXP_WIFI_MAX_AP_ENTRIES
#endif

#if CONFIG_NXP_WIFI_WLAN_KNOWN_NETWORKS
#define CONFIG_WLAN_KNOWN_NETWORKS CONFIG_NXP_WIFI_WLAN_KNOWN_NETWORKS
#endif

#if CONFIG_NXP_WIFI_SDIO_MULTI_PORT_RX_AGGR
#define CONFIG_SDIO_MULTI_PORT_RX_AGGR CONFIG_NXP_WIFI_SDIO_MULTI_PORT_RX_AGGR
#endif

#if CONFIG_NXP_WIFI_SDIO_MULTI_PORT_TX_AGGR
#define CONFIG_SDIO_MULTI_PORT_TX_AGGR CONFIG_NXP_WIFI_SDIO_MULTI_PORT_TX_AGGR
#endif

#if CONFIG_NXP_WIFI_AUTO_POWER_SAVE
#define CONFIG_WIFI_AUTO_POWER_SAVE 1
#endif

#if CONFIG_NXP_WIFI_TX_RX_ZERO_COPY
#define CONFIG_TX_RX_ZERO_COPY 1
#endif

#if CONFIG_NXP_WIFI_RF_TEST_MODE
#define CONFIG_WIFI_RF_TEST_MODE 1
#endif

#if CONFIG_NXP_WIFI_SOFTAP_SUPPORT
#define CONFIG_WIFI_SOFTAP_SUPPORT 1
#endif

#if CONFIG_NXP_WIFI_OFFLOAD
#define CONFIG_OFFLOAD CONFIG_NXP_WIFI_OFFLOAD
#endif

#if CONFIG_NXP_WIFI_STA_RECONNECT
#define CONFIG_WIFI_STA_RECONNECT 1
#endif

#if CONFIG_NXP_WIFI_11AX
#define CONFIG_11AX 1
#endif

#if CONFIG_NXP_WIFI_11AC
#define CONFIG_11AC 1
#endif

#if CONFIG_NXP_WIFI_ENABLE_HTTPSERVER
#define CONFIG_ENABLE_HTTPSERVER CONFIG_NXP_WIFI_ENABLE_HTTPSERVER
#endif

#if CONFIG_NXP_WIFI_TX_RX_ZERO_COPY
#define CONFIG_TX_RX_ZERO_COPY 1
#endif

#if CONFIG_NXP_WIFI_CAPA
#define CONFIG_WIFI_CAPA 1
#endif

#if CONFIG_NXP_WIFI_WMM_UAPSD
#define CONFIG_WMM_UAPSD 1
#endif

#if CONFIG_NXP_WIFI_GET_LOG
#define CONFIG_WIFI_GET_LOG 1
#endif

#if CONFIG_NXP_WIFI_TX_PER_TRACK
#define CONFIG_WIFI_TX_PER_TRACK 1
#endif

#if CONFIG_NXP_WIFI_CSI
#define CONFIG_CSI 1
#endif

#if CONFIG_NXP_WIFI_RESET
#define CONFIG_WIFI_RESET 1
#endif

#if CONFIG_NXP_WIFI_IND_DNLD
#define CONFIG_WIFI_IND_DNLD 1
#endif

#if CONFIG_NXP_WIFI_IND_RESET
#define CONFIG_WIFI_IND_RESET 1
#endif

#if CONFIG_NXP_WIFI_NET_MONITOR
#define CONFIG_NET_MONITOR 1
#endif

#if CONFIG_NXP_WIFI_HOST_TXRX_MGMT_FRAME
#define HOST_TXRX_MGMT_FRAME 1
#endif

#if CONFIG_NXP_WIFI_ECSA
#define CONFIG_ECSA 1
#endif

#if CONFIG_NXP_WIFI_UNII4_BAND_SUPPORT
#define CONFIG_UNII4_BAND_SUPPORT 1
#endif

#if CONFIG_NXP_WIFI_RECOVERY
#define CONFIG_WIFI_RECOVERY 1
#endif

#if CONFIG_NXP_WIFI_PKT_FWD
#define CONFIG_WIFI_PKT_FWD 1
#endif

#if CONFIG_NXP_WIFI_TSP
#define CONFIG_TSP 1
#endif

#if CONFIG_NXP_WIFI_11AX_TWT
#define CONFIG_11AX_TWT 1
#endif

#if CONFIG_NXP_WIFI_COMPRESS_TX_PWTBL
#define CONFIG_COMPRESS_TX_PWTBL 1
#endif

#if CONFIG_NXP_WIFI_COMPRESS_RU_TX_PWTBL
#define CONFIG_COMPRESS_RU_TX_PWTBL 1
#endif

#if CONFIG_NXP_WIFI_MAX_PRIO
#define CONFIG_WIFI_MAX_PRIO CONFIG_NXP_WIFI_MAX_PRIO
#endif

#if CONFIG_NXP_WIFI_IPS
#define CONFIG_IPS 1
#endif

#if CONFIG_NXP_WIFI_EXT_SCAN_SUPPORT
#define CONFIG_EXT_SCAN_SUPPORT 1
#endif

#if CONFIG_NXP_WIFI_SCAN_WITH_RSSIFILTER
#define CONFIG_SCAN_WITH_RSSIFILTER 1
#endif

#if CONFIG_NXP_WIFI_DTIM_PERIOD
#define CONFIG_WIFI_DTIM_PERIOD 1
#endif

#if CONFIG_NXP_WIFI_RX_ABORT_CFG
#define CONFIG_RX_ABORT_CFG 1
#endif

#if CONFIG_NXP_WIFI_RX_ABORT_CFG_EXT
#define CONFIG_RX_ABORT_CFG_EXT 1
#endif

#if CONFIG_NXP_WIFI_CCK_DESENSE_CFG
#define CONFIG_CCK_DESENSE_CFG 1
#endif

#if CONFIG_NXP_WIFI_MEM_ACCESS
#define CONFIG_WIFI_MEM_ACCESS 1
#endif

#if CONFIG_NXP_WIFI_REG_ACCESS
#define CONFIG_WIFI_REG_ACCESS 1
#endif

#if CONFIG_NXP_WIFI_SUBSCRIBE_EVENT_SUPPORT
#define CONFIG_SUBSCRIBE_EVENT_SUPPORT 1
#endif

#if CONFIG_NXP_WIFI_TX_RX_HISTOGRAM
#define CONFIG_TX_RX_HISTOGRAM 1
#endif

#if CONFIG_NXP_WIFI_COEX_DUTY_CYCLE
#define CONFIG_COEX_DUTY_CYCLE 1
#endif

#if CONFIG_NXP_WIFI_MMSF
#define CONFIG_MMSF 1
#endif

#if CONFIG_NXP_WIFI_USB_FILE_ACCESS
#define CONFIG_USB_FILE_ACCESS 1
#endif

#if CONFIG_NXP_WIFI_SCAN_CHANNEL_GAP_TIME
#define CONFIG_SCAN_CHANNEL_GAP_TIME CONFIG_NXP_WIFI_SCAN_CHANNEL_GAP_TIME
#endif

#if CONFIG_NXP_WIFI_INACTIVITY_TIMEOUT_EXT
#define CONFIG_INACTIVITY_TIMEOUT_EXT 1
#endif

#if CONFIG_NXP_WIFI_RF_TEST_MODE
#define CONFIG_RF_TEST_MODE 1
#endif

#if CONFIG_NXP_WIFI_IMD3_CFG
#define CONFIG_IMD3_CFG 1
#endif

#if CONFIG_NXP_WIFI_ANT_DETECT
#define CONFIG_ANT_DETECT 1
#endif

#if CONFIG_NXP_WIFI_WLAN_CALDATA_1ANT
#define CONFIG_WLAN_CALDATA_1ANT 1
#endif

#if CONFIG_NXP_WIFI_WLAN_CALDATA_1ANT_WITH_DIVERSITY
#define CONFIG_WLAN_CALDATA_1ANT_WITH_DIVERSITY 1
#endif

#if CONFIG_NXP_WIFI_WLAN_CALDATA_3ANT_DIVERSITY
#define CONFIG_WLAN_CALDATA_3ANT_DIVERSITY 1
#endif

#if CONFIG_NXP_OVERRIDE_CALIBRATION_DATA
#if defined(CONFIG_WLAN_CALDATA_2ANT_HI_ISO)
#define OVERRIDE_CALIBRATION_DATA "wifi_cal_data_iw612_2ant_hi_iso.h"
#elif defined(CONFIG_WLAN_CALDATA_2ANT_LO_ISO)
#define OVERRIDE_CALIBRATION_DATA "wifi_cal_data_iw612_2ant_lo_iso.h"
#else
#define OVERRIDE_CALIBRATION_DATA "wifi_cal_data_override.h"
#endif
#endif

#if !CONFIG_NXP_OVERRIDE_CALIBRATION_DATA
#if defined(RW610)
/*
 * FRDMRW610
 */
#if defined(FRDMRW610)
/* FRDMRW610 1ANT */
#define DEFAULT_CALDATA_RW610 "wifi_cal_data_frdmrw61x_1ant.h"
#else
/*
 * RW610
 */
/* RW610 1ANT */
#if CONFIG_WLAN_CALDATA_1ANT
#define DEFAULT_CALDATA_RW610 "wifi_cal_data_rw61x_1ant.h"
/* RW610 3ANT_DIVERSITY */
#elif CONFIG_WLAN_CALDATA_3ANT_DIVERSITY
#define DEFAULT_CALDATA_RW610 "wifi_cal_data_rw61x_3ant_diversity.h"
/* RW610 1ANT_DIVERSITY */
#elif CONFIG_WLAN_CALDATA_1ANT_WITH_DIVERSITY
#define DEFAULT_CALDATA_RW610 "wifi_cal_data_rw61x_1ant_diversity.h"
/* RW610 2ANT */
#else
#define DEFAULT_CALDATA_RW610 "wifi_cal_data_rw61x_2ant.h"
#endif
#endif
#endif /* RW610 */
#endif /* CONFIG_NXP_OVERRIDE_CALIBRATION_DATA */

#if CONFIG_NXP_WIFI_EU_VALIDATION
#define CONFIG_EU_VALIDATION 1
#endif

#if CONFIG_NXP_WIFI_WMM
#define CONFIG_WMM 1
#endif

#if CONFIG_NXP_WIFI_IPV6
#define CONFIG_IPV6 1
#endif

#if CONFIG_NET_IF_UNICAST_IPV6_ADDR_COUNT
#define CONFIG_MAX_IPV6_ADDRESSES CONFIG_NET_IF_UNICAST_IPV6_ADDR_COUNT
#endif

#if CONFIG_NXP_WIFI_5GHz_SUPPORT
#define CONFIG_5GHz_SUPPORT 1
#endif

#if CONFIG_NXP_WIFI_HOST_SLEEP
#define CONFIG_HOST_SLEEP 1
#endif

#if CONFIG_PM
#define CONFIG_POWER_MANAGER 1
#endif

#if CONFIG_NXP_WIFI_ROAMING
#define CONFIG_ROAMING 1
#endif

#if CONFIG_NXP_WIFI_CLOUD_KEEP_ALIVE
#define CONFIG_CLOUD_KEEP_ALIVE 1
#endif

#if CONFIG_NXP_WIFI_MEF_CFG
#define CONFIG_MEF_CFG 1
#endif

#if CONFIG_NXP_WIFI_TURBO_MODE
#define CONFIG_TURBO_MODE 1
#endif

#if CONFIG_NXP_WIFI_EU_CRYPTO
#define CONFIG_EU_CRYPTO 1
#endif

#if CONFIG_NXP_WIFI_FIPS
#define CONFIG_FIPS 1
#endif

#if CONFIG_NXP_WIFI_OWE
#define CONFIG_DRIVER_OWE 1
#endif

#if (CONFIG_NXP_WIFI_OWE && CONFIG_WIFI_NM_WPA_SUPPLICANT)
#define CONFIG_OWE
#endif

#if (!CONFIG_NXP_WIFI_OWE && CONFIG_WIFI_NM_WPA_SUPPLICANT)
#undef CONFIG_OWE
#endif

#if CONFIG_NXP_WIFI_11K
#define CONFIG_11K 1
#endif

#if CONFIG_NXP_WIFI_11V
#define CONFIG_11V 1
#endif

#if CONFIG_NXP_WIFI_11R
#define CONFIG_11R 1
#endif

#if CONFIG_NXP_WIFI_EU_CRYPTO
#define CONFIG_WIFI_EU_CRYPTO 1
#endif

#if CONFIG_NXP_WIFI_CLOCKSYNC
#define CONFIG_WIFI_CLOCKSYNC 1
#endif

#if CONFIG_NXP_WIFI_RTS_THRESHOLD
#define CONFIG_WIFI_RTS_THRESHOLD 1
#endif

#if CONFIG_NXP_WIFI_UAP_WORKAROUND_STICKY_TIM
#define CONFIG_UAP_WORKAROUND_STICKY_TIM CONFIG_NXP_WIFI_UAP_WORKAROUND_STICKY_TIM
#endif

#if CONFIG_NXP_WIFI_AUTO_NULL_TX
#define CONFIG_AUTO_NULL_TX 1
#endif

#if CONFIG_NXP_WIFI_ENABLE_ERROR_LOGS
#define CONFIG_ENABLE_ERROR_LOGS 1
#endif

#if CONFIG_NXP_WIFI_ENABLE_WARNING_LOGS
#define CONFIG_ENABLE_WARNING_LOGS 1
#endif

#if CONFIG_NXP_WIFI_DEBUG_BUILD
#define CONFIG_DEBUG_BUILD 1
#endif

#if CONFIG_NXP_WIFI_OS_DEBUG
#define CONFIG_OS_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_NET_DEBUG
#define CONFIG_NET_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_WLCMGR_DEBUG
#define CONFIG_WLCMGR_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_EXTRA_DEBUG
#define CONFIG_WIFI_EXTRA_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_UAP_DEBUG
#define CONFIG_WIFI_UAP_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_EVENTS_DEBUG
#define CONFIG_WIFI_EVENTS_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_CMD_RESP_DEBUG
#define CONFIG_WIFI_CMD_RESP_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_PS_DEBUG
#define CONFIG_WIFI_PS_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_SCAN_DEBUG
#define CONFIG_WIFI_SCAN_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_PKT_DEBUG
#define CONFIG_WIFI_PKT_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_IO_INFO_DUMP
#define CONFIG_WIFI_IO_INFO_DUMP 1
#endif

#if CONFIG_NXP_WIFI_IO_DEBUG
#define CONFIG_WIFI_IO_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_IO_DUMP
#define CONFIG_WIFI_IO_DUMP 1
#endif

#if CONFIG_NXP_WIFI_MEM_DEBUG
#define CONFIG_WIFI_MEM_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_AMPDU_DEBUG
#define CONFIG_WIFI_AMPDU_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_TIMER_DEBUG
#define CONFIG_WIFI_TIMER_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_SDIO_DEBUG
#define CONFIG_WIFI_SDIO_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_SDIO_IO_DEBUG
#define CONFIG_SDIO_IO_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_FWDNLD_IO_DEBUG
#define CONFIG_FWDNLD_IO_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_FW_DEBUG
#define CONFIG_WIFI_FW_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_FW_VDLL_DEBUG
#define CONFIG_FW_VDLL_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_DHCP_SERVER_DEBUG
#define CONFIG_DHCP_SERVER_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_HTC_DEBUG
#define CONFIG_WIFI_HTC_DEBUG 1
#endif

#if CONFIG_NXP_WIFI_SMOKE_TESTS
#define CONFIG_WIFI_SMOKE_TESTS 1
#endif

#if CONFIG_NXP_WIFI_SM_IP_DHCP
#define IP_USE_DHCP 1
#endif

#if CONFIG_NXP_WIFI_SIGMA_AGENT
#define CONFIG_SIGMA_AGENT 1
#endif

#if CONFIG_WIFI_NM_WPA_SUPPLICANT
#define CONFIG_WPA_SUPP 1
#endif

#if CONFIG_NXP_WIFI_SET_SU
#define CONFIG_SET_SU 1
#endif

#if CONFIG_NXP_WIFI_MULTI_BSSID_SUPPORT
#define CONFIG_MULTI_BSSID_SUPPORT 1
#endif

#if CONFIG_NXP_WIFI_FRAG_THRESHOLD
#define CONFIG_WIFI_FRAG_THRESHOLD 1
#endif

#if CONFIG_NXP_WIFI_FORCE_RTS
#define CONFIG_WIFI_FORCE_RTS 1
#endif

#if CONFIG_NXP_WIFI_CHANNEL_LOAD
#define CONFIG_WIFI_CHANNEL_LOAD 1
#endif

#if CONFIG_NXP_WIFI_TX_AMPDU_PROT_MODE
#define CONFIG_TX_AMPDU_PROT_MODE 1
#endif

#if CONFIG_NXP_WIFI_EXTERNAL_COEX_PTA
#define CONFIG_EXTERNAL_COEX_PTA 1
#endif

#if CONFIG_NXP_WIFI_FW_VDLLV2
#define CONFIG_FW_VDLLV2 1
#endif

#if CONFIG_WIFI_NM_HOSTAPD_AP
#define CONFIG_WPA_SUPP_AP 1
#endif
#if (CONFIG_NXP_WIFI_8978) || (CONFIG_NXP_WIFI_8987) || (CONFIG_NXP_WIFI_9177)

#define CONFIG_GTK_REKEY_OFFLOAD 1

#define CONFIG_FW_VDLL 1

#endif

#if (CONFIG_NXP_WIFI_9177)
#define CONFIG_TCP_ACK_ENH 1
#endif

#if CONFIG_11AX

#if !CONFIG_WPA_SUPP
#define CONFIG_DRIVER_MBO 1
#endif

#endif

#ifndef CONFIG_NXP_WIFI_SOFTAP_SUPPORT
#if UAP_SUPPORT
#undef UAP_SUPPORT
#define UAP_SUPPORT 0
#endif

#if UAP_HOST_MLME
#undef UAP_HOST_MLME
#define UAP_HOST_MLME 0
#endif

#if CONFIG_UAP_AMPDU_TX
#undef CONFIG_UAP_AMPDU_TX
#define CONFIG_UAP_AMPDU_TX 0
#endif

#if CONFIG_UAP_AMPDU_RX
#undef CONFIG_UAP_AMPDU_RX
#define CONFIG_UAP_AMPDU_RX 0
#endif
#endif

#ifdef __cplusplus
}
#endif

#endif /* __NXP_WIFI_H__ */
