/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK02FN128VLF10/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK02FN128VLH10-pinctrl.h with this part's differences applied
 * below (30 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: d0d3f070251977c9
 */

#ifndef _ZEPHYR_DTS_BINDING_MK02FN128VLF10_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK02FN128VLF10_WRAPPER_

#include "MK02FN128VLH10-pinctrl.h"

/* Signals not present on this part */
#undef CLKOUT32K_PTE0
#undef CMP0_IN2_PTC8
#undef CMP0_IN3_PTC9
#undef FTM0_CH2_PTA5
#undef FTM1_CH0_PTA12
#undef FTM1_CH1_PTA13
#undef FTM1_QD_PHA_PTA12
#undef FTM1_QD_PHB_PTA13
#undef FTM2_CH0_PTB18
#undef FTM2_CH1_PTB19
#undef FTM2_FLT0_PTC9
#undef FTM2_QD_PHA_PTB18
#undef FTM2_QD_PHB_PTB19
#undef JTAG_TRST_b_PTA5
#undef LLWU_P0_PTE1
#undef LLWU_P11_PTC11
#undef LLWU_P4_PTA13
#undef PTA12
#undef PTA13
#undef PTA5
#undef PTB18
#undef PTB19
#undef PTC10
#undef PTC11
#undef PTC8
#undef PTC9
#undef PTE0
#undef PTE1
#undef UART1_RX_PTE1
#undef UART1_TX_PTE0

#endif /* _ZEPHYR_DTS_BINDING_MK02FN128VLF10_WRAPPER_ */
