/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _FSL_INPUTMUX_CONNECTIONS_
#define _FSL_INPUTMUX_CONNECTIONS_

/*******************************************************************************
 * Definitions
 ******************************************************************************/
/* Component ID definition, used by tools. */
#ifndef FSL_COMPONENT_ID
#define FSL_COMPONENT_ID "platform.drivers.inputmux_connections"
#endif

/*! @name Driver version */
/*@{*/
/*! @brief INPUTMUX_CONNECTION driver version 2.0.0. */
#define FSL_INPUTMUX_CONNECTION_DRIVER_VERSION (MAKE_VERSION(2, 0, 0))
/*@}*/

#define INPUTMUX_GpioPortPinToPintsel(port, pin) ((pin) + (PINTSEL_PMUX_ID << PMUX_SHIFT))

/*!
 * @addtogroup inputmux_driver
 * @{
 */

/*!
 * @name Input multiplexing connections
 * @{
 */

/*! @brief Periphinmux IDs */
#define CTIMER0CAP_REG           (0x020U)
#define CTIMER0TRIG_REG          (0x030U)
#define CTIMER1CAP_REG           (0x040U)
#define CTIMER1TRIG_REG          (0x050U)
#define FREQMEAS_REF_REG         (0x180U)
#define FREQMEAS_TAR_REG         (0x184U)
#define CMP0_TRIG_REG            (0x260U)
#define ADC0_TRIG_REG            (0x280U)
#define FlexPWM0_SM0_EXTA0_REG   (0x3A0U)
#define FlexPWM0_SM0_EXTSYNC_REG (0x3A4U)
#define FlexPWM0_SM1_EXTA_REG    (0x3A8U)
#define FlexPWM0_SM1_EXTSYNC_REG (0x3ACU)
#define FlexPWM0_SM2_EXTA_REG    (0x3B0U)
#define FlexPWM0_SM2_EXTSYNC_REG (0x3B4U)
#define FlexPWM0_FAULT_REG       (0x3C0U)
#define FlexPWM0_FORCE_REG       (0x3D0U)
#define PWM0_EXT_CLK_REG         (0x420U)
#define EXT_TRIG_REG             (0x4C0U)
#define LPI2C0_TRIG_REG          (0x5A0U)
#define LPSPI0_TRIG_REG          (0x5E0U)
#define LPUART0_REG              (0x620U)
#define LPUART1_REG              (0x640U)
#define LPUART2_REG              (0x660U)
#define LPUART3_REG              (0x680U)
#define PMUX_SHIFT               (20U)

typedef enum _inputmux_index_t
{
    kINPUTMUX_INDEX_CTIMER0CAPTSEL0    = 0U,
    kINPUTMUX_INDEX_CTIMER0CAPTSEL1    = 1U,
    kINPUTMUX_INDEX_CTIMER0CAPTSEL2    = 2U,
    kINPUTMUX_INDEX_CTIMER0CAPTSEL3    = 3U,
    kINPUTMUX_INDEX_CTIMER1CAPTSEL0    = 0U,
    kINPUTMUX_INDEX_CTIMER1CAPTSEL1    = 1U,
    kINPUTMUX_INDEX_CTIMER1CAPTSEL2    = 2U,
    kINPUTMUX_INDEX_CTIMER1CAPTSEL3    = 3U,
    kINPUTMUX_INDEX_ADC0_TRIGSEL0      = 0U,
    kINPUTMUX_INDEX_ADC0_TRIGSEL1      = 1U,
    kINPUTMUX_INDEX_ADC0_TRIGSEL2      = 2U,
    kINPUTMUX_INDEX_ADC0_TRIGSEL3      = 3U,
    kINPUTMUX_INDEX_FLEXPWM0_FAULTSEL0 = 0U,
    kINPUTMUX_INDEX_FLEXPWM0_FAULTSEL1 = 1U,
    kINPUTMUX_INDEX_FLEXPWM0_FAULTSEL2 = 2U,
    kINPUTMUX_INDEX_FLEXPWM0_FAULTSEL3 = 3U,
    kINPUTMUX_INDEX_FLEXPWM1_FAULTSEL0 = 0U,
    kINPUTMUX_INDEX_FLEXPWM1_FAULTSEL1 = 1U,
    kINPUTMUX_INDEX_FLEXPWM1_FAULTSEL2 = 2U,
    kINPUTMUX_INDEX_FLEXPWM1_FAULTSEL3 = 3U,
    kINPUTMUX_INDEX_EXT_TRIGSEL0       = 0U,
    kINPUTMUX_INDEX_EXT_TRIGSEL1       = 1U,
    kINPUTMUX_INDEX_EXT_TRIGSEL2       = 2U,
    kINPUTMUX_INDEX_EXT_TRIGSEL3       = 3U,
    kINPUTMUX_INDEX_EXT_TRIGSEL4       = 4U,
    kINPUTMUX_INDEX_EXT_TRIGSEL6       = 6U,
    kINPUTMUX_INDEX_EXT_TRIGSEL7       = 7U,
} inputmux_index_t;

/*! @brief INPUTMUX connections type */
typedef enum _inputmux_connection_t
{
    /* Connections for CTIMER0CAP */
    kINPUTMUX_Ctinp0ToCtimer0Cap                     = 1U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp1ToCtimer0Cap                     = 2U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp2ToCtimer0Cap                     = 3U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp3ToCtimer0Cap                     = 4U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp4ToCtimer0Cap                     = 5U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp5ToCtimer0Cap                     = 6U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp6ToCtimer0Cap                     = 7U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp8ToCtimer0Cap                     = 9U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp9ToCtimer0Cap                     = 10U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp12ToCtimer0Cap                    = 13U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp13ToCtimer0Cap                    = 14U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp16ToCtimer0Cap                    = 17U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp17ToCtimer0Cap                    = 18U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp18ToCtimer0Cap                    = 19U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp19ToCtimer0Cap                    = 20U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp0ToCtimer0Cap                 = 26U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp1ToCtimer0Cap                 = 27U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp2ToCtimer0Cap                 = 28U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp3ToCtimer0Cap                 = 29U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToCtimer0Cap                    = 30U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat1ToCtimer0Cap                = 33U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToCtimer0Cap                = 34U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToCtimer0Cap                = 35U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig0ToCtimer0Cap            = 44U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig0ToCtimer0Cap            = 45U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig0ToCtimer0Cap            = 46U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpi2C0MasterendofpacketToCtimer0Cap    = 48U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpi2C0SlaveendofpacketToCtimer0Cap     = 49U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpspi0EndofframeToCtimer0Cap           = 52U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpspi0ReceiveddatawordToCtimer0Cap     = 53U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0ReceiveddatawordToCtimer0Cap    = 56U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0TransmitteddatawordToCtimer0Cap = 57U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0ReceivelineidleToCtimer0Cap     = 58U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1ReceiveddatawordToCtimer0Cap    = 59U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1TransmitteddatawordToCtimer0Cap = 60U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1ReceivelineidleToCtimer0Cap     = 61U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2ReceiveddatawordToCtimer0Cap    = 62U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2TransmitteddatawordToCtimer0Cap = 63U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2ReceivelineidleToCtimer0Cap     = 64U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToCtimer0Cap                    = 65U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToCtimer0Cap                    = 66U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToCtimer0Cap                    = 67U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToCtimer0Cap                    = 68U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToCtimer0Cap                    = 69U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToCtimer0Cap                    = 70U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToCtimer0Cap                    = 71U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToCtimer0Cap                    = 72U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToCtimer0Cap                    = 73U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToCtimer0Cap                    = 74U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToCtimer0Cap                   = 75U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToCtimer0Cap                   = 76U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3ReceiveddatawordToCtimer0Cap    = 77U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3TransmitteddatawordToCtimer0Cap = 78U + (CTIMER0CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3ReceivelineidleToCtimer0Cap     = 79U + (CTIMER0CAP_REG << PMUX_SHIFT),

    /* Connections for CTIMER1CAP */
    kINPUTMUX_Ctinp0ToCtimer1Cap                     = 1U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp1ToCtimer1Cap                     = 2U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp2ToCtimer1Cap                     = 3U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp3ToCtimer1Cap                     = 4U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp4ToCtimer1Cap                     = 5U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp5ToCtimer1Cap                     = 6U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp6ToCtimer1Cap                     = 7U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp8ToCtimer1Cap                     = 9U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp9ToCtimer1Cap                     = 10U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp12ToCtimer1Cap                    = 13U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp13ToCtimer1Cap                    = 14U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp16ToCtimer1Cap                    = 17U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp17ToCtimer1Cap                    = 18U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp18ToCtimer1Cap                    = 19U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp19ToCtimer1Cap                    = 20U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp0ToCtimer1Cap                 = 26U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp1ToCtimer1Cap                 = 27U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp2ToCtimer1Cap                 = 28U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp3ToCtimer1Cap                 = 29U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToCtimer1Cap                    = 30U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat1ToCtimer1Cap                = 33U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToCtimer1Cap                = 34U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToCtimer1Cap                = 35U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig0ToCtimer1Cap            = 44U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig0ToCtimer1Cap            = 45U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig0ToCtimer1Cap            = 46U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpi2C0MasterendofpacketToCtimer1Cap    = 48U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpi2C0SlaveendofpacketToCtimer1Cap     = 49U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpspi0EndofframeToCtimer1Cap           = 52U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpspi0ReceiveddatawordToCtimer1Cap     = 53U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0ReceiveddatawordToCtimer1Cap    = 56U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0TransmitteddatawordToCtimer1Cap = 57U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0ReceivelineidleToCtimer1Cap     = 58U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1ReceiveddatawordToCtimer1Cap    = 59U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1TransmitteddatawordToCtimer1Cap = 60U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1ReceivelineidleToCtimer1Cap     = 61U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2ReceiveddatawordToCtimer1Cap    = 62U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2TransmitteddatawordToCtimer1Cap = 63U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2ReceivelineidleToCtimer1Cap     = 64U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToCtimer1Cap                    = 65U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToCtimer1Cap                    = 66U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToCtimer1Cap                    = 67U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToCtimer1Cap                    = 68U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToCtimer1Cap                    = 69U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToCtimer1Cap                    = 70U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToCtimer1Cap                    = 71U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToCtimer1Cap                    = 72U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToCtimer1Cap                    = 73U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToCtimer1Cap                    = 74U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToCtimer1Cap                   = 75U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToCtimer1Cap                   = 76U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3ReceiveddatawordToCtimer1Cap    = 77U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3TransmitteddatawordToCtimer1Cap = 78U + (CTIMER1CAP_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3ReceivelineidleToCtimer1Cap     = 79U + (CTIMER1CAP_REG << PMUX_SHIFT),

    /* Connections for CTIMER0TRIG */
    kINPUTMUX_Ctinp0ToCtimer0Trig                     = 1U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp1ToCtimer0Trig                     = 2U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp2ToCtimer0Trig                     = 3U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp3ToCtimer0Trig                     = 4U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp4ToCtimer0Trig                     = 5U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp5ToCtimer0Trig                     = 6U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp6ToCtimer0Trig                     = 7U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp8ToCtimer0Trig                     = 9U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp9ToCtimer0Trig                     = 10U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp12ToCtimer0Trig                    = 13U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp13ToCtimer0Trig                    = 14U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp16ToCtimer0Trig                    = 17U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp17ToCtimer0Trig                    = 18U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp18ToCtimer0Trig                    = 19U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp19ToCtimer0Trig                    = 20U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp0ToCtimer0Trig                 = 26U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp1ToCtimer0Trig                 = 27U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp2ToCtimer0Trig                 = 28U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp3ToCtimer0Trig                 = 29U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToCtimer0Trig                    = 30U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat1ToCtimer0Trig                = 33U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToCtimer0Trig                = 34U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToCtimer0Trig                = 35U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig0ToCtimer0Trig            = 44U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig0ToCtimer0Trig            = 45U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig0ToCtimer0Trig            = 46U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpi2C0MasterendofpacketToCtimer0Trig    = 48U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpi2C0SlaveendofpacketToCtimer0Trig     = 49U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpspi0EndofframeToCtimer0Trig           = 52U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpspi0ReceiveddatawordToCtimer0Trig     = 53U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0ReceiveddatawordToCtimer0Trig    = 56U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0TransmitteddatawordToCtimer0Trig = 57U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0ReceivelineidleToCtimer0Trig     = 58U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1ReceiveddatawordToCtimer0Trig    = 59U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1TransmitteddatawordToCtimer0Trig = 60U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1ReceivelineidleToCtimer0Trig     = 61U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2ReceiveddatawordToCtimer0Trig    = 62U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2TransmitteddatawordToCtimer0Trig = 63U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2ReceivelineidleToCtimer0Trig     = 64U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToCtimer0Trig                    = 65U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToCtimer0Trig                    = 66U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToCtimer0Trig                    = 67U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToCtimer0Trig                    = 68U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToCtimer0Trig                    = 69U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToCtimer0Trig                    = 70U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToCtimer0Trig                    = 71U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToCtimer0Trig                    = 72U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToCtimer0Trig                    = 73U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToCtimer0Trig                    = 74U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToCtimer0Trig                   = 75U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToCtimer0Trig                   = 76U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3ReceiveddatawordToCtimer0Trig    = 77U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3TransmitteddatawordToCtimer0Trig = 78U + (CTIMER0TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3ReceivelineidleToCtimer0Trig     = 79U + (CTIMER0TRIG_REG << PMUX_SHIFT),

    /* Connections for CTIMER1TRIG */
    kINPUTMUX_Ctinp0ToCtimer1Trig                     = 1U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp1ToCtimer1Trig                     = 2U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp2ToCtimer1Trig                     = 3U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp3ToCtimer1Trig                     = 4U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp4ToCtimer1Trig                     = 5U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp5ToCtimer1Trig                     = 6U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp6ToCtimer1Trig                     = 7U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp8ToCtimer1Trig                     = 9U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp9ToCtimer1Trig                     = 10U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp12ToCtimer1Trig                    = 13U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp13ToCtimer1Trig                    = 14U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp16ToCtimer1Trig                    = 17U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp17ToCtimer1Trig                    = 18U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp18ToCtimer1Trig                    = 19U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctinp19ToCtimer1Trig                    = 20U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp0ToCtimer1Trig                 = 26U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp1ToCtimer1Trig                 = 27U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp2ToCtimer1Trig                 = 28U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Adc0Tcomp3ToCtimer1Trig                 = 29U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToCtimer1Trig                    = 30U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat1ToCtimer1Trig                = 33U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToCtimer1Trig                = 34U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToCtimer1Trig                = 35U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig0ToCtimer1Trig            = 44U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig0ToCtimer1Trig            = 45U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig0ToCtimer1Trig            = 46U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpi2C0MasterendofpacketToCtimer1Trig    = 48U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpi2C0SlaveendofpacketToCtimer1Trig     = 49U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpspi0EndofframeToCtimer1Trig           = 52U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpspi0ReceiveddatawordToCtimer1Trig     = 53U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0ReceiveddatawordToCtimer1Trig    = 56U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0TransmitteddatawordToCtimer1Trig = 57U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0ReceivelineidleToCtimer1Trig     = 58U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1ReceiveddatawordToCtimer1Trig    = 59U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1TransmitteddatawordToCtimer1Trig = 60U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1ReceivelineidleToCtimer1Trig     = 61U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2ReceiveddatawordToCtimer1Trig    = 62U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2TransmitteddatawordToCtimer1Trig = 63U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2ReceivelineidleToCtimer1Trig     = 64U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToCtimer1Trig                    = 65U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToCtimer1Trig                    = 66U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToCtimer1Trig                    = 67U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToCtimer1Trig                    = 68U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToCtimer1Trig                    = 69U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToCtimer1Trig                    = 70U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToCtimer1Trig                    = 71U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToCtimer1Trig                    = 72U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToCtimer1Trig                    = 73U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToCtimer1Trig                    = 74U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToCtimer1Trig                   = 75U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToCtimer1Trig                   = 76U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3ReceiveddatawordToCtimer1Trig    = 77U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3TransmitteddatawordToCtimer1Trig = 78U + (CTIMER1TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3ReceivelineidleToCtimer1Trig     = 79U + (CTIMER1TRIG_REG << PMUX_SHIFT),

    /* Connections for FREQMEAS_REF */
    kINPUTMUX_ClkinToFreqmeasref           = 1U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Froosc12MToFreqmeasref       = 2U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_FrohfdivToFreqmeasref        = 3U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Osc32K1ToFreqmeasref         = 4U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Clk16K1ToFreqmeasref         = 5U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SlowclkToFreqmeasref         = 6U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Freqmeclkin0ToFreqmeasref    = 7U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Freqmeclkin1ToFreqmeasref    = 8U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig0ToFreqmeasref = 11U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig1ToFreqmeasref = 12U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig0ToFreqmeasref = 13U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig1ToFreqmeasref = 14U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig0ToFreqmeasref = 15U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig1ToFreqmeasref = 16U + (FREQMEAS_REF_REG << PMUX_SHIFT),

    /* Connections for FREQMEAS_TAR */
    kINPUTMUX_ClkinToFreqmeastar           = 1U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Froosc12MToFreqmeastar       = 2U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_FrohfdivToFreqmeastar        = 3U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Osc32K1ToFreqmeastar         = 4U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Clk16K1ToFreqmeastar         = 5U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SlowclkToFreqmeastar         = 6U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Freqmeclkin0ToFreqmeastar    = 7U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Freqmeclkin1ToFreqmeastar    = 8U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig0ToFreqmeastar = 11U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig1ToFreqmeastar = 12U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig0ToFreqmeastar = 13U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig1ToFreqmeastar = 14U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig0ToFreqmeastar = 15U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig1ToFreqmeastar = 16U + (FREQMEAS_TAR_REG << PMUX_SHIFT),

    /* Connections for CMP0_TRIG */
    kINPUTMUX_Ctimer0Mat0ToCmp0Trig        = 8U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToCmp0Trig        = 9U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat0ToCmp0Trig        = 10U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToCmp0Trig        = 11U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lptmr0ToCmp0Trig             = 14U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig0ToCmp0Trig    = 17U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig1ToCmp0Trig    = 18U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig0ToCmp0Trig    = 19U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig1ToCmp0Trig    = 20U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig0ToCmp0Trig    = 21U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig1ToCmp0Trig    = 22U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToCmp0Trig = 25U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToCmp0Trig = 26U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToCmp0Trig = 27U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToCmp0Trig = 28U + (CMP0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_WuuToCmp0Trig                = 30U + (CMP0_TRIG_REG << PMUX_SHIFT),

    /* Connections for ADC0_TRIG */
    kINPUTMUX_ArmtxevToAdc0Trig            = 1U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToAdc0Trig            = 6U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat0ToAdc0Trig        = 9U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat1ToAdc0Trig        = 10U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat0ToAdc0Trig        = 11U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat1ToAdc0Trig        = 12U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lptmr0ToAdc0Trig             = 15U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig0ToAdc0Trig    = 18U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm0Muxtrig1ToAdc0Trig    = 19U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig0ToAdc0Trig    = 20U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm1Muxtrig1ToAdc0Trig    = 21U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig0ToAdc0Trig    = 22U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Pwm0Sm2Muxtrig1ToAdc0Trig    = 23U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToAdc0Trig = 26U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToAdc0Trig = 27U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToAdc0Trig = 28U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToAdc0Trig = 29U + (ADC0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_WuuToAdc0Trig                = 31U + (ADC0_TRIG_REG << PMUX_SHIFT),

    /* Connections for FlexPWM0_SM0_EXTA0 */
    kINPUTMUX_ArmtxevToFlexpwm0Sm0Exta0            = 1U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToFlexpwm0Sm0Exta0            = 6U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToFlexpwm0Sm0Exta0        = 9U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToFlexpwm0Sm0Exta0        = 10U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToFlexpwm0Sm0Exta0        = 11U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToFlexpwm0Sm0Exta0        = 12U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToFlexpwm0Sm0Exta0            = 20U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToFlexpwm0Sm0Exta0            = 21U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToFlexpwm0Sm0Exta0            = 22U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToFlexpwm0Sm0Exta0            = 23U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToFlexpwm0Sm0Exta0            = 24U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToFlexpwm0Sm0Exta0            = 25U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToFlexpwm0Sm0Exta0            = 26U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToFlexpwm0Sm0Exta0            = 27U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToFlexpwm0Sm0Exta0            = 28U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToFlexpwm0Sm0Exta0            = 29U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToFlexpwm0Sm0Exta0           = 30U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToFlexpwm0Sm0Exta0           = 31U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToFlexpwm0Sm0Exta0 = 32U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToFlexpwm0Sm0Exta0 = 33U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToFlexpwm0Sm0Exta0 = 34U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToFlexpwm0Sm0Exta0 = 35U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_EccerrorinterruptToFlexpwm0Sm0Exta0  = 37U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),
    kINPUTMUX_WwdtinterruptToFlexpwm0Sm0Exta0      = 38U + (FlexPWM0_SM0_EXTA0_REG << PMUX_SHIFT),

    /* Connections for FlexPWM0_SM1_EXTA */
    kINPUTMUX_ArmtxevToFlexpwm0Sm1Exta            = 1U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToFlexpwm0Sm1Exta            = 6U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToFlexpwm0Sm1Exta        = 9U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToFlexpwm0Sm1Exta        = 10U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToFlexpwm0Sm1Exta        = 11U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToFlexpwm0Sm1Exta        = 12U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToFlexpwm0Sm1Exta            = 20U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToFlexpwm0Sm1Exta            = 21U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToFlexpwm0Sm1Exta            = 22U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToFlexpwm0Sm1Exta            = 23U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToFlexpwm0Sm1Exta            = 24U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToFlexpwm0Sm1Exta            = 25U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToFlexpwm0Sm1Exta            = 26U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToFlexpwm0Sm1Exta            = 27U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToFlexpwm0Sm1Exta            = 28U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToFlexpwm0Sm1Exta            = 29U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToFlexpwm0Sm1Exta           = 30U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToFlexpwm0Sm1Exta           = 31U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToFlexpwm0Sm1Exta = 32U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToFlexpwm0Sm1Exta = 33U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToFlexpwm0Sm1Exta = 34U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToFlexpwm0Sm1Exta = 35U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_EccerrorinterruptToFlexpwm0Sm1Exta  = 37U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_WwdtinterruptToFlexpwm0Sm1Exta      = 38U + (FlexPWM0_SM1_EXTA_REG << PMUX_SHIFT),

    /* Connections for FlexPWM0_SM2_EXTA */
    kINPUTMUX_ArmtxevToFlexpwm0Sm2Exta            = 1U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToFlexpwm0Sm2Exta            = 6U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToFlexpwm0Sm2Exta        = 9U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToFlexpwm0Sm2Exta        = 10U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToFlexpwm0Sm2Exta        = 11U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToFlexpwm0Sm2Exta        = 12U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToFlexpwm0Sm2Exta            = 20U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToFlexpwm0Sm2Exta            = 21U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToFlexpwm0Sm2Exta            = 22U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToFlexpwm0Sm2Exta            = 23U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToFlexpwm0Sm2Exta            = 24U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToFlexpwm0Sm2Exta            = 25U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToFlexpwm0Sm2Exta            = 26U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToFlexpwm0Sm2Exta            = 27U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToFlexpwm0Sm2Exta            = 28U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToFlexpwm0Sm2Exta            = 29U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToFlexpwm0Sm2Exta           = 30U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToFlexpwm0Sm2Exta           = 31U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToFlexpwm0Sm2Exta = 32U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToFlexpwm0Sm2Exta = 33U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToFlexpwm0Sm2Exta = 34U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToFlexpwm0Sm2Exta = 35U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_EccerrorinterruptToFlexpwm0Sm2Exta  = 37U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),
    kINPUTMUX_WwdtinterruptToFlexpwm0Sm2Exta      = 38U + (FlexPWM0_SM2_EXTA_REG << PMUX_SHIFT),

    /* Connections for FlexPWM0_SM0_EXTSYNC */
    kINPUTMUX_ArmtxevToFlexpwm0Sm0Extsync            = 1U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToFlexpwm0Sm0Extsync            = 6U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToFlexpwm0Sm0Extsync        = 9U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToFlexpwm0Sm0Extsync        = 10U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToFlexpwm0Sm0Extsync        = 11U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToFlexpwm0Sm0Extsync        = 12U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToFlexpwm0Sm0Extsync            = 20U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToFlexpwm0Sm0Extsync            = 21U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToFlexpwm0Sm0Extsync            = 22U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToFlexpwm0Sm0Extsync            = 23U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToFlexpwm0Sm0Extsync            = 24U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToFlexpwm0Sm0Extsync            = 25U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToFlexpwm0Sm0Extsync            = 26U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToFlexpwm0Sm0Extsync            = 27U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToFlexpwm0Sm0Extsync            = 28U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToFlexpwm0Sm0Extsync            = 29U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToFlexpwm0Sm0Extsync           = 30U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToFlexpwm0Sm0Extsync           = 31U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToFlexpwm0Sm0Extsync = 32U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToFlexpwm0Sm0Extsync = 33U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToFlexpwm0Sm0Extsync = 34U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToFlexpwm0Sm0Extsync = 35U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_EccerrorinterruptToFlexpwm0Sm0Extsync  = 37U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_WwdtinterruptToFlexpwm0Sm0Extsync      = 38U + (FlexPWM0_SM0_EXTSYNC_REG << PMUX_SHIFT),

    /* Connections for FlexPWM0_SM1_EXTSYNC */
    kINPUTMUX_ArmtxevToFlexpwm0Sm1Extsync            = 1U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToFlexpwm0Sm1Extsync            = 6U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToFlexpwm0Sm1Extsync        = 9U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToFlexpwm0Sm1Extsync        = 10U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToFlexpwm0Sm1Extsync        = 11U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToFlexpwm0Sm1Extsync        = 12U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToFlexpwm0Sm1Extsync            = 20U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToFlexpwm0Sm1Extsync            = 21U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToFlexpwm0Sm1Extsync            = 22U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToFlexpwm0Sm1Extsync            = 23U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToFlexpwm0Sm1Extsync            = 24U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToFlexpwm0Sm1Extsync            = 25U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToFlexpwm0Sm1Extsync            = 26U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToFlexpwm0Sm1Extsync            = 27U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToFlexpwm0Sm1Extsync            = 28U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToFlexpwm0Sm1Extsync            = 29U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToFlexpwm0Sm1Extsync           = 30U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToFlexpwm0Sm1Extsync           = 31U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToFlexpwm0Sm1Extsync = 32U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToFlexpwm0Sm1Extsync = 33U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToFlexpwm0Sm1Extsync = 34U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToFlexpwm0Sm1Extsync = 35U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_EccerrorinterruptToFlexpwm0Sm1Extsync  = 37U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_WwdtinterruptToFlexpwm0Sm1Extsync      = 38U + (FlexPWM0_SM1_EXTSYNC_REG << PMUX_SHIFT),

    /* Connections for FlexPWM0_SM2_EXTSYNC */
    kINPUTMUX_ArmtxevToFlexpwm0Sm2Extsync            = 1U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToFlexpwm0Sm2Extsync            = 6U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToFlexpwm0Sm2Extsync        = 9U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToFlexpwm0Sm2Extsync        = 10U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToFlexpwm0Sm2Extsync        = 11U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToFlexpwm0Sm2Extsync        = 12U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToFlexpwm0Sm2Extsync            = 20U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToFlexpwm0Sm2Extsync            = 21U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToFlexpwm0Sm2Extsync            = 22U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToFlexpwm0Sm2Extsync            = 23U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToFlexpwm0Sm2Extsync            = 24U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToFlexpwm0Sm2Extsync            = 25U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToFlexpwm0Sm2Extsync            = 26U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToFlexpwm0Sm2Extsync            = 27U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToFlexpwm0Sm2Extsync            = 28U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToFlexpwm0Sm2Extsync            = 29U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToFlexpwm0Sm2Extsync           = 30U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToFlexpwm0Sm2Extsync           = 31U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToFlexpwm0Sm2Extsync = 32U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToFlexpwm0Sm2Extsync = 33U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToFlexpwm0Sm2Extsync = 34U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToFlexpwm0Sm2Extsync = 35U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_EccerrorinterruptToFlexpwm0Sm2Extsync  = 37U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),
    kINPUTMUX_WwdtinterruptToFlexpwm0Sm2Extsync      = 38U + (FlexPWM0_SM2_EXTSYNC_REG << PMUX_SHIFT),

    /* Connections for FlexPWM0_FAULT */
    kINPUTMUX_ArmtxevToFlexpwm0Fault            = 1U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToFlexpwm0Fault            = 6U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToFlexpwm0Fault        = 9U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToFlexpwm0Fault        = 10U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToFlexpwm0Fault        = 11U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToFlexpwm0Fault        = 12U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToFlexpwm0Fault            = 20U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToFlexpwm0Fault            = 21U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToFlexpwm0Fault            = 22U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToFlexpwm0Fault            = 23U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToFlexpwm0Fault            = 24U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToFlexpwm0Fault            = 25U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToFlexpwm0Fault            = 26U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToFlexpwm0Fault            = 27U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToFlexpwm0Fault            = 28U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToFlexpwm0Fault            = 29U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToFlexpwm0Fault           = 30U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToFlexpwm0Fault           = 31U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToFlexpwm0Fault = 32U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToFlexpwm0Fault = 33U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToFlexpwm0Fault = 34U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToFlexpwm0Fault = 35U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_EccerrorinterruptToFlexpwm0Fault  = 37U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),
    kINPUTMUX_WwdtinterruptToFlexpwm0Fault      = 38U + (FlexPWM0_FAULT_REG << PMUX_SHIFT),

    /* Connections for FlexPWM0_FORCE */
    kINPUTMUX_ArmtxevToFlexpwm0Force            = 1U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Cmp0OutToFlexpwm0Force            = 6U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToFlexpwm0Force        = 9U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToFlexpwm0Force        = 10U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToFlexpwm0Force        = 11U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToFlexpwm0Force        = 12U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToFlexpwm0Force            = 20U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToFlexpwm0Force            = 21U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToFlexpwm0Force            = 22U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToFlexpwm0Force            = 23U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToFlexpwm0Force            = 24U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToFlexpwm0Force            = 25U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToFlexpwm0Force            = 26U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToFlexpwm0Force            = 27U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToFlexpwm0Force            = 28U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToFlexpwm0Force            = 29U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToFlexpwm0Force           = 30U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToFlexpwm0Force           = 31U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToFlexpwm0Force = 32U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToFlexpwm0Force = 33U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToFlexpwm0Force = 34U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToFlexpwm0Force = 35U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_EccerrorinterruptToFlexpwm0Force  = 37U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),
    kINPUTMUX_WwdtinterruptToFlexpwm0Force      = 38U + (FlexPWM0_FORCE_REG << PMUX_SHIFT),

    /* Connections for PWM0_EXT_CLK */
    kINPUTMUX_Clk16K1ToPwm0Extclk = 1U + (PWM0_EXT_CLK_REG << PMUX_SHIFT),
    kINPUTMUX_ClkinToPwm0Extclk   = 2U + (PWM0_EXT_CLK_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToPwm0Extclk = 5U + (PWM0_EXT_CLK_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToPwm0Extclk = 6U + (PWM0_EXT_CLK_REG << PMUX_SHIFT),

    /* Connections for EXT_TRIG */
    kINPUTMUX_Cmp0OutToExttrig               = 6U + (EXT_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart0IppdolpuarttxdToExttrig = 9U + (EXT_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart1IppdolpuarttxdToExttrig = 10U + (EXT_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart2IppdolpuarttxdToExttrig = 11U + (EXT_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lpuart3IppdolpuarttxdToExttrig = 12U + (EXT_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Rtc1HzclkToExttrig             = 19U + (EXT_TRIG_REG << PMUX_SHIFT),

    /* Connections for LPI2C0_TRIG */
    kINPUTMUX_Cmp0OutToLpi2C0Trig            = 6U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat0ToLpi2C0Trig        = 9U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat1ToLpi2C0Trig        = 10U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat0ToLpi2C0Trig        = 11U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat1ToLpi2C0Trig        = 12U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lptmr0ToLpi2C0Trig             = 15U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToLpi2C0Trig            = 17U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToLpi2C0Trig            = 18U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToLpi2C0Trig            = 19U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToLpi2C0Trig            = 20U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToLpi2C0Trig            = 21U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToLpi2C0Trig            = 22U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToLpi2C0Trig            = 23U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToLpi2C0Trig            = 24U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToLpi2C0Trig = 25U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToLpi2C0Trig = 26U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToLpi2C0Trig = 27U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToLpi2C0Trig = 28U + (LPI2C0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_WuuToLpi2C0Trig                = 30U + (LPI2C0_TRIG_REG << PMUX_SHIFT),

    /* Connections for LPSPI0_TRIG */
    kINPUTMUX_Cmp0OutToLpspi0Trig            = 6U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat1ToLpspi0Trig        = 9U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToLpspi0Trig        = 10U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat1ToLpspi0Trig        = 11U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToLpspi0Trig        = 12U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Lptmr0ToLpspi0Trig             = 15U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToLpspi0Trig            = 17U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToLpspi0Trig            = 18U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToLpspi0Trig            = 19U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToLpspi0Trig            = 20U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToLpspi0Trig            = 21U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToLpspi0Trig            = 22U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToLpspi0Trig            = 23U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToLpspi0Trig            = 24U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToLpspi0Trig = 25U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToLpspi0Trig = 26U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToLpspi0Trig = 27U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToLpspi0Trig = 28U + (LPSPI0_TRIG_REG << PMUX_SHIFT),
    kINPUTMUX_WuuToLpspi0Trig                = 30U + (LPSPI0_TRIG_REG << PMUX_SHIFT),

    /* Connections for LPUART0 */
    kINPUTMUX_Cmp0OutToLpuart0            = 6U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToLpuart0        = 9U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToLpuart0        = 10U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToLpuart0        = 11U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToLpuart0        = 12U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Lptmr0ToLpuart0             = 15U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToLpuart0            = 17U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToLpuart0            = 18U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToLpuart0            = 19U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToLpuart0            = 20U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToLpuart0            = 21U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToLpuart0            = 22U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToLpuart0            = 23U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToLpuart0            = 24U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToLpuart0            = 25U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToLpuart0            = 26U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToLpuart0           = 27U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToLpuart0           = 28U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToLpuart0 = 29U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToLpuart0 = 30U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToLpuart0 = 31U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToLpuart0 = 32U + (LPUART0_REG << PMUX_SHIFT),
    kINPUTMUX_WuuToLpuart0                = 34U + (LPUART0_REG << PMUX_SHIFT),

    /* Connections for LPUART1 */
    kINPUTMUX_Cmp0OutToLpuart1            = 6U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToLpuart1        = 9U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToLpuart1        = 10U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToLpuart1        = 11U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToLpuart1        = 12U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Lptmr0ToLpuart1             = 15U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToLpuart1            = 17U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToLpuart1            = 18U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToLpuart1            = 19U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToLpuart1            = 20U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToLpuart1            = 21U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToLpuart1            = 22U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToLpuart1            = 23U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToLpuart1            = 24U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToLpuart1            = 25U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToLpuart1            = 26U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToLpuart1           = 27U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToLpuart1           = 28U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToLpuart1 = 29U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToLpuart1 = 30U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToLpuart1 = 31U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToLpuart1 = 32U + (LPUART1_REG << PMUX_SHIFT),
    kINPUTMUX_WuuToLpuart1                = 34U + (LPUART1_REG << PMUX_SHIFT),

    /* Connections for LPUART2 */
    kINPUTMUX_Cmp0OutToLpuart2            = 6U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToLpuart2        = 9U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToLpuart2        = 10U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToLpuart2        = 11U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToLpuart2        = 12U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Lptmr0ToLpuart2             = 15U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToLpuart2            = 17U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToLpuart2            = 18U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToLpuart2            = 19U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToLpuart2            = 20U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToLpuart2            = 21U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToLpuart2            = 22U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToLpuart2            = 23U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToLpuart2            = 24U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToLpuart2            = 25U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToLpuart2            = 26U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToLpuart2           = 27U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToLpuart2           = 28U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToLpuart2 = 29U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToLpuart2 = 30U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToLpuart2 = 31U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToLpuart2 = 32U + (LPUART2_REG << PMUX_SHIFT),
    kINPUTMUX_WuuToLpuart2                = 34U + (LPUART2_REG << PMUX_SHIFT),

    /* Connections for LPUART3 */
    kINPUTMUX_Cmp0OutToLpuart3            = 6U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat2ToLpuart3        = 9U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer0Mat3ToLpuart3        = 10U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat2ToLpuart3        = 11U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Ctimer1Mat3ToLpuart3        = 12U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Lptmr0ToLpuart3             = 15U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin0ToLpuart3            = 17U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin1ToLpuart3            = 18U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin2ToLpuart3            = 19U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin3ToLpuart3            = 20U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin4ToLpuart3            = 21U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin5ToLpuart3            = 22U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin6ToLpuart3            = 23U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin7ToLpuart3            = 24U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin8ToLpuart3            = 25U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin9ToLpuart3            = 26U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin10ToLpuart3           = 27U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Trigin11ToLpuart3           = 28U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio0Pineventtrig0ToLpuart3 = 29U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio1Pineventtrig0ToLpuart3 = 30U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio2Pineventtrig0ToLpuart3 = 31U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_Gpio3Pineventtrig0ToLpuart3 = 32U + (LPUART3_REG << PMUX_SHIFT),
    kINPUTMUX_WuuToLpuart3                = 34U + (LPUART3_REG << PMUX_SHIFT),
} inputmux_connection_t;

/*@}*/

/*@}*/

#endif /* _FSL_INPUTMUX_CONNECTIONS_ */
