/*
 * NOTE: File generated by gen_soc_headers.py
 * from MIMXRT633SFVKB/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MIMXRT685SFVKB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 67e6fc680711ca13
 */

#ifndef _ZEPHYR_DTS_BINDING_MIMXRT633SFVKB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MIMXRT633SFVKB_WRAPPER_

#include "MIMXRT685SFVKB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MIMXRT633SFVKB_WRAPPER_ */
