/*
 * NOTE: File generated by gen_soc_headers.py
 * from MIMXRT633SFAWBR/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MIMXRT685SFAWBR-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 5e2acf67e2ac169a
 */

#ifndef _ZEPHYR_DTS_BINDING_MIMXRT633SFAWBR_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MIMXRT633SFAWBR_WRAPPER_

#include "MIMXRT685SFAWBR-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MIMXRT633SFAWBR_WRAPPER_ */
