/*
 * SPDX-FileCopyrightText: Copyright 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_IMX_CCM_REV3_RT266X_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_IMX_CCM_REV3_RT266X_H_

/**
 * @file
 * @brief i.MX RT266x clock identifiers for the nxp,imx-ccm-rev3 controller.
 *
 * Three independent identifier spaces:
 *
 *  - @c IMX_CCM_LPCG_* -- peripheral clock gates. The RT266x clock tree spans
 *    seven CCM instances (SYSCON, CMPT, MAIN, WAKE, COMM, AUDIO, MEDIA); a gate
 *    identifier names both the owning instance and the slice within it, which
 *    the HAL resolves at run time.
 *  - @c IMX_CCM_ROOT_* -- clock roots, likewise spanning all seven instances.
 *    A root is what carries a mux and dividers, so it is what determines a
 *    peripheral's frequency.
 *  - @c IMX_CCM_MUX_<root>_<source> -- the per-root mux selector values. Each
 *    root has its own source list, so these are namespaced by root.
 *
 * Peripheral nodes combine a gate and a root with @c IMX_CCM_CLK();
 * clock-root child nodes of the controller take a root identifier in @c reg
 * and a mux value in @c clock-mux.
 *
 * Generated from fsl_clock.h (clock_lpcg_t, clock_root_t,
 * clock_root_mux_source_t) by hal_nxp
 * mcux/scripts/clock/gen_ccm_rev3_ids.py, so the values cannot drift from
 * the HAL enumerations the driver passes them to. Do not edit by hand;
 * regenerate against a newer device release instead. The _START/_END range
 * markers and the invalid sentinels are intentionally not exported -- use
 * @c IMX_CCM_GATE_NONE / @c IMX_CCM_ROOT_NONE from
 * <zephyr/dt-bindings/clock/imx_ccm_rev3.h> instead.
 *
 * FSL clock driver version: 1.1.0
 * Source: hal_nxp 45f49e6ef / RT2660 MIMXRT2663 public SDK
 */

#include <zephyr/dt-bindings/clock/imx_ccm_rev3.h>

/* Peripheral clock gates (LPCG), from clock_lpcg_t. */
#define IMX_CCM_LPCG_SYSCON_FREQME         0
#define IMX_CCM_LPCG_CMPT_ROMCP            16
#define IMX_CCM_LPCG_CMPT_CM85_CLKIN       17
#define IMX_CCM_LPCG_CMPT_CM85_DBGCLK      18
#define IMX_CCM_LPCG_CMPT_CM85_IWIC        19
#define IMX_CCM_LPCG_CMPT_NPU_CORE         20
#define IMX_CCM_LPCG_CMPT_NPU_MEM          21
#define IMX_CCM_LPCG_CMPT_FREQME           22
#define IMX_CCM_LPCG_CMPT_MODCON           23
#define IMX_CCM_LPCG_CMPT_TRDC             24
#define IMX_CCM_LPCG_CMPT_SRAM_CTRL0       25
#define IMX_CCM_LPCG_CMPT_SRAM_CTRL1       26
#define IMX_CCM_LPCG_CMPT_SRAM_CTRL2       27
#define IMX_CCM_LPCG_CMPT_NIC_GPV          28
#define IMX_CCM_LPCG_CMPT_LLC              29
#define IMX_CCM_LPCG_MAIN_TRACE_RT2660     32
#define IMX_CCM_LPCG_MAIN_TSCLK            33
#define IMX_CCM_LPCG_MAIN_TPIU_TRACECLKIN  34
#define IMX_CCM_LPCG_MAIN_SWO_TRACECLKIN   35
#define IMX_CCM_LPCG_MAIN_XSPI0            36
#define IMX_CCM_LPCG_MAIN_XSPI1            37
#define IMX_CCM_LPCG_MAIN_EDMA0            38
#define IMX_CCM_LPCG_MAIN_EDMA1            39
#define IMX_CCM_LPCG_MAIN_FREQME           40
#define IMX_CCM_LPCG_MAIN_MODCON           41
#define IMX_CCM_LPCG_MAIN_HSP_CRC          42
#define IMX_CCM_LPCG_MAIN_HSP_DAC          43
#define IMX_CCM_LPCG_MAIN_HSP_ADC0         44
#define IMX_CCM_LPCG_MAIN_HSP_ADC1         45
#define IMX_CCM_LPCG_MAIN_HSP_EVTG0        46
#define IMX_CCM_LPCG_MAIN_HSP_EVTG1        47
#define IMX_CCM_LPCG_MAIN_HSP_EVTG2        48
#define IMX_CCM_LPCG_MAIN_HSP_EVTG3        49
#define IMX_CCM_LPCG_MAIN_HSP_XBAR0        50
#define IMX_CCM_LPCG_MAIN_HSP_XBAR1        51
#define IMX_CCM_LPCG_MAIN_HSP_XBAR2        52
#define IMX_CCM_LPCG_MAIN_SRAMC            53
#define IMX_CCM_LPCG_MAIN_TRDC             54
#define IMX_CCM_LPCG_MAIN_HSP_LPSPI0       55
#define IMX_CCM_LPCG_MAIN_HSP_LPSPI1       56
#define IMX_CCM_LPCG_MAIN_HSP_LPSPI2       57
#define IMX_CCM_LPCG_MAIN_HSP_LPSPI3       58
#define IMX_CCM_LPCG_MAIN_HSP_LPSPI4       59
#define IMX_CCM_LPCG_MAIN_HSP_LPI2C0       60
#define IMX_CCM_LPCG_MAIN_HSP_LPI2C1       61
#define IMX_CCM_LPCG_MAIN_HSP_LPUART0      62
#define IMX_CCM_LPCG_MAIN_HSP_LPUART1      63
#define IMX_CCM_LPCG_MAIN_HSP_LPUART2      64
#define IMX_CCM_LPCG_MAIN_HSP_LPUART3      65
#define IMX_CCM_LPCG_MAIN_HSP_LPUART4      66
#define IMX_CCM_LPCG_MAIN_HSP_LPUART5      67
#define IMX_CCM_LPCG_MAIN_HSP_FLEXPWM0     68
#define IMX_CCM_LPCG_MAIN_HSP_FLEXPWM1     69
#define IMX_CCM_LPCG_MAIN_HSP_FLEXPWM2     70
#define IMX_CCM_LPCG_MAIN_HSP_FLEXPWM3     71
#define IMX_CCM_LPCG_MAIN_HSP_LPIT0        72
#define IMX_CCM_LPCG_MAIN_HSP_LPIT1        73
#define IMX_CCM_LPCG_MAIN_HSP_QTPM0        74
#define IMX_CCM_LPCG_MAIN_HSP_QTIMER0      75
#define IMX_CCM_LPCG_MAIN_HSP_QTIMER1      76
#define IMX_CCM_LPCG_MAIN_HSP_QTIMER2      77
#define IMX_CCM_LPCG_MAIN_HSP_QTIMER3      78
#define IMX_CCM_LPCG_MAIN_HSP_CAN0         79
#define IMX_CCM_LPCG_MAIN_HSP_CAN1         80
#define IMX_CCM_LPCG_MAIN_HSP_CAN2         81
#define IMX_CCM_LPCG_MAIN_HSP_QDC0         82
#define IMX_CCM_LPCG_MAIN_HSP_QDC1         83
#define IMX_CCM_LPCG_MAIN_HSP_QDC2         84
#define IMX_CCM_LPCG_MAIN_HSP_QDC3         85
#define IMX_CCM_LPCG_MAIN_HSP_RGPIO0       86
#define IMX_CCM_LPCG_MAIN_HSP_RGPIO1       87
#define IMX_CCM_LPCG_MAIN_HSP_RGPIO2       88
#define IMX_CCM_LPCG_MAIN_HSP_RGPIO3       89
#define IMX_CCM_LPCG_MAIN_HSP_RGPIO4       90
#define IMX_CCM_LPCG_MAIN_HSP_I3C0         91
#define IMX_CCM_LPCG_MAIN_HSP_FLEXIO0      92
#define IMX_CCM_LPCG_MAIN_HSP_FLEXIO1      93
#define IMX_CCM_LPCG_MAIN_HSP_FLEXIO2      94
#define IMX_CCM_LPCG_MAIN_HSP_SINC0        95
#define IMX_CCM_LPCG_MAIN_HSP_SINC1        96
#define IMX_CCM_LPCG_MAIN_MTR_MASTER       97
#define IMX_CCM_LPCG_MAIN_IOMUXC           98
#define IMX_CCM_LPCG_MAIN_HSP_TRIG_SYNC0   99
#define IMX_CCM_LPCG_MAIN_HSP_TRIG_SYNC1   100
#define IMX_CCM_LPCG_MAIN_HSP_STM          101
#define IMX_CCM_LPCG_MAIN_HSP_NIC_MAIN_GPV 102
#define IMX_CCM_LPCG_MAIN_PRINCE0          103
#define IMX_CCM_LPCG_MAIN_PRINCE1          104
#define IMX_CCM_LPCG_MAIN_CSSI             105
#define IMX_CCM_LPCG_MAIN_MMU0             106
#define IMX_CCM_LPCG_WAKE_SYSCON_PMU       112
#define IMX_CCM_LPCG_WAKE_DAP_RT2660       113
#define IMX_CCM_LPCG_WAKE_EDMA             114
#define IMX_CCM_LPCG_WAKE_FREQME           115
#define IMX_CCM_LPCG_WAKE_MODCON           116
#define IMX_CCM_LPCG_WAKE_XBAR0            117
#define IMX_CCM_LPCG_WAKE_TRDC             118
#define IMX_CCM_LPCG_WAKE_SYSCON_RESETCON  119
#define IMX_CCM_LPCG_WAKE_SYSCON_PDCON     120
#define IMX_CCM_LPCG_WAKE_SYSCON_POWERCON  121
#define IMX_CCM_LPCG_WAKE_SYSCON_MEMCON    122
#define IMX_CCM_LPCG_WAKE_MICFIL           123
#define IMX_CCM_LPCG_WAKE_LPSPI            124
#define IMX_CCM_LPCG_WAKE_LPI2C0           125
#define IMX_CCM_LPCG_WAKE_LPI2C1           126
#define IMX_CCM_LPCG_WAKE_LPUART0          127
#define IMX_CCM_LPCG_WAKE_LPUART1          128
#define IMX_CCM_LPCG_WAKE_ACMP0            129
#define IMX_CCM_LPCG_WAKE_ACMP1            130
#define IMX_CCM_LPCG_WAKE_ACMP2            131
#define IMX_CCM_LPCG_WAKE_ACMP3            132
#define IMX_CCM_LPCG_WAKE_SWT0             133
#define IMX_CCM_LPCG_WAKE_SWT1             134
#define IMX_CCM_LPCG_WAKE_LPTIMER0         135
#define IMX_CCM_LPCG_WAKE_LPTIMER1         136
#define IMX_CCM_LPCG_WAKE_QTPM             137
#define IMX_CCM_LPCG_WAKE_EWM              138
#define IMX_CCM_LPCG_WAKE_RGPIO0           139
#define IMX_CCM_LPCG_WAKE_I3C0             140
#define IMX_CCM_LPCG_WAKE_RAM_CTRL         141
#define IMX_CCM_LPCG_WAKE_IOMUXC           142
#define IMX_CCM_LPCG_WAKE_VBAT_RTC_HP      143
#define IMX_CCM_LPCG_WAKE_TRIG_SYNC        144
#define IMX_CCM_LPCG_COMM_XSPIR            160
#define IMX_CCM_LPCG_COMM_ETH0             161
#define IMX_CCM_LPCG_COMM_ETH1             162
#define IMX_CCM_LPCG_COMM_USDHC0           163
#define IMX_CCM_LPCG_COMM_USDHC1           164
#define IMX_CCM_LPCG_COMM_USB0             165
#define IMX_CCM_LPCG_COMM_USB1             166
#define IMX_CCM_LPCG_COMM_XENOPHY0         167
#define IMX_CCM_LPCG_COMM_XENOPHY1         168
#define IMX_CCM_LPCG_COMM_FREQME           169
#define IMX_CCM_LPCG_COMM_MODCON           170
#define IMX_CCM_LPCG_COMM_TRDC             171
#define IMX_CCM_LPCG_COMM_NIC_GPV          172
#define IMX_CCM_LPCG_AUDIO_EDMA            176
#define IMX_CCM_LPCG_AUDIO_FREQME          177
#define IMX_CCM_LPCG_AUDIO_MODCON          178
#define IMX_CCM_LPCG_AUDIO_XBAR0           179
#define IMX_CCM_LPCG_AUDIO_TRDC            180
#define IMX_CCM_LPCG_AUDIO_SAI0            181
#define IMX_CCM_LPCG_AUDIO_SAI1            182
#define IMX_CCM_LPCG_AUDIO_SAI2            183
#define IMX_CCM_LPCG_AUDIO_MICFIL          184
#define IMX_CCM_LPCG_AUDIO_ASRC            185
#define IMX_CCM_LPCG_AUDIO_SPDIF_XCVR      186
#define IMX_CCM_LPCG_AUDIO_MQS             187
#define IMX_CCM_LPCG_AUDIO_RAM_CTRL        188
#define IMX_CCM_LPCG_MEDIA_JPEG_DECODER    192
#define IMX_CCM_LPCG_MEDIA_ISI             193
#define IMX_CCM_LPCG_MEDIA_REFORMATTER     194
#define IMX_CCM_LPCG_MEDIA_CSI             195
#define IMX_CCM_LPCG_MEDIA_MIPI_CSI        196
#define IMX_CCM_LPCG_MEDIA_GPU             197
#define IMX_CCM_LPCG_MEDIA_DCIF            198
#define IMX_CCM_LPCG_MEDIA_MIPI_DSI        199
#define IMX_CCM_LPCG_MEDIA_FREQME          200
#define IMX_CCM_LPCG_MEDIA_MODCON          201
#define IMX_CCM_LPCG_MEDIA_TRDC            202
#define IMX_CCM_LPCG_MEDIA_NIC_GPV         203

/* Clock roots, from clock_root_t. */
#define IMX_CCM_ROOT_CGU_SXOSC_ROOTCLK            0
#define IMX_CCM_ROOT_CGU_BASE_CLK                 1
#define IMX_CCM_ROOT_CGU_LOW_CLK                  2
#define IMX_CCM_ROOT_CGU_MAINPLL_DIVX             3
#define IMX_CCM_ROOT_CGU_SYSPLL_DIVX              4
#define IMX_CCM_ROOT_CGU_PLL_PFDX                 5
#define IMX_CCM_ROOT_CGU_MEDIA_PFDX               6
#define IMX_CCM_ROOT_CGU_MAINPFDX_ROOTCLK         7
#define IMX_CCM_ROOT_CGU_COMMPFDX_ROOTCLK         8
#define IMX_CCM_ROOT_CGU_MAINDIVX_ROOTCLK         9
#define IMX_CCM_ROOT_CGU_SAIMCLK_ROOTCLK          10
#define IMX_CCM_ROOT_CGU_SAIMCLK0_ROOTCLK         11
#define IMX_CCM_ROOT_CGU_SAIMCLK1_ROOTCLK         12
#define IMX_CCM_ROOT_CGU_SAIMCLK2_ROOTCLK         13
#define IMX_CCM_ROOT_CGU_LP12M_CORE_ROOTCLK       14
#define IMX_CCM_ROOT_CGU_LP1M_CORE_ROOTCLK        15
#define IMX_CCM_ROOT_CGU_ULP32K_ROOTCLK           16
#define IMX_CCM_ROOT_CGU_FRO192M_ROOTCLK          17
#define IMX_CCM_ROOT_CGU_FRO96M_ROOTCLK           18
#define IMX_CCM_ROOT_CGU_FRO48M_ROOTCLK           19
#define IMX_CCM_ROOT_CGU_FRO24M_ROOTCLK           20
#define IMX_CCM_ROOT_CGU_SYSPLLDIV4_ROOTCLK       21
#define IMX_CCM_ROOT_CGU_SYSPLLDIV5_ROOTCLK       22
#define IMX_CCM_ROOT_CGU_SYSPLLDIVX_ROOTCLK       23
#define IMX_CCM_ROOT_CGU_MAINPLLDIVX_ROOTCLK      24
#define IMX_CCM_ROOT_CGU_MAINPLLDIV8_ROOTCLK      25
#define IMX_CCM_ROOT_CGU_MAINPLLDIV10_ROOTCLK     26
#define IMX_CCM_ROOT_CGU_MAINPLLDIV20_ROOTCLK     27
#define IMX_CCM_ROOT_CGU_AUDIOPLL_ROOTCLK         28
#define IMX_CCM_ROOT_CGU_VIDEOPLL_ROOTCLK         29
#define IMX_CCM_ROOT_CGU_MAIN_ROOTCLK             30
#define IMX_CCM_ROOT_CGU_NPU_ROOTCLK              31
#define IMX_CCM_ROOT_CGU_MEDIABUS_ROOTCLK         32
#define IMX_CCM_ROOT_CGU_AUDIOBUS_ROOTCLK         33
#define IMX_CCM_ROOT_CGU_COMMBUS_ROOTCLK          34
#define IMX_CCM_ROOT_CGU_WAKEBUS_ROOTCLK          35
#define IMX_CCM_ROOT_CGU_SYSCON_PDMAIN_CLK        36
#define IMX_CCM_ROOT_CGU_PERI_ROOTCLK0            37
#define IMX_CCM_ROOT_CGU_PERI_ROOTCLK1            38
#define IMX_CCM_ROOT_CGU_PERI_ROOTCLK2            39
#define IMX_CCM_ROOT_CGU_PERI_ROOTCLK3            40
#define IMX_CCM_ROOT_CGU_PERI_ROOTCLK4            41
#define IMX_CCM_ROOT_CGU_PERI_ROOTCLK5            42
#define IMX_CCM_ROOT_CGU_PERI_ROOTCLK6            43
#define IMX_CCM_ROOT_CGU_PERI_ROOTCLK7            44
#define IMX_CCM_ROOT_CGU_AUDIO_ROOTCLK            45
#define IMX_CCM_ROOT_CGU_VIDEO_ROOTCLK            46
#define IMX_CCM_ROOT_CGU_USB1_ROOTCLK             47
#define IMX_CCM_ROOT_CGU_ETH_ROOTCLK              48
#define IMX_CCM_ROOT_CGU_TEST_ROOTCLK             49
#define IMX_CCM_ROOT_CGU_CLKOUT                   50
#define IMX_CCM_ROOT_CGU_MAIN_FRO192M             51
#define IMX_CCM_ROOT_CGU_MAIN_ULP32K              52
#define IMX_CCM_ROOT_CMPT_CMPT_CLK                64
#define IMX_CCM_ROOT_CMPT_CPU_CLK                 65
#define IMX_CCM_ROOT_CMPT_NPU_CLK                 66
#define IMX_CCM_ROOT_CMPT_SYSTICK_CLK0            67
#define IMX_CCM_ROOT_CMPT_SYSTICK_CLK1            68
#define IMX_CCM_ROOT_MAIN_MAIN_CLK_DIVIDED        80
#define IMX_CCM_ROOT_MAIN_XSPI0_FCLK_DIVIDED      81
#define IMX_CCM_ROOT_MAIN_XSPI1_FCLK_DIVIDED      82
#define IMX_CCM_ROOT_MAIN_I3C0_FCLK               83
#define IMX_CCM_ROOT_MAIN_LPI2C0_FCLK             84
#define IMX_CCM_ROOT_MAIN_LPI2C1_FCLK             85
#define IMX_CCM_ROOT_MAIN_LPSPI0_FCLK             86
#define IMX_CCM_ROOT_MAIN_LPSPI1_FCLK             87
#define IMX_CCM_ROOT_MAIN_LPSPI2_FCLK             88
#define IMX_CCM_ROOT_MAIN_LPSPI3_FCLK             89
#define IMX_CCM_ROOT_MAIN_LPSPI4_FCLK             90
#define IMX_CCM_ROOT_MAIN_LPUART0_FCLK            91
#define IMX_CCM_ROOT_MAIN_LPUART1_FCLK            92
#define IMX_CCM_ROOT_MAIN_LPUART2_FCLK            93
#define IMX_CCM_ROOT_MAIN_LPUART3_FCLK            94
#define IMX_CCM_ROOT_MAIN_LPUART4_FCLK            95
#define IMX_CCM_ROOT_MAIN_LPUART5_FCLK            96
#define IMX_CCM_ROOT_MAIN_FLEXCAN0_FCLK           97
#define IMX_CCM_ROOT_MAIN_FLEXCAN1_FCLK           98
#define IMX_CCM_ROOT_MAIN_FLEXCAN2_FCLK           99
#define IMX_CCM_ROOT_MAIN_FLEXCAN_GFCLK           100
#define IMX_CCM_ROOT_MAIN_QTPM0_FCLK              101
#define IMX_CCM_ROOT_MAIN_LPIT0_FCLK              102
#define IMX_CCM_ROOT_MAIN_LPIT1_FCLK              103
#define IMX_CCM_ROOT_MAIN_ADC0_FCLK               104
#define IMX_CCM_ROOT_MAIN_ADC1_FCLK               105
#define IMX_CCM_ROOT_MAIN_SINC0_FCLK              106
#define IMX_CCM_ROOT_MAIN_SINC1_FCLK              107
#define IMX_CCM_ROOT_MAIN_FLEXIO0_FCLK            108
#define IMX_CCM_ROOT_MAIN_FLEXIO1_FCLK            109
#define IMX_CCM_ROOT_MAIN_FLEXIO2_FCLK            110
#define IMX_CCM_ROOT_MAIN_TPIU_CLK                111
#define IMX_CCM_ROOT_MAIN_CSSI_REFCLK             112
#define IMX_CCM_ROOT_MAIN_OTP_CLK                 113
#define IMX_CCM_ROOT_MAIN_CLKOUT                  114
#define IMX_CCM_ROOT_MAIN_FRO192M                 115
#define IMX_CCM_ROOT_MAIN_ULP32K                  116
#define IMX_CCM_ROOT_WAKE_WAKE_CLK                128
#define IMX_CCM_ROOT_WAKE_WAKE_SXOSC              129
#define IMX_CCM_ROOT_WAKE_WAKE_LP1M               130
#define IMX_CCM_ROOT_WAKE_WAKE_LP12M              131
#define IMX_CCM_ROOT_WAKE_WAKE_ULP32K             132
#define IMX_CCM_ROOT_WAKE_WAKE_LPCLK              133
#define IMX_CCM_ROOT_WAKE_I3C0_FCLK               134
#define IMX_CCM_ROOT_WAKE_LPI2C0_FCLK             135
#define IMX_CCM_ROOT_WAKE_LPI2C1_FCLK             136
#define IMX_CCM_ROOT_WAKE_LPSPI0_FCLK             137
#define IMX_CCM_ROOT_WAKE_LPUART0_FCLK            138
#define IMX_CCM_ROOT_WAKE_LPUART1_FCLK            139
#define IMX_CCM_ROOT_WAKE_DMIC1_APPCLK            140
#define IMX_CCM_ROOT_WAKE_QTPM0_FCLK              141
#define IMX_CCM_ROOT_WAKE_LPTMR0_FCLK             142
#define IMX_CCM_ROOT_WAKE_LPTMR1_FCLK             143
#define IMX_CCM_ROOT_WAKE_SWT0_FCLK               144
#define IMX_CCM_ROOT_WAKE_SWT1_FCLK               145
#define IMX_CCM_ROOT_WAKE_EWM_FCLK                146
#define IMX_CCM_ROOT_WAKE_ACMP0_FCLK              147
#define IMX_CCM_ROOT_WAKE_ACMP1_FCLK              148
#define IMX_CCM_ROOT_WAKE_ACMP2_FCLK              149
#define IMX_CCM_ROOT_WAKE_ACMP3_FCLK              150
#define IMX_CCM_ROOT_WAKE_ACMP0_RRCLK             151
#define IMX_CCM_ROOT_WAKE_ACMP1_RRCLK             152
#define IMX_CCM_ROOT_WAKE_ACMP2_RRCLK             153
#define IMX_CCM_ROOT_WAKE_ACMP3_RRCLK             154
#define IMX_CCM_ROOT_COMM_COMM_CLK                160
#define IMX_CCM_ROOT_COMM_COMM_ULP32K             161
#define IMX_CCM_ROOT_COMM_USDHC0_FCLK             162
#define IMX_CCM_ROOT_COMM_USDHC1_FCLK             163
#define IMX_CCM_ROOT_COMM_XSPIR_ROOTCLK           164
#define IMX_CCM_ROOT_COMM_USB0_PHYCLK             165
#define IMX_CCM_ROOT_COMM_USB0_FRO48M             166
#define IMX_CCM_ROOT_COMM_USB1_FCLK               167
#define IMX_CCM_ROOT_COMM_USB0_WAKECLK            168
#define IMX_CCM_ROOT_COMM_ETH0_TRXCLK             169
#define IMX_CCM_ROOT_COMM_ETH0_TIMERCLK           170
#define IMX_CCM_ROOT_COMM_ETH1_TRXCLK             171
#define IMX_CCM_ROOT_COMM_ETH1_TIMERCLK           172
#define IMX_CCM_ROOT_COMM_ETH_REFCLK              173
#define IMX_CCM_ROOT_COMM_XENO0_LIWCLK            174
#define IMX_CCM_ROOT_COMM_XENO1_LIWCLK            175
#define IMX_CCM_ROOT_COMM_DLL_REFCLK              176
#define IMX_CCM_ROOT_AUDIO_AUDIO_CLK              192
#define IMX_CCM_ROOT_AUDIO_DMIC0_APPCLK           193
#define IMX_CCM_ROOT_AUDIO_SAI0_MCLK0             194
#define IMX_CCM_ROOT_AUDIO_SAI0_MCLK1             195
#define IMX_CCM_ROOT_AUDIO_SAI1_MCLK0             196
#define IMX_CCM_ROOT_AUDIO_SAI1_MCLK1             197
#define IMX_CCM_ROOT_AUDIO_SAI2_MCLK0             198
#define IMX_CCM_ROOT_AUDIO_SAI2_MCLK1             199
#define IMX_CCM_ROOT_AUDIO_SPDIF_TXCLK            200
#define IMX_CCM_ROOT_AUDIO_SPDIF_CDRCLK           201
#define IMX_CCM_ROOT_AUDIO_ASRC_CLK               202
#define IMX_CCM_ROOT_MEDIA_MEDIA_CLK              208
#define IMX_CCM_ROOT_MEDIA_MEDIAPLL_CLK           209
#define IMX_CCM_ROOT_MEDIA_MIPICSI_ESCCLK         210
#define IMX_CCM_ROOT_MEDIA_MIPICSI_CLK            211
#define IMX_CCM_ROOT_MEDIA_MIPIDSI_ESCCLK_DIVIDED 212
#define IMX_CCM_ROOT_MEDIA_MIPIDSI_REFCLK         213
#define IMX_CCM_ROOT_MEDIA_MIPIDSI_CLK            214
#define IMX_CCM_ROOT_MEDIA_REFORMAT_FCLK          215
#define IMX_CCM_ROOT_MEDIA_DCPIXEL_FCLK           216
#define IMX_CCM_ROOT_MEDIA_CSI_MCLKOUT            217

/* Per-root mux source selectors, from clock_root_mux_source_t. */
#define IMX_CCM_MUX_SXOSC_OSC_24M               0
#define IMX_CCM_MUX_BASE_FRO_192M               0
#define IMX_CCM_MUX_BASE_OSC_24M                1
#define IMX_CCM_MUX_BASE_LPOSC_12M_CORE         2
#define IMX_CCM_MUX_BASE_LPOSC_1M_CORE          3
#define IMX_CCM_MUX_LOW_FRO_24M                 0
#define IMX_CCM_MUX_LOW_OSC_24M                 1
#define IMX_CCM_MUX_LOW_LPOSC_12M_CORE          2
#define IMX_CCM_MUX_LOW_LPOSC_1M_CORE           3
#define IMX_CCM_MUX_MAINPLL_DIVX_MAINPLL_DIV4   0
#define IMX_CCM_MUX_MAINPLL_DIVX_MAINPLL_DIV5   1
#define IMX_CCM_MUX_SYSPLL_DIVX_SYSPLL_DIV4     0
#define IMX_CCM_MUX_SYSPLL_DIVX_SYSPLL_DIV5     1
#define IMX_CCM_MUX_PLL_PFDX_MAINPLL_DIVOUT1    0
#define IMX_CCM_MUX_PLL_PFDX_MAINPLL_DIVOUT2    1
#define IMX_CCM_MUX_PLL_PFDX_SYSPLL_DIVOUT1     2
#define IMX_CCM_MUX_PLL_PFDX_SYSPLL_DIVOUT2     3
#define IMX_CCM_MUX_MEDIA_PFDX_MAINPLL_DIVOUT1  0
#define IMX_CCM_MUX_MEDIA_PFDX_MAINPLL_DIVOUT2  1
#define IMX_CCM_MUX_MEDIA_PFDX_SYSPLL_DIVOUT1   2
#define IMX_CCM_MUX_MEDIA_PFDX_SYSPLL_DIVOUT2   3
#define IMX_CCM_MUX_MAINPFDX_COREPLL_OUT        0
#define IMX_CCM_MUX_MAINPFDX_MAINPLL_DIVOUT2    1
#define IMX_CCM_MUX_MAINPFDX_SYSPLL_DIVOUT1     2
#define IMX_CCM_MUX_MAINPFDX_SYSPLL_DIVOUT2     3
#define IMX_CCM_MUX_COMMPFDX_COREPLL_OUT        0
#define IMX_CCM_MUX_COMMPFDX_MAINPLL_DIVOUT2    1
#define IMX_CCM_MUX_COMMPFDX_SYSPLL_DIVOUT1     2
#define IMX_CCM_MUX_COMMPFDX_SYSPLL_DIVOUT2     3
#define IMX_CCM_MUX_MAINDIVX_MAINPLL_DIV4       0
#define IMX_CCM_MUX_MAINDIVX_MAINPLL_DIV5       1
#define IMX_CCM_MUX_MAINDIVX_SYSPLL_DIV4        2
#define IMX_CCM_MUX_MAINDIVX_SYSPLL_DIV5        3
#define IMX_CCM_MUX_SAIMCLK_SAI0_MCLK           0
#define IMX_CCM_MUX_SAIMCLK_SAI1_MCLK           1
#define IMX_CCM_MUX_SAIMCLK_SAI2_MCLK           2
#define IMX_CCM_MUX_SAIMCLK_LPOSC_12M_CORE      3
#define IMX_CCM_MUX_SAIMCLK0_SAI0_MCLK          0
#define IMX_CCM_MUX_SAIMCLK1_SAI1_MCLK          0
#define IMX_CCM_MUX_SAIMCLK2_SAI2_MCLK          0
#define IMX_CCM_MUX_LP12M_CORE_LPOSC_12M_CORE   0
#define IMX_CCM_MUX_LP1M_CORE_LPOSC_1M_CORE     0
#define IMX_CCM_MUX_ULP32K_LPOSC32K             0
#define IMX_CCM_MUX_FRO192M_FRO_192M            0
#define IMX_CCM_MUX_FRO96M_FRO_96M              0
#define IMX_CCM_MUX_FRO48M_FRO_48M              0
#define IMX_CCM_MUX_FRO24M_FRO_24M              0
#define IMX_CCM_MUX_SYSPLLDIV4_SYSPLL_DIV4      0
#define IMX_CCM_MUX_SYSPLLDIV5_SYSPLL_DIV5      0
#define IMX_CCM_MUX_SYSPLLDIVX_SYSPLL_DIV4      0
#define IMX_CCM_MUX_SYSPLLDIVX_SYSPLL_DIV5      1
#define IMX_CCM_MUX_MAINPLLDIVX_MAINPLL_DIV4    0
#define IMX_CCM_MUX_MAINPLLDIVX_MAINPLL_DIV5    1
#define IMX_CCM_MUX_MAINPLLDIV8_MAINPLL_DIV8    0
#define IMX_CCM_MUX_MAINPLLDIV10_MAINPLL_DIV10  0
#define IMX_CCM_MUX_MAINPLLDIV20_MAINPLL_DIV20  0
#define IMX_CCM_MUX_AUDIOPLL_AUDIOPLL_DIVOUT    0
#define IMX_CCM_MUX_VIDEOPLL_VIDEOPLL_DIVOUT    0
#define IMX_CCM_MUX_CGU_MAIN_BASE               0
#define IMX_CCM_MUX_CGU_MAIN_COREPLL_OUT        1
#define IMX_CCM_MUX_CGU_MAIN_MAINPLL_DIVX       2
#define IMX_CCM_MUX_CGU_MAIN_PLL_PFDX           3
#define IMX_CCM_MUX_NPU_BASE                    0
#define IMX_CCM_MUX_NPU_COREPLL_OUT             1
#define IMX_CCM_MUX_NPU_MAINPLL_DIVOUT1         2
#define IMX_CCM_MUX_NPU_PLL_PFDX                3
#define IMX_CCM_MUX_MEDIABUS_BASE               0
#define IMX_CCM_MUX_MEDIABUS_COREPLL_OUT        1
#define IMX_CCM_MUX_MEDIABUS_SYSPLL_DIVOUT2     2
#define IMX_CCM_MUX_MEDIABUS_PLL_PFDX           3
#define IMX_CCM_MUX_AUDIOBUS_BASE               0
#define IMX_CCM_MUX_AUDIOBUS_SYSPLL_DIVOUT2     1
#define IMX_CCM_MUX_AUDIOBUS_MAINPLL_DIVX       2
#define IMX_CCM_MUX_AUDIOBUS_SYSPLL_DIVX        3
#define IMX_CCM_MUX_COMMBUS_BASE                0
#define IMX_CCM_MUX_COMMBUS_SYSPLL_DIVOUT2      1
#define IMX_CCM_MUX_COMMBUS_MAINPLL_DIVX        2
#define IMX_CCM_MUX_COMMBUS_SYSPLL_DIVX         3
#define IMX_CCM_MUX_WAKEBUS_LOW                 0
#define IMX_CCM_MUX_WAKEBUS_FRO_192M            1
#define IMX_CCM_MUX_WAKEBUS_MAINPLL_DIVX        2
#define IMX_CCM_MUX_WAKEBUS_SYSPLL_DIVOUT2      3
#define IMX_CCM_MUX_SYSCON_PDMAIN_LOW           0
#define IMX_CCM_MUX_SYSCON_PDMAIN_FRO_48M       1
#define IMX_CCM_MUX_SYSCON_PDMAIN_MAINPLL_DIV10 2
#define IMX_CCM_MUX_SYSCON_PDMAIN_SYSPLL_DIV10  3
#define IMX_CCM_MUX_PERI0_BASE                  0
#define IMX_CCM_MUX_PERI0_MAINPLL_DIVOUT0       1
#define IMX_CCM_MUX_PERI0_SYSPLL_DIVOUT0        2
#define IMX_CCM_MUX_PERI0_SYSPLL_DIVOUT1        3
#define IMX_CCM_MUX_PERI1_BASE                  0
#define IMX_CCM_MUX_PERI1_MAINPLL_DIVOUT1       1
#define IMX_CCM_MUX_PERI1_SYSPLL_DIVOUT0        2
#define IMX_CCM_MUX_PERI1_SYSPLL_DIVOUT1        3
#define IMX_CCM_MUX_PERI2_BASE                  0
#define IMX_CCM_MUX_PERI2_MAINPLL_DIVOUT2       1
#define IMX_CCM_MUX_PERI2_SYSPLL_DIVOUT0        2
#define IMX_CCM_MUX_PERI2_SYSPLL_DIVOUT2        3
#define IMX_CCM_MUX_PERI3_BASE                  0
#define IMX_CCM_MUX_PERI3_MAINPLL_DIVOUT2       1
#define IMX_CCM_MUX_PERI3_MAINPLL_DIVX          2
#define IMX_CCM_MUX_PERI3_SYSPLL_DIVOUT2        3
#define IMX_CCM_MUX_PERI4_BASE                  0
#define IMX_CCM_MUX_PERI4_MAINPLL_DIVOUT0       1
#define IMX_CCM_MUX_PERI4_MAINPLL_DIVX          2
#define IMX_CCM_MUX_PERI4_SYSPLL_DIVOUT2        3
#define IMX_CCM_MUX_PERI5_BASE                  0
#define IMX_CCM_MUX_PERI5_MAINPLL_DIVOUT0       1
#define IMX_CCM_MUX_PERI5_MAINPLL_DIVX          2
#define IMX_CCM_MUX_PERI5_SYSPLL_DIVOUT2        3
#define IMX_CCM_MUX_PERI6_BASE                  0
#define IMX_CCM_MUX_PERI6_MAINPLL_DIVOUT1       1
#define IMX_CCM_MUX_PERI6_MAINPLL_DIVX          2
#define IMX_CCM_MUX_PERI6_SYSPLL_DIVOUT2        3
#define IMX_CCM_MUX_PERI7_LOW                   0
#define IMX_CCM_MUX_PERI7_FRO_192M              1
#define IMX_CCM_MUX_PERI7_MAINPLL_DIVOUT2       2
#define IMX_CCM_MUX_PERI7_SYSPLL_DIVOUT2        3
#define IMX_CCM_MUX_AUDIO_LOW                   0
#define IMX_CCM_MUX_AUDIO_AUDIOPLL_DIVOUT       1
#define IMX_CCM_MUX_AUDIO_VIDEOPLL_DIVOUT       2
#define IMX_CCM_MUX_AUDIO_SYSPLL_DIVOUT2        3
#define IMX_CCM_MUX_VIDEO_BASE                  0
#define IMX_CCM_MUX_VIDEO_AUDIOPLL_DIVOUT       1
#define IMX_CCM_MUX_VIDEO_VIDEOPLL_DIVOUT       2
#define IMX_CCM_MUX_VIDEO_MEDIA_PFDX            3
#define IMX_CCM_MUX_USB1_FRO_48M                0
#define IMX_CCM_MUX_USB1_MAINPLL_DIVOUT1        1
#define IMX_CCM_MUX_USB1_MAINPLL_DIVOUT2        2
#define IMX_CCM_MUX_USB1_SYSPLL_DIVOUT2         3
#define IMX_CCM_MUX_ETH_BASE                    0
#define IMX_CCM_MUX_ETH_MAINPLL_DIV8            1
#define IMX_CCM_MUX_ETH_MAINPLL_DIV20           2
#define IMX_CCM_MUX_ETH_SYSPLL_DIV20            3
#define IMX_CCM_MUX_TEST_TIE_LOW                0
#define IMX_CCM_MUX_TEST_COREPLL_OUT            1
#define IMX_CCM_MUX_TEST_MAINPLL_DIVOUT0        2
#define IMX_CCM_MUX_TEST_SYSPLL_DIVOUT0         3
#define IMX_CCM_MUX_CLKOUT_PERI3                0
#define IMX_CCM_MUX_CLKOUT_PERI5                1
#define IMX_CCM_MUX_CLKOUT_FRO192M              2
#define IMX_CCM_MUX_CLKOUT_MAINPLLDIV10         3
#define IMX_CCM_MUX_MAIN_FRO192M_FRO192M        0
#define IMX_CCM_MUX_MAIN_ULP32K_ULP32K          0
#define IMX_CCM_MUX_CMPT_MAIN                   0
#define IMX_CCM_MUX_CPU_CPU                     0
#define IMX_CCM_MUX_NPU_NPU                     0
#define IMX_CCM_MUX_SYSTICK0_LP1M_CORE          0
#define IMX_CCM_MUX_SYSTICK0_SXOSC              1
#define IMX_CCM_MUX_SYSTICK0_PERI4              2
#define IMX_CCM_MUX_SYSTICK0_MAINPLLDIV10       3
#define IMX_CCM_MUX_SYSTICK1_LP1M_CORE          0
#define IMX_CCM_MUX_SYSTICK1_SXOSC              1
#define IMX_CCM_MUX_SYSTICK1_PERI4              2
#define IMX_CCM_MUX_SYSTICK1_MAINPLLDIV10       3
#define IMX_CCM_MUX_MAIN_MAIN                   0
#define IMX_CCM_MUX_MAIN_TIE_LOW                1
#define IMX_CCM_MUX_XSPI0_MAIN_PERI0_DIV2       0
#define IMX_CCM_MUX_XSPI0_MAINPFDX_DIV2         1
#define IMX_CCM_MUX_XSPI0_SYSPLLDIV4            2
#define IMX_CCM_MUX_XSPI0_SYSPLLDIV5            3
#define IMX_CCM_MUX_XSPI1_MAIN_PERI1_DIV2       0
#define IMX_CCM_MUX_XSPI1_MAINPFDX_DIV2         1
#define IMX_CCM_MUX_XSPI1_SYSPLLDIV4            2
#define IMX_CCM_MUX_XSPI1_SYSPLLDIV5            3
#define IMX_CCM_MUX_I3C0_PERI3                  0
#define IMX_CCM_MUX_I3C0_PERI4                  1
#define IMX_CCM_MUX_I3C0_FRO192M                2
#define IMX_CCM_MUX_I3C0_SXOSC                  3
#define IMX_CCM_MUX_LPI2C0_PERI3                0
#define IMX_CCM_MUX_LPI2C0_PERI4                1
#define IMX_CCM_MUX_LPI2C0_FRO192M              2
#define IMX_CCM_MUX_LPI2C0_SXOSC                3
#define IMX_CCM_MUX_LPI2C1_PERI3                0
#define IMX_CCM_MUX_LPI2C1_PERI4                1
#define IMX_CCM_MUX_LPI2C1_FRO192M              2
#define IMX_CCM_MUX_LPI2C1_SXOSC                3
#define IMX_CCM_MUX_LPSPI0_PERI2                0
#define IMX_CCM_MUX_LPSPI0_PERI4                1
#define IMX_CCM_MUX_LPSPI0_FRO192M              2
#define IMX_CCM_MUX_LPSPI0_MAINDIVX             3
#define IMX_CCM_MUX_LPSPI1_PERI2                0
#define IMX_CCM_MUX_LPSPI1_PERI4                1
#define IMX_CCM_MUX_LPSPI1_FRO192M              2
#define IMX_CCM_MUX_LPSPI1_MAINDIVX             3
#define IMX_CCM_MUX_LPSPI2_PERI2                0
#define IMX_CCM_MUX_LPSPI2_PERI4                1
#define IMX_CCM_MUX_LPSPI2_FRO192M              2
#define IMX_CCM_MUX_LPSPI2_MAINDIVX             3
#define IMX_CCM_MUX_LPSPI3_PERI2                0
#define IMX_CCM_MUX_LPSPI3_PERI4                1
#define IMX_CCM_MUX_LPSPI3_FRO192M              2
#define IMX_CCM_MUX_LPSPI3_MAINDIVX             3
#define IMX_CCM_MUX_LPSPI4_PERI2                0
#define IMX_CCM_MUX_LPSPI4_PERI4                1
#define IMX_CCM_MUX_LPSPI4_FRO192M              2
#define IMX_CCM_MUX_LPSPI4_MAINDIVX             3
#define IMX_CCM_MUX_LPUART0_PERI3               0
#define IMX_CCM_MUX_LPUART0_PERI4               1
#define IMX_CCM_MUX_LPUART0_FRO192M             2
#define IMX_CCM_MUX_LPUART0_SXOSC               3
#define IMX_CCM_MUX_LPUART1_PERI3               0
#define IMX_CCM_MUX_LPUART1_PERI4               1
#define IMX_CCM_MUX_LPUART1_FRO192M             2
#define IMX_CCM_MUX_LPUART1_SXOSC               3
#define IMX_CCM_MUX_LPUART2_PERI3               0
#define IMX_CCM_MUX_LPUART2_PERI4               1
#define IMX_CCM_MUX_LPUART2_FRO192M             2
#define IMX_CCM_MUX_LPUART2_SXOSC               3
#define IMX_CCM_MUX_LPUART3_PERI3               0
#define IMX_CCM_MUX_LPUART3_PERI4               1
#define IMX_CCM_MUX_LPUART3_FRO192M             2
#define IMX_CCM_MUX_LPUART3_SXOSC               3
#define IMX_CCM_MUX_LPUART4_PERI3               0
#define IMX_CCM_MUX_LPUART4_PERI4               1
#define IMX_CCM_MUX_LPUART4_FRO192M             2
#define IMX_CCM_MUX_LPUART4_SXOSC               3
#define IMX_CCM_MUX_LPUART5_PERI3               0
#define IMX_CCM_MUX_LPUART5_PERI4               1
#define IMX_CCM_MUX_LPUART5_FRO192M             2
#define IMX_CCM_MUX_LPUART5_SXOSC               3
#define IMX_CCM_MUX_FLEXCAN0_PERI1              0
#define IMX_CCM_MUX_FLEXCAN0_PERI4              1
#define IMX_CCM_MUX_FLEXCAN0_FRO192M            2
#define IMX_CCM_MUX_FLEXCAN0_SXOSC              3
#define IMX_CCM_MUX_FLEXCAN1_PERI1              0
#define IMX_CCM_MUX_FLEXCAN1_PERI4              1
#define IMX_CCM_MUX_FLEXCAN1_FRO192M            2
#define IMX_CCM_MUX_FLEXCAN1_SXOSC              3
#define IMX_CCM_MUX_FLEXCAN2_PERI1              0
#define IMX_CCM_MUX_FLEXCAN2_PERI4              1
#define IMX_CCM_MUX_FLEXCAN2_FRO192M            2
#define IMX_CCM_MUX_FLEXCAN2_SXOSC              3
#define IMX_CCM_MUX_FLEXCAN_GFCLK_PERI1         0
#define IMX_CCM_MUX_FLEXCAN_GFCLK_PERI4         1
#define IMX_CCM_MUX_FLEXCAN_GFCLK_FRO192M       2
#define IMX_CCM_MUX_FLEXCAN_GFCLK_SXOSC         3
#define IMX_CCM_MUX_QTPM0_PERI3                 0
#define IMX_CCM_MUX_QTPM0_PERI5                 1
#define IMX_CCM_MUX_QTPM0_FRO192M               2
#define IMX_CCM_MUX_QTPM0_SXOSC                 3
#define IMX_CCM_MUX_LPIT0_PERI3                 0
#define IMX_CCM_MUX_LPIT0_PERI5                 1
#define IMX_CCM_MUX_LPIT0_FRO192M               2
#define IMX_CCM_MUX_LPIT0_MAINPLLDIV10          3
#define IMX_CCM_MUX_LPIT1_PERI3                 0
#define IMX_CCM_MUX_LPIT1_PERI5                 1
#define IMX_CCM_MUX_LPIT1_FRO192M               2
#define IMX_CCM_MUX_LPIT1_MAINPLLDIV10          3
#define IMX_CCM_MUX_ADC0_PERI3                  0
#define IMX_CCM_MUX_ADC0_PERI5                  1
#define IMX_CCM_MUX_ADC0_FRO192M                2
#define IMX_CCM_MUX_ADC0_MAINPLLDIV10           3
#define IMX_CCM_MUX_ADC1_PERI3                  0
#define IMX_CCM_MUX_ADC1_PERI5                  1
#define IMX_CCM_MUX_ADC1_FRO192M                2
#define IMX_CCM_MUX_ADC1_MAINPLLDIV10           3
#define IMX_CCM_MUX_SINC0_PERI3                 0
#define IMX_CCM_MUX_SINC0_PERI5                 1
#define IMX_CCM_MUX_SINC0_FRO192M               2
#define IMX_CCM_MUX_SINC0_MAINPLLDIV10          3
#define IMX_CCM_MUX_SINC1_PERI3                 0
#define IMX_CCM_MUX_SINC1_PERI5                 1
#define IMX_CCM_MUX_SINC1_FRO192M               2
#define IMX_CCM_MUX_SINC1_MAINPLLDIV10          3
#define IMX_CCM_MUX_FLEXIO0_PERI0               0
#define IMX_CCM_MUX_FLEXIO0_PERI5               1
#define IMX_CCM_MUX_FLEXIO0_FRO192M             2
#define IMX_CCM_MUX_FLEXIO0_MAINDIVX            3
#define IMX_CCM_MUX_FLEXIO1_PERI0               0
#define IMX_CCM_MUX_FLEXIO1_PERI5               1
#define IMX_CCM_MUX_FLEXIO1_FRO192M             2
#define IMX_CCM_MUX_FLEXIO1_MAINDIVX            3
#define IMX_CCM_MUX_FLEXIO2_PERI0               0
#define IMX_CCM_MUX_FLEXIO2_PERI5               1
#define IMX_CCM_MUX_FLEXIO2_FRO192M             2
#define IMX_CCM_MUX_FLEXIO2_MAINDIVX            3
#define IMX_CCM_MUX_TPIU_PERI3                  0
#define IMX_CCM_MUX_TPIU_SYSPLLDIV4             1
#define IMX_CCM_MUX_TPIU_FRO192M                2
#define IMX_CCM_MUX_TPIU_MAINDIVX               3
#define IMX_CCM_MUX_CSSI_REFCLK_FRO96M          0
#define IMX_CCM_MUX_CSSI_REFCLK_MAINPLLDIV10    1
#define IMX_CCM_MUX_CSSI_REFCLK_TIE_LOW         2
#define IMX_CCM_MUX_OTP_SXOSC                   0
#define IMX_CCM_MUX_OTP_MAINPLLDIV10            1
#define IMX_CCM_MUX_OTP_FRO192M                 2
#define IMX_CCM_MUX_OTP_FRO24M                  3
#define IMX_CCM_MUX_MAIN_CLKOUT_PERI3           0
#define IMX_CCM_MUX_MAIN_CLKOUT_PERI5           1
#define IMX_CCM_MUX_MAIN_CLKOUT_FRO192M         2
#define IMX_CCM_MUX_MAIN_CLKOUT_MAINPLLDIV10    3
#define IMX_CCM_MUX_MAIN_MAIN_FRO192M_FRO192M   0
#define IMX_CCM_MUX_MAIN_MAIN_ULP32K_ULP32K     0
#define IMX_CCM_MUX_WAKE_WAKEBUS                0
#define IMX_CCM_MUX_WAKE_LP12M_WAKE             1
#define IMX_CCM_MUX_WAKE_LP2M_WAKE              2
#define IMX_CCM_MUX_WAKE_SXOSC_SXOSC            0
#define IMX_CCM_MUX_WAKE_LP1M_LP1M_WAKE         0
#define IMX_CCM_MUX_WAKE_LP12M_LP12M_WAKE       0
#define IMX_CCM_MUX_WAKE_ULP32K_ULP32K          0
#define IMX_CCM_MUX_WAKE_LPCLK_LP1M_WAKE        0
#define IMX_CCM_MUX_WAKE_LPCLK_LP12M_WAKE       1
#define IMX_CCM_MUX_WAKE_LPCLK_LP2M_WAKE        2
#define IMX_CCM_MUX_WAKE_I3C0_PERI7             0
#define IMX_CCM_MUX_WAKE_I3C0_FRO24M            1
#define IMX_CCM_MUX_WAKE_I3C0_WAKE_LPCLK        2
#define IMX_CCM_MUX_WAKE_I3C0_SXOSC             3
#define IMX_CCM_MUX_WAKE_LPI2C0_PERI7           0
#define IMX_CCM_MUX_WAKE_LPI2C0_FRO24M          1
#define IMX_CCM_MUX_WAKE_LPI2C0_WAKE_LPCLK      2
#define IMX_CCM_MUX_WAKE_LPI2C0_SXOSC           3
#define IMX_CCM_MUX_WAKE_LPI2C1_PERI7           0
#define IMX_CCM_MUX_WAKE_LPI2C1_FRO24M          1
#define IMX_CCM_MUX_WAKE_LPI2C1_WAKE_LPCLK      2
#define IMX_CCM_MUX_WAKE_LPI2C1_SXOSC           3
#define IMX_CCM_MUX_WAKE_LPSPI0_PERI7           0
#define IMX_CCM_MUX_WAKE_LPSPI0_FRO24M          1
#define IMX_CCM_MUX_WAKE_LPSPI0_WAKE_LPCLK      2
#define IMX_CCM_MUX_WAKE_LPSPI0_SXOSC           3
#define IMX_CCM_MUX_WAKE_LPUART0_PERI7          0
#define IMX_CCM_MUX_WAKE_LPUART0_FRO24M         1
#define IMX_CCM_MUX_WAKE_LPUART0_WAKE_LPCLK     2
#define IMX_CCM_MUX_WAKE_LPUART0_ULP32K         3
#define IMX_CCM_MUX_WAKE_LPUART1_PERI7          0
#define IMX_CCM_MUX_WAKE_LPUART1_FRO24M         1
#define IMX_CCM_MUX_WAKE_LPUART1_WAKE_LPCLK     2
#define IMX_CCM_MUX_WAKE_LPUART1_ULP32K         3
#define IMX_CCM_MUX_DMIC1_APPCLK_PERI7          0
#define IMX_CCM_MUX_DMIC1_APPCLK_AUDIO          1
#define IMX_CCM_MUX_DMIC1_APPCLK_WAKE_LPCLK     2
#define IMX_CCM_MUX_DMIC1_APPCLK_SAIMCLK        3
#define IMX_CCM_MUX_QTPM0_PERI7                 0
#define IMX_CCM_MUX_QTPM0_AUDIO                 1
#define IMX_CCM_MUX_QTPM0_WAKE_LPCLK            2
#define IMX_CCM_MUX_QTPM0_ULP32K                3
#define IMX_CCM_MUX_LPTMR0_ULP32K               0
#define IMX_CCM_MUX_LPTMR0_LP1M_WAKE            1
#define IMX_CCM_MUX_LPTMR0_WAKE_LPCLK           2
#define IMX_CCM_MUX_LPTMR0_SXOSC                3
#define IMX_CCM_MUX_LPTMR1_ULP32K               0
#define IMX_CCM_MUX_LPTMR1_LP1M_WAKE            1
#define IMX_CCM_MUX_LPTMR1_WAKE_LPCLK           2
#define IMX_CCM_MUX_LPTMR1_SXOSC                3
#define IMX_CCM_MUX_SWT0_ULP32K                 0
#define IMX_CCM_MUX_SWT0_LP1M_WAKE              1
#define IMX_CCM_MUX_SWT0_TIE_LOW                2
#define IMX_CCM_MUX_SWT1_ULP32K                 0
#define IMX_CCM_MUX_SWT1_LP1M_WAKE              1
#define IMX_CCM_MUX_SWT1_TIE_LOW                2
#define IMX_CCM_MUX_EWM_ULP32K                  0
#define IMX_CCM_MUX_EWM_LP1M_WAKE               1
#define IMX_CCM_MUX_EWM_TIE_LOW                 2
#define IMX_CCM_MUX_ACMP0_PERI7                 0
#define IMX_CCM_MUX_ACMP0_FRO24M                1
#define IMX_CCM_MUX_ACMP0_WAKE_LPCLK            2
#define IMX_CCM_MUX_ACMP0_SXOSC                 3
#define IMX_CCM_MUX_ACMP1_PERI7                 0
#define IMX_CCM_MUX_ACMP1_FRO24M                1
#define IMX_CCM_MUX_ACMP1_WAKE_LPCLK            2
#define IMX_CCM_MUX_ACMP1_SXOSC                 3
#define IMX_CCM_MUX_ACMP2_PERI7                 0
#define IMX_CCM_MUX_ACMP2_FRO24M                1
#define IMX_CCM_MUX_ACMP2_WAKE_LPCLK            2
#define IMX_CCM_MUX_ACMP2_SXOSC                 3
#define IMX_CCM_MUX_ACMP3_PERI7                 0
#define IMX_CCM_MUX_ACMP3_FRO24M                1
#define IMX_CCM_MUX_ACMP3_WAKE_LPCLK            2
#define IMX_CCM_MUX_ACMP3_SXOSC                 3
#define IMX_CCM_MUX_ACMP0_RRCLK_ULP32K          0
#define IMX_CCM_MUX_ACMP0_RRCLK_FRO24M          1
#define IMX_CCM_MUX_ACMP0_RRCLK_WAKE_LPCLK      2
#define IMX_CCM_MUX_ACMP0_RRCLK_LP1M_WAKE       3
#define IMX_CCM_MUX_ACMP1_RRCLK_ULP32K          0
#define IMX_CCM_MUX_ACMP1_RRCLK_FRO24M          1
#define IMX_CCM_MUX_ACMP1_RRCLK_WAKE_LPCLK      2
#define IMX_CCM_MUX_ACMP1_RRCLK_LP1M_WAKE       3
#define IMX_CCM_MUX_ACMP2_RRCLK_ULP32K          0
#define IMX_CCM_MUX_ACMP2_RRCLK_FRO24M          1
#define IMX_CCM_MUX_ACMP2_RRCLK_WAKE_LPCLK      2
#define IMX_CCM_MUX_ACMP2_RRCLK_LP1M_WAKE       3
#define IMX_CCM_MUX_ACMP3_RRCLK_ULP32K          0
#define IMX_CCM_MUX_ACMP3_RRCLK_FRO24M          1
#define IMX_CCM_MUX_ACMP3_RRCLK_WAKE_LPCLK      2
#define IMX_CCM_MUX_ACMP3_RRCLK_LP1M_WAKE       3
#define IMX_CCM_MUX_COMM_COMMBUS                0
#define IMX_CCM_MUX_COMM_ULP32K_ULP32K          0
#define IMX_CCM_MUX_USDHC0_COMM_PERI1_DIV2      0
#define IMX_CCM_MUX_USDHC0_COMMPFDX_DIV2        1
#define IMX_CCM_MUX_USDHC0_SYSPLLDIV4           2
#define IMX_CCM_MUX_USDHC0_SYSPLLDIV5           3
#define IMX_CCM_MUX_USDHC1_COMM_PERI2_DIV2      0
#define IMX_CCM_MUX_USDHC1_COMMPFDX_DIV2        1
#define IMX_CCM_MUX_USDHC1_SYSPLLDIV4           2
#define IMX_CCM_MUX_USDHC1_SYSPLLDIV5           3
#define IMX_CCM_MUX_XSPIR_PERI1                 0
#define IMX_CCM_MUX_XSPIR_PERI2                 1
#define IMX_CCM_MUX_XSPIR_SYSPLLDIV4            2
#define IMX_CCM_MUX_XSPIR_SYSPLLDIV5            3
#define IMX_CCM_MUX_USB0_PHYCLK_SXOSC           0
#define IMX_CCM_MUX_USB0_FRO48M_FRO48M          0
#define IMX_CCM_MUX_USB1_USB1                   0
#define IMX_CCM_MUX_USB1_USBPLL_OUT             1
#define IMX_CCM_MUX_USB1_USBPLL_48M             2
#define IMX_CCM_MUX_USB1_FRO48M                 3
#define IMX_CCM_MUX_USB0_WAKECLK_ULP32K         0
#define IMX_CCM_MUX_USB0_WAKECLK_LP1M_CORE      1
#define IMX_CCM_MUX_USB0_WAKECLK_SXOSC          2
#define IMX_CCM_MUX_USB0_WAKECLK_TIE_LOW        3
#define IMX_CCM_MUX_ETH0_TRXCLK_COMMBUS         0
#define IMX_CCM_MUX_ETH0_TRXCLK_ETH             1
#define IMX_CCM_MUX_ETH0_TRXCLK_SYSPLLDIV4      2
#define IMX_CCM_MUX_ETH0_TRXCLK_MAINPLLDIV8     3
#define IMX_CCM_MUX_ETH0_TIMERCLK_COMMBUS       0
#define IMX_CCM_MUX_ETH0_TIMERCLK_ETH           1
#define IMX_CCM_MUX_ETH0_TIMERCLK_SXOSC         2
#define IMX_CCM_MUX_ETH0_TIMERCLK_MAINPLLDIV8   3
#define IMX_CCM_MUX_ETH1_TRXCLK_COMMBUS         0
#define IMX_CCM_MUX_ETH1_TRXCLK_ETH             1
#define IMX_CCM_MUX_ETH1_TRXCLK_SYSPLLDIV4      2
#define IMX_CCM_MUX_ETH1_TRXCLK_MAINPLLDIV8     3
#define IMX_CCM_MUX_ETH1_TIMERCLK_COMMBUS       0
#define IMX_CCM_MUX_ETH1_TIMERCLK_ETH           1
#define IMX_CCM_MUX_ETH1_TIMERCLK_SXOSC         2
#define IMX_CCM_MUX_ETH1_TIMERCLK_MAINPLLDIV8   3
#define IMX_CCM_MUX_ETH_REFCLK_COMMBUS          0
#define IMX_CCM_MUX_ETH_REFCLK_ETH              1
#define IMX_CCM_MUX_ETH_REFCLK_SXOSC            2
#define IMX_CCM_MUX_ETH_REFCLK_MAINPLLDIV8      3
#define IMX_CCM_MUX_XENO0_LIWCLK_COMMBUS        0
#define IMX_CCM_MUX_XENO0_LIWCLK_MAINPLLDIV10   1
#define IMX_CCM_MUX_XENO0_LIWCLK_SYSPLLDIV4     2
#define IMX_CCM_MUX_XENO0_LIWCLK_SYSPLLDIV5     3
#define IMX_CCM_MUX_XENO1_LIWCLK_COMMBUS        0
#define IMX_CCM_MUX_XENO1_LIWCLK_MAINPLLDIV10   1
#define IMX_CCM_MUX_XENO1_LIWCLK_SYSPLLDIV4     2
#define IMX_CCM_MUX_XENO1_LIWCLK_SYSPLLDIV5     3
#define IMX_CCM_MUX_DLL_REFCLK_MAINPLLDIV10     0
#define IMX_CCM_MUX_AUDIO_CLK_AUDIOBUS          0
#define IMX_CCM_MUX_DMIC0_APPCLK_PERI6          0
#define IMX_CCM_MUX_DMIC0_APPCLK_AUDIOPLL       1
#define IMX_CCM_MUX_DMIC0_APPCLK_AUDIO          2
#define IMX_CCM_MUX_DMIC0_APPCLK_SAIMCLK        3
#define IMX_CCM_MUX_SAI0_MCLK0_PERI6            0
#define IMX_CCM_MUX_SAI0_MCLK0_AUDIOPLL         1
#define IMX_CCM_MUX_SAI0_MCLK0_AUDIO            2
#define IMX_CCM_MUX_SAI0_MCLK0_SAIMCLK0         3
#define IMX_CCM_MUX_SAI0_MCLK1_PERI6            0
#define IMX_CCM_MUX_SAI0_MCLK1_AUDIOPLL         1
#define IMX_CCM_MUX_SAI0_MCLK1_AUDIO            2
#define IMX_CCM_MUX_SAI0_MCLK1_SAIMCLK          3
#define IMX_CCM_MUX_SAI1_MCLK0_PERI6            0
#define IMX_CCM_MUX_SAI1_MCLK0_AUDIOPLL         1
#define IMX_CCM_MUX_SAI1_MCLK0_AUDIO            2
#define IMX_CCM_MUX_SAI1_MCLK0_SAIMCLK1         3
#define IMX_CCM_MUX_SAI1_MCLK1_PERI6            0
#define IMX_CCM_MUX_SAI1_MCLK1_AUDIOPLL         1
#define IMX_CCM_MUX_SAI1_MCLK1_AUDIO            2
#define IMX_CCM_MUX_SAI1_MCLK1_SAIMCLK          3
#define IMX_CCM_MUX_SAI2_MCLK0_PERI6            0
#define IMX_CCM_MUX_SAI2_MCLK0_AUDIOPLL         1
#define IMX_CCM_MUX_SAI2_MCLK0_AUDIO            2
#define IMX_CCM_MUX_SAI2_MCLK0_SAIMCLK2         3
#define IMX_CCM_MUX_SAI2_MCLK1_PERI6            0
#define IMX_CCM_MUX_SAI2_MCLK1_AUDIOPLL         1
#define IMX_CCM_MUX_SAI2_MCLK1_AUDIO            2
#define IMX_CCM_MUX_SAI2_MCLK1_SAIMCLK          3
#define IMX_CCM_MUX_SPDIF_TXCLK_PERI6           0
#define IMX_CCM_MUX_SPDIF_TXCLK_AUDIOPLL        1
#define IMX_CCM_MUX_SPDIF_TXCLK_AUDIO           2
#define IMX_CCM_MUX_SPDIF_TXCLK_SAIMCLK         3
#define IMX_CCM_MUX_SPDIF_CDRCLK_PERI6          0
#define IMX_CCM_MUX_SPDIF_CDRCLK_AUDIOPLL       1
#define IMX_CCM_MUX_SPDIF_CDRCLK_MAINPLLDIV10   2
#define IMX_CCM_MUX_SPDIF_CDRCLK_AUDIOBUS       3
#define IMX_CCM_MUX_ASRC_PERI6                  0
#define IMX_CCM_MUX_ASRC_AUDIOPLL               1
#define IMX_CCM_MUX_ASRC_MAINPLLDIV10           2
#define IMX_CCM_MUX_ASRC_AUDIOBUS               3
#define IMX_CCM_MUX_MEDIA_MEDIABUS              0
#define IMX_CCM_MUX_MEDIAPLL_MAINPLLDIV10       0
#define IMX_CCM_MUX_MEDIAPLL_MIPIPLL_DIV8       1
#define IMX_CCM_MUX_MIPICSI_ESCCLK_PERI5        0
#define IMX_CCM_MUX_MIPICSI_ESCCLK_VIDEOPLL     1
#define IMX_CCM_MUX_MIPICSI_ESCCLK_VIDEO        2
#define IMX_CCM_MUX_MIPICSI_ESCCLK_MEDIAPLL     3
#define IMX_CCM_MUX_MIPICSI_PERI5               0
#define IMX_CCM_MUX_MIPICSI_VIDEOPLL            1
#define IMX_CCM_MUX_MIPICSI_VIDEO               2
#define IMX_CCM_MUX_MIPICSI_MEDIAPLL            3
#define IMX_CCM_MUX_MIPIDSI_ESCCLK_PERI5        0
#define IMX_CCM_MUX_MIPIDSI_ESCCLK_VIDEOPLL     1
#define IMX_CCM_MUX_MIPIDSI_ESCCLK_VIDEO        2
#define IMX_CCM_MUX_MIPIDSI_ESCCLK_MEDIAPLL     3
#define IMX_CCM_MUX_MIPIDSI_REFCLK_SXOSC        0
#define IMX_CCM_MUX_MIPIDSI_PERI5               0
#define IMX_CCM_MUX_MIPIDSI_VIDEOPLL            1
#define IMX_CCM_MUX_MIPIDSI_VIDEO               2
#define IMX_CCM_MUX_MIPIDSI_MEDIAPLL            3
#define IMX_CCM_MUX_REFORMAT_PERI5              0
#define IMX_CCM_MUX_REFORMAT_VIDEOPLL           1
#define IMX_CCM_MUX_REFORMAT_VIDEO              2
#define IMX_CCM_MUX_REFORMAT_MEDIAPLL           3
#define IMX_CCM_MUX_DCPIXEL_PERI5               0
#define IMX_CCM_MUX_DCPIXEL_VIDEOPLL            1
#define IMX_CCM_MUX_DCPIXEL_VIDEO               2
#define IMX_CCM_MUX_DCPIXEL_MEDIAPLL            3
#define IMX_CCM_MUX_CSI_MCLKOUT_PERI5           0
#define IMX_CCM_MUX_CSI_MCLKOUT_SXOSC           1
#define IMX_CCM_MUX_CSI_MCLKOUT_VIDEO           2
#define IMX_CCM_MUX_CSI_MCLKOUT_MEDIAPLL        3

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_IMX_CCM_REV3_RT266X_H_ */
