/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC5536JBD100/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on LPC55S36JBD100-pinctrl.h with this part's differences applied
 * below (25 removed, 2 changed,
 * 4 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: a29f6de5ce1b936c
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC5536JBD100_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC5536JBD100_WRAPPER_

#include "LPC55S36JBD100-pinctrl.h"

/* Signals not present on this part */
#undef QSPI_CS0_DIS_PIO0_28
#undef QSPI_CS0_DIS_PIO1_15
#undef QSPI_CS0_PIO0_7
#undef QSPI_CS0_PIO1_30
#undef QSPI_CS1_DIS_PIO1_16
#undef QSPI_CS1_DIS_PIO1_26
#undef QSPI_DIN0_PIO1_14
#undef QSPI_DIN0_PIO1_19
#undef QSPI_DIN1_PIO0_18
#undef QSPI_DIN2_PIO1_13
#undef QSPI_DIN3_PIO1_18
#undef QSPI_DIN3_PIO1_22
#undef QSPI_SCLK_PIO0_17
#undef QSPI_SCLK_PIO1_12
#undef SPI_CS0_DIS_PIO0_24
#undef SPI_CS0_PIO0_20
#undef SPI_CS1_DIS_PIO0_27
#undef SPI_CS1_DIS_PIO1_28
#undef SPI_DIN_PIO0_29
#undef SPI_DIN_PIO1_4
#undef SPI_SCLK_PIO1_11
#undef SPI_SCLK_PIO1_25
#undef SYSCON_FREQMEA_PIO0_11
#undef SYSCON_FREQMEA_PIO1_4
#undef SYSCON_FREQMEB_PIO0_12

/* Signals with different mux data on this part */
#undef PWM0_B2_PIO1_1
#define PWM0_B2_PIO1_1 IOCON_MUX(33, IOCON_TYPE_D, 11)
#undef RTC_ALARMOUT_PIO1_1
#define RTC_ALARMOUT_PIO1_1 IOCON_MUX(33, IOCON_TYPE_D, 10)

/* Signals specific to this part */
#define FREQME_FREQMEA_PIO0_11 IOCON_MUX(11, IOCON_TYPE_D, 3)
#define FREQME_FREQMEA_PIO1_4 IOCON_MUX(36, IOCON_TYPE_D, 5)
#define FREQME_FREQMEB_PIO0_12 IOCON_MUX(12, IOCON_TYPE_D, 3)
#define I3C0_SCL_PIO0_31 IOCON_MUX(31, IOCON_TYPE_A, 15)

#endif /* _ZEPHYR_DTS_BINDING_LPC5536JBD100_WRAPPER_ */
