/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC5534JHI48/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC5536JHI48-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 24b504adb2c13ad3
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC5534JHI48_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC5534JHI48_WRAPPER_

#include "LPC5536JHI48-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC5534JHI48_WRAPPER_ */
