/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC55S14JBD100/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC5516JBD100-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 1cc398690fc2f0a7
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC55S14JBD100_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC55S14JBD100_WRAPPER_

#include "LPC5516JBD100-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC55S14JBD100_WRAPPER_ */
