/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC5512JBD100/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on LPC55S69JBD100-pinctrl.h with this part's differences applied
 * below (47 removed, 0 changed,
 * 7 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: d0fef7b5a4939490
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC5512JBD100_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC5512JBD100_WRAPPER_

#include "LPC55S69JBD100-pinctrl.h"

/* Signals not present on this part */
#undef SD0_CARD_DET_N_PIO0_17
#undef SD0_CARD_DET_N_PIO1_13
#undef SD0_CARD_INT_N_PIO0_17
#undef SD0_CLK_PIO0_7
#undef SD0_CLK_PIO1_8
#undef SD0_CMD_PIO0_8
#undef SD0_CMD_PIO1_16
#undef SD0_CMD_PIO1_22
#undef SD0_POW_EN_PIO0_12
#undef SD0_POW_EN_PIO0_9
#undef SD0_WR_PRT_PIO0_15
#undef SD0_WR_PRT_PIO0_18
#undef SD1_BACKEND_PWR_PIO0_12
#undef SD1_CARD_DET_N_PIO1_17
#undef SD1_CARD_INT_N_PIO0_0
#undef SD1_CARD_INT_N_PIO1_17
#undef SD1_CLK_PIO0_1
#undef SD1_CLK_PIO1_31
#undef SD1_CMD_PIO0_28
#undef SD1_CMD_PIO1_14
#undef SD1_POW_EN_PIO1_18
#undef SDIF_SD0_D0_PIO0_24
#undef SDIF_SD0_D0_PIO1_4
#undef SDIF_SD0_D1_PIO0_25
#undef SDIF_SD0_D1_PIO1_7
#undef SDIF_SD0_D2_PIO0_31
#undef SDIF_SD0_D2_PIO1_5
#undef SDIF_SD0_D3_PIO1_0
#undef SDIF_SD0_D3_PIO1_6
#undef SDIF_SD0_D4_PIO1_27
#undef SDIF_SD0_D5_PIO1_28
#undef SDIF_SD0_D6_PIO1_29
#undef SDIF_SD0_D7_PIO1_30
#undef SDIF_SD1_D0_PIO0_22
#undef SDIF_SD1_D0_PIO1_25
#undef SDIF_SD1_D1_PIO0_23
#undef SDIF_SD1_D1_PIO1_24
#undef SDIF_SD1_D2_PIO0_29
#undef SDIF_SD1_D2_PIO1_15
#undef SDIF_SD1_D3_PIO0_30
#undef SDIF_SD1_D3_PIO1_23
#undef USB1_FRAME_PIO1_29
#undef USB1_LEDN_PIO1_30
#undef USB1_OVERCURRENTN_PIO1_1
#undef USB1_OVERCURRENTN_PIO1_30
#undef USB1_PORTPWRN_PIO1_2
#undef USB1_PORTPWRN_PIO1_29

/* Signals specific to this part */
#define CAN0_RD_PIO0_4 IOCON_MUX(4, IOCON_TYPE_D, 1)
#define CAN0_RD_PIO1_22 IOCON_MUX(54, IOCON_TYPE_D, 9)
#define CAN0_RD_PIO1_3 IOCON_MUX(35, IOCON_TYPE_D, 1)
#define CAN0_TD_PIO0_5 IOCON_MUX(5, IOCON_TYPE_D, 1)
#define CAN0_TD_PIO1_2 IOCON_MUX(34, IOCON_TYPE_D, 1)
#define CAN0_TD_PIO1_27 IOCON_MUX(59, IOCON_TYPE_D, 9)
#define HS_SPI_SSEL3_PIO0_21 IOCON_MUX(21, IOCON_TYPE_D, 8)

#endif /* _ZEPHYR_DTS_BINDING_LPC5512JBD100_WRAPPER_ */
