/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC5528JEV59/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC55S69JEV59-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 88c3e9c0b4648589
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC5528JEV59_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC5528JEV59_WRAPPER_

#include "LPC55S69JEV59-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC5528JEV59_WRAPPER_ */
