/*--------------------------------------------------------------------------*/
/* Copyright 2021-2026 NXP                                                  */
/*                                                                          */
/* SPDX-License-Identifier: BSD-3-Clause                                    */
/*                                                                          */
/* Redistribution and use in source and binary forms, with or without       */
/* modification, are permitted provided that the following conditions are   */
/* met:                                                                     */
/*                                                                          */
/* 1. Redistributions of source code must retain the above copyright        */
/*    notice, this list of conditions and the following disclaimer.         */
/*                                                                          */
/* 2. Redistributions in binary form must reproduce the above copyright     */
/*    notice, this list of conditions and the following disclaimer in the   */
/*    documentation and/or other materials provided with the distribution.  */
/*                                                                          */
/* 3. Neither the name of the copyright holder nor the names of its         */
/*    contributors may be used to endorse or promote products derived from  */
/*    this software without specific prior written permission.              */
/*                                                                          */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  */
/* IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED    */
/* TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A          */
/* PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT       */
/* HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,   */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR   */
/* PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF   */
/* LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING     */
/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS       */
/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.             */
/*--------------------------------------------------------------------------*/

#include <mcuxClCore_Platform.h>
#include <mcuxClCore_Macros.h>
#include <mcuxCsslAnalysis.h>

#include <mcuxClHashModes_Constants.h> // hash output sizes
#include <internal/mcuxClHashModes_Internal_Memory.h>
#include <internal/mcuxClRandomModes_Internal_SizeDefinitions.h>
#include <internal/mcuxClKey_Types_Internal.h>

#include <mcuxClEcc_Types.h>
#include <internal/mcuxClPkc_Internal_Types.h>
#include <internal/mcuxClEcc_Internal.h>

#include <internal/mcuxClEcc_Internal_MemoryConsumption.h>
#include <internal/mcuxClSignature_Internal.h>

#include <internal/mcuxClEcc_ECDSA_Internal.h>

#ifdef MCUXCL_FEATURE_ECC_EDDSA
#include <internal/mcuxClEcc_EdDSA_Internal.h>
#include <internal/mcuxClEcc_EdDSA_Internal_Hash.h>
#include <internal/mcuxClHash_Internal.h>
#include <internal/mcuxClEcc_TwEd_Internal.h>
#endif /* MCUXCL_FEATURE_ECC_EDDSA */

#include <internal/mcuxClEcc_Weier_Internal.h>

#include <internal/mcuxClEcc_Mont_Internal_PkcWaLayout.h>

#include <internal/mcuxClEcc_TwEd_Internal_PkcWaLayout.h>


MCUX_CSSL_ANALYSIS_START_PATTERN_DESCRIPTIVE_IDENTIFIER()
MCUX_CSSL_ANALYSIS_START_PATTERN_OBJ_SIZES()
volatile uint8_t mcuxClEcc_GenerateKeyPair_WaCPU_SIZE     [SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_GENERATEKEYPAIR_NO_OF_BUFFERS, ECC_GENERATEKEYPAIR_NO_OF_VIRTUALS) + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(MCUXCLRANDOMMODES_CPUWA_MAXSIZE)];
volatile uint8_t mcuxClEcc_GenerateSignature_WaCPU_SIZE   [SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_GENERATESIGNATURE_NO_OF_BUFFERS, ECC_GENERATESIGNATURE_NO_OF_VIRTUALS) + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(MCUXCLRANDOMMODES_CPUWA_MAXSIZE)];
volatile uint8_t mcuxClEcc_VerifySignature_WaCPU_SIZE     [SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_VERIFYSIGNATURE_NO_OF_BUFFERS, ECC_VERIFYSIGNATURE_NO_OF_VIRTUALS) + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(MCUXCLRANDOMMODES_CPUWA_MAXSIZE)];
volatile uint8_t mcuxClEcc_KeyAgreement_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_KEYAGREEMENT_NO_OF_BUFFERS, ECC_KEYAGREEMENT_NO_OF_VIRTUALS) + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(MCUXCLRANDOMMODES_CPUWA_MAXSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_GenerateDomainParams_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS, ECC_GENERATEDOMAINPARAMS_NO_OF_VIRTUALS)];
volatile uint8_t mcuxClEcc_WeierECC_DecodePoint_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_DECODEPOINT_NO_OF_BUFFERS, ECC_DECODEPOINT_NO_OF_VIRTUALS)];

#ifdef MCUXCL_FEATURE_ECC_ARITHMETICOPERATION
#ifdef MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_SCALARMULT
volatile uint8_t mcuxClEcc_ArithmeticOperation_ScalarMult_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_VIRTUALS)];
#endif /* MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_SCALARMULT */

#ifdef MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_SECURESCALARMULT
volatile uint8_t mcuxClEcc_ArithmeticOperation_SecureScalarMult_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_VIRTUALS)];
#endif /* MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_SECURESCALARMULT */

#ifdef MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_POINTADD
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointAdd_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTADD_NO_OF_VIRTUALS)];
#endif /* MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_POINTADD */

#ifdef MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_POINTSUB
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointSub_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_VIRTUALS)];
#endif /* MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_POINTSUB */
#endif /* MCUXCL_FEATURE_ECC_ARITHMETICOPERATION */

volatile uint8_t mcuxClEcc_WeierECC_PrivateKeyValidation_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_VIRTUALS)];
volatile uint8_t mcuxClEcc_WeierECC_PublicKeyValidation_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_VIRTUALS)];
volatile uint8_t mcuxClEcc_PKC_wordsize[MCUXCLPKC_WORDSIZE];

volatile uint8_t mcuxClEcc_GenerateKeyPair_WaPKC_NoOfBuffers   [ECC_GENERATEKEYPAIR_NO_OF_BUFFERS];
volatile uint8_t mcuxClEcc_GenerateSignature_WaPKC_NoOfBuffers   [ECC_GENERATESIGNATURE_NO_OF_BUFFERS];
volatile uint8_t mcuxClEcc_VerifySignature_WaPKC_NoOfBuffers     [ECC_VERIFYSIGNATURE_NO_OF_BUFFERS];
volatile uint8_t mcuxClEcc_KeyAgreement_WaPKC_NoOfBuffers[ECC_KEYAGREEMENT_NO_OF_BUFFERS];
volatile uint8_t mcuxClEcc_WeierECC_GenerateDomainParams_WaPKC_NoOfBuffers[ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS];
volatile uint8_t mcuxClEcc_WeierECC_DecodePoint_WaPKC_NoOfBuffers[ECC_DECODEPOINT_NO_OF_BUFFERS];

volatile uint8_t mcuxClEcc_WeierECC_CustomDomainParamsSize_Fixed   [MCUXCLECC_CUSTOMPARAMS_SIZE_FIXED];
volatile uint8_t mcuxClEcc_WeierECC_CustomDomainParamsSize_NoOfPLen[MCUXCLECC_CUSTOMPARAMS_SIZE_NO_OF_PLEN];
volatile uint8_t mcuxClEcc_WeierECC_CustomDomainParamsSize_NoOfNLen[MCUXCLECC_CUSTOMPARAMS_SIZE_NO_OF_NLEN];

volatile uint8_t mcuxClEcc_GenerateKeyPair_WaPKC_Size_Uptrt [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEKEYPAIR_NO_OF_BUFFERS, ECC_GENERATEKEYPAIR_NO_OF_VIRTUALS)];
volatile uint8_t mcuxClEcc_GenerateKeyPair_WaPKC_Size_128   [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEKEYPAIR_NO_OF_BUFFERS, ECC_GENERATEKEYPAIR_NO_OF_VIRTUALS) + (ECC_GENERATEKEYPAIR_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_GenerateKeyPair_WaPKC_Size_256   [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEKEYPAIR_NO_OF_BUFFERS, ECC_GENERATEKEYPAIR_NO_OF_VIRTUALS) + (ECC_GENERATEKEYPAIR_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_GenerateKeyPair_WaPKC_Size_384   [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEKEYPAIR_NO_OF_BUFFERS, ECC_GENERATEKEYPAIR_NO_OF_VIRTUALS) + (ECC_GENERATEKEYPAIR_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_GenerateKeyPair_WaPKC_Size_512   [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEKEYPAIR_NO_OF_BUFFERS, ECC_GENERATEKEYPAIR_NO_OF_VIRTUALS) + (ECC_GENERATEKEYPAIR_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_GenerateKeyPair_WaPKC_Size_640   [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEKEYPAIR_NO_OF_BUFFERS, ECC_GENERATEKEYPAIR_NO_OF_VIRTUALS) + (ECC_GENERATEKEYPAIR_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];


volatile uint8_t mcuxClEcc_GenerateSignature_WaPKC_Size_Uptrt [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATESIGNATURE_NO_OF_BUFFERS, ECC_GENERATESIGNATURE_NO_OF_VIRTUALS)];
volatile uint8_t mcuxClEcc_GenerateSignature_WaPKC_Size_128   [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATESIGNATURE_NO_OF_BUFFERS, ECC_GENERATESIGNATURE_NO_OF_VIRTUALS) + (ECC_GENERATESIGNATURE_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_GenerateSignature_WaPKC_Size_256   [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATESIGNATURE_NO_OF_BUFFERS, ECC_GENERATESIGNATURE_NO_OF_VIRTUALS) + (ECC_GENERATESIGNATURE_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_GenerateSignature_WaPKC_Size_384   [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATESIGNATURE_NO_OF_BUFFERS, ECC_GENERATESIGNATURE_NO_OF_VIRTUALS) + (ECC_GENERATESIGNATURE_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_GenerateSignature_WaPKC_Size_512   [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATESIGNATURE_NO_OF_BUFFERS, ECC_GENERATESIGNATURE_NO_OF_VIRTUALS) + (ECC_GENERATESIGNATURE_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_GenerateSignature_WaPKC_Size_640   [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATESIGNATURE_NO_OF_BUFFERS, ECC_GENERATESIGNATURE_NO_OF_VIRTUALS) + (ECC_GENERATESIGNATURE_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];

volatile uint8_t mcuxClEcc_VerifySignature_WaPKC_Size_Uptrt [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_VERIFYSIGNATURE_NO_OF_BUFFERS, ECC_VERIFYSIGNATURE_NO_OF_VIRTUALS)];
volatile uint8_t mcuxClEcc_VerifySignature_WaPKC_Size_128  [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_VERIFYSIGNATURE_NO_OF_BUFFERS, ECC_VERIFYSIGNATURE_NO_OF_VIRTUALS) + (ECC_VERIFYSIGNATURE_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_VerifySignature_WaPKC_Size_256  [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_VERIFYSIGNATURE_NO_OF_BUFFERS, ECC_VERIFYSIGNATURE_NO_OF_VIRTUALS) + (ECC_VERIFYSIGNATURE_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_VerifySignature_WaPKC_Size_384  [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_VERIFYSIGNATURE_NO_OF_BUFFERS, ECC_VERIFYSIGNATURE_NO_OF_VIRTUALS) + (ECC_VERIFYSIGNATURE_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_VerifySignature_WaPKC_Size_512  [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_VERIFYSIGNATURE_NO_OF_BUFFERS, ECC_VERIFYSIGNATURE_NO_OF_VIRTUALS) + (ECC_VERIFYSIGNATURE_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_VerifySignature_WaPKC_Size_640  [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_VERIFYSIGNATURE_NO_OF_BUFFERS, ECC_VERIFYSIGNATURE_NO_OF_VIRTUALS) + (ECC_VERIFYSIGNATURE_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];

/* ECDSA signature protocol descriptor size */
volatile uint8_t mcuxClEcc_ECDSA_SignatureProtocolDescriptor_SIZE[MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(sizeof(mcuxClEcc_ECDSA_SignatureProtocolDescriptor_t))];

volatile uint8_t mcuxClKey_Agreement_ECDH_WaPKC_Size_Uptrt [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_KEYAGREEMENT_NO_OF_BUFFERS, ECC_KEYAGREEMENT_NO_OF_VIRTUALS)];
volatile uint8_t mcuxClKey_Agreement_ECDH_WaPKC_Size_128 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_KEYAGREEMENT_NO_OF_BUFFERS, ECC_KEYAGREEMENT_NO_OF_VIRTUALS) + (ECC_KEYAGREEMENT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClKey_Agreement_ECDH_WaPKC_Size_256 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_KEYAGREEMENT_NO_OF_BUFFERS, ECC_KEYAGREEMENT_NO_OF_VIRTUALS) + (ECC_KEYAGREEMENT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClKey_Agreement_ECDH_WaPKC_Size_384 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_KEYAGREEMENT_NO_OF_BUFFERS, ECC_KEYAGREEMENT_NO_OF_VIRTUALS) + (ECC_KEYAGREEMENT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClKey_Agreement_ECDH_WaPKC_Size_512 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_KEYAGREEMENT_NO_OF_BUFFERS, ECC_KEYAGREEMENT_NO_OF_VIRTUALS) + (ECC_KEYAGREEMENT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClKey_Agreement_ECDH_WaPKC_Size_640 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_KEYAGREEMENT_NO_OF_BUFFERS, ECC_KEYAGREEMENT_NO_OF_VIRTUALS) + (ECC_KEYAGREEMENT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];

volatile uint8_t mcuxClEcc_Weierecc_GenerateDomainParams_WaPKC_Size_Uptrt [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS, ECC_GENERATEDOMAINPARAMS_NO_OF_VIRTUALS)];
volatile uint8_t mcuxClEcc_Weierecc_GenerateDomainParams_WaPKC_Size_128 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS, ECC_GENERATEDOMAINPARAMS_NO_OF_VIRTUALS) + (ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_Weierecc_GenerateDomainParams_WaPKC_Size_256 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS, ECC_GENERATEDOMAINPARAMS_NO_OF_VIRTUALS) + (ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_Weierecc_GenerateDomainParams_WaPKC_Size_384 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS, ECC_GENERATEDOMAINPARAMS_NO_OF_VIRTUALS) + (ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_Weierecc_GenerateDomainParams_WaPKC_Size_512 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS, ECC_GENERATEDOMAINPARAMS_NO_OF_VIRTUALS) + (ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_Weierecc_GenerateDomainParams_WaPKC_Size_640 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS, ECC_GENERATEDOMAINPARAMS_NO_OF_VIRTUALS) + (ECC_GENERATEDOMAINPARAMS_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];

volatile uint8_t mcuxClEcc_WeierECC_DecodePoint_WaPKC_Size_128 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_DECODEPOINT_NO_OF_BUFFERS, ECC_DECODEPOINT_NO_OF_VIRTUALS) + (ECC_DECODEPOINT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_DecodePoint_WaPKC_Size_256 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_DECODEPOINT_NO_OF_BUFFERS, ECC_DECODEPOINT_NO_OF_VIRTUALS) + (ECC_DECODEPOINT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_DecodePoint_WaPKC_Size_384 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_DECODEPOINT_NO_OF_BUFFERS, ECC_DECODEPOINT_NO_OF_VIRTUALS) + (ECC_DECODEPOINT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_DecodePoint_WaPKC_Size_512 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_DECODEPOINT_NO_OF_BUFFERS, ECC_DECODEPOINT_NO_OF_VIRTUALS) + (ECC_DECODEPOINT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_DecodePoint_WaPKC_Size_640 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_DECODEPOINT_NO_OF_BUFFERS, ECC_DECODEPOINT_NO_OF_VIRTUALS) + (ECC_DECODEPOINT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];

#ifdef MCUXCL_FEATURE_ECC_ARITHMETICOPERATION
#ifdef MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_SCALARMULT
volatile uint8_t mcuxClEcc_ArithmeticOperation_ScalarMult_WaPKC_Size_128 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_ScalarMult_WaPKC_Size_256 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_ScalarMult_WaPKC_Size_384 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_ScalarMult_WaPKC_Size_512 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_ScalarMult_WaPKC_Size_640 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_SCALARMULT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];
#endif /* MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_SCALARMULT */

#ifdef MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_SECURESCALARMULT
volatile uint8_t mcuxClEcc_ArithmeticOperation_SecureScalarMult_WaPKC_Size_128 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_SecureScalarMult_WaPKC_Size_256 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_SecureScalarMult_WaPKC_Size_384 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_SecureScalarMult_WaPKC_Size_512 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_SecureScalarMult_WaPKC_Size_640 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_SECURESCALARMULT_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];
#endif /* MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_SECURESCALARMULT */

#ifdef MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_POINTADD
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointAdd_WaPKC_Size_128 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTADD_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointAdd_WaPKC_Size_256 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTADD_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointAdd_WaPKC_Size_384 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTADD_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointAdd_WaPKC_Size_512 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTADD_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointAdd_WaPKC_Size_640 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTADD_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_POINTADD_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];
#endif /* MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_POINTADD */

#ifdef MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_POINTSUB
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointSub_WaPKC_Size_128 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointSub_WaPKC_Size_256 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointSub_WaPKC_Size_384 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointSub_WaPKC_Size_512 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_ArithmeticOperation_PointSub_WaPKC_Size_640 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS, ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_VIRTUALS) + (ECC_ARITHMETICOPERATION_POINTSUB_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];
#endif /* MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_POINTSUB */
#endif /* MCUXCL_FEATURE_ECC_ARITHMETICOPERATION */

volatile uint8_t mcuxClEcc_WeierECC_PrivateKeyValidation_WaPKC_Size_128 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_VIRTUALS) + (ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_PrivateKeyValidation_WaPKC_Size_256 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_VIRTUALS) + (ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_PrivateKeyValidation_WaPKC_Size_384 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_VIRTUALS) + (ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_PrivateKeyValidation_WaPKC_Size_512 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_VIRTUALS) + (ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_PrivateKeyValidation_WaPKC_Size_640 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_VIRTUALS) + (ECC_WEIERECC_PRIVATEKEYVALIDATION_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];

volatile uint8_t mcuxClEcc_WeierECC_PublicKeyValidation_WaPKC_Size_128 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_VIRTUALS) + (ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(16) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_PublicKeyValidation_WaPKC_Size_256 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_VIRTUALS) + (ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(32) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_PublicKeyValidation_WaPKC_Size_384 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_VIRTUALS) + (ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(48) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_PublicKeyValidation_WaPKC_Size_512 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_VIRTUALS) + (ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(64) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_WeierECC_PublicKeyValidation_WaPKC_Size_640 [MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS, ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_VIRTUALS) + (ECC_WEIERECC_PUBLICKEYVALIDATION_NO_OF_BUFFERS) * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(80) + MCUXCLPKC_WORDSIZE)];

MCUX_CSSL_ANALYSIS_STOP_PATTERN_OBJ_SIZES()

#ifdef MCUXCL_FEATURE_ECC_MONTDH

MCUX_CSSL_ANALYSIS_START_PATTERN_OBJ_SIZES()
#ifdef MCUXCL_FEATURE_ECC_CURVE25519
volatile uint8_t mcuxClEcc_MontDH_GenerateKeyPair_Curve25519_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_MONTDH_NO_OF_BUFFERS, ECC_MONTDH_NO_OF_VIRTUALS) + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(MCUXCLRANDOMMODES_CPUWA_MAXSIZE)];
volatile uint8_t mcuxClEcc_MontDH_KeyAgreement_Curve25519_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_MONTDH_NO_OF_BUFFERS, ECC_MONTDH_NO_OF_VIRTUALS)];
volatile uint8_t mcuxClEcc_MontDH_GenerateKeyPair_Curve25519_WaPKC_SIZE[MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_MONTDH_NO_OF_BUFFERS, ECC_MONTDH_NO_OF_VIRTUALS) + ECC_MONTDH_NO_OF_BUFFERS * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(MCUXCLECC_MONTDH_CURVE25519_SIZE_PRIMEP) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_MontDH_KeyAgreement_Curve25519_WaPKC_SIZE[MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_MONTDH_NO_OF_BUFFERS, ECC_MONTDH_NO_OF_VIRTUALS) + ECC_MONTDH_NO_OF_BUFFERS * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(MCUXCLECC_MONTDH_CURVE25519_SIZE_PRIMEP) + MCUXCLPKC_WORDSIZE)];
#endif /* MCUXCL_FEATURE_ECC_CURVE25519 */
#ifdef MCUXCL_FEATURE_ECC_CURVE448
volatile uint8_t mcuxClEcc_MontDH_GenerateKeyPair_Curve448_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_MONTDH_NO_OF_BUFFERS, ECC_MONTDH_NO_OF_VIRTUALS) + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(MCUXCLRANDOMMODES_CPUWA_MAXSIZE)];
volatile uint8_t mcuxClEcc_MontDH_KeyAgreement_Curve448_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_MONTDH_NO_OF_BUFFERS, ECC_MONTDH_NO_OF_VIRTUALS)];
volatile uint8_t mcuxClEcc_MontDH_GenerateKeyPair_Curve448_WaPKC_SIZE[MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_MONTDH_NO_OF_BUFFERS, ECC_MONTDH_NO_OF_VIRTUALS) + ECC_MONTDH_NO_OF_BUFFERS * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(MCUXCLECC_MONTDH_CURVE448_SIZE_PRIMEP) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_MontDH_KeyAgreement_Curve448_WaPKC_SIZE[MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_MONTDH_NO_OF_BUFFERS, ECC_MONTDH_NO_OF_VIRTUALS) + ECC_MONTDH_NO_OF_BUFFERS * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(MCUXCLECC_MONTDH_CURVE448_SIZE_PRIMEP) + MCUXCLPKC_WORDSIZE)];
#endif /* MCUXCL_FEATURE_ECC_CURVE448 */
MCUX_CSSL_ANALYSIS_STOP_PATTERN_OBJ_SIZES()
#endif /* MCUXCL_FEATURE_ECC_MONTDH */

#ifdef MCUXCL_FEATURE_ECC_EDDSA


#define SIZEOF_EDDSA_UPTRT_CPUWA  MCUXCLECC_SIZEOF_UPTRT_CPUWA(ECC_EDDSA_NO_OF_BUFFERS, ECC_EDDSA_NO_OF_VIRTUALS)

MCUX_CSSL_ANALYSIS_START_PATTERN_OBJ_SIZES()
volatile uint8_t mcuxClEcc_EdDSA_GenerateKeyPair_Ed25519_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + SIZEOF_EDDSA_UPTRT_CPUWA
                                                                   + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(MCUXCLRANDOMMODES_CPUWA_MAXSIZE)
                                                                   + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(MCUXCLECC_EDDSA_ED25519_SIZE_PRIVATEKEY)
                                                                   + MCUXCLHASH_INTERNAL_WACPU_SIZE_SHA2_512
                                                                   /* Memory needed for the TwEd_SecureFixScalarMult CPU workarea */
                                                                   + (sizeof(mcuxClEcc_TwEd_SecureFixScalarMult_CpuWa_t) + sizeof(uint32_t))];
volatile uint8_t mcuxClEcc_EdDSA_GenerateSignature_Ed25519_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + SIZEOF_EDDSA_UPTRT_CPUWA
                                                                     /* Memory needed for message pre-hashing */
                                                                     + MCUXCLHASH_OUTPUT_SIZE_SHA_512
                                                                     /* Memory needed for storing a hash context for the upcoming multipart hash operations */
                                                                     + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(sizeof(mcuxClHash_ContextDescriptor_t) + MCUXCLHASH_CONTEXT_MAX_ALIGNMENT_OFFSET + MCUXCLHASH_STATE_SIZE_SHA_512 + MCUXCLHASH_BLOCK_SIZE_SHA_512)
                                                                     + MCUXCLHASH_INTERNAL_WACPU_SIZE_SHA2_512
                                                                     /* Memory needed for storing a secure hash context for the upcoming multipart hash operations on secure data */
                                                                     + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(sizeof(mcuxClHash_ContextDescriptor_t) + MCUXCLHASH_CONTEXT_MAX_ALIGNMENT_OFFSET + MCUXCLHASH_STATE_SIZE_SECSHA_512 + MCUXCLHASH_BLOCK_SIZE_SECSHA_512)
                                                                     + MCUXCLHASH_INTERNAL_WACPU_SIZE_SHA2_512
                                                                     /* Memory needed for the TwEd_SecureFixScalarMult CPU workarea */
                                                                     + (sizeof(mcuxClEcc_TwEd_SecureFixScalarMult_CpuWa_t) + sizeof(uint32_t))];
volatile uint8_t mcuxClEcc_EdDSA_VerifySignature_Ed25519_WaCPU_SIZE[SIZEOF_ECCCPUWA_T + SIZEOF_EDDSA_UPTRT_CPUWA
                                                                   /* Memory needed for message pre-hashing */
                                                                   + MCUXCLHASH_OUTPUT_SIZE_SHA_512
                                                                   /* Memory needed for storing a hash context for the upcoming multipart hash operations */
                                                                   + MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(sizeof(mcuxClHash_ContextDescriptor_t) + MCUXCLHASH_CONTEXT_MAX_ALIGNMENT_OFFSET + MCUXCLHASH_STATE_SIZE_SHA_512 + MCUXCLHASH_BLOCK_SIZE_SHA_512)
                                                                   + MCUXCLHASH_INTERNAL_WACPU_SIZE_SHA2_512];

/* byteLenP = byteLenN in both Ed25519 and Ed448. */
volatile uint8_t mcuxClEcc_EdDSA_GenerateKeyPair_Ed25519_WaPKC_SIZE[MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_EDDSA_NO_OF_BUFFERS, ECC_EDDSA_NO_OF_VIRTUALS) + ECC_EDDSA_NO_OF_BUFFERS * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(MCUXCLECC_EDDSA_ED25519_SIZE_PRIMEP) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_EdDSA_GenerateSignature_Ed25519_WaPKC_SIZE[MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_EDDSA_NO_OF_BUFFERS, ECC_EDDSA_NO_OF_VIRTUALS) + ECC_EDDSA_NO_OF_BUFFERS * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(MCUXCLECC_EDDSA_ED25519_SIZE_PRIMEP) + MCUXCLPKC_WORDSIZE)];
volatile uint8_t mcuxClEcc_EdDSA_VerifySignature_Ed25519_WaPKC_SIZE[MCUXCLECC_SIZEOF_UPTRT_PKCWA(ECC_EDDSA_NO_OF_BUFFERS, ECC_EDDSA_NO_OF_VIRTUALS) + ECC_EDDSA_NO_OF_BUFFERS * (MCUXCLPKC_ALIGN_TO_PKC_WORDSIZE(MCUXCLECC_EDDSA_ED25519_SIZE_PRIMEP) + MCUXCLPKC_WORDSIZE)];


/* EdDSA key pair generation descriptor size */
volatile uint8_t mcuxClEcc_EdDSA_GenerateKeyPairDescriptor_SIZE[MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(sizeof(mcuxClEcc_EdDSA_GenerateKeyPairDescriptor_t) + sizeof(mcuxClKey_GenerationDescriptor_t))];

/* EdDSA signature mode generation descriptor size */
volatile uint8_t mcuxClEcc_EdDSA_SignatureProtocolDescriptor_SIZE[MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(sizeof(mcuxClEcc_EdDSA_SignatureProtocolDescriptor_t))];

/* EdDSA signature mode generation descriptor size */
volatile uint8_t mcuxClEcc_EdDSA_Signature_ProtocolMode_Descriptors_SIZE[MCUXCLCORE_ALIGN_TO_CPU_WORDSIZE(sizeof(mcuxClSignature_ModeDescriptor_t) + sizeof(mcuxClEcc_EdDSA_SignatureProtocolDescriptor_t))];

MCUX_CSSL_ANALYSIS_STOP_PATTERN_OBJ_SIZES()
#endif /* MCUXCL_FEATURE_ECC_EDDSA */

MCUX_CSSL_ANALYSIS_STOP_PATTERN_DESCRIPTIVE_IDENTIFIER()

