/*
 * Copyright 2025-2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _FSL_INPUTMUX_CONNECTIONS_
#define _FSL_INPUTMUX_CONNECTIONS_
/*******************************************************************************
 * Definitions
 ******************************************************************************/
/* Component ID definition, used by tools. */
#ifndef FSL_COMPONENT_ID
#define FSL_COMPONENT_ID "platform.drivers.inputmux_connections"
#endif

/*! @name Driver version */
/*@{*/
/*! @brief INPUTMUX_CONNECTION driver version 2.0.1. */
#define FSL_INPUTMUX_CONNECTION_DRIVER_VERSION (MAKE_VERSION(2, 0, 1))
/*@}*/

/*!
 * @addtogroup inputmux_driver
 * @{
 */

/*!
 * @name Input multiplexing connections
 * @{
 */

/*! @brief Periphinmux IDs */
#define FREQMEAS_REF_REG          0x0U
#define FREQMEAS_TAR_REG          0x4U

#define PMUX_SHIFT 20U

typedef enum _inputmux_index_t
{
    /*!< For AUDIO SS*/
    /*!< Selection for frequency measurement reference clock. */
    kINPUTMUX_AUDIO_xbar_out0_ref                    = 1U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_audio_clk_ref                    = 16U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_dmic0_appclk_ref                 = 17U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai0_mclk0_ref                   = 18U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai0_mclk1_ref                   = 19U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai1_mclk0_ref                   = 20U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai1_mclk1_ref                   = 21U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai2_mclk0_ref                   = 22U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai2_mclk1_ref                   = 23U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_spdif_txclk_ref                  = 24U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_spdif_cdrclk_ref                 = 25U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_asrc_clk_ref                     = 26U + (FREQMEAS_REF_REG << PMUX_SHIFT),

    /*!< Selection for frequency measurement target clock. */
    kINPUTMUX_AUDIO_xbar_out0_tar                    = 1U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_audio_clk_tar                    = 16U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_dmic0_appclk_tar                 = 17U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai0_mclk0_tar                   = 18U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai0_mclk1_tar                   = 19U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai1_mclk0_tar                   = 20U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai1_mclk1_tar                   = 21U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai2_mclk0_tar                   = 22U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_sai2_mclk1_tar                   = 23U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_spdif_txclk_tar                  = 24U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_spdif_cdrclk_tar                 = 25U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_AUDIO_asrc_clk_tar                     = 26U + (FREQMEAS_TAR_REG << PMUX_SHIFT),

    /*!< For CMPT SS*/
    /*!< Selection for frequency measurement reference clock. */
    kINPUTMUX_CMPT_hsp_ss_xbar0_out217_ref           = 1U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104mix_5m3c2m_lvt_ref          = 2U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104mix_5m3c2m_slvt_ref         = 3U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104mix_5m3c2m_lvt_sbs_ref      = 4U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104mix_5m3c2m_slvt_sbs_ref     = 5U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104pmro1_5m3c2m_lvt_ref        = 6U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104pmro1_5m3c2m_lvt_sbs_ref    = 7U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104pmro1_5m3c2m_slvt_ref       = 8U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104pmro1_5m3c2m_slvt_sbs_ref   = 9U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104htol1_5m3c2m_lvt_ref        = 10U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104htol1_5m3c2m_slvt_ref       = 11U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_cmpt_clk_ref                      = 16U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_cpu_clk_ref                       = 17U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_npu_clk_ref                       = 18U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_systick_clk0_ref                  = 19U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_systick_clk1_ref                  = 20U + (FREQMEAS_REF_REG << PMUX_SHIFT),

    /*!< Selection for frequency measurement target clock. */
    kINPUTMUX_CMPT_hsp_ss_xbar0_out217_tar           = 1U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104mix_5m3c2m_lvt_tar          = 2U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104mix_5m3c2m_slvt_tar         = 3U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104mix_5m3c2m_lvt_sbs_tar      = 4U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104mix_5m3c2m_slvt_sbs_tar     = 5U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104pmro1_5m3c2m_lvt_tar        = 6U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104pmro1_5m3c2m_lvt_sbs_tar    = 7U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104pmro1_5m3c2m_slvt_tar       = 8U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104pmro1_5m3c2m_slvt_sbs_tar   = 9U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104htol1_5m3c2m_lvt_tar        = 10U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_pm_104htol1_5m3c2m_slvt_tar       = 11U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_cmpt_clk_tar                      = 16U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_cpu_clk_tar                       = 17U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_npu_clk_tar                       = 18U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_systick_clk0_tar                  = 19U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_CMPT_systick_clk1_tar                  = 20U + (FREQMEAS_TAR_REG << PMUX_SHIFT),

    /*!< For COMM SS*/
    /*!< Selection for frequency measurement reference clock. */
    kINPUTMUX_COMM_hsp_ss_xbar0_out199_ref           = 1U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_gf22_pm_104mix_5m3c2m_lvt_ref     = 2U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_gf22_pm_104mix_5m3c2m_slvt_ref    = 3U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_gf22_pm_104pmro1_5m3c2m_lvt_ref   = 4U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_gf22_pm_104pmro1_5m3c2m_slvt_ref  = 5U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usbphy0_tsto_pll_out_div_ref      = 6U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usbphy0_utmi_clk_ref              = 7U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usbphy0_utmi_linestate_ref        = 8U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_comm_clk_ref                      = 16U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_comm_ulp32k_ref                   = 17U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usdhc0_fclk_ref                   = 18U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usdhc1_fclk_ref                   = 19U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_xspir_rootclk_ref                 = 20U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usb0_phyclk_ref                   = 21U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usb0_fro48m_ref                   = 22U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usb1_fclk_ref                     = 23U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usb0_wakeclk_ref                  = 24U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth0_trxclk_ref                   = 25U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth0_timerclk_ref                 = 26U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth1_trxclk_ref                   = 27U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth1_trxclk_divided_ref           = 28U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth1_timerclk_ref                 = 31U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth_refclk_ref                    = 32U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_xeno0_liwclk_ref                  = 33U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_xeno1_liwclk_ref                  = 34U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_dll_refclk_ref                    = 35U + (FREQMEAS_REF_REG << PMUX_SHIFT),

    /*!< Selection for frequency measurement target clock. */
    kINPUTMUX_COMM_hsp_ss_xbar0_out199_tar           = 1U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_gf22_pm_104mix_5m3c2m_lvt_tar     = 2U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_gf22_pm_104mix_5m3c2m_slvt_tar    = 3U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_gf22_pm_104pmro1_5m3c2m_lvt_tar   = 4U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_gf22_pm_104pmro1_5m3c2m_slvt_tar  = 5U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usbphy0_tsto_pll_out_div_tar      = 6U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usbphy0_utmi_clk_tar              = 7U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usbphy0_utmi_linestate_tar        = 8U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_comm_clk_tar                      = 16U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_comm_ulp32k_tar                   = 17U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usdhc0_fclk_tar                   = 18U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usdhc1_fclk_tar                   = 19U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_xspir_rootclk_tar                 = 20U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usb0_phyclk_tar                   = 21U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usb0_fro48m_tar                   = 22U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usb1_fclk_tar                     = 23U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_usb0_wakeclk_tar                  = 24U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth0_trxclk_tar                   = 25U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth0_timerclk_tar                 = 26U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth1_trxclk_tar                   = 27U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth1_trxclk_divided_tar           = 28U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth1_timerclk_tar                 = 31U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_eth_tarclk_tar                    = 32U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_xeno0_liwclk_tar                  = 33U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_xeno1_liwclk_tar                  = 34U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_COMM_dll_tarclk_tar                    = 35U + (FREQMEAS_TAR_REG << PMUX_SHIFT),

    /*!< For MAIN SS*/
    /*!< Selection for frequency measurement reference clock. */
    kINPUTMUX_MAIN_hsp_ss_xbar0_out8_ref             = 1U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104mix_5m3c2m_lvt_ref          = 2U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104mix_5m3c2m_slvt_ref         = 3U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104mix_5m3c2m_hvt_ref          = 4U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104mix_5m3c2m_rvt_ref          = 5U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104pmro1_5m3c2m_lvt_ref        = 6U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104pmro1_5m3c2m_slvt_ref       = 7U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_main_clk_ref                      = 16U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_main_clk_divided_ref              = 17U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_xspi0_fclk_ref                    = 20U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_xspi0_fclk_divided_ref            = 21U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_xspi1_fclk_ref                    = 24U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_xspi1_fclk_divided_ref            = 25U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_i3c0_fclk_ref                     = 28U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpi2c0_fclk_ref                   = 29U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpi2c1_fclk_ref                   = 30U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpspi0_fclk_ref                   = 31U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpspi1_fclk_ref                   = 32U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpspi2_fclk_ref                   = 33U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpspi3_fclk_ref                   = 34U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpspi4_fclk_ref                   = 35U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart0_fclk_ref                  = 36U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart1_fclk_ref                  = 37U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart2_fclk_ref                  = 38U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart3_fclk_ref                  = 39U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart4_fclk_ref                  = 40U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart5_fclk_ref                  = 41U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexcan0_fclk_ref                 = 42U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexcan1_fclk_ref                 = 43U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexcan2_fclk_ref                 = 44U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexcan_gfclk_ref                 = 45U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_qtpm0_fclk_ref                    = 46U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpit0_fclk_ref                    = 47U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpit1_fclk_ref                    = 48U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_adc0_fclk_ref                     = 49U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_adc1_fclk_ref                     = 50U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_sinc0_fclk_ref                    = 51U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_sinc1_fclk_ref                    = 52U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexio0_fclk_ref                  = 53U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexio1_fclk_ref                  = 54U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexio2_fclk_ref                  = 55U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_tpiu_clk_ref                      = 56U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_cssi_refclk_ref                   = 57U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_otp_clk_ref                       = 58U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_clkout_ref                        = 59U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_main_fro192m_ref                  = 60U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_main_ulp32k_ref                   = 61U + (FREQMEAS_REF_REG << PMUX_SHIFT),

    /*!< Selection for frequency measurement target clock. */
    kINPUTMUX_MAIN_hsp_ss_xbar0_out8_tar             = 1U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104mix_5m3c2m_lvt_tar          = 2U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104mix_5m3c2m_slvt_tar         = 3U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104mix_5m3c2m_hvt_tar          = 4U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104mix_5m3c2m_rvt_tar          = 5U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104pmro1_5m3c2m_lvt_tar        = 6U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_pm_104pmro1_5m3c2m_slvt_tar       = 7U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_main_clk_tar                      = 16U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_main_clk_divided_tar              = 17U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_xspi0_fclk_tar                    = 20U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_xspi0_fclk_divided_tar            = 21U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_xspi1_fclk_tar                    = 24U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_xspi1_fclk_divided_tar            = 25U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_i3c0_fclk_tar                     = 28U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpi2c0_fclk_tar                   = 29U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpi2c1_fclk_tar                   = 30U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpspi0_fclk_tar                   = 31U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpspi1_fclk_tar                   = 32U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpspi2_fclk_tar                   = 33U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpspi3_fclk_tar                   = 34U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpspi4_fclk_tar                   = 35U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart0_fclk_tar                  = 36U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart1_fclk_tar                  = 37U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart2_fclk_tar                  = 38U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart3_fclk_tar                  = 39U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart4_fclk_tar                  = 40U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpuart5_fclk_tar                  = 41U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexcan0_fclk_tar                 = 42U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexcan1_fclk_tar                 = 43U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexcan2_fclk_tar                 = 44U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexcan_gfclk_tar                 = 45U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_qtpm0_fclk_tar                    = 46U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpit0_fclk_tar                    = 47U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_lpit1_fclk_tar                    = 48U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_adc0_fclk_tar                     = 49U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_adc1_fclk_tar                     = 50U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_sinc0_fclk_tar                    = 51U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_sinc1_fclk_tar                    = 52U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexio0_fclk_tar                  = 53U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexio1_fclk_tar                  = 54U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_flexio2_fclk_tar                  = 55U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_tpiu_clk_tar                      = 56U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_cssi_refclk_tar                   = 57U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_otp_clk_tar                       = 58U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_clkout_tar                        = 59U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_main_fro192m_tar                  = 60U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MAIN_main_ulp32k_tar                   = 61U + (FREQMEAS_TAR_REG << PMUX_SHIFT),

    /*!< For MEDIA SS*/
    /*!< Selection for frequency measurement reference clock. */
    kINPUTMUX_MEDIA_hsp_ss_xbar0_out218_ref          = 1U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_gf22_pm_104mix_5m3c2m_lvt_ref    = 2U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_gf22_pm_104mix_5m3c2m_slvt_ref   = 3U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_gf22_pm_104pmro1_5m3c2m_lvt_ref  = 4U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_gf22_pm_104pmro1_5m3c2m_slvt_ref = 5U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_media_clk_ref                    = 16U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mediapll_rootclk_ref             = 17U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipicsi_escclk_ref               = 18U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipicsi_clk_ref                  = 19U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipidsi_escclk_ref               = 20U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipidsi_escclk_divided_ref       = 21U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipidsi_refclk_ref               = 24U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipidsi_clk_ref                  = 25U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_reformat_fclk_ref                = 26U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_dcpixel_fclk_ref                 = 27U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_csi_mclkout_ref                  = 28U + (FREQMEAS_REF_REG << PMUX_SHIFT),

    /*!< Selection for frequency measurement target clock. */
    kINPUTMUX_MEDIA_hsp_ss_xbar0_out218_tar          = 1U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_gf22_pm_104mix_5m3c2m_lvt_tar    = 2U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_gf22_pm_104mix_5m3c2m_slvt_tar   = 3U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_gf22_pm_104pmro1_5m3c2m_lvt_tar  = 4U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_gf22_pm_104pmro1_5m3c2m_slvt_tar = 5U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_media_clk_tar                    = 16U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mediapll_rootclk_tar             = 17U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipicsi_escclk_tar               = 18U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipicsi_clk_tar                  = 19U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipidsi_escclk_tar               = 20U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipidsi_escclk_divided_tar       = 21U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipidsi_tarclk_tar               = 24U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_mipidsi_clk_tar                  = 25U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_tarormat_fclk_tar                = 26U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_dcpixel_fclk_tar                 = 27U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_MEDIA_csi_mclkout_tar                  = 28U + (FREQMEAS_TAR_REG << PMUX_SHIFT),

    /*!< For SYSCON SS*/
    /*!< Selection for frequency measurement reference clock. */
    kINPUTMUX_SYSCON_hsp_ss_xbar0_out9_ref           = 1U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_sxosc_rootclk_ref               = 16U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_base_clk_ref                    = 17U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_low_clk_ref                     = 18U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainpll_divx_ref                = 19U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_syspll_divx_ref                 = 20U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_pll_pfdx_ref                    = 21U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_media_pfdx_ref                  = 22U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainpfdx_rootclk_ref            = 23U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_commpfdx_rootclk_ref            = 24U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_maindivx_rootclk_ref            = 25U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_saimclk_rootclk_ref             = 26U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_saimclk0_rootclk_ref            = 27U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_saimclk1_rootclk_ref            = 28U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_saimclk2_rootclk_ref            = 29U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_lp12m_core_rootclk_ref          = 30U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_lp1m_core_rootclk_ref           = 31U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_ulp32k_rootclk_ref              = 32U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_fro192m_rootclk_ref             = 33U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_fro96m_rootclk_ref              = 34U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_fro48m_rootclk_ref              = 35U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_fro24m_rootclk_ref              = 36U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_sysplldiv4_rootclk_ref          = 37U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_sysplldiv5_rootclk_ref          = 38U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_sysplldivx_rootclk_ref          = 39U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainplldivx_rootclk_ref         = 40U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainplldiv8_rootclk_ref         = 41U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainplldiv10_rootclk_ref        = 42U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainplldiv20_rootclk_ref        = 43U + (FREQMEAS_REF_REG << PMUX_SHIFT),    
    kINPUTMUX_SYSCON_audiopll_rootclk_ref            = 44U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_videopll_rootclk_ref            = 45U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_cpu_rootclk_ref                 = 46U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_cpu_rootclk_divided_ref         = 47U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_npu_rootclk_ref                 = 50U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mediabus_rootclk_ref            = 51U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_audiobus_rootclk_ref            = 52U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_commbus_rootclk_ref             = 53U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_wakebus_rootclk_ref             = 54U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_syscon_pdmain_clk_ref           = 55U + (FREQMEAS_REF_REG << PMUX_SHIFT),    
    kINPUTMUX_SYSCON_peri_rootclk0_ref               = 56U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk1_ref               = 57U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk2_ref               = 58U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk3_ref               = 59U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk4_ref               = 60U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk5_ref               = 61U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk6_ref               = 62U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk7_ref               = 63U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_audio_rootclk_ref               = 64U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_video_rootclk_ref               = 65U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_usb1_rootclk_ref                = 66U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_eth_rootclk_ref                 = 67U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_test_rootclk_ref                = 68U + (FREQMEAS_REF_REG << PMUX_SHIFT),

    /*!< Selection for frequency measurement target clock. */
    kINPUTMUX_SYSCON_hsp_ss_xbar0_out9_tar           = 1U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_sxosc_rootclk_tar               = 16U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_base_clk_tar                    = 17U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_low_clk_tar                     = 18U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainpll_divx_tar                = 19U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_syspll_divx_tar                 = 20U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_pll_pfdx_tar                    = 21U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_media_pfdx_tar                  = 22U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainpfdx_rootclk_tar            = 23U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_commpfdx_rootclk_tar            = 24U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_maindivx_rootclk_tar            = 25U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_saimclk_rootclk_tar             = 26U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_saimclk0_rootclk_tar            = 27U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_saimclk1_rootclk_tar            = 28U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_saimclk2_rootclk_tar            = 29U + (FREQMEAS_TAR_REG << PMUX_SHIFT),    
    kINPUTMUX_SYSCON_lp12m_core_rootclk_tar          = 30U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_lp1m_core_rootclk_tar           = 31U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_ulp32k_rootclk_tar              = 32U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_fro192m_rootclk_tar             = 33U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_fro96m_rootclk_tar              = 34U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_fro48m_rootclk_tar              = 35U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_fro24m_rootclk_tar              = 36U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_sysplldiv4_rootclk_tar          = 37U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_sysplldiv5_rootclk_tar          = 38U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_sysplldivx_rootclk_tar          = 39U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainplldivx_rootclk_tar         = 40U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainplldiv8_rootclk_tar         = 41U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainplldiv10_rootclk_tar        = 42U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mainplldiv20_rootclk_tar        = 43U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_audiopll_rootclk_tar            = 44U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_videopll_rootclk_tar            = 45U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_cpu_rootclk_tar                 = 46U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_cpu_rootclk_divided_tar         = 47U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_npu_rootclk_tar                 = 50U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_mediabus_rootclk_tar            = 51U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_audiobus_rootclk_tar            = 52U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_commbus_rootclk_tar             = 53U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_wakebus_rootclk_tar             = 54U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_syscon_pdmain_clk_tar           = 55U + (FREQMEAS_TAR_REG << PMUX_SHIFT),    
    kINPUTMUX_SYSCON_peri_rootclk0_tar               = 56U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk1_tar               = 57U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk2_tar               = 58U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk3_tar               = 59U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk4_tar               = 60U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk5_tar               = 61U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk6_tar               = 62U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_peri_rootclk7_tar               = 63U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_audio_rootclk_tar               = 64U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_video_rootclk_tar               = 65U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_usb1_rootclk_tar                = 66U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_eth_rootclk_tar                 = 67U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_SYSCON_test_rootclk_tar                = 68U + (FREQMEAS_TAR_REG << PMUX_SHIFT),


    /*!< For WAKE SS*/
    /*!< Selection for frequency measurement reference clock. */
    kINPUTMUX_WAKE_wake_ss_xbar_out8_ref             = 1U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_buck_vddcore_testbus_0_ref        = 2U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_buck_vddcore_testbus_1_ref        = 3U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_clk_lposc_1m_vdd0v8_ref           = 4U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_clk_lposc_2m_vdd0v8_ref           = 5U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_clk_ckfro12m_wake_ref             = 6U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_pmu_lfro32k_clk_vddcoreaon_ref    = 7U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_pmu_clk_xosc_32k_vddcoreaon_ref   = 8U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_pmu_bb_tst_dig_out_ref            = 9U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_clk_ref                      = 16U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_sxosc_ref                    = 17U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_lp1m_ref                     = 18U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_lp12m_ref                    = 19U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_ulp32k_ref                   = 20U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_lpclk_ref                    = 21U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_i3c0_fclk_ref                     = 22U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lpi2c0_fclk_ref                   = 23U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lpi2c1_fclk_ref                   = 24U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lpspi0_fclk_ref                   = 25U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lpuart0_fclk_ref                  = 26U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lpuart1_fclk_ref                  = 27U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_dmic1_appclk_ref                  = 28U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_qtpm0_fclk_ref                    = 29U + (FREQMEAS_REF_REG << PMUX_SHIFT),    
    kINPUTMUX_WAKE_lptmr0_fclk_ref                   = 30U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lptmr1_fclk_ref                   = 31U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_swt0_fclk_ref                     = 32U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_swt1_fclk_ref                     = 33U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_ewm_fclk_ref                      = 34U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp0_fclk_ref                    = 35U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp1_fclk_ref                    = 36U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp2_fclk_ref                    = 37U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp3_fclk_ref                    = 38U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp0_rrclk_ref                   = 39U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp1_rrclk_ref                   = 40U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp2_rrclk_ref                   = 41U + (FREQMEAS_REF_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp3_rrclk_ref                   = 42U + (FREQMEAS_REF_REG << PMUX_SHIFT),

    /*!< Selection for frequency measurement target clock. */
    kINPUTMUX_WAKE_wake_ss_xbar_out8_tar             = 1U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_buck_vddcore_testbus_0_tar        = 2U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_buck_vddcore_testbus_1_tar        = 3U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_clk_lposc_1m_vdd0v8_tar           = 4U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_clk_lposc_2m_vdd0v8_tar           = 5U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_clk_ckfro12m_wake_tar             = 6U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_pmu_lfro32k_clk_vddcoreaon_tar    = 7U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_pmu_clk_xosc_32k_vddcoreaon_tar   = 8U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_pmu_bb_tst_dig_out_tar            = 9U + (FREQMEAS_TAR_REG << PMUX_SHIFT),    
    kINPUTMUX_WAKE_wake_clk_tar                      = 16U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_sxosc_tar                    = 17U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_lp1m_tar                     = 18U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_lp12m_tar                    = 19U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_ulp32k_tar                   = 20U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_wake_lpclk_tar                    = 21U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_i3c0_fclk_tar                     = 22U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lpi2c0_fclk_tar                   = 23U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lpi2c1_fclk_tar                   = 24U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lpspi0_fclk_tar                   = 25U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lpuart0_fclk_tar                  = 26U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lpuart1_fclk_tar                  = 27U + (FREQMEAS_TAR_REG << PMUX_SHIFT),    
    kINPUTMUX_WAKE_dmic1_appclk_tar                  = 28U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_qtpm0_fclk_tar                    = 29U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lptmr0_fclk_tar                   = 30U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_lptmr1_fclk_tar                   = 31U + (FREQMEAS_TAR_REG << PMUX_SHIFT),    
    kINPUTMUX_WAKE_swt0_fclk_tar                     = 32U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_swt1_fclk_tar                     = 33U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_ewm_fclk_tar                      = 34U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp0_fclk_tar                    = 35U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp1_fclk_tar                    = 36U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp2_fclk_tar                    = 37U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp3_fclk_tar                    = 38U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp0_rrclk_tar                   = 39U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp1_rrclk_tar                   = 40U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp2_rrclk_tar                   = 41U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
    kINPUTMUX_WAKE_acmp3_rrclk_tar                   = 42U + (FREQMEAS_TAR_REG << PMUX_SHIFT),
} inputmux_connection_t;

/*@}*/

/*@}*/

#endif /* _FSL_INPUTMUX_CONNECTIONS_ */
