/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC5534JBD64/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC5536JBD64-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: a51d0191eb537ac5
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC5534JBD64_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC5534JBD64_WRAPPER_

#include "LPC5536JBD64-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC5534JBD64_WRAPPER_ */
