/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC54606J256ET180/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC54616J256ET180-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 0fb4a7e7e4c8254c
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC54606J256ET180_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC54606J256ET180_WRAPPER_

#include "LPC54616J256ET180-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC54606J256ET180_WRAPPER_ */
