/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC54113J256UK49/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC54114J256UK49-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: c2001ea99edb3ad8
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC54113J256UK49_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC54113J256UK49_WRAPPER_

#include "LPC54114J256UK49-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC54113J256UK49_WRAPPER_ */
