/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC54005JET100/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC54005JBD100-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 915b1e5825723d4f
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC54005JET100_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC54005JET100_WRAPPER_

#include "LPC54005JBD100-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC54005JET100_WRAPPER_ */
