/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC54607J256ET180/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC54607J512ET180-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: d1b7cd81c09ab6b9
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC54607J256ET180_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC54607J256ET180_WRAPPER_

#include "LPC54607J512ET180-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC54607J256ET180_WRAPPER_ */
