/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for K32L2B31VFT0A/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on K32L2B31VLH0A-pinctrl.h with this part's differences applied
 * below (109 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 67cd35d41ddbc29c
 */

#ifndef _ZEPHYR_DTS_BINDING_K32L2B31VFT0A_WRAPPER_
#define _ZEPHYR_DTS_BINDING_K32L2B31VFT0A_WRAPPER_

#include "K32L2B31VLH0A-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_DM3_PTE23
#undef ADC0_DP3_PTE22
#undef ADC0_SE3_PTE22
#undef ADC0_SE7a_PTE23
#undef CLKOUT32K_PTE0
#undef CMP0_OUT_PTE0
#undef FXIO0_D6_PTE22
#undef FXIO0_D7_PTE23
#undef I2C1_SCL_PTE1
#undef I2C1_SDA_PTE0
#undef LCD_P0_Fault_PTB0
#undef LCD_P0_PTB0
#undef LCD_P12_Fault_PTB16
#undef LCD_P12_PTB16
#undef LCD_P13_Fault_PTB17
#undef LCD_P13_PTB17
#undef LCD_P14_Fault_PTB18
#undef LCD_P14_PTB18
#undef LCD_P15_Fault_PTB19
#undef LCD_P15_PTB19
#undef LCD_P1_Fault_PTB1
#undef LCD_P1_PTB1
#undef LCD_P20_Fault_PTC0
#undef LCD_P20_PTC0
#undef LCD_P21_Fault_PTC1
#undef LCD_P21_PTC1
#undef LCD_P22_Fault_PTC2
#undef LCD_P22_PTC2
#undef LCD_P23_Fault_PTC3
#undef LCD_P23_PTC3
#undef LCD_P24_Fault_PTC4
#undef LCD_P24_PTC4
#undef LCD_P25_Fault_PTC5
#undef LCD_P25_PTC5
#undef LCD_P26_Fault_PTC6
#undef LCD_P26_PTC6
#undef LCD_P27_Fault_PTC7
#undef LCD_P27_PTC7
#undef LCD_P2_Fault_PTB2
#undef LCD_P2_PTB2
#undef LCD_P39_Fault_PTC23
#undef LCD_P39_PTC23
#undef LCD_P3_Fault_PTB3
#undef LCD_P3_PTB3
#undef LCD_P40_Fault_PTD0
#undef LCD_P40_PTD0
#undef LCD_P41_Fault_PTD1
#undef LCD_P41_PTD1
#undef LCD_P42_Fault_PTD2
#undef LCD_P42_PTD2
#undef LCD_P43_Fault_PTD3
#undef LCD_P43_PTD3
#undef LCD_P44_Fault_PTD4
#undef LCD_P44_PTD4
#undef LCD_P45_Fault_PTD5
#undef LCD_P45_PTD5
#undef LCD_P46_Fault_PTD6
#undef LCD_P46_PTD6
#undef LCD_P47_Fault_PTD7
#undef LCD_P47_PTD7
#undef LCD_P48_Fault_PTE0
#undef LCD_P48_PTE0
#undef LCD_P49_Fault_PTE1
#undef LCD_P49_PTE1
#undef LCD_P4_Fault_PTC20
#undef LCD_P4_PTC20
#undef LCD_P59_Fault_PTE20
#undef LCD_P59_PTE20
#undef LCD_P5_Fault_PTC21
#undef LCD_P5_PTC21
#undef LCD_P60_Fault_PTE21
#undef LCD_P60_PTE21
#undef LCD_P6_Fault_PTC22
#undef LCD_P6_PTC22
#undef LPUART1_RX_PTE1
#undef LPUART1_TX_PTE0
#undef PTA12
#undef PTA13
#undef PTA5
#undef PTB18
#undef PTB19
#undef PTC20
#undef PTC21
#undef PTC22
#undef PTC23
#undef PTE0
#undef PTE1
#undef PTE22
#undef PTE23
#undef PTE31
#undef RTC_CLKOUT_PTE0
#undef SPI1_MISO_PTE0
#undef SPI1_MISO_PTE1
#undef SPI1_MOSI_PTE1
#undef TPM0_CH2_PTA5
#undef TPM0_CH4_PTE31
#undef TPM1_CH0_PTA12
#undef TPM1_CH1_PTA13
#undef TPM2_CH0_PTB18
#undef TPM2_CH0_PTE22
#undef TPM2_CH1_PTB19
#undef TPM2_CH1_PTE23
#undef UART2_RX_PTE23
#undef UART2_TX_PTE22
#undef USB_CLKIN_PTA5
#undef VCAP1_PTC23
#undef VCAP2_PTC22
#undef VLL1_PTC21
#undef VLL2_PTC20

#endif /* _ZEPHYR_DTS_BINDING_K32L2B31VFT0A_WRAPPER_ */
