/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for K32L2B21VMP0A/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to K32L2B31VLH0A-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 67cd35d41ddbc29c
 */

#ifndef _ZEPHYR_DTS_BINDING_K32L2B21VMP0A_WRAPPER_
#define _ZEPHYR_DTS_BINDING_K32L2B21VMP0A_WRAPPER_

#include "K32L2B31VLH0A-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_K32L2B21VMP0A_WRAPPER_ */
