/*
 * NOTE: Autogenerated file by kinetis_cfg_utils.py
 * for MK22FX512VMC12/signal_configuration.xml
 *
 * Copyright 2023 Daniel DeGrasse
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK24FN256VDC12-pinctrl.h with this part's differences applied
 * below (9 removed, 0 changed,
 * 27 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 29a4bf770d72f0ae
 */

#ifndef _ZEPHYR_DTS_BINDING_MK22FX512VMC12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK22FX512VMC12_WRAPPER_

#include "MK24FN256VDC12-pinctrl.h"

/* Signals not present on this part */
#undef FTM_CLKIN0_PTC12
#undef FTM_CLKIN1_PTC13
#undef I2C0_SCL_PTE24
#undef I2C0_SDA_PTE25
#undef SPI1_PCS0_PTD4
#undef SPI1_SCK_PTD5
#undef SPI1_SIN_PTD7
#undef SPI1_SOUT_PTD6
#undef USB_SOF_OUT_PTC0

/* Signals specific to this part */
#define ADC0_DM2_PTE3 KINETIS_MUX('E',3,0)
#define ADC0_DP2_PTE2 KINETIS_MUX('E',2,0)
#define CAN0_RX_PTA13 KINETIS_MUX('A',13,2)
#define CAN0_RX_PTB19 KINETIS_MUX('B',19,2)
#define CAN0_TX_PTA12 KINETIS_MUX('A',12,2)
#define CAN0_TX_PTB18 KINETIS_MUX('B',18,2)
#define CMP2_IN0_PTA12 KINETIS_MUX('A',12,0)
#define CMP2_IN1_PTA13 KINETIS_MUX('A',13,0)
#define CMP2_OUT_PTA5 KINETIS_MUX('A',5,5)
#define CMP2_OUT_PTB22 KINETIS_MUX('B',22,6)
#define SDHC0_CLKIN_PTD11 KINETIS_MUX('D',11,4)
#define SDHC0_CMD_PTE3 KINETIS_MUX('E',3,4)
#define SDHC0_D0_PTE1 KINETIS_MUX('E',1,4)
#define SDHC0_D1_PTE0 KINETIS_MUX('E',0,4)
#define SDHC0_D2_PTE5 KINETIS_MUX('E',5,4)
#define SDHC0_D3_PTE4 KINETIS_MUX('E',4,4)
#define SDHC0_D4_PTD12 KINETIS_MUX('D',12,4)
#define SDHC0_D5_PTD13 KINETIS_MUX('D',13,4)
#define SDHC0_D6_PTD14 KINETIS_MUX('D',14,4)
#define SDHC0_D7_PTD15 KINETIS_MUX('D',15,4)
#define SDHC0_DCLK_PTE2 KINETIS_MUX('E',2,4)
#define TRACE_CLKOUT_PTE0 KINETIS_MUX('E',0,5)
#define TRACE_D0_PTA10 KINETIS_MUX('A',10,7)
#define TRACE_D0_PTE4 KINETIS_MUX('E',4,5)
#define TRACE_D1_PTE3 KINETIS_MUX('E',3,5)
#define TRACE_D2_PTE2 KINETIS_MUX('E',2,5)
#define TRACE_D3_PTE1 KINETIS_MUX('E',1,5)

#endif /* _ZEPHYR_DTS_BINDING_MK22FX512VMC12_WRAPPER_ */
