/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK22FN256CAH12/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK24FN256VDC12-pinctrl.h with this part's differences applied
 * below (158 removed, 0 changed,
 * 8 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 29a4bf770d72f0ae
 */

#ifndef _ZEPHYR_DTS_BINDING_MK22FN256CAH12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK22FN256CAH12_WRAPPER_

#include "MK24FN256VDC12-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE17_PTE24
#undef ADC0_SE18_PTE25
#undef ADC1_SE12_PTB6
#undef ADC1_SE13_PTB7
#undef ADC1_SE14_PTB10
#undef ADC1_SE15_PTB11
#undef ADC1_SE17_PTA17
#undef ADC1_SE6a_PTE2
#undef ADC1_SE7a_PTE3
#undef CMP0_OUT_PTB20
#undef CMP1_OUT_PTB21
#undef CMT_IRO_PTD7
#undef EWM_IN_PTE25
#undef EWM_OUT_b_PTE24
#undef FTM0_CH4_PTB12
#undef FTM0_CH5_PTB13
#undef FTM0_FLT1_PTB10
#undef FTM0_FLT2_PTB11
#undef FTM1_CH0_PTB12
#undef FTM1_CH1_PTB13
#undef FTM1_QD_PHA_PTB12
#undef FTM1_QD_PHB_PTB13
#undef FTM2_CH0_PTA10
#undef FTM2_CH1_PTA11
#undef FTM2_QD_PHA_PTA10
#undef FTM2_QD_PHB_PTA11
#undef FTM3_CH0_PTD0
#undef FTM3_CH0_PTE5
#undef FTM3_CH1_PTD1
#undef FTM3_CH1_PTE6
#undef FTM3_CH2_PTD2
#undef FTM3_CH3_PTD3
#undef FTM3_CH4_PTC8
#undef FTM3_CH5_PTC9
#undef FTM3_CH6_PTC10
#undef FTM3_CH7_PTC11
#undef FTM3_FLT0_PTC12
#undef FTM3_FLT0_PTD12
#undef FTM_CLKIN0_PTC12
#undef FTM_CLKIN1_PTC13
#undef I2C0_SCL_PTD8
#undef I2C0_SCL_PTE24
#undef I2C0_SDA_PTD9
#undef I2C0_SDA_PTE25
#undef I2C2_SCL_PTA12
#undef I2C2_SCL_PTA14
#undef I2C2_SDA_PTA11
#undef I2C2_SDA_PTA13
#undef I2S0_MCLK_PTA17
#undef I2S0_MCLK_PTE6
#undef I2S0_RXD0_PTA15
#undef I2S0_RXD1_PTA16
#undef I2S0_RXD1_PTC11
#undef I2S0_RX_BCLK_PTA14
#undef I2S0_RX_FS_PTA16
#undef I2S0_TXD1_PTA14
#undef I2S0_TXD1_PTC0
#undef LLWU_P1_PTE2
#undef LLWU_P2_PTE4
#undef PTA10
#undef PTA11
#undef PTA14
#undef PTA15
#undef PTA16
#undef PTA17
#undef PTA29
#undef PTB10
#undef PTB11
#undef PTB12
#undef PTB13
#undef PTB20
#undef PTB21
#undef PTB22
#undef PTB23
#undef PTB6
#undef PTB7
#undef PTB8
#undef PTB9
#undef PTC12
#undef PTC13
#undef PTC14
#undef PTC15
#undef PTC16
#undef PTC17
#undef PTC18
#undef PTC19
#undef PTD10
#undef PTD11
#undef PTD12
#undef PTD13
#undef PTD14
#undef PTD15
#undef PTD8
#undef PTD9
#undef PTE2
#undef PTE24
#undef PTE25
#undef PTE26
#undef PTE3
#undef PTE4
#undef PTE5
#undef PTE6
#undef RTC_CLKOUT_PTE26
#undef SPI0_PCS0_PTA14
#undef SPI0_PCS5_PTB23
#undef SPI0_SCK_PTA15
#undef SPI0_SIN_PTA17
#undef SPI0_SOUT_PTA16
#undef SPI1_PCS0_PTB10
#undef SPI1_PCS0_PTE4
#undef SPI1_PCS1_PTB9
#undef SPI1_PCS2_PTE5
#undef SPI1_PCS3_PTE6
#undef SPI1_SCK_PTB11
#undef SPI1_SCK_PTE2
#undef SPI1_SIN_PTE3
#undef SPI1_SOUT_PTE3
#undef SPI2_PCS0_PTB20
#undef SPI2_PCS0_PTD11
#undef SPI2_PCS1_PTD15
#undef SPI2_SCK_PTB21
#undef SPI2_SCK_PTD12
#undef SPI2_SIN_PTB23
#undef SPI2_SIN_PTD14
#undef SPI2_SOUT_PTB22
#undef SPI2_SOUT_PTD13
#undef UART0_CTS_b_PTA16
#undef UART0_RTS_b_PTA17
#undef UART0_RX_PTA15
#undef UART0_TX_PTA14
#undef UART1_CTS_b_PTE2
#undef UART1_RTS_b_PTE3
#undef UART3_CTS_b_PTB13
#undef UART3_CTS_b_PTB9
#undef UART3_CTS_b_PTC19
#undef UART3_CTS_b_PTE6
#undef UART3_RTS_b_PTB12
#undef UART3_RTS_b_PTB8
#undef UART3_RTS_b_PTC18
#undef UART3_RX_PTB10
#undef UART3_RX_PTC16
#undef UART3_RX_PTE5
#undef UART3_TX_PTB11
#undef UART3_TX_PTC17
#undef UART3_TX_PTE4
#undef UART4_CTS_b_PTC13
#undef UART4_CTS_b_PTE26
#undef UART4_RTS_b_PTC12
#undef UART4_RX_PTC14
#undef UART4_RX_PTE25
#undef UART4_TX_PTC15
#undef UART4_TX_PTE24
#undef UART5_CTS_b_PTD11
#undef UART5_RTS_b_PTD10
#undef UART5_RX_PTD8
#undef UART5_TX_PTD9
#undef USB_CLKIN_PTE26
#undef USB_SOF_OUT_PTE6

/* Signals specific to this part */
#define LPUART0_CTS_b_PTC2 KINETIS_MUX('C',2,7)
#define LPUART0_CTS_b_PTD1 KINETIS_MUX('D',1,6)
#define LPUART0_RTS_b_PTC1 KINETIS_MUX('C',1,7)
#define LPUART0_RTS_b_PTD0 KINETIS_MUX('D',0,6)
#define LPUART0_RX_PTC3 KINETIS_MUX('C',3,7)
#define LPUART0_RX_PTD2 KINETIS_MUX('D',2,6)
#define LPUART0_TX_PTC4 KINETIS_MUX('C',4,7)
#define LPUART0_TX_PTD3 KINETIS_MUX('D',3,6)

#endif /* _ZEPHYR_DTS_BINDING_MK22FN256CAH12_WRAPPER_ */
