/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MK22FN512VLL12/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK24FN256VDC12-pinctrl.h with this part's differences applied
 * below (76 removed, 0 changed,
 * 19 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 29a4bf770d72f0ae
 */

#ifndef _ZEPHYR_DTS_BINDING_MK22FN512VLL12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK22FN512VLL12_WRAPPER_

#include "MK24FN256VDC12-pinctrl.h"

/* Signals not present on this part */
#undef ADC1_SE12_PTB6
#undef ADC1_SE13_PTB7
#undef CMT_IRO_PTD7
#undef FTM0_CH4_PTB12
#undef FTM0_CH5_PTB13
#undef FTM1_CH0_PTB12
#undef FTM1_CH1_PTB13
#undef FTM1_QD_PHA_PTB12
#undef FTM1_QD_PHB_PTB13
#undef FTM2_CH0_PTA10
#undef FTM2_CH1_PTA11
#undef FTM2_QD_PHA_PTA10
#undef FTM2_QD_PHB_PTA11
#undef FTM3_FLT0_PTD12
#undef FTM_CLKIN0_PTC12
#undef FTM_CLKIN1_PTC13
#undef I2C0_SCL_PTD8
#undef I2C0_SDA_PTD9
#undef I2C2_SCL_PTA12
#undef I2C2_SCL_PTA14
#undef I2C2_SDA_PTA11
#undef I2C2_SDA_PTA13
#undef I2S0_RXD1_PTA16
#undef I2S0_RXD1_PTC11
#undef I2S0_TXD1_PTA14
#undef I2S0_TXD1_PTC0
#undef PTA10
#undef PTA11
#undef PTA29
#undef PTB12
#undef PTB13
#undef PTB6
#undef PTB7
#undef PTB8
#undef PTC19
#undef PTD10
#undef PTD11
#undef PTD12
#undef PTD13
#undef PTD14
#undef PTD15
#undef PTD8
#undef PTD9
#undef SPI2_PCS0_PTB20
#undef SPI2_PCS0_PTD11
#undef SPI2_PCS1_PTD15
#undef SPI2_SCK_PTB21
#undef SPI2_SCK_PTD12
#undef SPI2_SIN_PTB23
#undef SPI2_SIN_PTD14
#undef SPI2_SOUT_PTB22
#undef SPI2_SOUT_PTD13
#undef UART3_CTS_b_PTB13
#undef UART3_CTS_b_PTB9
#undef UART3_CTS_b_PTC19
#undef UART3_CTS_b_PTE6
#undef UART3_RTS_b_PTB12
#undef UART3_RTS_b_PTB8
#undef UART3_RTS_b_PTC18
#undef UART3_RX_PTB10
#undef UART3_RX_PTC16
#undef UART3_RX_PTE5
#undef UART3_TX_PTB11
#undef UART3_TX_PTC17
#undef UART3_TX_PTE4
#undef UART4_CTS_b_PTC13
#undef UART4_CTS_b_PTE26
#undef UART4_RTS_b_PTC12
#undef UART4_RX_PTC14
#undef UART4_RX_PTE25
#undef UART4_TX_PTC15
#undef UART4_TX_PTE24
#undef UART5_CTS_b_PTD11
#undef UART5_RTS_b_PTD10
#undef UART5_RX_PTD8
#undef UART5_TX_PTD9

/* Signals specific to this part */
#define CLKOUT32K_PTE0 KINETIS_MUX('E',0,1)
#define CLKOUT32K_PTE26 KINETIS_MUX('E',26,1)
#define LPUART0_CTS_b_PTB9 KINETIS_MUX('B',9,3)
#define LPUART0_CTS_b_PTC2 KINETIS_MUX('C',2,7)
#define LPUART0_CTS_b_PTD1 KINETIS_MUX('D',1,6)
#define LPUART0_CTS_b_PTE6 KINETIS_MUX('E',6,3)
#define LPUART0_RTS_b_PTC1 KINETIS_MUX('C',1,7)
#define LPUART0_RTS_b_PTC18 KINETIS_MUX('C',18,3)
#define LPUART0_RTS_b_PTD0 KINETIS_MUX('D',0,6)
#define LPUART0_RX_PTB10 KINETIS_MUX('B',10,3)
#define LPUART0_RX_PTC16 KINETIS_MUX('C',16,3)
#define LPUART0_RX_PTC3 KINETIS_MUX('C',3,7)
#define LPUART0_RX_PTD2 KINETIS_MUX('D',2,6)
#define LPUART0_RX_PTE5 KINETIS_MUX('E',5,3)
#define LPUART0_TX_PTB11 KINETIS_MUX('B',11,3)
#define LPUART0_TX_PTC17 KINETIS_MUX('C',17,3)
#define LPUART0_TX_PTC4 KINETIS_MUX('C',4,7)
#define LPUART0_TX_PTD3 KINETIS_MUX('D',3,6)
#define LPUART0_TX_PTE4 KINETIS_MUX('E',4,3)

#endif /* _ZEPHYR_DTS_BINDING_MK22FN512VLL12_WRAPPER_ */
