/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#ifndef FSL_FLASH_ADAPTER_H_
#define FSL_FLASH_ADAPTER_H_

/*******************************************************************************
 * Definitions
 ******************************************************************************/

#ifdef __RAM_IMAGE__
#define FLASH_DRIVER_IS_FLASH_RESIDENT 0
#endif

#if !defined(FLASH_DRIVER_IS_FLASH_RESIDENT)
#if (!defined(BL_TARGET_ROM) && !defined(BL_TARGET_RAM))
#define FLASH_DRIVER_IS_FLASH_RESIDENT 1 /*!< Used for the flash resident application. */
#else
#define FLASH_DRIVER_IS_FLASH_RESIDENT 0 /*!< Used for the non-flash resident application. */
#endif
#endif

#define FLASH                   FMU
#define FLASH_FSTAT_FAIL_MASK   FMU_FSTAT_FAIL_MASK
#define FLASH_FSTAT_CMDABT_MASK FMU_FSTAT_CMDABT_MASK
#define FLASH_FSTAT_PVIOL_MASK  FMU_FSTAT_PVIOL_MASK
#define FLASH_FSTAT_ACCERR_MASK FMU_FSTAT_ACCERR_MASK
#define FLASH_FSTAT_CWSABT_MASK FMU_FSTAT_CWSABT_MASK
#define FLASH_FSTAT_CCIF_MASK   FMU_FSTAT_CCIF_MASK
#define FLASH_FSTAT_CMDPRT_MASK FMU_FSTAT_CMDPRT_MASK
#define FLASH_FSTAT_CMDP_MASK   FMU_FSTAT_CMDP_MASK
#define FLASH_FSTAT_CMDDID_MASK FMU_FSTAT_CMDDID_MASK
#define FLASH_FSTAT_DFDIF_MASK  FMU_FSTAT_DFDIF_MASK
#define FLASH_FSTAT_PEWEN_MASK  FMU_FSTAT_PEWEN_MASK
#define FLASH_FSTAT_PERDY_MASK  FMU_FSTAT_PERDY_MASK


#define FLASH_FEATURE_ARRAY_COUNT             FSL_FEATURE_FLASH_ARRAY_COUNT

#define FLASH_FEATURE_ARRAY0_START_ADDRESS    FSL_FEATURE_FLASH_ARRAY0_START_ADDRESS
#define FLASH_FEATURE_ARRAY0_SIZE             FSL_FEATURE_FLASH_ARRAY0_SIZE
#define FLASH_FEATURE_ARRAY1_START_ADDRESS    FSL_FEATURE_FLASH_ARRAY1_START_ADDRESS
#define FLASH_FEATURE_ARRAY1_SIZE             FSL_FEATURE_FLASH_ARRAY1_SIZE

#define FLASH_FEATURE_IFR0_ARRAY0_START_ADDRESS     FSL_FEATURE_FLASH_IFR0_ARRAY0_START_ADDRESS
#define FLASH_FEATURE_IFR0_ARRAY0_SIZE              FSL_FEATURE_FLASH_IFR0_ARRAY0_SIZE
#define FLASH_FEATURE_IFR0_ARRAY1_START_ADDRESS     FSL_FEATURE_FLASH_IFR0_ARRAY1_START_ADDRESS
#define FLASH_FEATURE_IFR0_ARRAY1_SIZE              FSL_FEATURE_FLASH_IFR0_ARRAY1_SIZE

#define FLASH_FEATURE_SECTOR_SIZE         FSL_FEATURE_FLASH_SECTOR_SIZE
#define FLASH_FEATURE_PHRASE_SIZE         FSL_FEATURE_FLASH_PHRASE_SIZE
#define FLASH_FEATURE_PAGE_SIZE           FSL_FEATURE_FLASH_PAGE_SIZE
#define FLASH_FEATURE_PHRASE_SIZE_IN_WORD (4u)
#define FLASH_FEATURE_PAGE_SIZE_IN_WORD   (32u)


#endif /* FSL_FLASH_ADAPTER_H_ */
