/*
 * Copyright 2022-2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef NETC_ETHSWT_IP_SA_INIT_PBCFG_H
#define NETC_ETHSWT_IP_SA_INIT_PBCFG_H

#define NETC_ETHSWT_IP_SA_INIT_PBCFG_VENDOR_ID                    43
#define NETC_ETHSWT_IP_SA_INIT_PBCFG_MODULE_ID                    89
#define NETC_ETHSWT_IP_SA_INIT_PBCFG_AR_RELEASE_MAJOR_VERSION     4
#define NETC_ETHSWT_IP_SA_INIT_PBCFG_AR_RELEASE_MINOR_VERSION     7
#define NETC_ETHSWT_IP_SA_INIT_PBCFG_AR_RELEASE_REVISION_VERSION  0
#define NETC_ETHSWT_IP_SA_INIT_PBCFG_SW_MAJOR_VERSION             2
#define NETC_ETHSWT_IP_SA_INIT_PBCFG_SW_MINOR_VERSION             0
#define NETC_ETHSWT_IP_SA_INIT_PBCFG_SW_PATCH_VERSION             1

/* Not used but required to build the baremetal drivers */
#define NETC_ETHSWT_CONFIG_SA_INIT_PB

#endif /* NETC_ETHSWT_IP_SA_INIT_PBCFG_H */
