/*
 * Copyright 2021-2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SRX_IP_INIT_PBCFG_H
#define SRX_IP_INIT_PBCFG_H

/**
*   @file       Srx_Ip_Init_PBcfg.h
*   @version 2.0.1
*
*   @brief   AUTOSAR Sent - module interface
*   @details Configuration settings generated by user settings.
*
*   @addtogroup SENT_DRIVER
*   @{
*/

#ifdef __cplusplus
extern "C" {
#endif


/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
#include "Mcal.h"

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
#define SRX_IP_PBCFG_INIT_VENDOR_ID                         43
#define SRX_IP_PBCFG_INIT_AR_RELEASE_MAJOR_VERSION          4
#define SRX_IP_PBCFG_INIT_AR_RELEASE_MINOR_VERSION          7
#define SRX_IP_PBCFG_INIT_AR_RELEASE_REVISION_VERSION       0
#define SRX_IP_PBCFG_INIT_SW_MAJOR_VERSION                  2
#define SRX_IP_PBCFG_INIT_SW_MINOR_VERSION                  0
#define SRX_IP_PBCFG_INIT_SW_PATCH_VERSION                  1

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/
#ifndef DISABLE_MCAL_INTERMODULE_ASR_CHECK
    /* Check if current file and Mcal.h header file are of the same Autosar version */
    #if ((SRX_IP_PBCFG_INIT_AR_RELEASE_MAJOR_VERSION != MCAL_AR_RELEASE_MAJOR_VERSION) || \
         (SRX_IP_PBCFG_INIT_AR_RELEASE_MINOR_VERSION != MCAL_AR_RELEASE_MINOR_VERSION))
        #error "AutoSar Version Numbers of Srx_Ip_PBcfg.h and Mcal.h are different"
    #endif
#endif
/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/

#ifdef __cplusplus
           }
#endif

/** @} */

#endif /* SRX_IP_INIT_PBCFG_H */


