/*--------------------------------------------------------------------------*/
/* Copyright 2025-2026 NXP                                                  */
/*                                                                          */
/* SPDX-License-Identifier: BSD-3-Clause                                    */
/*                                                                          */
/* Redistribution and use in source and binary forms, with or without       */
/* modification, are permitted provided that the following conditions are   */
/* met:                                                                     */
/*                                                                          */
/* 1. Redistributions of source code must retain the above copyright        */
/*    notice, this list of conditions and the following disclaimer.         */
/*                                                                          */
/* 2. Redistributions in binary form must reproduce the above copyright     */
/*    notice, this list of conditions and the following disclaimer in the   */
/*    documentation and/or other materials provided with the distribution.  */
/*                                                                          */
/* 3. Neither the name of the copyright holder nor the names of its         */
/*    contributors may be used to endorse or promote products derived from  */
/*    this software without specific prior written permission.              */
/*                                                                          */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  */
/* IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED    */
/* TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A          */
/* PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT       */
/* HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,   */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR   */
/* PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF   */
/* LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING     */
/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS       */
/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.             */
/*--------------------------------------------------------------------------*/

#ifndef NXPCL_CONFIG_H_
#define NXPCL_CONFIG_H_

//commented defines for all enabled features
//#define MCUXCL_FEATURE_AEADMODES_CCM
//#define MCUXCL_FEATURE_AEADMODES_GCM
//#define MCUXCL_FEATURE_AEAD_CONTEXT_INTEGRITY_PROTECTION
//#define MCUXCL_FEATURE_AEAD_ENCRYPT_DECRYPT
//#define MCUXCL_FEATURE_AEAD_MULTIPART
//#define MCUXCL_FEATURE_AEAD_ONESHOT
//#define MCUXCL_FEATURE_AES
//#define MCUXCL_FEATURE_AES128
//#define MCUXCL_FEATURE_AES256
//#define MCUXCL_FEATURE_AES_MASKED_SUBKEY_IN_CONTEXT
//#define MCUXCL_FEATURE_BUFFER_USE_POINTER
//#define MCUXCL_FEATURE_CIPHERMODES_CBC
//#define MCUXCL_FEATURE_CIPHERMODES_CTR
//#define MCUXCL_FEATURE_CIPHERMODES_CTR_INTERNAL
//#define MCUXCL_FEATURE_CIPHERMODES_DMA_NONBLOCKING
//#define MCUXCL_FEATURE_CIPHERMODES_ECB
//#define MCUXCL_FEATURE_CIPHER_CONTEXT_INTEGRITY_PROTECTION
//#define MCUXCL_FEATURE_CIPHER_ENCRYPT_DECRYPT
//#define MCUXCL_FEATURE_CIPHER_MULTIPART
//#define MCUXCL_FEATURE_CIPHER_ONESHOT
//#define MCUXCL_FEATURE_CRC
//#define MCUXCL_FEATURE_CRC_CRC32
//#define MCUXCL_FEATURE_CRC_HW
//#define MCUXCL_FEATURE_CSSL_DI_INCLUDE_NONE
//#define MCUXCL_FEATURE_CSSL_DI_INCLUDE_SECURE_COUNTER
//#define MCUXCL_FEATURE_CSSL_DI_USE_SECURE_COUNTER
//#define MCUXCL_FEATURE_CSSL_FP_EXCLUDE_COVERITY_PRAGMAS
//#define MCUXCL_FEATURE_CSSL_FP_INCLUDE_NONE
//#define MCUXCL_FEATURE_CSSL_FP_INCLUDE_SECURE_COUNTER
//#define MCUXCL_FEATURE_CSSL_FP_USE_SECURE_COUNTER
//#define MCUXCL_FEATURE_CSSL_MEMORY_ARM
//#define MCUXCL_FEATURE_CSSL_MEMORY_ARM_COMPARE
//#define MCUXCL_FEATURE_CSSL_MEMORY_ARM_COPY
//#define MCUXCL_FEATURE_CSSL_MEMORY_C_CLEAR
//#define MCUXCL_FEATURE_CSSL_MEMORY_C_SECURE_SET
//#define MCUXCL_FEATURE_CSSL_MEMORY_C_SET
//#define MCUXCL_FEATURE_CSSL_MEMORY_C_XOR
//#define MCUXCL_FEATURE_CSSL_MEMORY_PRNG_STUB
//#define MCUXCL_FEATURE_CSSL_SC_ARM_ASM
//#define MCUXCL_FEATURE_CSSL_SC_INCLUDE_NONE
//#define MCUXCL_FEATURE_CSSL_SC_INCLUDE_SW_LOCAL
//#define MCUXCL_FEATURE_CSSL_SC_USE_SW_LOCAL
//#define MCUXCL_FEATURE_DMA
//#define MCUXCL_FEATURE_DMA_SGI_HANDSHAKE
//#define MCUXCL_FEATURE_ECC
//#define MCUXCL_FEATURE_ECC_ANSIX9P_CURVES
//#define MCUXCL_FEATURE_ECC_BRAINPOOLR1_CURVES
//#define MCUXCL_FEATURE_ECC_BRAINPOOLT1_CURVES
//#define MCUXCL_FEATURE_ECC_CURVE25519
//#define MCUXCL_FEATURE_ECC_CURVE448
//#define MCUXCL_FEATURE_ECC_ECDH
//#define MCUXCL_FEATURE_ECC_ECDSA_SIGN
//#define MCUXCL_FEATURE_ECC_ECDSA_VERIFY
//#define MCUXCL_FEATURE_ECC_ED25519
//#define MCUXCL_FEATURE_ECC_EDDSA
//#define MCUXCL_FEATURE_ECC_EDDSA_SIGN
//#define MCUXCL_FEATURE_ECC_EDDSA_VERIFY
//#define MCUXCL_FEATURE_ECC_MONTDH
//#define MCUXCL_FEATURE_ECC_MONTGOMERY
//#define MCUXCL_FEATURE_ECC_NISTPR1_CURVES
//#define MCUXCL_FEATURE_ECC_SECPK1_CURVES
//#define MCUXCL_FEATURE_ECC_SECPR1_CURVES
//#define MCUXCL_FEATURE_ECC_STRENGTH_CHECK
//#define MCUXCL_FEATURE_ECC_TWISTEDEDWARDS
//#define MCUXCL_FEATURE_ECC_WEIERECC_DECODEPOINT
//#define MCUXCL_FEATURE_ECC_WEIERECC_GENERATECUSTOMDOMAINPARAMS
//#define MCUXCL_FEATURE_ECC_WEIERECC_KEYGENERATION
//#define MCUXCL_FEATURE_ECC_WEIERECC_KEYVALIDATION
//#define MCUXCL_FEATURE_ECC_WEIERSTRASS
//#define MCUXCL_FEATURE_EXAMPLE_PKC_ENABLED
//#define MCUXCL_FEATURE_EXPORTED_FEATURE_HEADER
//#define MCUXCL_FEATURE_FFDH
//#define MCUXCL_FEATURE_FFDH_RFC2631_EXTENDED_PUBLIC_KEY_VALIDATION
//#define MCUXCL_FEATURE_FFDH_RFC7919_FFDHE2048
//#define MCUXCL_FEATURE_FFDH_RFC7919_FFDHE3072
//#define MCUXCL_FEATURE_FFDH_RFC7919_FFDHE4096
//#define MCUXCL_FEATURE_FFDH_RFC7919_FFDHE6144
//#define MCUXCL_FEATURE_FFDH_RFC7919_FFDHE8192
//#define MCUXCL_FEATURE_GLIKEY
//#define MCUXCL_FEATURE_GLIKEY_STEPS_4
//#define MCUXCL_FEATURE_HASH
//#define MCUXCL_FEATURE_HASHMODES
//#define MCUXCL_FEATURE_HASH_COMPUTE
//#define MCUXCL_FEATURE_HASH_DMA_NONBLOCKING
//#define MCUXCL_FEATURE_HASH_MULTIPART
//#define MCUXCL_FEATURE_HASH_OIDS
//#define MCUXCL_FEATURE_HASH_ONESHOT
//#define MCUXCL_FEATURE_HASH_SGI
//#define MCUXCL_FEATURE_HASH_SGI_COUNT_WORKAROUND
//#define MCUXCL_FEATURE_HASH_SGI_SHA_224
//#define MCUXCL_FEATURE_HASH_SGI_SHA_256
//#define MCUXCL_FEATURE_HASH_SGI_SHA_384
//#define MCUXCL_FEATURE_HASH_SGI_SHA_512
//#define MCUXCL_FEATURE_HMAC
//#define MCUXCL_FEATURE_HW_ARM
//#define MCUXCL_FEATURE_HW_DMA
//#define MCUXCL_FEATURE_HW_GLIKEY
//#define MCUXCL_FEATURE_HW_PKC
//#define MCUXCL_FEATURE_HW_SGI
//#define MCUXCL_FEATURE_HW_TRNG
//#define MCUXCL_FEATURE_HW_UNALIGNED_MEMORY_ACCESS
//#define MCUXCL_FEATURE_INTERNAL_INCLUDES_FLAG
//#define MCUXCL_FEATURE_KEY_AGREEMENT
//#define MCUXCL_FEATURE_KEY_ENCODE
//#define MCUXCL_FEATURE_KEY_ENCODING_AES_RFC3394
//#define MCUXCL_FEATURE_KEY_FLUSH
//#define MCUXCL_FEATURE_KEY_GENERATION
//#define MCUXCL_FEATURE_KEY_GENERATION_RSA
//#define MCUXCL_FEATURE_KEY_LOAD
//#define MCUXCL_FEATURE_KEY_PRELOADEDKEYS
//#define MCUXCL_FEATURE_KEY_RECODE
//#define MCUXCL_FEATURE_KEY_SETENCODING
//#define MCUXCL_FEATURE_KEY_VALIDATION
//#define MCUXCL_FEATURE_MAC
//#define MCUXCL_FEATURE_MACMODES_CBCMAC_INTERNAL
//#define MCUXCL_FEATURE_MACMODES_CMAC
//#define MCUXCL_FEATURE_MACMODES_DMA_NONBLOCKING
//#define MCUXCL_FEATURE_MACMODES_GMAC_INTERNAL
//#define MCUXCL_FEATURE_MACMODES_MULTIPART_INTERNAL
//#define MCUXCL_FEATURE_MAC_COMPUTE
//#define MCUXCL_FEATURE_MAC_CONTEXT_INTEGRITY_PROTECTION
//#define MCUXCL_FEATURE_MAC_MULTIPART
//#define MCUXCL_FEATURE_MAC_ONESHOT
//#define MCUXCL_FEATURE_MATH_EXACTDIVIDE
//#define MCUXCL_FEATURE_MATH_MOD_SQUAREROOT
//#define MCUXCL_FEATURE_MATH_REDUCEMODEVEN
//#define MCUXCL_FEATURE_MATH_SECMODEXP
//#define MCUXCL_FEATURE_MATH_SQRMULTL2R
//#define MCUXCL_FEATURE_PADDING_ISO9797_1_M1
//#define MCUXCL_FEATURE_PADDING_ISO9797_1_M2
//#define MCUXCL_FEATURE_PADDING_PKCS7
//#define MCUXCL_FEATURE_PADDING_REMOVAL
//#define MCUXCL_FEATURE_PKC
//#define MCUXCL_FEATURE_PKC_CRR_HEADER
//#define MCUXCL_FEATURE_PKC_EXPORT_BE_INTERNAL
//#define MCUXCL_FEATURE_PKC_EXPORT_LE_INTERNAL
//#define MCUXCL_FEATURE_PKC_IMPORT_BE_INTERNAL
//#define MCUXCL_FEATURE_PKC_IMPORT_LE_INTERNAL
//#define MCUXCL_FEATURE_PKC_RAM_8KB
//#define MCUXCL_FEATURE_PKC_SECURE_EXPORT_BE_INTERNAL
//#define MCUXCL_FEATURE_PKC_SECURE_EXPORT_LE_INTERNAL
//#define MCUXCL_FEATURE_PKC_SECURE_IMPORT_BE_INTERNAL
//#define MCUXCL_FEATURE_PKC_SWITCH_ENDIANNESS_INTERNAL
//#define MCUXCL_FEATURE_PKC_UPTRT_RANDOMIZATION_INTERNAL
//#define MCUXCL_FEATURE_PRNG
//#define MCUXCL_FEATURE_PRNG_SGI_SFRSEED
//#define MCUXCL_FEATURE_RANDOM
//#define MCUXCL_FEATURE_RANDOMMODES_CTRDRBG
//#define MCUXCL_FEATURE_RANDOMMODES_CTRDRBG_SGI
//#define MCUXCL_FEATURE_RANDOMMODES_DERIVATION_FUNCTION
//#define MCUXCL_FEATURE_RANDOMMODES_NORMALMODE
//#define MCUXCL_FEATURE_RANDOMMODES_PATCHMODE
//#define MCUXCL_FEATURE_RANDOMMODES_PR_DISABLED
//#define MCUXCL_FEATURE_RANDOMMODES_SECSTRENGTH_256
//#define MCUXCL_FEATURE_RANDOMMODES_TESTMODE
//#define MCUXCL_FEATURE_RSA_PKC
//#define MCUXCL_FEATURE_RSA_RSAES_PKCS1v15
//#define MCUXCL_FEATURE_RSA_RSASSA_PKCS1v15
//#define MCUXCL_FEATURE_RSA_RSASSA_PSS
//#define MCUXCL_FEATURE_RSA_STRENGTH_CHECK
//#define MCUXCL_FEATURE_SESSION_ENTRYEXIT_EARLYEXIT
//#define MCUXCL_FEATURE_SESSION_HAS_RANDOM
//#define MCUXCL_FEATURE_SESSION_JOBS
//#define MCUXCL_FEATURE_SESSION_PKCWA_CHECK
//#define MCUXCL_FEATURE_SGI
//#define MCUXCL_FEATURE_SGI_AUTOMODE_WORKAROUND_READ_FULL_DATOUT
//#define MCUXCL_FEATURE_SIGNATURE_DOUBLE_VERIFICATION
//#define MCUXCL_FEATURE_SIGNATURE_ECDSA
//#define MCUXCL_FEATURE_SIGNATURE_EDDSA
//#define MCUXCL_FEATURE_SIGNATURE_ONESHOT
//#define MCUXCL_FEATURE_SIGNATURE_RSA_SIGN
//#define MCUXCL_FEATURE_SIGNATURE_RSA_VERIFY
//#define MCUXCL_FEATURE_SIGNATURE_SIGN
//#define MCUXCL_FEATURE_SIGNATURE_VERIFY
//#define MCUXCL_FEATURE_SIGNATURE_VERIFY_PARAMETER_PROTECTION
//#define MCUXCL_FEATURE_SOURCE_DELIVERY
//#define MCUXCL_FEATURE_TRNG_CRR_HEADER
//#define MCUXCL_FEATURE_TRNG_SA_TRNG
//#define MCUXCL_FEATURE_TRNG_SA_TRNG_256
//#define MCUXCL_FEATURE_TRNG_SA_TRNG_DUAL_OSCILLATOR_MODE

//defines for exported features
#define MCUXCL_FEATURE_AEAD_SELFTEST 1
#define MCUXCL_FEATURE_CIPHERMODES_DMA_NONBLOCKING 1
#define MCUXCL_FEATURE_CIPHER_RSA_DECRYPT 1
#define MCUXCL_FEATURE_CIPHER_RSA_ENCRYPT 1
#define MCUXCL_FEATURE_CIPHER_SELFTEST 1
#define MCUXCL_FEATURE_CSSL_MEMORY_ARM_SECURE_COMPARE 1
#define MCUXCL_FEATURE_CSSL_MEMORY_ARM_SECURE_COPY 1
#define MCUXCL_FEATURE_CSSL_MEMORY_ARM_SECURE_XOR 1
#define MCUXCL_FEATURE_ECC_ANSIX9P_CURVES 1
#define MCUXCL_FEATURE_ECC_ARITHMETICOPERATION 1
#define MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_POINTADD 1
#define MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_POINTSUB 1
#define MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_SCALARMULT 1
#define MCUXCL_FEATURE_ECC_ARITHMETICOPERATION_SECURESCALARMULT 1
#define MCUXCL_FEATURE_ECC_BRAINPOOLR1_CURVES 1
#define MCUXCL_FEATURE_ECC_BRAINPOOLT1_CURVES 1
#define MCUXCL_FEATURE_ECC_CURVE25519 1
#define MCUXCL_FEATURE_ECC_EDDSA 1
#define MCUXCL_FEATURE_ECC_MONTDH 1
#define MCUXCL_FEATURE_ECC_NISTPR1_CURVES 1
#define MCUXCL_FEATURE_ECC_SECPK1_CURVES 1
#define MCUXCL_FEATURE_ECC_SECPR1_CURVES 1
#define MCUXCL_FEATURE_FFDH_RFC2631_EXTENDED_PUBLIC_KEY_VALIDATION 1
#define MCUXCL_FEATURE_FFDH_RFC7919_FFDHE6144 1
#define MCUXCL_FEATURE_FFDH_RFC7919_FFDHE8192 1
#define MCUXCL_FEATURE_HASH_C_SHA3 1
#define MCUXCL_FEATURE_HASH_C_SHA3_SHAKE 1
#define MCUXCL_FEATURE_HASH_OIDS 1
#define MCUXCL_FEATURE_HASH_SELFTEST 1
#define MCUXCL_FEATURE_KEY_DERIVATION 1
#define MCUXCL_FEATURE_KEY_SELFTEST 1
#define MCUXCL_FEATURE_MAC_SELFTEST 1
#define MCUXCL_FEATURE_PKC_RAM_8KB 1
#define MCUXCL_FEATURE_PRNG_SGI_SFRSEED 1
#define MCUXCL_FEATURE_RANDOMMODES_SECSTRENGTH_256 1
#define MCUXCL_FEATURE_RSA_RSAES_OAEP 1
#define MCUXCL_FEATURE_SIGNATURE_SELFTEST 1
#define MCUXCL_FEATURE_TRNG_SA_TRNG 1
#define MCUXCL_FEATURE_TRNG_SA_TRNG_256 1
#define MCUXCL_FEATURE_XOF_C_SHAKE_128 1
#define MCUXCL_FEATURE_XOF_C_SHAKE_256 1

#endif
