/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC54016JET100/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC54016JBD100-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 524a2a38a6eed7d8
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC54016JET100_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC54016JET100_WRAPPER_

#include "LPC54016JBD100-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC54016JET100_WRAPPER_ */
