/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC54608J512BD208/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC54618J512BD208-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 225a91e7569881e5
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC54608J512BD208_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC54608J512BD208_WRAPPER_

#include "LPC54618J512BD208-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC54608J512BD208_WRAPPER_ */
