/*
 * NOTE: File generated by gen_soc_headers.py
 * from LPC54S018J4MET180/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to LPC54018J4MET180-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 06f895fe03141b69
 */

#ifndef _ZEPHYR_DTS_BINDING_LPC54S018J4MET180_WRAPPER_
#define _ZEPHYR_DTS_BINDING_LPC54S018J4MET180_WRAPPER_

#include "LPC54018J4MET180-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_LPC54S018J4MET180_WRAPPER_ */
