/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXL255VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXL255VDF-pinctrl.h with this part's differences applied
 * below (67 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 04fb576203f0bd83
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXL255VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXL255VLL_WRAPPER_

#include "MCXL255VDF-pinctrl.h"

/* Signals not present on this part */
#undef CT0_MAT0_P3_8
#undef CT0_MAT2_P1_4
#undef CT0_MAT3_P1_5
#undef CT1_MAT1_P2_26
#undef CT2_MAT0_P1_13
#undef CT2_MAT1_P1_14
#undef CT2_MAT3_P1_8
#undef CT2_MAT3_P2_9
#undef HSADC0_A8_P2_26
#undef LPI2C0_SCLS_P1_8
#undef LPI2C0_SDAS_P1_9
#undef LPI2C1_SCL_P1_13
#undef LPI2C1_SCL_P1_4
#undef LPI2C1_SDA_P1_14
#undef LPI2C1_SDA_P1_5
#undef LPSPI1_SCK_P1_9
#undef LPSPI1_SDO_P1_8
#undef LPUART0_CTS_B_P1_14
#undef LPUART0_RTS_B_P1_13
#undef LPUART0_RXD_P1_8
#undef LPUART0_TXD_P1_9
#undef LPUART1_CTS_B_P1_5
#undef LPUART1_CTS_B_P3_7
#undef LPUART1_RTS_B_P1_4
#undef LPUART1_RXD_P2_8
#undef LPUART1_TXD_P2_9
#undef P1_13
#undef P1_14
#undef P1_4
#undef P1_5
#undef P1_8
#undef P1_9
#undef P2_26
#undef P2_8
#undef P2_9
#undef P3_7
#undef P3_8
#undef SLCD_23_P2_8
#undef SLCD_24_P2_9
#undef SLCD_32_P2_26
#undef SLCD_34_P3_7
#undef SLCD_35_P3_8
#undef SLCD_4_P1_8
#undef SLCD_5_P1_9
#undef SLCD_7_P1_13
#undef SLCD_8_P1_14
#undef TRIG_IN10_P3_8
#undef TRIG_IN12_P2_9
#undef TRIG_IN13_P2_26
#undef TRIG_IN13_P2_8
#undef TRIG_IN16_P1_8
#undef TRIG_IN17_P1_4
#undef TRIG_IN17_P1_9
#undef TRIG_IN18_P1_13
#undef TRIG_IN18_P1_5
#undef TRIG_IN19_P1_14
#undef TRIG_IN9_P3_7
#undef TRIG_OUT0_P3_8
#undef TRIG_OUT3_P2_26
#undef TRIG_OUT4_P2_9
#undef TRIG_OUT5_P2_8
#undef TRIG_OUT6_P1_4
#undef TRIG_OUT7_P1_5
#undef WUU_P24_P3_7
#undef WUU_P2_P1_5
#undef WUU_P4_P1_8
#undef WUU_P5_P1_14

#endif /* _ZEPHYR_DTS_BINDING_MCXL255VLL_WRAPPER_ */
