/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXL254VDF/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXL255VDF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 04fb576203f0bd83
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXL254VDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXL254VDF_WRAPPER_

#include "MCXL255VDF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXL254VDF_WRAPPER_ */
