/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXL254VLL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXL255VLL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: b7e8a8d22dfc51a5
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXL254VLL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXL254VLL_WRAPPER_

#include "MCXL255VLL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXL254VLL_WRAPPER_ */
