/*
** ###################################################################
**     Processors:          MIMX95294AVTN_ca55
**                          MIMX95294AVTN_cm33
**                          MIMX95294AVTN_cm7
**                          MIMX95294AVYN_ca55
**                          MIMX95294AVYN_cm33
**                          MIMX95294AVYN_cm7
**                          MIMX95294AVZN_ca55
**                          MIMX95294AVZN_cm33
**                          MIMX95294AVZN_cm7
**                          MIMX95294CVTN_ca55
**                          MIMX95294CVTN_cm33
**                          MIMX95294CVTN_cm7
**                          MIMX95294CVYN_ca55
**                          MIMX95294CVYN_cm33
**                          MIMX95294CVYN_cm7
**                          MIMX95294CVZN_ca55
**                          MIMX95294CVZN_cm33
**                          MIMX95294CVZN_cm7
**                          MIMX95294DVTN_ca55
**                          MIMX95294DVTN_cm33
**                          MIMX95294DVTN_cm7
**                          MIMX95294DVYN_ca55
**                          MIMX95294DVYN_cm33
**                          MIMX95294DVYN_cm7
**                          MIMX95294DVZN_ca55
**                          MIMX95294DVZN_cm33
**                          MIMX95294DVZN_cm7
**                          MIMX95294XVTN_ca55
**                          MIMX95294XVTN_cm33
**                          MIMX95294XVTN_cm7
**                          MIMX95294XVYN_ca55
**                          MIMX95294XVYN_cm33
**                          MIMX95294XVYN_cm7
**                          MIMX95294XVZN_ca55
**                          MIMX95294XVZN_cm33
**                          MIMX95294XVZN_cm7
**
**     Version:             rev. 2.0, 2024-10-29
**     Build:               b250903
**
**     Abstract:
**         CMSIS Peripheral Access Layer for HSIO_BLK_CTRL_HSIOMIX
**
**     Copyright 1997-2016 Freescale Semiconductor, Inc.
**     Copyright 2016-2025 NXP
**     SPDX-License-Identifier: BSD-3-Clause
**
**     http:                 www.nxp.com
**     mail:                 support@nxp.com
**
**     Revisions:
**     - rev. 1.0 (2023-01-10)
**         Initial version.
**     - rev. 2.0 (2024-10-29)
**         Change the device header file from single flat file to multiple files based on peripherals,
**         each peripheral with dedicated header file located in periphN folder.
**
** ###################################################################
*/

/*!
 * @file PERI_HSIO_BLK_CTRL_HSIOMIX.h
 * @version 2.0
 * @date 2024-10-29
 * @brief CMSIS Peripheral Access Layer for HSIO_BLK_CTRL_HSIOMIX
 *
 * CMSIS Peripheral Access Layer for HSIO_BLK_CTRL_HSIOMIX
 */

#if !defined(PERI_HSIO_BLK_CTRL_HSIOMIX_H_)
#define PERI_HSIO_BLK_CTRL_HSIOMIX_H_            /**< Symbol preventing repeated inclusion */

#if (defined(CPU_MIMX95294AVTN_ca55) || defined(CPU_MIMX95294AVYN_ca55) || defined(CPU_MIMX95294AVZN_ca55) || defined(CPU_MIMX95294CVTN_ca55) || defined(CPU_MIMX95294CVYN_ca55) || defined(CPU_MIMX95294CVZN_ca55) || defined(CPU_MIMX95294DVTN_ca55) || defined(CPU_MIMX95294DVYN_ca55) || defined(CPU_MIMX95294DVZN_ca55) || defined(CPU_MIMX95294XVTN_ca55) || defined(CPU_MIMX95294XVYN_ca55) || defined(CPU_MIMX95294XVZN_ca55))
#include "MIMX95294_ca55_COMMON.h"
#elif (defined(CPU_MIMX95294AVTN_cm33) || defined(CPU_MIMX95294AVYN_cm33) || defined(CPU_MIMX95294AVZN_cm33) || defined(CPU_MIMX95294CVTN_cm33) || defined(CPU_MIMX95294CVYN_cm33) || defined(CPU_MIMX95294CVZN_cm33) || defined(CPU_MIMX95294DVTN_cm33) || defined(CPU_MIMX95294DVYN_cm33) || defined(CPU_MIMX95294DVZN_cm33) || defined(CPU_MIMX95294XVTN_cm33) || defined(CPU_MIMX95294XVYN_cm33) || defined(CPU_MIMX95294XVZN_cm33))
#include "MIMX95294_cm33_COMMON.h"
#elif (defined(CPU_MIMX95294AVTN_cm7) || defined(CPU_MIMX95294AVYN_cm7) || defined(CPU_MIMX95294AVZN_cm7) || defined(CPU_MIMX95294CVTN_cm7) || defined(CPU_MIMX95294CVYN_cm7) || defined(CPU_MIMX95294CVZN_cm7) || defined(CPU_MIMX95294DVTN_cm7) || defined(CPU_MIMX95294DVYN_cm7) || defined(CPU_MIMX95294DVZN_cm7) || defined(CPU_MIMX95294XVTN_cm7) || defined(CPU_MIMX95294XVYN_cm7) || defined(CPU_MIMX95294XVZN_cm7))
#include "MIMX95294_cm7_COMMON.h"
#else
  #error "No valid CPU defined!"
#endif

/* ----------------------------------------------------------------------------
   -- Device Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup Peripheral_access_layer Device Peripheral Access Layer
 * @{
 */


/*
** Start of section using anonymous unions
*/

#if defined(__ARMCC_VERSION)
  #if (__ARMCC_VERSION >= 6010050)
    #pragma clang diagnostic push
  #else
    #pragma push
    #pragma anon_unions
  #endif
#elif defined(__GNUC__)
  /* anonymous unions are enabled by default */
#elif defined(__IAR_SYSTEMS_ICC__)
  #pragma language=extended
#else
  #error Not supported compiler type
#endif

/* ----------------------------------------------------------------------------
   -- HSIO_BLK_CTRL_HSIOMIX Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup HSIO_BLK_CTRL_HSIOMIX_Peripheral_Access_Layer HSIO_BLK_CTRL_HSIOMIX Peripheral Access Layer
 * @{
 */

/** HSIO_BLK_CTRL_HSIOMIX - Register Layout Typedef */
typedef struct {
  __IO uint32_t GPR_REG0;                          /**< General Purpose Register 0, offset: 0x0 */
       uint8_t RESERVED_0[12];
  __IO uint32_t USB1_WAKEUP_CTRL;                  /**< USB1 Wakeup Control, offset: 0x10 */
  __IO uint32_t USB2_WAKEUP_CTRL;                  /**< USB2 Wakeup Control, offset: 0x14 */
  __I  uint32_t USB1_WAKEUP_STATUS;                /**< USB1 Wakeup Status, offset: 0x18 */
  __I  uint32_t USB2_WAKEUP_STATUS;                /**< USB2 Wakeup Status, offset: 0x1C */
       uint8_t RESERVED_1[8];
  __IO uint32_t USB2_AXQOS_DEFAULT;                /**< USB2 AXI Initiator QoS Programmable, offset: 0x28 */
  __IO uint32_t USB2_AXQOS_PANIC;                  /**< USB2 AXI Initiator QoS (Panic Mode) Programmable, offset: 0x2C */
  __IO uint32_t PCIE1_AXQOS_DEFAULT;               /**< PCIE1 AXI Initiator QoS Programmable, offset: 0x30 */
  __IO uint32_t PCIE1_AXQOS_PANIC;                 /**< PCIE1 AXI Initiator QoS (Panic Mode) Programmable, offset: 0x34 */
       uint8_t RESERVED_2[8];
  __IO uint32_t PCIE1_DMA_XFER_GO_TOGG;            /**< PCIE1 DMA Engine Descriptor Transfer Go Toggle, offset: 0x40 */
       uint8_t RESERVED_3[12];
  __IO uint32_t PCIE1_REG;                         /**< PCIe1, offset: 0x50 */
       uint8_t RESERVED_4[12];
  __I  uint32_t PCIE1_MSTR_AWMISC_INFO_HDR_34DW_0; /**< PCIe1 Controller 0 AXI Initiator 3rd and 4th Header DW [31:0], offset: 0x60 */
  __I  uint32_t PCIE1_MSTR_AWMISC_INFO_HDR_34DW_1; /**< PCIe1 Controller 0 AXI Initiator 3rd and 4th Header DW [63:32], offset: 0x64 */
       uint8_t RESERVED_5[8];
  __I  uint32_t PCIE1_MSTR_AWMISC_INFO_0;          /**< PCIe1 Controller 0 AXI Target Write Transaction Information, offset: 0x70 */
  __I  uint32_t PCIE1_MSTR_AWMISC_INFO_1;          /**< PCIe1 Controller 0 AXI Target Write Transaction Information, offset: 0x74 */
       uint8_t RESERVED_6[8];
  __I  uint32_t PCIE1_MSTR_ARMISC_INFO_0;          /**< PCIe1 Controller 0 AXI Target Read Transaction Information, offset: 0x80 */
  __I  uint32_t PCIE1_MSTR_ARMISC_INFO_1;          /**< PCIe1 Controller 0 AXI Target Read Transaction Information, offset: 0x84 */
       uint8_t RESERVED_7[8];
  __I  uint32_t PCIE1_DEBUG_SIGNAL;                /**< PCIe1 Debug Trace Bus, offset: 0x90 */
       uint8_t RESERVED_8[4];
  __I  uint32_t PCIE1_PHY_DTB_OUT;                 /**< Digital Test Bus Output, offset: 0x98 */
  __IO uint32_t LPCG_FORCE_ON_OFF_SEL;             /**< Force ON OFF Select of LPCG, offset: 0x9C */
  __IO uint32_t LPCG_FORCE_ON_OFF;                 /**< LPCG Force ON OFF Control, offset: 0xA0 */
  __IO uint32_t USB_SLAVE_RD_HURRY;                /**< USB AXI Bus Read Hurry Signal, offset: 0xA4 */
  __IO uint32_t USB_SLAVE_RD_PRESS;                /**< USB AXI Bus Read Press Signal, offset: 0xA8 */
  __IO uint32_t USB_SLAVE_WR_HURRY;                /**< USB AXI Bus Write Hurry Signal, offset: 0xAC */
       uint8_t RESERVED_9[4];
  __IO uint32_t USB_SLAVE_WR_PRESS;                /**< USB AXI Bus Write Press Signal, offset: 0xB4 */
       uint8_t RESERVED_10[4];
  __IO uint32_t CR_PARA_CLK_GATE;                  /**< cr_para Clock Gate Signal, offset: 0xBC */
  __IO uint32_t LFAST_IO_REG;                      /**< General Purpose Register for LFAST IO, offset: 0xC0 */
  __IO uint32_t APB_IPS_ERR_GEN;                   /**< USB and PCIe IPS/APB Bus Error Signal Generation Control, offset: 0xC4 */
  __IO uint32_t ENTLINK_UNDERFLOW_CTRL;            /**< ENETlink TX Adapter Underflow Control, offset: 0xC8 */
  __IO uint32_t PCIE_AXI_RD_HURRY_PRESS;           /**< PCIE AXI Read Hurry/Press, offset: 0xCC */
  __IO uint32_t PCIE_AXI_WR_HURRY_PRESS;           /**< PCIE AXI Write Hurry/Press, offset: 0xD0 */
} HSIO_BLK_CTRL_HSIOMIX_Type;

/* ----------------------------------------------------------------------------
   -- HSIO_BLK_CTRL_HSIOMIX Register Masks
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup HSIO_BLK_CTRL_HSIOMIX_Register_Masks HSIO_BLK_CTRL_HSIOMIX Register Masks
 * @{
 */

/*! @name GPR_REG0 - General Purpose Register 0 */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE1_PERST_N_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE1_PERST_N_SHIFT (0U)
/*! PCIE1_PERST_N - PCIE1_PERST_N */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE1_PERST_N(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE1_PERST_N_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE1_PERST_N_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB1_BYPASS_LOGIC_SEL_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB1_BYPASS_LOGIC_SEL_SHIFT (4U)
/*! USB1_BYPASS_LOGIC_SEL - USB1 AUTO_RESUME Logic Selection
 *  0b0..From USB2 Controller
 *  0b1..From Wakeup logic outside USB2
 */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB1_BYPASS_LOGIC_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB1_BYPASS_LOGIC_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB1_BYPASS_LOGIC_SEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB2_BYPASS_LOGIC_SEL_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB2_BYPASS_LOGIC_SEL_SHIFT (5U)
/*! USB2_BYPASS_LOGIC_SEL - USB2 AUTO_RESUME Logic Selection
 *  0b0..From USB2 Controller
 *  0b1..From Wakeup logic outside USB2
 */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB2_BYPASS_LOGIC_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB2_BYPASS_LOGIC_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB2_BYPASS_LOGIC_SEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB_PHY_REF_CLK_SEL_MASK (0x40U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB_PHY_REF_CLK_SEL_SHIFT (6U)
/*! USB_PHY_REF_CLK_SEL - USB PHY Reference Clock Selection
 *  0b0..24 MHz external oscillator
 *  0b1..100 MHz high performance PLL
 */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB_PHY_REF_CLK_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB_PHY_REF_CLK_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB_PHY_REF_CLK_SEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CFG_READY_MASK (0x80U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CFG_READY_SHIFT (7U)
/*! CFG_READY - Configuration Ready */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CFG_READY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CFG_READY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CFG_READY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CRS_CLEAR_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CRS_CLEAR_SHIFT (8U)
/*! CRS_CLEAR - Clear Configuration Retry Status Interrupt */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CRS_CLEAR(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CRS_CLEAR_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CRS_CLEAR_MASK)
/*! @} */

/*! @name USB1_WAKEUP_CTRL - USB1 Wakeup Control */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_SHIFT (0U)
/*! OTG_WKDPDMCHG_EN - Enable Signal for Wakeup from DP/DM Change
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WKDPDMCHG_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_SHIFT (1U)
/*! OTG_VBUS_WAKE_EN - Enable Signal for Wakeup from VBUS Valid Change
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_WAKE_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_SHIFT (2U)
/*! OTG_ID_WAKEUP_EN - Enable Signal for Wakeup from ID Change
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_ID_WAKEUP_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_U3_WAKE_EN_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_U3_WAKE_EN_SHIFT (3U)
/*! OTG_U3_WAKE_EN - Enable Signal for Wakeup from U3 State
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_U3_WAKE_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_U3_WAKE_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_U3_WAKE_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_SHIFT (4U)
/*! OTG_VBUS_SOURCE_SEL - OTG VBUS Source Select
 *  0b0..Select vbus_valid
 *  0b1..Select sessvld
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_SHIFT (5U)
/*! OTG_CONN_WAKEUP_EN - Enable Signal for Wakeup from Connection or Disconnection
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_EN_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_EN_SHIFT (8U)
/*! AUTORESUME_EN - Auto-Resume Enable
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_DATADLY_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_DATADLY_SHIFT (9U)
/*! AUTORESUME_DATADLY - AUTORESUME_DATADLY */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_DATADLY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_DATADLY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_DATADLY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_ENDLY_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_ENDLY_SHIFT (10U)
/*! AUTORESUME_ENDLY - Auto-Resume Finish Signal */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_ENDLY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_ENDLY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_ENDLY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_LOWSPEED_EN_MASK (0x800U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_LOWSPEED_EN_SHIFT (11U)
/*! LOWSPEED_EN - Low-speed Auto-resume Enable
 *  0b0..Full/high speed
 *  0b1..Low speed
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_LOWSPEED_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_LOWSPEED_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_LOWSPEED_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMDATA_MASK (0x1000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMDATA_SHIFT (12U)
/*! PHY_BYPASSDMDATA - Data for DM Transmitter Digital Bypass */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMDATA(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMDATA_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMDATA_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMEN_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMEN_SHIFT (13U)
/*! PHY_BYPASSDMEN - DM Transmitter Digital Bypass Enable
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMEN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMEN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMEN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPDATA_MASK (0x4000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPDATA_SHIFT (14U)
/*! PHY_BYPASSDPDATA - Data for DP Transmitter Digital Bypass */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPDATA(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPDATA_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPDATA_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPEN_MASK (0x8000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPEN_SHIFT (15U)
/*! PHY_BYPASSDPEN - DP Transmitter Digital Bypass Enable
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPEN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPEN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPEN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSSEL_MASK (0x10000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSSEL_SHIFT (16U)
/*! PHY_BYPASSSEL - Transmitter Digital Bypass Select */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSSEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSSEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSSEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WAKE_ENABLE_MASK (0x80000000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WAKE_ENABLE_SHIFT (31U)
/*! OTG_WAKE_ENABLE - Global Wakeup Interrupt Enable
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WAKE_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WAKE_ENABLE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WAKE_ENABLE_MASK)
/*! @} */

/*! @name USB2_WAKEUP_CTRL - USB2 Wakeup Control */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_SHIFT (0U)
/*! OTG_WKDPDMCHG_EN - Enable Signal for Wakeup from DP/DM Change
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WKDPDMCHG_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_SHIFT (1U)
/*! OTG_VBUS_WAKE_EN - Enable Signal for Wakeup from VBUS Valid Change
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_WAKE_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_SHIFT (2U)
/*! OTG_ID_WAKEUP_EN - Enable Signal for Wakeup from ID Change
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_ID_WAKEUP_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_U3_WAKE_EN_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_U3_WAKE_EN_SHIFT (3U)
/*! OTG_U3_WAKE_EN - Enable Signal for Wakeup from U3 State
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_U3_WAKE_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_U3_WAKE_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_U3_WAKE_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_SHIFT (4U)
/*! OTG_VBUS_SOURCE_SEL - OTG VBUS Source Select
 *  0b0..Select vbus_valid
 *  0b1..Select ssvld
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_SHIFT (5U)
/*! OTG_CONN_WAKEUP_EN - Enable Signal for Wakeup from Connection or Disconnection */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_EN_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_EN_SHIFT (8U)
/*! AUTORESUME_EN - Auto-Resume Enable
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_DATADLY_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_DATADLY_SHIFT (9U)
/*! AUTORESUME_DATADLY - AUTORESUME_DATADLY */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_DATADLY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_DATADLY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_DATADLY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_ENDLY_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_ENDLY_SHIFT (10U)
/*! AUTORESUME_ENDLY - Auto-Resume Finish Signal */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_ENDLY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_ENDLY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_ENDLY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_LOWSPEED_EN_MASK (0x800U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_LOWSPEED_EN_SHIFT (11U)
/*! LOWSPEED_EN - Low-speed Auto-resume Enable
 *  0b0..Full/high speed
 *  0b1..Low speed
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_LOWSPEED_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_LOWSPEED_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_LOWSPEED_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMDATA_MASK (0x1000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMDATA_SHIFT (12U)
/*! PHY_BYPASSDMDATA - Data for DM Transmitter Digital Bypass */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMDATA(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMDATA_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMDATA_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMEN_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMEN_SHIFT (13U)
/*! PHY_BYPASSDMEN - DM Transmitter Digital Bypass Enable
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMEN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMEN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMEN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPDATA_MASK (0x4000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPDATA_SHIFT (14U)
/*! PHY_BYPASSDPDATA - Data for DP Transmitter Digital Bypass */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPDATA(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPDATA_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPDATA_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPEN_MASK (0x8000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPEN_SHIFT (15U)
/*! PHY_BYPASSDPEN - DP Transmitter Digital Bypass Enable
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPEN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPEN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPEN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSSEL_MASK (0x10000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSSEL_SHIFT (16U)
/*! PHY_BYPASSSEL - Transmitter Digital Bypass Select */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSSEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSSEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSSEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WAKE_ENABLE_MASK (0x80000000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WAKE_ENABLE_SHIFT (31U)
/*! OTG_WAKE_ENABLE - Global Wakeup Interrupt Enable
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WAKE_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WAKE_ENABLE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WAKE_ENABLE_MASK)
/*! @} */

/*! @name USB1_WAKEUP_STATUS - USB1 Wakeup Status */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_SHIFT (0U)
/*! OTG_DP_DM_WAKEUP_INTERRUPT - Wakeup Interrupt Status of DP DM */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_SHIFT (1U)
/*! OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT - Wakeup Interrupt Status of VBUS or Session Valid */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_SHIFT (2U)
/*! OTG_ID_WAKEUP_INTERRUPT - Wakeup Interrupt Status form ID */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_SHIFT (3U)
/*! OTG_U3_WAKEUP_INTERRUP - Wakeup Interrupt Status form U3 State */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_SHIFT (4U)
/*! OTG_PHY_LINESTATE0_0 - Wakeup Source Linestate[0] */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_SHIFT (5U)
/*! OTG_PHY_LINESTATE0_1 - Wakeup Source Linestate[1] */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_IDDIG0_MASK (0x40U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_IDDIG0_SHIFT (6U)
/*! OTG_PHY_IDDIG0 - Wakeup Source ID Status */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_IDDIG0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_IDDIG0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_IDDIG0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_MASK (0x80U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_SHIFT (7U)
/*! OTG_PHY_VBUSVALID0 - Wakeup Source VBUS Valid */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_VBUSVALID0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_SHIFT (8U)
/*! OTG_PHY_OTGSESSVLD0 - Wakeup Source Session Valid */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE_RXELECIDLE_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE_RXELECIDLE_SHIFT (9U)
/*! PIPE_RXELECIDLE - Wakeup Source pipe_rxelecidel */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE_RXELECIDLE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE_RXELECIDLE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE_RXELECIDLE_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_HOST_MODE_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_HOST_MODE_SHIFT (10U)
/*! OTG_HOST_MODE - USB drd Mode Indicator
 *  0b0..Device mode
 *  0b1..Host mode
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_HOST_MODE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_HOST_MODE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_HOST_MODE_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE3_POWERDOWN_MASK (0x1800U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE3_POWERDOWN_SHIFT (11U)
/*! PIPE3_POWERDOWN - Pipe Power-down */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE3_POWERDOWN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE3_POWERDOWN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE3_POWERDOWN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_SHIFT (13U)
/*! OTG_CONN_WAKEUP_INTERRUPT - Wakeup Interrupt Status of Connection */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_MASK (0x80000000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_SHIFT (31U)
/*! OTG_WAKEUP_INTERRUPT - Wakeup Interrupt Status */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_MASK)
/*! @} */

/*! @name USB2_WAKEUP_STATUS - USB2 Wakeup Status */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_SHIFT (0U)
/*! OTG_DP_DM_WAKEUP_INTERRUPT - Wakeup Interrupt Status of DP DM */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_SHIFT (1U)
/*! OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT - Wakeup Interrupt Status of VBUS or Session Valid */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_SHIFT (2U)
/*! OTG_ID_WAKEUP_INTERRUPT - Wakeup Interrupt Status form ID */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_SHIFT (3U)
/*! OTG_U3_WAKEUP_INTERRUP - Wakeup Interrupt Status form U3 State */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_SHIFT (4U)
/*! OTG_PHY_LINESTATE0_0 - Wakeup Source Linestate[0] */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_SHIFT (5U)
/*! OTG_PHY_LINESTATE0_1 - Wakeup Source Linestate[1] */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_IDDIG0_MASK (0x40U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_IDDIG0_SHIFT (6U)
/*! OTG_PHY_IDDIG0 - Wakeup Source ID Status */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_IDDIG0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_IDDIG0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_IDDIG0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_MASK (0x80U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_SHIFT (7U)
/*! OTG_PHY_VBUSVALID0 - Wakeup Source VBUS Valid */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_VBUSVALID0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_SHIFT (8U)
/*! OTG_PHY_OTGSESSVLD0 - Wakeup Source Session Valid */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE_RXELECIDLE_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE_RXELECIDLE_SHIFT (9U)
/*! PIPE_RXELECIDLE - Wakeup Source pipe_rxelecidel */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE_RXELECIDLE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE_RXELECIDLE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE_RXELECIDLE_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_HOST_MODE_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_HOST_MODE_SHIFT (10U)
/*! OTG_HOST_MODE - USB drd Mode Indicator
 *  0b0..Device mode
 *  0b1..Host mode
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_HOST_MODE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_HOST_MODE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_HOST_MODE_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE3_POWERDOWN_MASK (0x1800U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE3_POWERDOWN_SHIFT (11U)
/*! PIPE3_POWERDOWN - Pipe Power-down */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE3_POWERDOWN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE3_POWERDOWN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE3_POWERDOWN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_SHIFT (13U)
/*! OTG_CONN_WAKEUP_INTERRUPT - Wakeup Interrupt Status of Connection */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_MASK (0x80000000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_SHIFT (31U)
/*! OTG_WAKEUP_INTERRUPT - Wakeup Interrupt Status */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_MASK)
/*! @} */

/*! @name USB2_AXQOS_DEFAULT - USB2 AXI Initiator QoS Programmable */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT (0U)
/*! AW_QOS_DEFAULT - Write Channel QoS Default Value */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AW_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT (8U)
/*! AR_QOS_DEFAULT - Read Channel QoS Default Value */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AR_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK)
/*! @} */

/*! @name USB2_AXQOS_PANIC - USB2 AXI Initiator QoS (Panic Mode) Programmable */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AW_QOS_PANIC_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AW_QOS_PANIC_SHIFT (0U)
/*! AW_QOS_PANIC - Write Channel QoS Panic Value */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AW_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AW_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AW_QOS_PANIC_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AR_QOS_PANIC_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AR_QOS_PANIC_SHIFT (8U)
/*! AR_QOS_PANIC - Read Channel QoS Panic Value */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AR_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AR_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AR_QOS_PANIC_MASK)
/*! @} */

/*! @name PCIE1_AXQOS_DEFAULT - PCIE1 AXI Initiator QoS Programmable */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT (0U)
/*! AW_QOS_DEFAULT - Write Channel QoS Panic Value */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AW_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT (8U)
/*! AR_QOS_DEFAULT - Read Channel QoS Panic Value */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AR_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK)
/*! @} */

/*! @name PCIE1_AXQOS_PANIC - PCIE1 AXI Initiator QoS (Panic Mode) Programmable */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AW_QOS_PANIC_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AW_QOS_PANIC_SHIFT (0U)
/*! AW_QOS_PANIC - Write Channel QoS Panic Value */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AW_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AW_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AW_QOS_PANIC_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AR_QOS_PANIC_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AR_QOS_PANIC_SHIFT (8U)
/*! AR_QOS_PANIC - Read Channel QoS Panic Value */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AR_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AR_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AR_QOS_PANIC_MASK)
/*! @} */

/*! @name PCIE1_DMA_XFER_GO_TOGG - PCIE1 DMA Engine Descriptor Transfer Go Toggle */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_MASK (0xFU)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_SHIFT (0U)
/*! DMA_RDXFER_GO_TOGG - DMA Read Engine Descriptor Transfer Go Toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_MASK (0xF00U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_SHIFT (8U)
/*! DMA_WDXFER_GO_TOGG - DMA Write Engine Descriptor Transfer Go Toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_MASK (0xF0000U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_SHIFT (16U)
/*! DMA_RDXFER_DONE_TOGG - DMA Read Engine Descriptor Transfer Done Toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_MASK (0xF000000U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_SHIFT (24U)
/*! DMA_WDXFER_DONE_TOGG - DMA Write Engine Descriptor Transfer Done Toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_MASK)
/*! @} */

/*! @name PCIE1_REG - PCIe1 */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_RADM_CPL_TIMEOUT_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_RADM_CPL_TIMEOUT_SHIFT (0U)
/*! RADM_CPL_TIMEOUT - Completion TLP for a Request Received within Expected Time Frame */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_RADM_CPL_TIMEOUT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_RADM_CPL_TIMEOUT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_RADM_CPL_TIMEOUT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_PHY_LANE0_POWER_PRESENT_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_PHY_LANE0_POWER_PRESENT_SHIFT (1U)
/*! PHY_LANE0_POWER_PRESENT - Power Present Indicator for Lane 0 */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_PHY_LANE0_POWER_PRESENT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_PHY_LANE0_POWER_PRESENT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_PHY_LANE0_POWER_PRESENT_MASK)
/*! @} */

/*! @name PCIE1_MSTR_AWMISC_INFO_HDR_34DW_0 - PCIe1 Controller 0 AXI Initiator 3rd and 4th Header DW [31:0] */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_HDR_34DW_0_PCIE1_INFO_MASK (0xFFFFFFFFU)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_HDR_34DW_0_PCIE1_INFO_SHIFT (0U)
/*! PCIE1_INFO - AXI Initiator 3rd and 4th Header DW Bit[31:0] */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_HDR_34DW_0_PCIE1_INFO(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_HDR_34DW_0_PCIE1_INFO_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_HDR_34DW_0_PCIE1_INFO_MASK)
/*! @} */

/*! @name PCIE1_MSTR_AWMISC_INFO_HDR_34DW_1 - PCIe1 Controller 0 AXI Initiator 3rd and 4th Header DW [63:32] */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_HDR_34DW_1_PCIE1_INFO_MASK (0xFFFFFFFFU)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_HDR_34DW_1_PCIE1_INFO_SHIFT (0U)
/*! PCIE1_INFO - AXI Initiator 3rd and 4th Header DW Bit[63:32] */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_HDR_34DW_1_PCIE1_INFO(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_HDR_34DW_1_PCIE1_INFO_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_HDR_34DW_1_PCIE1_INFO_MASK)
/*! @} */

/*! @name PCIE1_MSTR_AWMISC_INFO_0 - PCIe1 Controller 0 AXI Target Write Transaction Information */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_0_PCIE1_MSTR_AWMISC_INFO_MASK (0xFFFFFFFFU)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_0_PCIE1_MSTR_AWMISC_INFO_SHIFT (0U)
/*! PCIE1_MSTR_AWMISC_INFO - AXI Target Write Transaction Information */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_0_PCIE1_MSTR_AWMISC_INFO(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_0_PCIE1_MSTR_AWMISC_INFO_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_0_PCIE1_MSTR_AWMISC_INFO_MASK)
/*! @} */

/*! @name PCIE1_MSTR_AWMISC_INFO_1 - PCIe1 Controller 0 AXI Target Write Transaction Information */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_1_PCIE1_MSTR_AWMISC_INFO_MASK (0xFFFFU)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_1_PCIE1_MSTR_AWMISC_INFO_SHIFT (0U)
/*! PCIE1_MSTR_AWMISC_INFO - AXI Target Write Transaction Information */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_1_PCIE1_MSTR_AWMISC_INFO(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_1_PCIE1_MSTR_AWMISC_INFO_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_AWMISC_INFO_1_PCIE1_MSTR_AWMISC_INFO_MASK)
/*! @} */

/*! @name PCIE1_MSTR_ARMISC_INFO_0 - PCIe1 Controller 0 AXI Target Read Transaction Information */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_ARMISC_INFO_0_PCIE1_MSTR_ARMISC_INFO_MASK (0xFFFFFFFFU)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_ARMISC_INFO_0_PCIE1_MSTR_ARMISC_INFO_SHIFT (0U)
/*! PCIE1_MSTR_ARMISC_INFO - AXI Target Read Transaction Information */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_ARMISC_INFO_0_PCIE1_MSTR_ARMISC_INFO(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_ARMISC_INFO_0_PCIE1_MSTR_ARMISC_INFO_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_ARMISC_INFO_0_PCIE1_MSTR_ARMISC_INFO_MASK)
/*! @} */

/*! @name PCIE1_MSTR_ARMISC_INFO_1 - PCIe1 Controller 0 AXI Target Read Transaction Information */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_ARMISC_INFO_1_PCIE1_MSTR_ARMISC_INFO_MASK (0xFFFFU)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_ARMISC_INFO_1_PCIE1_MSTR_ARMISC_INFO_SHIFT (0U)
/*! PCIE1_MSTR_ARMISC_INFO - AXI Target Read Transaction Information */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_ARMISC_INFO_1_PCIE1_MSTR_ARMISC_INFO(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_ARMISC_INFO_1_PCIE1_MSTR_ARMISC_INFO_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_MSTR_ARMISC_INFO_1_PCIE1_MSTR_ARMISC_INFO_MASK)
/*! @} */

/*! @name PCIE1_DEBUG_SIGNAL - PCIe1 Debug Trace Bus */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DEBUG_SIGNAL_dbg_signals_MASK (0xFFFFFFFFU)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DEBUG_SIGNAL_dbg_signals_SHIFT (0U)
/*! dbg_signals - PCIe Debug Signals */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DEBUG_SIGNAL_dbg_signals(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_DEBUG_SIGNAL_dbg_signals_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_DEBUG_SIGNAL_dbg_signals_MASK)
/*! @} */

/*! @name PCIE1_PHY_DTB_OUT - Digital Test Bus Output */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_PHY_DTB_OUT_PCIE1_PHY_DTB_OUT_MASK (0x3U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_PHY_DTB_OUT_PCIE1_PHY_DTB_OUT_SHIFT (0U)
/*! PCIE1_PHY_DTB_OUT - Digital Test Bus Output */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_PHY_DTB_OUT_PCIE1_PHY_DTB_OUT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_PHY_DTB_OUT_PCIE1_PHY_DTB_OUT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_PHY_DTB_OUT_PCIE1_PHY_DTB_OUT_MASK)
/*! @} */

/*! @name LPCG_FORCE_ON_OFF_SEL - Force ON OFF Select of LPCG */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_root_clk_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_root_clk_SHIFT (0U)
/*! ipc_hsiomix_root_clk - Force ON OFF Select of ipc_hsiomix_root_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_root_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_root_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_root_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_bus_netcmix_133_enet_phy_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_bus_netcmix_133_enet_phy_SHIFT (1U)
/*! bus_netcmix_133_enet_phy - Force ON OFF Select of bus_netcmix_133_enet_phy
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_bus_netcmix_133_enet_phy(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_bus_netcmix_133_enet_phy_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_bus_netcmix_133_enet_phy_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_500M_DIV1_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_500M_DIV1_SHIFT (2U)
/*! ipc_test_netc_eth_500M_DIV1 - Force ON OFF Select of ipc_test_netc_eth_500M_DIV1
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_500M_DIV1(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_500M_DIV1_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_500M_DIV1_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_mgr_clk_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_mgr_clk_SHIFT (3U)
/*! ipc_mgr_clk - Force ON OFF Select of ipc_mgr_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_mgr_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_mgr_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_mgr_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_gpr_clk_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_gpr_clk_SHIFT (4U)
/*! ipc_hsiomix_gpr_clk - Force ON OFF Select of ipc_hsiomix_gpr_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_gpr_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_gpr_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_gpr_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_trout_24M_root_clk_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_trout_24M_root_clk_SHIFT (5U)
/*! ipc_trout_24M_root_clk - Force ON OFF Select of ipc_trout_24M_root_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_trout_24M_root_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_trout_24M_root_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_trout_24M_root_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_24M_clk_root_MASK (0x40U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_24M_clk_root_SHIFT (6U)
/*! ipc_hsiomix_24M_clk_root - Force ON OFF Select of ipc_hsiomix_24M_clk_root
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_24M_clk_root(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_24M_clk_root_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_hsiomix_24M_clk_root_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pll_ai_clk_MASK (0x80U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pll_ai_clk_SHIFT (7U)
/*! ipc_pll_ai_clk - Force ON OFF Select of ipc_pll_ai_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pll_ai_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pll_ai_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pll_ai_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_clk_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_clk_SHIFT (8U)
/*! ipc_usb2_clk - Force ON OFF Select of ipc_usb2_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_32k_sw_clk_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_32k_sw_clk_SHIFT (9U)
/*! ipc_usb2_32k_sw_clk - Force ON OFF Select of ipc_usb2_32k_sw_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_32k_sw_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_32k_sw_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_32k_sw_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_32k_clk_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_32k_clk_SHIFT (10U)
/*! ipc_usb2_32k_clk - Force ON OFF Select of ipc_usb2_32k_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_32k_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_32k_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_32k_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie1_clk_MASK (0x800U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie1_clk_SHIFT (11U)
/*! ipc_pcie1_clk - Force ON OFF Select of ipc_pcie1_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie1_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie1_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie1_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie1_auxclk_MASK (0x1000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie1_auxclk_SHIFT (12U)
/*! ipc_pcie1_auxclk - Force ON OFF Select of ipc_pcie1_auxclk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie1_auxclk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie1_auxclk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie1_auxclk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_157M_clk_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_157M_clk_SHIFT (13U)
/*! ipc_test_pcie_157M_clk - Force ON OFF Select of ipc_test_pcie_157M_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_157M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_157M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_157M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_400M_clk_MASK (0x4000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_400M_clk_SHIFT (14U)
/*! ipc_test_pcie_400M_clk - Force ON OFF Select of ipc_test_pcie_400M_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_400M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_400M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_400M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_500M_clk_MASK (0x8000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_500M_clk_SHIFT (15U)
/*! ipc_test_pcie_500M_clk - Force ON OFF Select of ipc_test_pcie_500M_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_500M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_500M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_pcie_500M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_60M_clk_MASK (0x10000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_60M_clk_SHIFT (16U)
/*! ipc_usb2_scan_60M_clk - Force ON OFF Select of ipc_usb2_scan_60M_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_60M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_60M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_60M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_100M_clk_MASK (0x20000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_100M_clk_SHIFT (17U)
/*! ipc_usb2_scan_100M_clk - Force ON OFF Select of ipc_usb2_scan_100M_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_100M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_100M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_100M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_480M_clk_MASK (0x40000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_480M_clk_SHIFT (18U)
/*! ipc_usb2_scan_480M_clk - Force ON OFF Select of ipc_usb2_scan_480M_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_480M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_480M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_usb2_scan_480M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie_phyref_bist_clk_MASK (0x80000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie_phyref_bist_clk_SHIFT (19U)
/*! ipc_pcie_phyref_bist_clk - Force ON OFF Select of ipc_pcie_phyref_bist_clk
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie_phyref_bist_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie_phyref_bist_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_pcie_phyref_bist_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_netcmix_clk_root_333_enet_phy_MASK (0x100000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_netcmix_clk_root_333_enet_phy_SHIFT (20U)
/*! netcmix_clk_root_333_enet_phy - Force ON OFF Select of netcmix_clk_root_333_enet_phy
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_netcmix_clk_root_333_enet_phy(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_netcmix_clk_root_333_enet_phy_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_netcmix_clk_root_333_enet_phy_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_200M_DIV2_MASK (0x200000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_200M_DIV2_SHIFT (21U)
/*! ipc_test_netc_eth_200M_DIV2 - Force ON OFF Select of ipc_test_netc_eth_200M_DIV2
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_200M_DIV2(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_200M_DIV2_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_200M_DIV2_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_625M_DIV2_MASK (0x400000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_625M_DIV2_SHIFT (22U)
/*! ipc_test_netc_eth_625M_DIV2 - Force ON OFF Select of ipc_test_netc_eth_625M_DIV2
 *  0b0..Not selected
 *  0b1..Selected
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_625M_DIV2(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_625M_DIV2_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_SEL_ipc_test_netc_eth_625M_DIV2_MASK)
/*! @} */

/*! @name LPCG_FORCE_ON_OFF - LPCG Force ON OFF Control */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_root_clk_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_root_clk_SHIFT (0U)
/*! ipc_hsiomix_root_clk - Force ON OFF of ipc_hsiomix_root_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_root_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_root_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_root_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_bus_netcmix_133_enet_phy_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_bus_netcmix_133_enet_phy_SHIFT (1U)
/*! bus_netcmix_133_enet_phy - Force ON OFF of bus_netcmix_133_enet_phy
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_bus_netcmix_133_enet_phy(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_bus_netcmix_133_enet_phy_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_bus_netcmix_133_enet_phy_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_500M_DIV1_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_500M_DIV1_SHIFT (2U)
/*! ipc_test_netc_eth_500M_DIV1 - Force ON OFF of ipc_test_netc_eth_500M_DIV1
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_500M_DIV1(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_500M_DIV1_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_500M_DIV1_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_mgr_clk_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_mgr_clk_SHIFT (3U)
/*! ipc_mgr_clk - Force ON OFF of ipc_mgr_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_mgr_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_mgr_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_mgr_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_gpr_clk_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_gpr_clk_SHIFT (4U)
/*! ipc_hsiomix_gpr_clk - Force ON OFF of ipc_hsiomix_gpr_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_gpr_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_gpr_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_gpr_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_trout_24M_root_clk_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_trout_24M_root_clk_SHIFT (5U)
/*! ipc_trout_24M_root_clk - Force ON OFF of ipc_trout_24M_root_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_trout_24M_root_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_trout_24M_root_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_trout_24M_root_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_24M_clk_root_MASK (0x40U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_24M_clk_root_SHIFT (6U)
/*! ipc_hsiomix_24M_clk_root - Force ON OFF of ipc_hsiomix_24M_clk_root
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_24M_clk_root(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_24M_clk_root_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_hsiomix_24M_clk_root_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pll_ai_clk_MASK (0x80U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pll_ai_clk_SHIFT (7U)
/*! ipc_pll_ai_clk - Force ON OFF of ipc_pll_ai_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pll_ai_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pll_ai_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pll_ai_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_clk_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_clk_SHIFT (8U)
/*! ipc_usb2_clk - Force ON OFF of ipc_usb2_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_32k_sw_clk_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_32k_sw_clk_SHIFT (9U)
/*! ipc_usb2_32k_sw_clk - Force ON OFF of ipc_usb2_32k_sw_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_32k_sw_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_32k_sw_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_32k_sw_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_32k_clk_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_32k_clk_SHIFT (10U)
/*! ipc_usb2_32k_clk - Force ON OFF of ipc_usb2_32k_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_32k_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_32k_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_32k_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie1_clk_MASK (0x800U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie1_clk_SHIFT (11U)
/*! ipc_pcie1_clk - Force ON OFF of ipc_pcie1_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie1_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie1_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie1_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie1_auxclk_MASK (0x1000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie1_auxclk_SHIFT (12U)
/*! ipc_pcie1_auxclk - Force ON OFF of ipc_pcie1_auxclk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie1_auxclk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie1_auxclk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie1_auxclk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_157M_clk_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_157M_clk_SHIFT (13U)
/*! ipc_test_pcie_157M_clk - Force ON OFF of ipc_test_pcie_157M_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_157M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_157M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_157M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_400M_clk_MASK (0x4000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_400M_clk_SHIFT (14U)
/*! ipc_test_pcie_400M_clk - Force ON OFF of ipc_test_pcie_400M_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_400M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_400M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_400M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_500M_clk_MASK (0x8000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_500M_clk_SHIFT (15U)
/*! ipc_test_pcie_500M_clk - Force ON OFF of ipc_test_pcie_500M_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_500M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_500M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_pcie_500M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_60M_clk_MASK (0x10000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_60M_clk_SHIFT (16U)
/*! ipc_usb2_scan_60M_clk - Force ON OFF of ipc_usb2_scan_60M_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_60M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_60M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_60M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_100M_clk_MASK (0x20000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_100M_clk_SHIFT (17U)
/*! ipc_usb2_scan_100M_clk - Force ON OFF of ipc_usb2_scan_100M_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_100M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_100M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_100M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_480M_clk_MASK (0x40000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_480M_clk_SHIFT (18U)
/*! ipc_usb2_scan_480M_clk - Force ON OFF of ipc_usb2_scan_480M_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_480M_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_480M_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_usb2_scan_480M_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie_phyref_bist_clk_MASK (0x80000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie_phyref_bist_clk_SHIFT (19U)
/*! ipc_pcie_phyref_bist_clk - Force ON OFF of ipc_pcie_phyref_bist_clk
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie_phyref_bist_clk(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie_phyref_bist_clk_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_pcie_phyref_bist_clk_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_netcmix_clk_root_333_enet_phy_MASK (0x100000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_netcmix_clk_root_333_enet_phy_SHIFT (20U)
/*! netcmix_clk_root_333_enet_phy - Force ON OFF of netcmix_clk_root_333_enet_phy
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_netcmix_clk_root_333_enet_phy(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_netcmix_clk_root_333_enet_phy_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_netcmix_clk_root_333_enet_phy_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_200M_DIV2_MASK (0x200000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_200M_DIV2_SHIFT (21U)
/*! ipc_test_netc_eth_200M_DIV2 - Force ON OFF of ipc_test_netc_eth_200M_DIV2
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_200M_DIV2(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_200M_DIV2_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_200M_DIV2_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_625M_DIV2_MASK (0x400000U)
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_625M_DIV2_SHIFT (22U)
/*! ipc_test_netc_eth_625M_DIV2 - Force ON OFF of ipc_test_netc_eth_625M_DIV2
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_625M_DIV2(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_625M_DIV2_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LPCG_FORCE_ON_OFF_ipc_test_netc_eth_625M_DIV2_MASK)
/*! @} */

/*! @name USB_SLAVE_RD_HURRY - USB AXI Bus Read Hurry Signal */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_RD_HURRY_RD_HURRY_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_RD_HURRY_RD_HURRY_SHIFT (0U)
/*! RD_HURRY - USB AXI Bus Read Hurry Signal */
#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_RD_HURRY_RD_HURRY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_RD_HURRY_RD_HURRY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_RD_HURRY_RD_HURRY_MASK)
/*! @} */

/*! @name USB_SLAVE_RD_PRESS - USB AXI Bus Read Press Signal */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_RD_PRESS_RD_PRESS_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_RD_PRESS_RD_PRESS_SHIFT (0U)
/*! RD_PRESS - USB AXI Bus Read Press Signal */
#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_RD_PRESS_RD_PRESS(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_RD_PRESS_RD_PRESS_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_RD_PRESS_RD_PRESS_MASK)
/*! @} */

/*! @name USB_SLAVE_WR_HURRY - USB AXI Bus Write Hurry Signal */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_WR_HURRY_WR_HURRY_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_WR_HURRY_WR_HURRY_SHIFT (0U)
/*! WR_HURRY - USB AXI Bus Write Hurry Signal */
#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_WR_HURRY_WR_HURRY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_WR_HURRY_WR_HURRY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_WR_HURRY_WR_HURRY_MASK)
/*! @} */

/*! @name USB_SLAVE_WR_PRESS - USB AXI Bus Write Press Signal */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_WR_PRESS_WR_PRESS_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_WR_PRESS_WR_PRESS_SHIFT (0U)
/*! WR_PRESS - USB AXI Bus Write Press Signal */
#define HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_WR_PRESS_WR_PRESS(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_WR_PRESS_WR_PRESS_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB_SLAVE_WR_PRESS_WR_PRESS_MASK)
/*! @} */

/*! @name CR_PARA_CLK_GATE - cr_para Clock Gate Signal */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_CR_PARA_CLK_GATE_cr_para_clk_gate_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_CR_PARA_CLK_GATE_cr_para_clk_gate_SHIFT (0U)
/*! cr_para_clk_gate - cr_para Clock Gate */
#define HSIO_BLK_CTRL_HSIOMIX_CR_PARA_CLK_GATE_cr_para_clk_gate(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_CR_PARA_CLK_GATE_cr_para_clk_gate_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_CR_PARA_CLK_GATE_cr_para_clk_gate_MASK)
/*! @} */

/*! @name LFAST_IO_REG - General Purpose Register for LFAST IO */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_INT_LOOPBACK_EN_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_INT_LOOPBACK_EN_SHIFT (0U)
/*! INT_LOOPBACK_EN - Enable Signal for Internal Loopback Testing for ATE */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_INT_LOOPBACK_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_INT_LOOPBACK_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_INT_LOOPBACK_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_LOOPBACK_LV_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_LOOPBACK_LV_SHIFT (1U)
/*! LOOPBACK_LV - Loopback Data to Core Side from Transmitter Output Stage */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_LOOPBACK_LV(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_LOOPBACK_LV_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_LOOPBACK_LV_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_FUNC_OUPUT_EN_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_FUNC_OUPUT_EN_SHIFT (2U)
/*! FUNC_OUPUT_EN - Functional Output Transmitter Enable */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_FUNC_OUPUT_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_FUNC_OUPUT_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_FUNC_OUPUT_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TERM_EN_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TERM_EN_SHIFT (3U)
/*! TERM_EN - Enable Internal 100 Ohm Termination */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TERM_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TERM_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TERM_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_POWER_ON_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_POWER_ON_SHIFT (4U)
/*! POWER_ON - Power ON Indicator from Core_v_det Cell */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_POWER_ON(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_POWER_ON_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_POWER_ON_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_ESD_BOOST_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_ESD_BOOST_SHIFT (5U)
/*! ESD_BOOST - ESD Boost Bus */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_ESD_BOOST(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_ESD_BOOST_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_ESD_BOOST_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_CREF_EN_MASK (0x40U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_CREF_EN_SHIFT (6U)
/*! CREF_EN - Enable Current Reference Control Signal */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_CREF_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_CREF_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_CREF_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT1_MASK (0x80U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT1_SHIFT (7U)
/*! IREF_TX_OPT1 - Control Signal to Adjust/Boost Transmitter Current */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT1(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT1_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT1_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT2_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT2_SHIFT (8U)
/*! IREF_TX_OPT2 - Control Signal to Adjust/Boost Transmitter Current */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT2(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT2_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT2_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT3_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT3_SHIFT (9U)
/*! IREF_TX_OPT3 - Control Signal to Adjust/Boost Transmitter Current */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT3(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT3_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT3_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT4_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT4_SHIFT (10U)
/*! IREF_TX_OPT4 - Control Signal to Adjust/Boost Transmitter Current */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT4(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT4_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT4_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TEST_MODE_SEL_MASK (0x1800U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TEST_MODE_SEL_SHIFT (11U)
/*! TEST_MODE_SEL - Test Mode Control Signal Select */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TEST_MODE_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TEST_MODE_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TEST_MODE_SEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TX_AURORA_MODE_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TX_AURORA_MODE_SHIFT (13U)
/*! TX_AURORA_MODE - TX Aurora Mode */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TX_AURORA_MODE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TX_AURORA_MODE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_TX_AURORA_MODE_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_SWING_TEST_SEL_MASK (0x4000U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_SWING_TEST_SEL_SHIFT (14U)
/*! SWING_TEST_SEL - Swing Test Output Select
 *  0b0..Output 0
 *  0b1..Output 1
 */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_SWING_TEST_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_SWING_TEST_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_SWING_TEST_SEL_MASK)
/*! @} */

/*! @name APB_IPS_ERR_GEN - USB and PCIe IPS/APB Bus Error Signal Generation Control */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_otg1_err_gen_ctrl_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_otg1_err_gen_ctrl_SHIFT (0U)
/*! otg1_err_gen_ctrl - OTG1 IPS Bus Error Signal Generation Control
 *  0b0..Enables
 *  0b1..Disables
 */
#define HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_otg1_err_gen_ctrl(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_otg1_err_gen_ctrl_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_otg1_err_gen_ctrl_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_otg2_err_gen_ctrl_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_otg2_err_gen_ctrl_SHIFT (1U)
/*! otg2_err_gen_ctrl - OTG2 IPS Bus Error Signal Generation Control
 *  0b0..Enables
 *  0b1..Disables
 */
#define HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_otg2_err_gen_ctrl(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_otg2_err_gen_ctrl_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_otg2_err_gen_ctrl_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_pcie_apb_err_gen_ctrl_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_pcie_apb_err_gen_ctrl_SHIFT (2U)
/*! pcie_apb_err_gen_ctrl - PCIe APB Bus Error Signal Generation Control
 *  0b0..Enables
 *  0b1..Disables
 */
#define HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_pcie_apb_err_gen_ctrl(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_pcie_apb_err_gen_ctrl_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_APB_IPS_ERR_GEN_pcie_apb_err_gen_ctrl_MASK)
/*! @} */

/*! @name ENTLINK_UNDERFLOW_CTRL - ENETlink TX Adapter Underflow Control */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_irq_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_irq_SHIFT (0U)
/*! irq - Underflow IRQ Signal */
#define HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_irq(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_irq_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_irq_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_soft_reset_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_soft_reset_SHIFT (1U)
/*! soft_reset - ENETlink Soft Reset */
#define HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_soft_reset(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_soft_reset_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_soft_reset_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_clock_compare_enable_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_clock_compare_enable_SHIFT (2U)
/*! clock_compare_enable - ENETlink Clock Compare Enable
 *  0b0..Disables
 *  0b1..Enables
 */
#define HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_clock_compare_enable(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_clock_compare_enable_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_ENTLINK_UNDERFLOW_CTRL_clock_compare_enable_MASK)
/*! @} */

/*! @name PCIE_AXI_RD_HURRY_PRESS - PCIE AXI Read Hurry/Press */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_RD_HURRY_PRESS_HURRY_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_RD_HURRY_PRESS_HURRY_SHIFT (0U)
/*! HURRY - Read Hurry */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_RD_HURRY_PRESS_HURRY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_RD_HURRY_PRESS_HURRY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_RD_HURRY_PRESS_HURRY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_RD_HURRY_PRESS_PRESS_MASK (0x38U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_RD_HURRY_PRESS_PRESS_SHIFT (3U)
/*! PRESS - Read Press */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_RD_HURRY_PRESS_PRESS(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_RD_HURRY_PRESS_PRESS_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_RD_HURRY_PRESS_PRESS_MASK)
/*! @} */

/*! @name PCIE_AXI_WR_HURRY_PRESS - PCIE AXI Write Hurry/Press */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_WR_HURRY_PRESS_HURRY_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_WR_HURRY_PRESS_HURRY_SHIFT (0U)
/*! HURRY - Write Hurry */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_WR_HURRY_PRESS_HURRY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_WR_HURRY_PRESS_HURRY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_WR_HURRY_PRESS_HURRY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_WR_HURRY_PRESS_PRESS_MASK (0x38U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_WR_HURRY_PRESS_PRESS_SHIFT (3U)
/*! PRESS - Write Press */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_WR_HURRY_PRESS_PRESS(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_WR_HURRY_PRESS_PRESS_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE_AXI_WR_HURRY_PRESS_PRESS_MASK)
/*! @} */


/*!
 * @}
 */ /* end of group HSIO_BLK_CTRL_HSIOMIX_Register_Masks */


/*!
 * @}
 */ /* end of group HSIO_BLK_CTRL_HSIOMIX_Peripheral_Access_Layer */


/*
** End of section using anonymous unions
*/

#if defined(__ARMCC_VERSION)
  #if (__ARMCC_VERSION >= 6010050)
    #pragma clang diagnostic pop
  #else
    #pragma pop
  #endif
#elif defined(__GNUC__)
  /* leave anonymous unions enabled */
#elif defined(__IAR_SYSTEMS_ICC__)
  #pragma language=default
#else
  #error Not supported compiler type
#endif

/*!
 * @}
 */ /* end of group Peripheral_access_layer */


#endif  /* PERI_HSIO_BLK_CTRL_HSIOMIX_H_ */

