/*
** ###################################################################
**     Processors:          MIMX95294AVTN_ca55
**                          MIMX95294AVTN_cm33
**                          MIMX95294AVTN_cm7
**                          MIMX95294AVYN_ca55
**                          MIMX95294AVYN_cm33
**                          MIMX95294AVYN_cm7
**                          MIMX95294AVZN_ca55
**                          MIMX95294AVZN_cm33
**                          MIMX95294AVZN_cm7
**                          MIMX95294CVTN_ca55
**                          MIMX95294CVTN_cm33
**                          MIMX95294CVTN_cm7
**                          MIMX95294CVYN_ca55
**                          MIMX95294CVYN_cm33
**                          MIMX95294CVYN_cm7
**                          MIMX95294CVZN_ca55
**                          MIMX95294CVZN_cm33
**                          MIMX95294CVZN_cm7
**                          MIMX95294DVTN_ca55
**                          MIMX95294DVTN_cm33
**                          MIMX95294DVTN_cm7
**                          MIMX95294DVYN_ca55
**                          MIMX95294DVYN_cm33
**                          MIMX95294DVYN_cm7
**                          MIMX95294DVZN_ca55
**                          MIMX95294DVZN_cm33
**                          MIMX95294DVZN_cm7
**                          MIMX95294XVTN_ca55
**                          MIMX95294XVTN_cm33
**                          MIMX95294XVTN_cm7
**                          MIMX95294XVYN_ca55
**                          MIMX95294XVYN_cm33
**                          MIMX95294XVYN_cm7
**                          MIMX95294XVZN_ca55
**                          MIMX95294XVZN_cm33
**                          MIMX95294XVZN_cm7
**
**     Version:             rev. 2.0, 2024-10-29
**     Build:               b250903
**
**     Abstract:
**         CMSIS Peripheral Access Layer for DSI_V2_HOST_INT
**
**     Copyright 1997-2016 Freescale Semiconductor, Inc.
**     Copyright 2016-2025 NXP
**     SPDX-License-Identifier: BSD-3-Clause
**
**     http:                 www.nxp.com
**     mail:                 support@nxp.com
**
**     Revisions:
**     - rev. 1.0 (2023-01-10)
**         Initial version.
**     - rev. 2.0 (2024-10-29)
**         Change the device header file from single flat file to multiple files based on peripherals,
**         each peripheral with dedicated header file located in periphN folder.
**
** ###################################################################
*/

/*!
 * @file PERI_DSI_V2_HOST_INT.h
 * @version 2.0
 * @date 2024-10-29
 * @brief CMSIS Peripheral Access Layer for DSI_V2_HOST_INT
 *
 * CMSIS Peripheral Access Layer for DSI_V2_HOST_INT
 */

#if !defined(PERI_DSI_V2_HOST_INT_H_)
#define PERI_DSI_V2_HOST_INT_H_                  /**< Symbol preventing repeated inclusion */

#if (defined(CPU_MIMX95294AVTN_ca55) || defined(CPU_MIMX95294AVYN_ca55) || defined(CPU_MIMX95294AVZN_ca55) || defined(CPU_MIMX95294CVTN_ca55) || defined(CPU_MIMX95294CVYN_ca55) || defined(CPU_MIMX95294CVZN_ca55) || defined(CPU_MIMX95294DVTN_ca55) || defined(CPU_MIMX95294DVYN_ca55) || defined(CPU_MIMX95294DVZN_ca55) || defined(CPU_MIMX95294XVTN_ca55) || defined(CPU_MIMX95294XVYN_ca55) || defined(CPU_MIMX95294XVZN_ca55))
#include "MIMX95294_ca55_COMMON.h"
#elif (defined(CPU_MIMX95294AVTN_cm33) || defined(CPU_MIMX95294AVYN_cm33) || defined(CPU_MIMX95294AVZN_cm33) || defined(CPU_MIMX95294CVTN_cm33) || defined(CPU_MIMX95294CVYN_cm33) || defined(CPU_MIMX95294CVZN_cm33) || defined(CPU_MIMX95294DVTN_cm33) || defined(CPU_MIMX95294DVYN_cm33) || defined(CPU_MIMX95294DVZN_cm33) || defined(CPU_MIMX95294XVTN_cm33) || defined(CPU_MIMX95294XVYN_cm33) || defined(CPU_MIMX95294XVZN_cm33))
#include "MIMX95294_cm33_COMMON.h"
#elif (defined(CPU_MIMX95294AVTN_cm7) || defined(CPU_MIMX95294AVYN_cm7) || defined(CPU_MIMX95294AVZN_cm7) || defined(CPU_MIMX95294CVTN_cm7) || defined(CPU_MIMX95294CVYN_cm7) || defined(CPU_MIMX95294CVZN_cm7) || defined(CPU_MIMX95294DVTN_cm7) || defined(CPU_MIMX95294DVYN_cm7) || defined(CPU_MIMX95294DVZN_cm7) || defined(CPU_MIMX95294XVTN_cm7) || defined(CPU_MIMX95294XVYN_cm7) || defined(CPU_MIMX95294XVZN_cm7))
#include "MIMX95294_cm7_COMMON.h"
#else
  #error "No valid CPU defined!"
#endif

/* ----------------------------------------------------------------------------
   -- Device Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup Peripheral_access_layer Device Peripheral Access Layer
 * @{
 */


/*
** Start of section using anonymous unions
*/

#if defined(__ARMCC_VERSION)
  #if (__ARMCC_VERSION >= 6010050)
    #pragma clang diagnostic push
  #else
    #pragma push
    #pragma anon_unions
  #endif
#elif defined(__GNUC__)
  /* anonymous unions are enabled by default */
#elif defined(__IAR_SYSTEMS_ICC__)
  #pragma language=extended
#else
  #error Not supported compiler type
#endif

/* ----------------------------------------------------------------------------
   -- DSI_V2_HOST_INT Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup DSI_V2_HOST_INT_Peripheral_Access_Layer DSI_V2_HOST_INT Peripheral Access Layer
 * @{
 */

/** DSI_V2_HOST_INT - Register Layout Typedef */
typedef struct {
  __I  uint32_t INT_ST_MAIN;                       /**< Interrupt Status Main, offset: 0x0 */
       uint8_t RESERVED_0[28];
  __I  uint32_t INT_ST_PHY;                        /**< PHY Interrupt Sources, offset: 0x20 */
  __I  uint32_t INT_ST_TO;                         /**< PHY Timeouts Interrupt Sources, offset: 0x24 */
  __I  uint32_t INT_ST_ACK;                        /**< ACK Interrupt Sources, offset: 0x28 */
  __I  uint32_t INT_ST_IPI;                        /**< IPI Interrupt Sources, offset: 0x2C */
  __I  uint32_t INT_ST_PRI;                        /**< PRI Interrupt Sources, offset: 0x30 */
  __I  uint32_t INT_ST_CRI;                        /**< CRI Interrupt Sources, offset: 0x34 */
       uint8_t RESERVED_1[40];
  __IO uint32_t INT_UNMASK_PHY;                    /**< Unmask for PHY Interrupt Sources, offset: 0x60 */
  __IO uint32_t INT_UNMASK_TO;                     /**< Unmasks for PHY Timeouts Interrupt Sources, offset: 0x64 */
  __IO uint32_t INT_UNMASK_ACK;                    /**< Unmasks for ACK Interrupt Sources, offset: 0x68 */
  __IO uint32_t INT_UNMASK_IPI;                    /**< Unmasks for IPI Interrupt Sources, offset: 0x6C */
  __IO uint32_t INT_UNMASK_PRI;                    /**< Unmasks for PRI Interrupt Sources, offset: 0x70 */
  __IO uint32_t INT_UNMASK_CRI;                    /**< Unmask for CRI Interrupt Sources, offset: 0x74 */
       uint8_t RESERVED_2[40];
  __IO uint32_t INT_FORCE_PHY;                     /**< Force Flags for PHY Interrupt Sources, offset: 0xA0 */
  __IO uint32_t INT_FORCE_TO;                      /**< Force Flags for PHY Timeouts Interrupt Sources, offset: 0xA4 */
  __IO uint32_t INT_FORCE_ACK;                     /**< Force Flags for ACK Interrupt Sources, offset: 0xA8 */
  __IO uint32_t INT_FORCE_IPI;                     /**< Force Flags for IPI Interrupt Sources, offset: 0xAC */
  __IO uint32_t INT_FORCE_PRI;                     /**< Force Flags for PRI Interrupt Sources, offset: 0xB0 */
  __IO uint32_t INT_FORCE_CRI;                     /**< Force Flags for CRI Interrupt Sources, offset: 0xB4 */
} DSI_V2_HOST_INT_Type;

/* ----------------------------------------------------------------------------
   -- DSI_V2_HOST_INT Register Masks
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup DSI_V2_HOST_INT_Register_Masks DSI_V2_HOST_INT Register Masks
 * @{
 */

/*! @name INT_ST_MAIN - Interrupt Status Main */
/*! @{ */

#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_PHY_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_PHY_SHIFT (0U)
/*! INT_ST_PHY
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_PHY(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_PHY_SHIFT)) & DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_PHY_MASK)

#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_TO_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_TO_SHIFT (1U)
/*! INT_ST_TO
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_TO(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_TO_SHIFT)) & DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_TO_MASK)

#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_ACK_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_ACK_SHIFT (2U)
/*! INT_ST_ACK
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_ACK(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_ACK_SHIFT)) & DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_ACK_MASK)

#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_IPI_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_IPI_SHIFT (3U)
/*! INT_ST_IPI
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_IPI(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_IPI_SHIFT)) & DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_IPI_MASK)

#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_PRI_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_PRI_SHIFT (4U)
/*! INT_ST_PRI
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_PRI(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_PRI_SHIFT)) & DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_PRI_MASK)

#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_CRI_MASK (0x20U)
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_CRI_SHIFT (5U)
/*! INT_ST_CRI
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_CRI(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_CRI_SHIFT)) & DSI_V2_HOST_INT_INT_ST_MAIN_INT_ST_CRI_MASK)
/*! @} */

/*! @name INT_ST_PHY - PHY Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRESC_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRESC_SHIFT (0U)
/*! PHY_L0_ERRESC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRESC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRESC_SHIFT)) & DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRESC_MASK)

#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRSYNCESC_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRSYNCESC_SHIFT (1U)
/*! PHY_L0_ERRSYNCESC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRSYNCESC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRSYNCESC_SHIFT)) & DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRSYNCESC_MASK)

#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTROL_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTROL_SHIFT (2U)
/*! PHY_L0_ERRCONTROL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTROL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTROL_SHIFT)) & DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTROL_MASK)

#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTENTIONLP0_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTENTIONLP0_SHIFT (3U)
/*! PHY_L0_ERRCONTENTIONLP0
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTENTIONLP0(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTENTIONLP0_SHIFT)) & DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTENTIONLP0_MASK)

#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTENTIONLP1_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTENTIONLP1_SHIFT (4U)
/*! PHY_L0_ERRCONTENTIONLP1
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTENTIONLP1(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTENTIONLP1_SHIFT)) & DSI_V2_HOST_INT_INT_ST_PHY_PHY_L0_ERRCONTENTIONLP1_MASK)
/*! @} */

/*! @name INT_ST_TO - PHY Timeouts Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_HSTX_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_HSTX_SHIFT (0U)
/*! ERR_TO_HSTX
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_HSTX(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_HSTX_SHIFT)) & DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_HSTX_MASK)

#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_HSTXRDY_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_HSTXRDY_SHIFT (1U)
/*! ERR_TO_HSTXRDY
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_HSTXRDY(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_HSTXRDY_SHIFT)) & DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_HSTXRDY_MASK)

#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPRX_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPRX_SHIFT (2U)
/*! ERR_TO_LPRX
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPRX(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPRX_SHIFT)) & DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPRX_MASK)

#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXRDY_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXRDY_SHIFT (3U)
/*! ERR_TO_LPTXRDY
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXRDY(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXRDY_SHIFT)) & DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXRDY_MASK)

#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXTRIG_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXTRIG_SHIFT (4U)
/*! ERR_TO_LPTXTRIG
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXTRIG(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXTRIG_SHIFT)) & DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXTRIG_MASK)

#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXULPS_MASK (0x20U)
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXULPS_SHIFT (5U)
/*! ERR_TO_LPTXULPS
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXULPS(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXULPS_SHIFT)) & DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_LPTXULPS_MASK)

#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_BTA_MASK (0x40U)
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_BTA_SHIFT (6U)
/*! ERR_TO_BTA
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_BTA(x)  (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_BTA_SHIFT)) & DSI_V2_HOST_INT_INT_ST_TO_ERR_TO_BTA_MASK)
/*! @} */

/*! @name INT_ST_ACK - ACK Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_0_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_0_SHIFT (0U)
/*! ERR_ACK_RPT_0
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_0(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_0_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_0_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_1_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_1_SHIFT (1U)
/*! ERR_ACK_RPT_1
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_1(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_1_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_1_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_2_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_2_SHIFT (2U)
/*! ERR_ACK_RPT_2
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_2(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_2_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_2_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_3_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_3_SHIFT (3U)
/*! ERR_ACK_RPT_3
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_3(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_3_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_3_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_4_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_4_SHIFT (4U)
/*! ERR_ACK_RPT_4
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_4(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_4_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_4_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_5_MASK (0x20U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_5_SHIFT (5U)
/*! ERR_ACK_RPT_5
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_5(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_5_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_5_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_6_MASK (0x40U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_6_SHIFT (6U)
/*! ERR_ACK_RPT_6
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_6(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_6_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_6_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_7_MASK (0x80U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_7_SHIFT (7U)
/*! ERR_ACK_RPT_7
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_7(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_7_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_7_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_8_MASK (0x100U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_8_SHIFT (8U)
/*! ERR_ACK_RPT_8
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_8(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_8_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_8_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_9_MASK (0x200U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_9_SHIFT (9U)
/*! ERR_ACK_RPT_9
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_9(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_9_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_9_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_10_MASK (0x400U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_10_SHIFT (10U)
/*! ERR_ACK_RPT_10
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_10(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_10_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_10_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_11_MASK (0x800U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_11_SHIFT (11U)
/*! ERR_ACK_RPT_11
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_11(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_11_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_11_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_12_MASK (0x1000U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_12_SHIFT (12U)
/*! ERR_ACK_RPT_12
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_12(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_12_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_12_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_13_MASK (0x2000U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_13_SHIFT (13U)
/*! ERR_ACK_RPT_13
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_13(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_13_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_13_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_14_MASK (0x4000U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_14_SHIFT (14U)
/*! ERR_ACK_RPT_14
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_14(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_14_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_14_MASK)

#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_15_MASK (0x8000U)
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_15_SHIFT (15U)
/*! ERR_ACK_RPT_15
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_15(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_15_SHIFT)) & DSI_V2_HOST_INT_INT_ST_ACK_ERR_ACK_RPT_15_MASK)
/*! @} */

/*! @name INT_ST_IPI - IPI Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_DISPLAY_CMD_TIME_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_DISPLAY_CMD_TIME_SHIFT (0U)
/*! ERR_DISPLAY_CMD_TIME
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_DISPLAY_CMD_TIME(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_IPI_ERR_DISPLAY_CMD_TIME_SHIFT)) & DSI_V2_HOST_INT_INT_ST_IPI_ERR_DISPLAY_CMD_TIME_MASK)

#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_IPI_DTYPE_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_IPI_DTYPE_SHIFT (1U)
/*! ERR_IPI_DTYPE
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_IPI_DTYPE(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_IPI_ERR_IPI_DTYPE_SHIFT)) & DSI_V2_HOST_INT_INT_ST_IPI_ERR_IPI_DTYPE_MASK)

#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_VID_BANDWIDTH_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_VID_BANDWIDTH_SHIFT (2U)
/*! ERR_VID_BANDWIDTH
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_VID_BANDWIDTH(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_IPI_ERR_VID_BANDWIDTH_SHIFT)) & DSI_V2_HOST_INT_INT_ST_IPI_ERR_VID_BANDWIDTH_MASK)

#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_IPI_CMD_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_IPI_CMD_SHIFT (3U)
/*! ERR_IPI_CMD
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_IPI_CMD(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_IPI_ERR_IPI_CMD_SHIFT)) & DSI_V2_HOST_INT_INT_ST_IPI_ERR_IPI_CMD_MASK)

#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_DISPLAY_CMD_OVFL_MASK (0x100U)
#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_DISPLAY_CMD_OVFL_SHIFT (8U)
/*! ERR_DISPLAY_CMD_OVFL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_IPI_ERR_DISPLAY_CMD_OVFL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_IPI_ERR_DISPLAY_CMD_OVFL_SHIFT)) & DSI_V2_HOST_INT_INT_ST_IPI_ERR_DISPLAY_CMD_OVFL_MASK)

#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_EVENT_FIFO_OVER_MASK (0x10000U)
#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_EVENT_FIFO_OVER_SHIFT (16U)
/*! IPI_EVENT_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_EVENT_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_IPI_IPI_EVENT_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_ST_IPI_IPI_EVENT_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_EVENT_FIFO_UNDER_MASK (0x20000U)
#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_EVENT_FIFO_UNDER_SHIFT (17U)
/*! IPI_EVENT_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_EVENT_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_IPI_IPI_EVENT_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_ST_IPI_IPI_EVENT_FIFO_UNDER_MASK)

#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_PIXEL_FIFO_OVER_MASK (0x40000U)
#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_PIXEL_FIFO_OVER_SHIFT (18U)
/*! IPI_PIXEL_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_PIXEL_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_IPI_IPI_PIXEL_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_ST_IPI_IPI_PIXEL_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_PIXEL_FIFO_UNDER_MASK (0x80000U)
#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_PIXEL_FIFO_UNDER_SHIFT (19U)
/*! IPI_PIXEL_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_IPI_IPI_PIXEL_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_IPI_IPI_PIXEL_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_ST_IPI_IPI_PIXEL_FIFO_UNDER_MASK)
/*! @} */

/*! @name INT_ST_PRI - PRI Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_ST_PRI_ERR_PRI_TX_TIME_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_ST_PRI_ERR_PRI_TX_TIME_SHIFT (0U)
/*! ERR_PRI_TX_TIME
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_PRI_ERR_PRI_TX_TIME(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_PRI_ERR_PRI_TX_TIME_SHIFT)) & DSI_V2_HOST_INT_INT_ST_PRI_ERR_PRI_TX_TIME_MASK)

#define DSI_V2_HOST_INT_INT_ST_PRI_ERR_PRI_TX_CMD_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_ST_PRI_ERR_PRI_TX_CMD_SHIFT (1U)
/*! ERR_PRI_TX_CMD
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_PRI_ERR_PRI_TX_CMD(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_PRI_ERR_PRI_TX_CMD_SHIFT)) & DSI_V2_HOST_INT_INT_ST_PRI_ERR_PRI_TX_CMD_MASK)
/*! @} */

/*! @name INT_ST_CRI - CRI Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_CMD_TIME_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_CMD_TIME_SHIFT (0U)
/*! ERR_CRI_CMD_TIME
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_CMD_TIME(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_CMD_TIME_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_CMD_TIME_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_DTYPE_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_DTYPE_SHIFT (1U)
/*! ERR_CRI_DTYPE
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_DTYPE(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_DTYPE_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_DTYPE_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_VCHANNEL_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_VCHANNEL_SHIFT (2U)
/*! ERR_CRI_VCHANNEL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_VCHANNEL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_VCHANNEL_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_VCHANNEL_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_RX_LENGTH_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_RX_LENGTH_SHIFT (3U)
/*! ERR_CRI_RX_LENGTH
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_RX_LENGTH(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_RX_LENGTH_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_RX_LENGTH_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_ECC_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_ECC_SHIFT (4U)
/*! ERR_CRI_ECC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_ECC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_ECC_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_ECC_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_ECC_FATAL_MASK (0x20U)
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_ECC_FATAL_SHIFT (5U)
/*! ERR_CRI_ECC_FATAL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_ECC_FATAL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_ECC_FATAL_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_ECC_FATAL_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_CRC_MASK (0x40U)
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_CRC_SHIFT (6U)
/*! ERR_CRI_CRC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_CRC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_CRC_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_ERR_CRI_CRC_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_RD_PLD_FIFO_OVER_MASK (0x10000U)
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_RD_PLD_FIFO_OVER_SHIFT (16U)
/*! CMD_RD_PLD_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_RD_PLD_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_CMD_RD_PLD_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_CMD_RD_PLD_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_RD_PLD_FIFO_UNDER_MASK (0x20000U)
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_RD_PLD_FIFO_UNDER_SHIFT (17U)
/*! CMD_RD_PLD_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_RD_PLD_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_CMD_RD_PLD_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_CMD_RD_PLD_FIFO_UNDER_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_PLD_FIFO_OVER_MASK (0x40000U)
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_PLD_FIFO_OVER_SHIFT (18U)
/*! CMD_WR_PLD_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_PLD_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_PLD_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_PLD_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_PLD_FIFO_UNDER_MASK (0x80000U)
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_PLD_FIFO_UNDER_SHIFT (19U)
/*! CMD_WR_PLD_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_PLD_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_PLD_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_PLD_FIFO_UNDER_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_HDR_FIFO_OVER_MASK (0x100000U)
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_HDR_FIFO_OVER_SHIFT (20U)
/*! CMD_WR_HDR_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_HDR_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_HDR_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_HDR_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_HDR_FIFO_UNDER_MASK (0x200000U)
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_HDR_FIFO_UNDER_SHIFT (21U)
/*! CMD_WR_HDR_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_HDR_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_HDR_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_ST_CRI_CMD_WR_HDR_FIFO_UNDER_MASK)
/*! @} */

/*! @name INT_UNMASK_PHY - Unmask for PHY Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRESC_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRESC_SHIFT (0U)
/*! UNMASK_PHY_L0_ERRESC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRESC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRESC_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRESC_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRSYNCESC_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRSYNCESC_SHIFT (1U)
/*! UNMASK_PHY_L0_ERRSYNCESC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRSYNCESC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRSYNCESC_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRSYNCESC_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTROL_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTROL_SHIFT (2U)
/*! UNMASK_PHY_L0_ERRCONTROL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTROL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTROL_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTROL_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTENTIONLP0_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTENTIONLP0_SHIFT (3U)
/*! UNMASK_PHY_L0_ERRCONTENTIONLP0
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTENTIONLP0(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTENTIONLP0_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTENTIONLP0_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTENTIONLP1_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTENTIONLP1_SHIFT (4U)
/*! UNMASK_PHY_L0_ERRCONTENTIONLP1
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTENTIONLP1(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTENTIONLP1_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_PHY_L0_ERRCONTENTIONLP1_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_TXHS_FIFO_OVER_MASK (0x10000U)
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_TXHS_FIFO_OVER_SHIFT (16U)
/*! UNMASK_TXHS_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_TXHS_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_TXHS_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_TXHS_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_TXHS_FIFO_UNDER_MASK (0x20000U)
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_TXHS_FIFO_UNDER_SHIFT (17U)
/*! UNMASK_TXHS_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_TXHS_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_TXHS_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_PHY_UNMASK_TXHS_FIFO_UNDER_MASK)
/*! @} */

/*! @name INT_UNMASK_TO - Unmasks for PHY Timeouts Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_HSTX_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_HSTX_SHIFT (0U)
/*! UNMASK_ERR_TO_HSTX
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_HSTX(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_HSTX_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_HSTX_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_HSTXRDY_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_HSTXRDY_SHIFT (1U)
/*! UNMASK_ERR_TO_HSTXRDY
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_HSTXRDY(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_HSTXRDY_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_HSTXRDY_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPRX_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPRX_SHIFT (2U)
/*! UNMASK_ERR_TO_LPRX
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPRX(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPRX_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPRX_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXRDY_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXRDY_SHIFT (3U)
/*! UNMASK_ERR_TO_LPTXRDY
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXRDY(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXRDY_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXRDY_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXTRIG_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXTRIG_SHIFT (4U)
/*! UNMASK_ERR_TO_LPTXTRIG
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXTRIG(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXTRIG_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXTRIG_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXULPS_MASK (0x20U)
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXULPS_SHIFT (5U)
/*! UNMASK_ERR_TO_LPTXULPS
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXULPS(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXULPS_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_LPTXULPS_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_BTA_MASK (0x40U)
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_BTA_SHIFT (6U)
/*! UNMASK_ERR_TO_BTA
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_BTA(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_BTA_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_TO_UNMASK_ERR_TO_BTA_MASK)
/*! @} */

/*! @name INT_UNMASK_ACK - Unmasks for ACK Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_0_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_0_SHIFT (0U)
/*! UNMASK_ERR_ACK_RPT_0
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_0(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_0_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_0_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_1_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_1_SHIFT (1U)
/*! UNMASK_ERR_ACK_RPT_1
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_1(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_1_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_1_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_2_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_2_SHIFT (2U)
/*! UNMASK_ERR_ACK_RPT_2
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_2(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_2_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_2_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_3_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_3_SHIFT (3U)
/*! UNMASK_ERR_ACK_RPT_3
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_3(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_3_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_3_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_4_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_4_SHIFT (4U)
/*! UNMASK_ERR_ACK_RPT_4
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_4(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_4_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_4_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_5_MASK (0x20U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_5_SHIFT (5U)
/*! UNMASK_ERR_ACK_RPT_5
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_5(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_5_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_5_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_6_MASK (0x40U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_6_SHIFT (6U)
/*! UNMASK_ERR_ACK_RPT_6
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_6(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_6_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_6_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_7_MASK (0x80U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_7_SHIFT (7U)
/*! UNMASK_ERR_ACK_RPT_7
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_7(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_7_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_7_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_8_MASK (0x100U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_8_SHIFT (8U)
/*! UNMASK_ERR_ACK_RPT_8
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_8(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_8_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_8_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_9_MASK (0x200U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_9_SHIFT (9U)
/*! UNMASK_ERR_ACK_RPT_9
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_9(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_9_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_9_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_10_MASK (0x400U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_10_SHIFT (10U)
/*! UNMASK_ERR_ACK_RPT_10
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_10(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_10_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_10_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_11_MASK (0x800U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_11_SHIFT (11U)
/*! UNMASK_ERR_ACK_RPT_11
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_11(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_11_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_11_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_12_MASK (0x1000U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_12_SHIFT (12U)
/*! UNMASK_ERR_ACK_RPT_12
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_12(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_12_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_12_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_13_MASK (0x2000U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_13_SHIFT (13U)
/*! UNMASK_ERR_ACK_RPT_13
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_13(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_13_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_13_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_14_MASK (0x4000U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_14_SHIFT (14U)
/*! UNMASK_ERR_ACK_RPT_14
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_14(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_14_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_14_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_15_MASK (0x8000U)
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_15_SHIFT (15U)
/*! UNMASK_ERR_ACK_RPT_15
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_15(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_15_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_ACK_UNMASK_ERR_ACK_RPT_15_MASK)
/*! @} */

/*! @name INT_UNMASK_IPI - Unmasks for IPI Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_DISPLAY_CMD_TIME_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_DISPLAY_CMD_TIME_SHIFT (0U)
/*! UNMASK_ERR_DISPLAY_CMD_TIME
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_DISPLAY_CMD_TIME(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_DISPLAY_CMD_TIME_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_DISPLAY_CMD_TIME_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_IPI_DTYPE_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_IPI_DTYPE_SHIFT (1U)
/*! UNMASK_ERR_IPI_DTYPE
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_IPI_DTYPE(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_IPI_DTYPE_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_IPI_DTYPE_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_VID_BANDWIDTH_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_VID_BANDWIDTH_SHIFT (2U)
/*! UNMASK_ERR_VID_BANDWIDTH
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_VID_BANDWIDTH(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_VID_BANDWIDTH_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_VID_BANDWIDTH_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_IPI_CMD_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_IPI_CMD_SHIFT (3U)
/*! UNMASK_ERR_IPI_CMD
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_IPI_CMD(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_IPI_CMD_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_IPI_CMD_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_DISPLAY_CMD_OVFL_MASK (0x100U)
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_DISPLAY_CMD_OVFL_SHIFT (8U)
/*! UNMASK_ERR_DISPLAY_CMD_OVFL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_DISPLAY_CMD_OVFL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_DISPLAY_CMD_OVFL_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_ERR_DISPLAY_CMD_OVFL_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_EVENT_FIFO_OVER_MASK (0x10000U)
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_EVENT_FIFO_OVER_SHIFT (16U)
/*! UNMASK_IPI_EVENT_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_EVENT_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_EVENT_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_EVENT_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_EVENT_FIFO_UNDER_MASK (0x20000U)
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_EVENT_FIFO_UNDER_SHIFT (17U)
/*! UNMASK_IPI_EVENT_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_EVENT_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_EVENT_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_EVENT_FIFO_UNDER_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_PIXEL_FIFO_OVER_MASK (0x40000U)
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_PIXEL_FIFO_OVER_SHIFT (18U)
/*! UNMASK_IPI_PIXEL_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_PIXEL_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_PIXEL_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_PIXEL_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_PIXEL_FIFO_UNDER_MASK (0x80000U)
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_PIXEL_FIFO_UNDER_SHIFT (19U)
/*! UNMASK_IPI_PIXEL_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_PIXEL_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_PIXEL_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_IPI_UNMASK_IPI_PIXEL_FIFO_UNDER_MASK)
/*! @} */

/*! @name INT_UNMASK_PRI - Unmasks for PRI Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_UNMASK_PRI_UNMASK_ERR_PRI_TX_TIME_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_UNMASK_PRI_UNMASK_ERR_PRI_TX_TIME_SHIFT (0U)
/*! UNMASK_ERR_PRI_TX_TIME
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_PRI_UNMASK_ERR_PRI_TX_TIME(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_PRI_UNMASK_ERR_PRI_TX_TIME_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_PRI_UNMASK_ERR_PRI_TX_TIME_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_PRI_UNMASK_ERR_PRI_TX_CMD_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_UNMASK_PRI_UNMASK_ERR_PRI_TX_CMD_SHIFT (1U)
/*! UNMASK_ERR_PRI_TX_CMD
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_PRI_UNMASK_ERR_PRI_TX_CMD(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_PRI_UNMASK_ERR_PRI_TX_CMD_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_PRI_UNMASK_ERR_PRI_TX_CMD_MASK)
/*! @} */

/*! @name INT_UNMASK_CRI - Unmask for CRI Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_CMD_TIME_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_CMD_TIME_SHIFT (0U)
/*! UNMASK_ERR_CRI_CMD_TIME
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_CMD_TIME(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_CMD_TIME_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_CMD_TIME_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_DTYPE_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_DTYPE_SHIFT (1U)
/*! UNMASK_ERR_CRI_DTYPE
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_DTYPE(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_DTYPE_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_DTYPE_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_VCHANNEL_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_VCHANNEL_SHIFT (2U)
/*! UNMASK_ERR_CRI_VCHANNEL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_VCHANNEL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_VCHANNEL_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_VCHANNEL_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_RX_LENGTH_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_RX_LENGTH_SHIFT (3U)
/*! UNMASK_ERR_CRI_RX_LENGTH
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_RX_LENGTH(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_RX_LENGTH_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_RX_LENGTH_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_ECC_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_ECC_SHIFT (4U)
/*! UNMASK_ERR_CRI_ECC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_ECC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_ECC_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_ECC_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_ECC_FATAL_MASK (0x20U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_ECC_FATAL_SHIFT (5U)
/*! UNMASK_ERR_CRI_ECC_FATAL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_ECC_FATAL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_ECC_FATAL_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_ECC_FATAL_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_CRC_MASK (0x40U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_CRC_SHIFT (6U)
/*! UNMASK_ERR_CRI_CRC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_CRC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_CRC_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_ERR_CRI_CRC_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_RD_PLD_FIFO_OVER_MASK (0x10000U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_RD_PLD_FIFO_OVER_SHIFT (16U)
/*! UNMASK_CMD_RD_PLD_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_RD_PLD_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_RD_PLD_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_RD_PLD_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_RD_PLD_FIFO_UNDER_MASK (0x20000U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_RD_PLD_FIFO_UNDER_SHIFT (17U)
/*! UNMASK_CMD_RD_PLD_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_RD_PLD_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_RD_PLD_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_RD_PLD_FIFO_UNDER_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_PLD_FIFO_OVER_MASK (0x40000U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_PLD_FIFO_OVER_SHIFT (18U)
/*! UNMASK_CMD_WR_PLD_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_PLD_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_PLD_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_PLD_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_PLD_FIFO_UNDER_MASK (0x80000U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_PLD_FIFO_UNDER_SHIFT (19U)
/*! UNMASK_CMD_WR_PLD_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_PLD_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_PLD_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_PLD_FIFO_UNDER_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_HDR_FIFO_OVER_MASK (0x100000U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_HDR_FIFO_OVER_SHIFT (20U)
/*! UNMASK_CMD_WR_HDR_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_HDR_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_HDR_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_HDR_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_HDR_FIFO_UNDER_MASK (0x200000U)
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_HDR_FIFO_UNDER_SHIFT (21U)
/*! UNMASK_CMD_WR_HDR_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_HDR_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_HDR_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_UNMASK_CRI_UNMASK_CMD_WR_HDR_FIFO_UNDER_MASK)
/*! @} */

/*! @name INT_FORCE_PHY - Force Flags for PHY Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRESC_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRESC_SHIFT (0U)
/*! FORCE_PHY_L0_ERRESC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRESC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRESC_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRESC_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRSYNCESC_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRSYNCESC_SHIFT (1U)
/*! FORCE_PHY_L0_ERRSYNCESC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRSYNCESC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRSYNCESC_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRSYNCESC_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTROL_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTROL_SHIFT (2U)
/*! FORCE_PHY_L0_ERRCONTROL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTROL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTROL_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTROL_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTENTIONLP0_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTENTIONLP0_SHIFT (3U)
/*! FORCE_PHY_L0_ERRCONTENTIONLP0
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTENTIONLP0(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTENTIONLP0_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTENTIONLP0_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTENTIONLP1_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTENTIONLP1_SHIFT (4U)
/*! FORCE_PHY_L0_ERRCONTENTIONLP1
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTENTIONLP1(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTENTIONLP1_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_PHY_L0_ERRCONTENTIONLP1_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_TXHS_FIFO_OVER_MASK (0x10000U)
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_TXHS_FIFO_OVER_SHIFT (16U)
/*! FORCE_TXHS_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_TXHS_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_TXHS_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_TXHS_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_TXHS_FIFO_UNDER_MASK (0x20000U)
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_TXHS_FIFO_UNDER_SHIFT (17U)
/*! FORCE_TXHS_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_TXHS_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_TXHS_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_PHY_FORCE_TXHS_FIFO_UNDER_MASK)
/*! @} */

/*! @name INT_FORCE_TO - Force Flags for PHY Timeouts Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_HSTX_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_HSTX_SHIFT (0U)
/*! FORCE_ERR_TO_HSTX
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_HSTX(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_HSTX_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_HSTX_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_HSTXRDY_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_HSTXRDY_SHIFT (1U)
/*! FORCE_ERR_TO_HSTXRDY
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_HSTXRDY(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_HSTXRDY_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_HSTXRDY_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPRX_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPRX_SHIFT (2U)
/*! FORCE_ERR_TO_LPRX
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPRX(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPRX_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPRX_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXRDY_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXRDY_SHIFT (3U)
/*! FORCE_ERR_TO_LPTXRDY
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXRDY(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXRDY_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXRDY_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXTRIG_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXTRIG_SHIFT (4U)
/*! FORCE_ERR_TO_LPTXTRIG
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXTRIG(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXTRIG_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXTRIG_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXULPS_MASK (0x20U)
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXULPS_SHIFT (5U)
/*! FORCE_ERR_TO_LPTXULPS
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXULPS(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXULPS_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_LPTXULPS_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_BTA_MASK (0x40U)
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_BTA_SHIFT (6U)
/*! FORCE_ERR_TO_BTA
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_BTA(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_BTA_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_TO_FORCE_ERR_TO_BTA_MASK)
/*! @} */

/*! @name INT_FORCE_ACK - Force Flags for ACK Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_0_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_0_SHIFT (0U)
/*! FORCE_ERR_ACK_RPT_0
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_0(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_0_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_0_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_1_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_1_SHIFT (1U)
/*! FORCE_ERR_ACK_RPT_1
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_1(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_1_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_1_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_2_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_2_SHIFT (2U)
/*! FORCE_ERR_ACK_RPT_2
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_2(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_2_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_2_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_3_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_3_SHIFT (3U)
/*! FORCE_ERR_ACK_RPT_3
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_3(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_3_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_3_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_4_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_4_SHIFT (4U)
/*! FORCE_ERR_ACK_RPT_4
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_4(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_4_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_4_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_5_MASK (0x20U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_5_SHIFT (5U)
/*! FORCE_ERR_ACK_RPT_5
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_5(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_5_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_5_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_6_MASK (0x40U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_6_SHIFT (6U)
/*! FORCE_ERR_ACK_RPT_6
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_6(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_6_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_6_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_7_MASK (0x80U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_7_SHIFT (7U)
/*! FORCE_ERR_ACK_RPT_7
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_7(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_7_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_7_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_8_MASK (0x100U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_8_SHIFT (8U)
/*! FORCE_ERR_ACK_RPT_8
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_8(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_8_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_8_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_9_MASK (0x200U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_9_SHIFT (9U)
/*! FORCE_ERR_ACK_RPT_9
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_9(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_9_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_9_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_10_MASK (0x400U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_10_SHIFT (10U)
/*! FORCE_ERR_ACK_RPT_10
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_10(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_10_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_10_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_11_MASK (0x800U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_11_SHIFT (11U)
/*! FORCE_ERR_ACK_RPT_11
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_11(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_11_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_11_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_12_MASK (0x1000U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_12_SHIFT (12U)
/*! FORCE_ERR_ACK_RPT_12
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_12(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_12_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_12_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_13_MASK (0x2000U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_13_SHIFT (13U)
/*! FORCE_ERR_ACK_RPT_13
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_13(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_13_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_13_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_14_MASK (0x4000U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_14_SHIFT (14U)
/*! FORCE_ERR_ACK_RPT_14
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_14(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_14_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_14_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_15_MASK (0x8000U)
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_15_SHIFT (15U)
/*! FORCE_ERR_ACK_RPT_15
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_15(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_15_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_ACK_FORCE_ERR_ACK_RPT_15_MASK)
/*! @} */

/*! @name INT_FORCE_IPI - Force Flags for IPI Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_DISPLAY_CMD_TIME_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_DISPLAY_CMD_TIME_SHIFT (0U)
/*! FORCE_ERR_DISPLAY_CMD_TIME
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_DISPLAY_CMD_TIME(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_DISPLAY_CMD_TIME_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_DISPLAY_CMD_TIME_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_IPI_DTYPE_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_IPI_DTYPE_SHIFT (1U)
/*! FORCE_ERR_IPI_DTYPE
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_IPI_DTYPE(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_IPI_DTYPE_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_IPI_DTYPE_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_VID_BANDWIDTH_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_VID_BANDWIDTH_SHIFT (2U)
/*! FORCE_ERR_VID_BANDWIDTH
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_VID_BANDWIDTH(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_VID_BANDWIDTH_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_VID_BANDWIDTH_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_IPI_CMD_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_IPI_CMD_SHIFT (3U)
/*! FORCE_ERR_IPI_CMD
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_IPI_CMD(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_IPI_CMD_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_IPI_CMD_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_DISPLAY_CMD_OVFL_MASK (0x100U)
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_DISPLAY_CMD_OVFL_SHIFT (8U)
/*! FORCE_ERR_DISPLAY_CMD_OVFL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_DISPLAY_CMD_OVFL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_DISPLAY_CMD_OVFL_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_ERR_DISPLAY_CMD_OVFL_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_EVENT_FIFO_OVER_MASK (0x10000U)
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_EVENT_FIFO_OVER_SHIFT (16U)
/*! FORCE_IPI_EVENT_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_EVENT_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_EVENT_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_EVENT_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_EVENT_FIFO_UNDER_MASK (0x20000U)
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_EVENT_FIFO_UNDER_SHIFT (17U)
/*! FORCE_IPI_EVENT_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_EVENT_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_EVENT_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_EVENT_FIFO_UNDER_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_PIXEL_FIFO_OVER_MASK (0x40000U)
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_PIXEL_FIFO_OVER_SHIFT (18U)
/*! FORCE_IPI_PIXEL_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_PIXEL_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_PIXEL_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_PIXEL_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_PIXEL_FIFO_UNDER_MASK (0x80000U)
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_PIXEL_FIFO_UNDER_SHIFT (19U)
/*! FORCE_IPI_PIXEL_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_PIXEL_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_PIXEL_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_IPI_FORCE_IPI_PIXEL_FIFO_UNDER_MASK)
/*! @} */

/*! @name INT_FORCE_PRI - Force Flags for PRI Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_FORCE_PRI_FORCE_ERR_PRI_TX_TIME_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_FORCE_PRI_FORCE_ERR_PRI_TX_TIME_SHIFT (0U)
/*! FORCE_ERR_PRI_TX_TIME
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_PRI_FORCE_ERR_PRI_TX_TIME(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_PRI_FORCE_ERR_PRI_TX_TIME_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_PRI_FORCE_ERR_PRI_TX_TIME_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_PRI_FORCE_ERR_PRI_TX_CMD_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_FORCE_PRI_FORCE_ERR_PRI_TX_CMD_SHIFT (1U)
/*! FORCE_ERR_PRI_TX_CMD
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_PRI_FORCE_ERR_PRI_TX_CMD(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_PRI_FORCE_ERR_PRI_TX_CMD_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_PRI_FORCE_ERR_PRI_TX_CMD_MASK)
/*! @} */

/*! @name INT_FORCE_CRI - Force Flags for CRI Interrupt Sources */
/*! @{ */

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_CMD_TIME_MASK (0x1U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_CMD_TIME_SHIFT (0U)
/*! FORCE_ERR_CRI_CMD_TIME
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_CMD_TIME(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_CMD_TIME_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_CMD_TIME_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_DTYPE_MASK (0x2U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_DTYPE_SHIFT (1U)
/*! FORCE_ERR_CRI_DTYPE
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_DTYPE(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_DTYPE_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_DTYPE_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_VCHANNEL_MASK (0x4U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_VCHANNEL_SHIFT (2U)
/*! FORCE_ERR_CRI_VCHANNEL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_VCHANNEL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_VCHANNEL_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_VCHANNEL_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_RX_LENGTH_MASK (0x8U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_RX_LENGTH_SHIFT (3U)
/*! FORCE_ERR_CRI_RX_LENGTH
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_RX_LENGTH(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_RX_LENGTH_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_RX_LENGTH_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_ECC_MASK (0x10U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_ECC_SHIFT (4U)
/*! FORCE_ERR_CRI_ECC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_ECC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_ECC_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_ECC_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_ECC_FATAL_MASK (0x20U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_ECC_FATAL_SHIFT (5U)
/*! FORCE_ERR_CRI_ECC_FATAL
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_ECC_FATAL(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_ECC_FATAL_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_ECC_FATAL_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_CRC_MASK (0x40U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_CRC_SHIFT (6U)
/*! FORCE_ERR_CRI_CRC
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_CRC(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_CRC_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_ERR_CRI_CRC_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_RD_PLD_FIFO_OVER_MASK (0x10000U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_RD_PLD_FIFO_OVER_SHIFT (16U)
/*! FORCE_CMD_RD_PLD_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_RD_PLD_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_RD_PLD_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_RD_PLD_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_RD_PLD_FIFO_UNDER_MASK (0x20000U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_RD_PLD_FIFO_UNDER_SHIFT (17U)
/*! FORCE_CMD_RD_PLD_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_RD_PLD_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_RD_PLD_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_RD_PLD_FIFO_UNDER_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_PLD_FIFO_OVER_MASK (0x40000U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_PLD_FIFO_OVER_SHIFT (18U)
/*! FORCE_CMD_WR_PLD_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_PLD_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_PLD_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_PLD_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_PLD_FIFO_UNDER_MASK (0x80000U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_PLD_FIFO_UNDER_SHIFT (19U)
/*! FORCE_CMD_WR_PLD_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_PLD_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_PLD_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_PLD_FIFO_UNDER_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_HDR_FIFO_OVER_MASK (0x100000U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_HDR_FIFO_OVER_SHIFT (20U)
/*! FORCE_CMD_WR_HDR_FIFO_OVER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_HDR_FIFO_OVER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_HDR_FIFO_OVER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_HDR_FIFO_OVER_MASK)

#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_HDR_FIFO_UNDER_MASK (0x200000U)
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_HDR_FIFO_UNDER_SHIFT (21U)
/*! FORCE_CMD_WR_HDR_FIFO_UNDER
 *  0b0..
 */
#define DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_HDR_FIFO_UNDER(x) (((uint32_t)(((uint32_t)(x)) << DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_HDR_FIFO_UNDER_SHIFT)) & DSI_V2_HOST_INT_INT_FORCE_CRI_FORCE_CMD_WR_HDR_FIFO_UNDER_MASK)
/*! @} */


/*!
 * @}
 */ /* end of group DSI_V2_HOST_INT_Register_Masks */


/*!
 * @}
 */ /* end of group DSI_V2_HOST_INT_Peripheral_Access_Layer */


/*
** End of section using anonymous unions
*/

#if defined(__ARMCC_VERSION)
  #if (__ARMCC_VERSION >= 6010050)
    #pragma clang diagnostic pop
  #else
    #pragma pop
  #endif
#elif defined(__GNUC__)
  /* leave anonymous unions enabled */
#elif defined(__IAR_SYSTEMS_ICC__)
  #pragma language=default
#else
  #error Not supported compiler type
#endif

/*!
 * @}
 */ /* end of group Peripheral_access_layer */


#endif  /* PERI_DSI_V2_HOST_INT_H_ */

