/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKE13Z128VLH7/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MKE13Z256VLH7-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: ca29b3b1721fc363
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE13Z128VLH7_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE13Z128VLH7_WRAPPER_

#include "MKE13Z256VLH7-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MKE13Z128VLH7_WRAPPER_ */
