/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKE14Z32VFP4/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MKE14Z64VFP4-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 2d84bbace7d6efa3
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE14Z32VFP4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE14Z32VFP4_WRAPPER_

#include "MKE14Z64VFP4-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MKE14Z32VFP4_WRAPPER_ */
