/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKE12Z128VLF7/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MKE12Z256VLF7-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: e9f6c66ca9de7949
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE12Z128VLF7_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE12Z128VLF7_WRAPPER_

#include "MKE12Z256VLF7-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MKE12Z128VLF7_WRAPPER_ */
