/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * Copyright 2020-2021 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _FLASH_CONFIG_H_
#define _FLASH_CONFIG_H_

/************************** Flash configuration field *********************/

#define FCF_BACKDOOR_KEY0 0xFFU
#define FCF_BACKDOOR_KEY1 0xFFU
#define FCF_BACKDOOR_KEY2 0xFFU
#define FCF_BACKDOOR_KEY3 0xFFU
#define FCF_BACKDOOR_KEY4 0xFFU
#define FCF_BACKDOOR_KEY5 0xFFU
#define FCF_BACKDOOR_KEY6 0xFFU
#define FCF_BACKDOOR_KEY7 0xFFU

/*
 * FCF_FLASH_PROTECTION_BYTEn
 *   See FTFL FPROTn register description
 */
#define FCF_FLASH_PROTECTION_BYTE0 0xFFU
#define FCF_FLASH_PROTECTION_BYTE1 0xFFU
#define FCF_FLASH_PROTECTION_BYTE2 0xFFU
#define FCF_FLASH_PROTECTION_BYTE3 0xFFU

/*
 * FCF_FLASH_SECURE_BYTE
 *   Bit[7:6]: KEYEN, Backdoor Key Security Enable. 0b10 = enable, others = disable.
 *   Bit[5:4]: MEEN, Mass Erase Enable Bits. 0b10 = disable, others = enable.
 *   Bit[3:2]: FSLACC, Factory Security Level Access Code. 0b00 or 0b11 = granted, others = denied.
 *   Bit[1:0]: SEC, Flash Security. 0b10 = unsecure, others = secure.
 */
#define FCF_FLASH_SECURE_BYTE 0x7EU

/*
 * FCF_FLASH_OPTION_BYTE
 *   Bit[7:1]: Reserved.
 *   Bit[0]:   PowerMode. 0b1 = writing SIM_PWRMODE register takes effect, writing SIM_PWR register doesn't take effect.
 *                        0b0 = writing SIM_PWRMODE register doesn't take effect, writing SIM_PWR register takes effect.
 */
#define FCF_FLASH_OPTION_BYTE 0x3FU

/*
 * FCF_EEPROM_PROTECTION_BYTE
 *   See RM FTFL FEPROT register description
 */
#define FCF_EEPROM_PROTECTION_BYTE 0xFFU

/*
 * FCF_DATA_FLASH_PROTECTION_BYTE
 *   See RM FTFL FDPROT register description
 */
#define FCF_DATA_FLASH_PROTECTION_BYTE 0xFFU

#endif /* _FLASH_CONFIG_H_*/
