/*
** ###################################################################
**     Processors:          MIMX9594AVZXN_ca55
**                          MIMX9594AVZXN_cm33
**                          MIMX9594AVZXN_cm7
**                          MIMX9596AVTXN_ca55
**                          MIMX9596AVTXN_cm33
**                          MIMX9596AVTXN_cm7
**                          MIMX9596AVYXN_ca55
**                          MIMX9596AVYXN_cm33
**                          MIMX9596AVYXN_cm7
**                          MIMX9596AVZXN_ca55
**                          MIMX9596AVZXN_cm33
**                          MIMX9596AVZXN_cm7
**                          MIMX9596CVTXN_ca55
**                          MIMX9596CVTXN_cm33
**                          MIMX9596CVTXN_cm7
**                          MIMX9596CVYXN_ca55
**                          MIMX9596CVYXN_cm33
**                          MIMX9596CVYXN_cm7
**                          MIMX9596CVZXN_ca55
**                          MIMX9596CVZXN_cm33
**                          MIMX9596CVZXN_cm7
**                          MIMX9596DVTXN_ca55
**                          MIMX9596DVTXN_cm33
**                          MIMX9596DVTXN_cm7
**                          MIMX9596DVYXN_ca55
**                          MIMX9596DVYXN_cm33
**                          MIMX9596DVYXN_cm7
**                          MIMX9596DVYXQ_ca55
**                          MIMX9596DVYXQ_cm33
**                          MIMX9596DVYXQ_cm7
**                          MIMX9596DVZXN_ca55
**                          MIMX9596DVZXN_cm33
**                          MIMX9596DVZXN_cm7
**                          MIMX9596XVTXN_ca55
**                          MIMX9596XVTXN_cm33
**                          MIMX9596XVTXN_cm7
**                          MIMX9596XVYXN_ca55
**                          MIMX9596XVYXN_cm33
**                          MIMX9596XVYXN_cm7
**                          MIMX9596XVZXN_ca55
**                          MIMX9596XVZXN_cm33
**                          MIMX9596XVZXN_cm7
**
**     Version:             rev. 1.0, 2023-01-10
**     Build:               b240728
**
**     Abstract:
**         CMSIS Peripheral Access Layer for HSIO_BLK_CTRL_HSIOMIX
**
**     Copyright 1997-2016 Freescale Semiconductor, Inc.
**     Copyright 2016-2024 NXP
**     SPDX-License-Identifier: BSD-3-Clause
**
**     http:                 www.nxp.com
**     mail:                 support@nxp.com
**
**     Revisions:
**     - rev. 1.0 (2023-01-10)
**         Initial version.
**
** ###################################################################
*/

/*!
 * @file HSIO_BLK_CTRL_HSIOMIX.h
 * @version 1.0
 * @date 2023-01-10
 * @brief CMSIS Peripheral Access Layer for HSIO_BLK_CTRL_HSIOMIX
 *
 * CMSIS Peripheral Access Layer for HSIO_BLK_CTRL_HSIOMIX
 */

#if !defined(HSIO_BLK_CTRL_HSIOMIX_H_)
#define HSIO_BLK_CTRL_HSIOMIX_H_                 /**< Symbol preventing repeated inclusion */

#if (defined(CPU_MIMX9594AVZXN_ca55))
#include "MIMX9594_ca55_COMMON.h"
#elif (defined(CPU_MIMX9594AVZXN_cm33))
#include "MIMX9594_cm33_COMMON.h"
#elif (defined(CPU_MIMX9594AVZXN_cm7))
#include "MIMX9594_cm7_COMMON.h"
#elif (defined(CPU_MIMX9596AVTXN_ca55) || defined(CPU_MIMX9596AVYXN_ca55) || defined(CPU_MIMX9596AVZXN_ca55) || defined(CPU_MIMX9596CVTXN_ca55) || defined(CPU_MIMX9596CVYXN_ca55) || defined(CPU_MIMX9596CVZXN_ca55) || defined(CPU_MIMX9596DVTXN_ca55) || defined(CPU_MIMX9596DVYXN_ca55) || defined(CPU_MIMX9596DVYXQ_ca55) || defined(CPU_MIMX9596DVZXN_ca55) || defined(CPU_MIMX9596XVTXN_ca55) || defined(CPU_MIMX9596XVYXN_ca55) || defined(CPU_MIMX9596XVZXN_ca55))
#include "MIMX9596_ca55_COMMON.h"
#elif (defined(CPU_MIMX9596AVTXN_cm33) || defined(CPU_MIMX9596AVYXN_cm33) || defined(CPU_MIMX9596AVZXN_cm33) || defined(CPU_MIMX9596CVTXN_cm33) || defined(CPU_MIMX9596CVYXN_cm33) || defined(CPU_MIMX9596CVZXN_cm33) || defined(CPU_MIMX9596DVTXN_cm33) || defined(CPU_MIMX9596DVYXN_cm33) || defined(CPU_MIMX9596DVYXQ_cm33) || defined(CPU_MIMX9596DVZXN_cm33) || defined(CPU_MIMX9596XVTXN_cm33) || defined(CPU_MIMX9596XVYXN_cm33) || defined(CPU_MIMX9596XVZXN_cm33))
#include "MIMX9596_cm33_COMMON.h"
#elif (defined(CPU_MIMX9596AVTXN_cm7) || defined(CPU_MIMX9596AVYXN_cm7) || defined(CPU_MIMX9596AVZXN_cm7) || defined(CPU_MIMX9596CVTXN_cm7) || defined(CPU_MIMX9596CVYXN_cm7) || defined(CPU_MIMX9596CVZXN_cm7) || defined(CPU_MIMX9596DVTXN_cm7) || defined(CPU_MIMX9596DVYXN_cm7) || defined(CPU_MIMX9596DVYXQ_cm7) || defined(CPU_MIMX9596DVZXN_cm7) || defined(CPU_MIMX9596XVTXN_cm7) || defined(CPU_MIMX9596XVYXN_cm7) || defined(CPU_MIMX9596XVZXN_cm7))
#include "MIMX9596_cm7_COMMON.h"
#else
  #error "No valid CPU defined!"
#endif

/* ----------------------------------------------------------------------------
   -- Device Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup Peripheral_access_layer Device Peripheral Access Layer
 * @{
 */


/*
** Start of section using anonymous unions
*/

#if defined(__ARMCC_VERSION)
  #if (__ARMCC_VERSION >= 6010050)
    #pragma clang diagnostic push
  #else
    #pragma push
    #pragma anon_unions
  #endif
#elif defined(__GNUC__)
  /* anonymous unions are enabled by default */
#elif defined(__IAR_SYSTEMS_ICC__)
  #pragma language=extended
#else
  #error Not supported compiler type
#endif

/* ----------------------------------------------------------------------------
   -- HSIO_BLK_CTRL_HSIOMIX Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup HSIO_BLK_CTRL_HSIOMIX_Peripheral_Access_Layer HSIO_BLK_CTRL_HSIOMIX Peripheral Access Layer
 * @{
 */

/** HSIO_BLK_CTRL_HSIOMIX - Register Layout Typedef */
typedef struct {
  __IO uint32_t GPR_REG0;                          /**< GPR Register 0, offset: 0x0 */
       uint8_t RESERVED_0[12];
  __IO uint32_t USB1_WAKEUP_CTRL;                  /**< USB1 Wakeup Control, offset: 0x10 */
  __IO uint32_t USB2_WAKEUP_CTRL;                  /**< USB2 Wakeup Control, offset: 0x14 */
  __I  uint32_t USB1_WAKEUP_STATUS;                /**< USB1 Wakeup Status, offset: 0x18 */
  __I  uint32_t USB2_WAKEUP_STATUS;                /**< USB2 Wakeup Status, offset: 0x1C */
  __IO uint32_t USB1_AXQOS_DEFAULT;                /**< USB1 AXi master QoS programmable register, offset: 0x20 */
  __IO uint32_t USB1_AXQOS_PANIC;                  /**< USB1 AXi master QoS (panic mode) programmable register, offset: 0x24 */
  __IO uint32_t USB2_AXQOS_DEFAULT;                /**< USB2 AXi master QoS programmable register, offset: 0x28 */
  __IO uint32_t USB2_AXQOS_PANIC;                  /**< USB2 AXi master QoS (panic mode) programmable register, offset: 0x2C */
  __IO uint32_t PCIE1_AXQOS_DEFAULT;               /**< PCIE1 AXi master QoS programmable register, offset: 0x30 */
  __IO uint32_t PCIE1_AXQOS_PANIC;                 /**< PCIE1 AXi master QoS (panic mode) programmable register, offset: 0x34 */
  __IO uint32_t PCIE2_AXQOS_DEFAULT;               /**< PCIE2 AXi master QoS programmable register, offset: 0x38 */
  __IO uint32_t PCIE2_AXQOS_PANIC;                 /**< PCIE2 AXi master QoS (panic mode) programmable register, offset: 0x3C */
  __IO uint32_t PCIE1_DMA_XFER_GO_TOGG;            /**< PCIE1 DMA engine descriptor transfer go toggle register., offset: 0x40 */
  __IO uint32_t PCIE2_DMA_XFER_GO_TOGG;            /**< PCIE2 DMA engine descriptor transfer go toggle register., offset: 0x44 */
       uint8_t RESERVED_1[8];
  __IO uint32_t PCIE1_REG;                         /**< PCIe1 register, offset: 0x50 */
  __IO uint32_t PCIE2_REG;                         /**< PCIe2 register, offset: 0x54 */
       uint8_t RESERVED_2[104];
  __IO uint32_t LFAST_IO_REG;                      /**< GPR registers for LFAST IO, offset: 0xC0 */
} HSIO_BLK_CTRL_HSIOMIX_Type;

/* ----------------------------------------------------------------------------
   -- HSIO_BLK_CTRL_HSIOMIX Register Masks
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup HSIO_BLK_CTRL_HSIOMIX_Register_Masks HSIO_BLK_CTRL_HSIOMIX Register Masks
 * @{
 */

/*! @name GPR_REG0 - GPR Register 0 */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE1_PERST_N_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE1_PERST_N_SHIFT (0U)
/*! PCIE1_PERST_N - PCIE1_PERST_N */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE1_PERST_N(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE1_PERST_N_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE1_PERST_N_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE2_PERST_N_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE2_PERST_N_SHIFT (1U)
/*! PCIE2_PERST_N - PCIE2_PERST_N */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE2_PERST_N(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE2_PERST_N_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_PCIE2_PERST_N_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB2_BYPASS_LOGIC_SEL_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB2_BYPASS_LOGIC_SEL_SHIFT (5U)
/*! USB2_BYPASS_LOGIC_SEL - USB2 AUTO_RESUME LOGIC SELECTION */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB2_BYPASS_LOGIC_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB2_BYPASS_LOGIC_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB2_BYPASS_LOGIC_SEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB_PHY_REF_CLK_SEL_MASK (0x40U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB_PHY_REF_CLK_SEL_SHIFT (6U)
/*! USB_PHY_REF_CLK_SEL - USB 3.0 PHY ref clock selection
 *  0b1..100 MHz high performance PLL
 *  0b0..24 MHz external oscillator
 */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB_PHY_REF_CLK_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB_PHY_REF_CLK_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_USB_PHY_REF_CLK_SEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CFG_READY_MASK (0x80U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CFG_READY_SHIFT (7U)
/*! CFG_READY - Configuration ready */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CFG_READY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CFG_READY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CFG_READY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CRS_CLEAR_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CRS_CLEAR_SHIFT (8U)
/*! CRS_CLEAR - Clear Configuration Retry Status interrupt */
#define HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CRS_CLEAR(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CRS_CLEAR_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_GPR_REG0_CRS_CLEAR_MASK)
/*! @} */

/*! @name USB1_WAKEUP_CTRL - USB1 Wakeup Control */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_SHIFT (0U)
/*! OTG_WKDPDMCHG_EN - Enable signal for wake up from dp/dm change.
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WKDPDMCHG_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_SHIFT (1U)
/*! OTG_VBUS_WAKE_EN - Enable signal for wake up from vbus valid or session valid changes
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_WAKE_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_SHIFT (2U)
/*! OTG_ID_WAKEUP_EN - Enable signal for wake up from id change
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_ID_WAKEUP_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_U3_WAKE_EN_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_U3_WAKE_EN_SHIFT (3U)
/*! OTG_U3_WAKE_EN - Enable signal for wake up from u3 state, only for super-speed
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_U3_WAKE_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_U3_WAKE_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_U3_WAKE_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_SHIFT (4U)
/*! OTG_VBUS_SOURCE_SEL - otg_vbus_source_sel
 *  0b0..Select vbus_valid
 *  0b1..Select sessvld
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_SHIFT (5U)
/*! OTG_CONN_WAKEUP_EN - Enable signal for wakeup from connection or disconnection, only for super-speed.
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_EN_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_EN_SHIFT (8U)
/*! AUTORESUME_EN - Enable auto-resume feature. When using phy_bypass signal, this bit should be 1'b0.
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_DATADLY_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_DATADLY_SHIFT (9U)
/*! AUTORESUME_DATADLY - Please refer to the bit field description for AUTORESUME_ENDLY. */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_DATADLY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_DATADLY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_DATADLY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_ENDLY_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_ENDLY_SHIFT (10U)
/*! AUTORESUME_ENDLY - Tuning the timing between dp/dm data and enable signal when auto-resume finish. */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_ENDLY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_ENDLY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_AUTORESUME_ENDLY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_LOWSPEED_EN_MASK (0x800U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_LOWSPEED_EN_SHIFT (11U)
/*! LOWSPEED_EN - Enable low-speed auto-resume feature
 *  0b1..Low speed
 *  0b0..Full/high speed
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_LOWSPEED_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_LOWSPEED_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_LOWSPEED_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMDATA_MASK (0x1000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMDATA_SHIFT (12U)
/*! PHY_BYPASSDMDATA - Data for DM Transmitter Digital Bypass */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMDATA(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMDATA_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMDATA_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMEN_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMEN_SHIFT (13U)
/*! PHY_BYPASSDMEN - DM Transmitter Digital Bypass Enable
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMEN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMEN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDMEN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPDATA_MASK (0x4000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPDATA_SHIFT (14U)
/*! PHY_BYPASSDPDATA - Data for DP Transmitter Digital Bypass */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPDATA(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPDATA_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPDATA_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPEN_MASK (0x8000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPEN_SHIFT (15U)
/*! PHY_BYPASSDPEN - DP Transmitter Digital Bypass Enable
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPEN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPEN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSDPEN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSSEL_MASK (0x10000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSSEL_SHIFT (16U)
/*! PHY_BYPASSSEL - Transmitter Digital Bypass Select */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSSEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSSEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_PHY_BYPASSSEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WAKE_ENABLE_MASK (0x80000000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WAKE_ENABLE_SHIFT (31U)
/*! OTG_WAKE_ENABLE - Global wakeup interrupt enable. Used to clear interrupt. Default 0, same as WIE before.
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WAKE_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WAKE_ENABLE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_CTRL_OTG_WAKE_ENABLE_MASK)
/*! @} */

/*! @name USB2_WAKEUP_CTRL - USB2 Wakeup Control */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_SHIFT (0U)
/*! OTG_WKDPDMCHG_EN - Enable signal for wake up from dp/dm change
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WKDPDMCHG_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WKDPDMCHG_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_SHIFT (1U)
/*! OTG_VBUS_WAKE_EN - Enable signal for wake up from vbus valid or session valid changes
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_WAKE_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_WAKE_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_SHIFT (2U)
/*! OTG_ID_WAKEUP_EN - Enable signal for wake up from id change
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_ID_WAKEUP_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_ID_WAKEUP_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_U3_WAKE_EN_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_U3_WAKE_EN_SHIFT (3U)
/*! OTG_U3_WAKE_EN - Enable signal for wake up from u3 state, only for super-speed
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_U3_WAKE_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_U3_WAKE_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_U3_WAKE_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_SHIFT (4U)
/*! OTG_VBUS_SOURCE_SEL - otg_vbus_source_sel
 *  0b1..Select ssvld
 *  0b0..Select vbus_valid
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_VBUS_SOURCE_SEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_SHIFT (5U)
/*! OTG_CONN_WAKEUP_EN - Enable signal for wakeup from connection or disconnection, only for super-speed. */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_CONN_WAKEUP_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_EN_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_EN_SHIFT (8U)
/*! AUTORESUME_EN - Enable auto-resume feature. When using phy_bypass signal, this bit should be 1'b0.
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_DATADLY_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_DATADLY_SHIFT (9U)
/*! AUTORESUME_DATADLY - Please refer to the bitfield description for AUTORESUME_ENDLY. */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_DATADLY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_DATADLY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_DATADLY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_ENDLY_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_ENDLY_SHIFT (10U)
/*! AUTORESUME_ENDLY - Tuning the timing between dp/dm data and enable signal when auto-resume finish. */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_ENDLY(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_ENDLY_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_AUTORESUME_ENDLY_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_LOWSPEED_EN_MASK (0x800U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_LOWSPEED_EN_SHIFT (11U)
/*! LOWSPEED_EN - Enable low-speed auto-resume feature
 *  0b0..Full/high speed
 *  0b1..Low speed
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_LOWSPEED_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_LOWSPEED_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_LOWSPEED_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMDATA_MASK (0x1000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMDATA_SHIFT (12U)
/*! PHY_BYPASSDMDATA - Data for DM Transmitter Digital Bypass */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMDATA(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMDATA_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMDATA_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMEN_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMEN_SHIFT (13U)
/*! PHY_BYPASSDMEN - DM Transmitter Digital Bypass Enable
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMEN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMEN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDMEN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPDATA_MASK (0x4000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPDATA_SHIFT (14U)
/*! PHY_BYPASSDPDATA - Data for DP Transmitter Digital Bypass */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPDATA(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPDATA_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPDATA_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPEN_MASK (0x8000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPEN_SHIFT (15U)
/*! PHY_BYPASSDPEN - DP Transmitter Digital Bypass Enable
 *  0b1..Enable
 *  0b0..Disable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPEN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPEN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSDPEN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSSEL_MASK (0x10000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSSEL_SHIFT (16U)
/*! PHY_BYPASSSEL - Transmitter Digital Bypass Select */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSSEL(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSSEL_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_PHY_BYPASSSEL_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WAKE_ENABLE_MASK (0x80000000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WAKE_ENABLE_SHIFT (31U)
/*! OTG_WAKE_ENABLE - Global wakeup interrupt enable. Used to clear interrupt. Default 0, same as WIE before.
 *  0b0..Disable
 *  0b1..Enable
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WAKE_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WAKE_ENABLE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_CTRL_OTG_WAKE_ENABLE_MASK)
/*! @} */

/*! @name USB1_WAKEUP_STATUS - USB1 Wakeup Status */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_SHIFT (0U)
/*! OTG_DP_DM_WAKEUP_INTERRUPT - Interrupt status of dm or dp, otg_dp_wakeup_interrupt | otg_dm_wakeup_interrupt */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_SHIFT (1U)
/*! OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT - Interrupt status of vbus or session valid signal. otg_vbus_wakeup_interrupt | otg_sessvld_wakeup_interrupt */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_SHIFT (2U)
/*! OTG_ID_WAKEUP_INTERRUPT - Interrupt status of wakeup from id */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_SHIFT (3U)
/*! OTG_U3_WAKEUP_INTERRUP - Interrupt status of wakeup from u3 state */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_SHIFT (4U)
/*! OTG_PHY_LINESTATE0_0 - linestate[0], wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_SHIFT (5U)
/*! OTG_PHY_LINESTATE0_1 - linestate[1], wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_IDDIG0_MASK (0x40U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_IDDIG0_SHIFT (6U)
/*! OTG_PHY_IDDIG0 - ID status, wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_IDDIG0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_IDDIG0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_IDDIG0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_MASK (0x80U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_SHIFT (7U)
/*! OTG_PHY_VBUSVALID0 - vbus valid, wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_VBUSVALID0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_SHIFT (8U)
/*! OTG_PHY_OTGSESSVLD0 - session valid, wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE_RXELECIDLE_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE_RXELECIDLE_SHIFT (9U)
/*! PIPE_RXELECIDLE - pipe_rxelecidel, wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE_RXELECIDLE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE_RXELECIDLE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE_RXELECIDLE_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_HOST_MODE_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_HOST_MODE_SHIFT (10U)
/*! OTG_HOST_MODE - USB drd mode
 *  0b0..host mode
 *  0b1..device mode
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_HOST_MODE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_HOST_MODE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_HOST_MODE_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE3_POWERDOWN_MASK (0x1800U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE3_POWERDOWN_SHIFT (11U)
/*! PIPE3_POWERDOWN - Pipe power-down */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE3_POWERDOWN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE3_POWERDOWN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_PIPE3_POWERDOWN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_SHIFT (13U)
/*! OTG_CONN_WAKEUP_INTERRUPT - Interrupt status of connection */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_MASK (0x80000000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_SHIFT (31U)
/*! OTG_WAKEUP_INTERRUPT - Same as WIR before, it's OR of all wakeup interrupt, then AND with otg_wakeup_enable. */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_MASK)
/*! @} */

/*! @name USB2_WAKEUP_STATUS - USB2 Wakeup Status */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_SHIFT (0U)
/*! OTG_DP_DM_WAKEUP_INTERRUPT - Interrupt status of dm or dp, otg_dp_wakeup_interrupt | otg_dm_wakeup_interrupt */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_DP_DM_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_SHIFT (1U)
/*! OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT - Interrupt status of vbus or session valid signal. otg_vbus_wakeup_interrupt | otg_sessvld_wakeup_interrupt */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_VBUS_SESSVLD_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_MASK (0x4U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_SHIFT (2U)
/*! OTG_ID_WAKEUP_INTERRUPT - Interrupt status of wakeup from id */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_ID_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_MASK (0x8U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_SHIFT (3U)
/*! OTG_U3_WAKEUP_INTERRUP - Interrupt status of wakeup from u3 state */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_U3_WAKEUP_INTERRUP_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_MASK (0x10U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_SHIFT (4U)
/*! OTG_PHY_LINESTATE0_0 - linestate[0], wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_MASK (0x20U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_SHIFT (5U)
/*! OTG_PHY_LINESTATE0_1 - linestate[1], wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_LINESTATE0_1_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_IDDIG0_MASK (0x40U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_IDDIG0_SHIFT (6U)
/*! OTG_PHY_IDDIG0 - ID status, wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_IDDIG0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_IDDIG0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_IDDIG0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_MASK (0x80U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_SHIFT (7U)
/*! OTG_PHY_VBUSVALID0 - vbus valid, wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_VBUSVALID0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_VBUSVALID0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_SHIFT (8U)
/*! OTG_PHY_OTGSESSVLD0 - session valid, wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_PHY_OTGSESSVLD0_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE_RXELECIDLE_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE_RXELECIDLE_SHIFT (9U)
/*! PIPE_RXELECIDLE - pipe_rxelecidel, wakeup source */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE_RXELECIDLE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE_RXELECIDLE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE_RXELECIDLE_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_HOST_MODE_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_HOST_MODE_SHIFT (10U)
/*! OTG_HOST_MODE - USB drd mode indicator
 *  0b0..Device mode
 *  0b1..Host mode
 */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_HOST_MODE(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_HOST_MODE_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_HOST_MODE_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE3_POWERDOWN_MASK (0x1800U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE3_POWERDOWN_SHIFT (11U)
/*! PIPE3_POWERDOWN - Pipe power-down */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE3_POWERDOWN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE3_POWERDOWN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_PIPE3_POWERDOWN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_MASK (0x2000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_SHIFT (13U)
/*! OTG_CONN_WAKEUP_INTERRUPT - Interrupt status of connection */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_CONN_WAKEUP_INTERRUPT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_MASK (0x80000000U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_SHIFT (31U)
/*! OTG_WAKEUP_INTERRUPT - Same as WIR before, it's OR of all wakeup interrupt, then AND with otg_wakeup_enable. */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_WAKEUP_STATUS_OTG_WAKEUP_INTERRUPT_MASK)
/*! @} */

/*! @name USB1_AXQOS_DEFAULT - USB1 AXi master QoS programmable register */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT (0U)
/*! AW_QOS_DEFAULT - write channel Qos default value register */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_DEFAULT_AW_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT (8U)
/*! AR_QOS_DEFAULT - Read channel Qos default value register */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_DEFAULT_AR_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK)
/*! @} */

/*! @name USB1_AXQOS_PANIC - USB1 AXi master QoS (panic mode) programmable register */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_PANIC_AW_QOS_PANIC_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_PANIC_AW_QOS_PANIC_SHIFT (0U)
/*! AW_QOS_PANIC - write channel Qos panic value register */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_PANIC_AW_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_PANIC_AW_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_PANIC_AW_QOS_PANIC_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_PANIC_AR_QOS_PANIC_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_PANIC_AR_QOS_PANIC_SHIFT (8U)
/*! AR_QOS_PANIC - Read channel Qos panic value register */
#define HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_PANIC_AR_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_PANIC_AR_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB1_AXQOS_PANIC_AR_QOS_PANIC_MASK)
/*! @} */

/*! @name USB2_AXQOS_DEFAULT - USB2 AXi master QoS programmable register */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT (0U)
/*! AW_QOS_DEFAULT - write channel Qos default value register */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AW_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT (8U)
/*! AR_QOS_DEFAULT - Read channel Qos default value register */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AR_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK)
/*! @} */

/*! @name USB2_AXQOS_PANIC - USB2 AXi master QoS (panic mode) programmable register */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AW_QOS_PANIC_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AW_QOS_PANIC_SHIFT (0U)
/*! AW_QOS_PANIC - write channel Qos panic value register */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AW_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AW_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AW_QOS_PANIC_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AR_QOS_PANIC_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AR_QOS_PANIC_SHIFT (8U)
/*! AR_QOS_PANIC - Read channel Qos panic value register */
#define HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AR_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AR_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_USB2_AXQOS_PANIC_AR_QOS_PANIC_MASK)
/*! @} */

/*! @name PCIE1_AXQOS_DEFAULT - PCIE1 AXi master QoS programmable register */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT (0U)
/*! AW_QOS_DEFAULT - write channel Qos default value register */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AW_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT (8U)
/*! AR_QOS_DEFAULT - Read channel Qos default value register */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AR_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK)
/*! @} */

/*! @name PCIE1_AXQOS_PANIC - PCIE1 AXi master QoS (panic mode) programmable register */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AW_QOS_PANIC_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AW_QOS_PANIC_SHIFT (0U)
/*! AW_QOS_PANIC - write channel Qos panic value register */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AW_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AW_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AW_QOS_PANIC_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AR_QOS_PANIC_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AR_QOS_PANIC_SHIFT (8U)
/*! AR_QOS_PANIC - Read channel Qos panic value register */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AR_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AR_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_AXQOS_PANIC_AR_QOS_PANIC_MASK)
/*! @} */

/*! @name PCIE2_AXQOS_DEFAULT - PCIE2 AXi master QoS programmable register */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT (0U)
/*! AW_QOS_DEFAULT - write channel Qos default value register */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_DEFAULT_AW_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_DEFAULT_AW_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_DEFAULT_AW_QOS_DEFAULT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT (8U)
/*! AR_QOS_DEFAULT - Read channel Qos default value register */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_DEFAULT_AR_QOS_DEFAULT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_DEFAULT_AR_QOS_DEFAULT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_DEFAULT_AR_QOS_DEFAULT_MASK)
/*! @} */

/*! @name PCIE2_AXQOS_PANIC - PCIE2 AXi master QoS (panic mode) programmable register */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_PANIC_AW_QOS_PANIC_MASK (0x7U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_PANIC_AW_QOS_PANIC_SHIFT (0U)
/*! AW_QOS_PANIC - write channel Qos panic value register */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_PANIC_AW_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_PANIC_AW_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_PANIC_AW_QOS_PANIC_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_PANIC_AR_QOS_PANIC_MASK (0x700U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_PANIC_AR_QOS_PANIC_SHIFT (8U)
/*! AR_QOS_PANIC - Read channel Qos panic value register */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_PANIC_AR_QOS_PANIC(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_PANIC_AR_QOS_PANIC_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE2_AXQOS_PANIC_AR_QOS_PANIC_MASK)
/*! @} */

/*! @name PCIE1_DMA_XFER_GO_TOGG - PCIE1 DMA engine descriptor transfer go toggle register. */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_MASK (0xFU)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_SHIFT (0U)
/*! DMA_RDXFER_GO_TOGG - DMA read engine descriptor transfer go toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_MASK (0xF00U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_SHIFT (8U)
/*! DMA_WDXFER_GO_TOGG - DMA write engine descriptor transfer go toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_MASK (0xF0000U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_SHIFT (16U)
/*! DMA_RDXFER_DONE_TOGG - DMA read engine descriptor transfer done toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_MASK (0xF000000U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_SHIFT (24U)
/*! DMA_WDXFER_DONE_TOGG - DMA write engine descriptor transfer done toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_MASK)
/*! @} */

/*! @name PCIE2_DMA_XFER_GO_TOGG - PCIE2 DMA engine descriptor transfer go toggle register. */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_MASK (0xFU)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_SHIFT (0U)
/*! DMA_RDXFER_GO_TOGG - DMA read engine descriptor transfer go toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_RDXFER_GO_TOGG_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_MASK (0xF00U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_SHIFT (8U)
/*! DMA_WDXFER_GO_TOGG - DMA write engine descriptor transfer go toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_WDXFER_GO_TOGG_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_MASK (0xF0000U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_SHIFT (16U)
/*! DMA_RDXFER_DONE_TOGG - DMA read engine descriptor transfer done toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_RDXFER_DONE_TOGG_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_MASK (0xF000000U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_SHIFT (24U)
/*! DMA_WDXFER_DONE_TOGG - DMA write engine descriptor transfer done toggle */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE2_DMA_XFER_GO_TOGG_DMA_WDXFER_DONE_TOGG_MASK)
/*! @} */

/*! @name PCIE1_REG - PCIe1 register */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_RADM_CPL_TIMEOUT_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_RADM_CPL_TIMEOUT_SHIFT (0U)
/*! RADM_CPL_TIMEOUT - Indicates that the completion TLP for a request has not been received within the expected time window. */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_RADM_CPL_TIMEOUT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_RADM_CPL_TIMEOUT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_RADM_CPL_TIMEOUT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_PHY_LANE0_POWER_PRESENT_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_PHY_LANE0_POWER_PRESENT_SHIFT (1U)
/*! PHY_LANE0_POWER_PRESENT - Power present indicator for lane 0 */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_PHY_LANE0_POWER_PRESENT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_PHY_LANE0_POWER_PRESENT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE1_REG_PHY_LANE0_POWER_PRESENT_MASK)
/*! @} */

/*! @name PCIE2_REG - PCIe2 register */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_REG_RADM_CPL_TIMEOUT_MASK (0x1U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_REG_RADM_CPL_TIMEOUT_SHIFT (0U)
/*! RADM_CPL_TIMEOUT - Indicates that the completion TLP for a request has not been received within the expected time window. */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_REG_RADM_CPL_TIMEOUT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE2_REG_RADM_CPL_TIMEOUT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE2_REG_RADM_CPL_TIMEOUT_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_REG_PHY_LANE0_POWER_PRESENT_MASK (0x2U)
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_REG_PHY_LANE0_POWER_PRESENT_SHIFT (1U)
/*! PHY_LANE0_POWER_PRESENT - Power present indicator for lane 0 */
#define HSIO_BLK_CTRL_HSIOMIX_PCIE2_REG_PHY_LANE0_POWER_PRESENT(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_PCIE2_REG_PHY_LANE0_POWER_PRESENT_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_PCIE2_REG_PHY_LANE0_POWER_PRESENT_MASK)
/*! @} */

/*! @name LFAST_IO_REG - GPR registers for LFAST IO */
/*! @{ */

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_CREF_EN_MASK (0x40U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_CREF_EN_SHIFT (6U)
/*! CREF_EN - Enable current reference control signal */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_CREF_EN(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_CREF_EN_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_CREF_EN_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT1_MASK (0x80U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT1_SHIFT (7U)
/*! IREF_TX_OPT1 - Control signal to adjust/boost transmitter current reference by 16% . Must be programmed through Fuse */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT1(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT1_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT1_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT2_MASK (0x100U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT2_SHIFT (8U)
/*! IREF_TX_OPT2 - Control signal to adjust/boost transmitter current reference by 17% . Must be programmed through Fuse */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT2(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT2_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT2_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT3_MASK (0x200U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT3_SHIFT (9U)
/*! IREF_TX_OPT3 - Control signal to adjust/boost transmitter current reference by 18% . Must be programmed through Fuse */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT3(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT3_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT3_MASK)

#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT4_MASK (0x400U)
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT4_SHIFT (10U)
/*! IREF_TX_OPT4 - Control signal to adjust/boost transmitter current reference by 19% . Must be programmed through Fuse */
#define HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT4(x) (((uint32_t)(((uint32_t)(x)) << HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT4_SHIFT)) & HSIO_BLK_CTRL_HSIOMIX_LFAST_IO_REG_IREF_TX_OPT4_MASK)
/*! @} */


/*!
 * @}
 */ /* end of group HSIO_BLK_CTRL_HSIOMIX_Register_Masks */


/*!
 * @}
 */ /* end of group HSIO_BLK_CTRL_HSIOMIX_Peripheral_Access_Layer */


/*
** End of section using anonymous unions
*/

#if defined(__ARMCC_VERSION)
  #if (__ARMCC_VERSION >= 6010050)
    #pragma clang diagnostic pop
  #else
    #pragma pop
  #endif
#elif defined(__GNUC__)
  /* leave anonymous unions enabled */
#elif defined(__IAR_SYSTEMS_ICC__)
  #pragma language=default
#else
  #error Not supported compiler type
#endif

/*!
 * @}
 */ /* end of group Peripheral_access_layer */


#endif  /* HSIO_BLK_CTRL_HSIOMIX_H_ */

