/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKV31F512VLH12/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKV31F512VLL12-pinctrl.h with this part's differences applied
 * below (68 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 78fcf9d44f6a7254
 */

#ifndef _ZEPHYR_DTS_BINDING_MKV31F512VLH12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKV31F512VLH12_WRAPPER_

#include "MKV31F512VLL12-pinctrl.h"

/* Signals not present on this part */
#undef ADC1_SE14_PTB10
#undef ADC1_SE15_PTB11
#undef ADC1_SE17_PTA17
#undef ADC1_SE6a_PTE2
#undef ADC1_SE7a_PTE3
#undef CLKOUT32K_PTE26
#undef CMP0_OUT_PTB20
#undef CMP1_OUT_PTB21
#undef FTM0_FLT1_PTB10
#undef FTM0_FLT2_PTB11
#undef FTM3_CH0_PTE5
#undef FTM3_CH1_PTE6
#undef FTM3_FLT0_PTC12
#undef LLWU_P1_PTE2
#undef LLWU_P2_PTE4
#undef LPUART0_CTS_b_PTB9
#undef LPUART0_CTS_b_PTE6
#undef LPUART0_RTS_b_PTC18
#undef LPUART0_RX_PTB10
#undef LPUART0_RX_PTC16
#undef LPUART0_RX_PTE5
#undef LPUART0_TX_PTB11
#undef LPUART0_TX_PTC17
#undef LPUART0_TX_PTE4
#undef PTA14
#undef PTA15
#undef PTA16
#undef PTA17
#undef PTB10
#undef PTB11
#undef PTB20
#undef PTB21
#undef PTB22
#undef PTB23
#undef PTB9
#undef PTC12
#undef PTC13
#undef PTC14
#undef PTC15
#undef PTC16
#undef PTC17
#undef PTC18
#undef PTE2
#undef PTE26
#undef PTE3
#undef PTE4
#undef PTE5
#undef PTE6
#undef SPI0_PCS0_PTA14
#undef SPI0_PCS5_PTB23
#undef SPI0_SCK_PTA15
#undef SPI0_SIN_PTA17
#undef SPI0_SOUT_PTA16
#undef SPI1_PCS0_PTB10
#undef SPI1_PCS0_PTE4
#undef SPI1_PCS1_PTB9
#undef SPI1_PCS2_PTE5
#undef SPI1_PCS3_PTE6
#undef SPI1_SCK_PTB11
#undef SPI1_SCK_PTE2
#undef SPI1_SIN_PTE3
#undef SPI1_SOUT_PTE3
#undef UART0_CTS_b_PTA16
#undef UART0_RTS_b_PTA17
#undef UART0_RX_PTA15
#undef UART0_TX_PTA14
#undef UART1_CTS_b_PTE2
#undef UART1_RTS_b_PTE3

#endif /* _ZEPHYR_DTS_BINDING_MKV31F512VLH12_WRAPPER_ */
