/*
** ###################################################################
**     Processors:          MIMX9534AVZXN_cm7
**                          MIMX9534CVTXN_cm7
**                          MIMX9534CVZXN_cm7
**                          MIMX9534DVTXN_cm7
**                          MIMX9534DVZXN_cm7
**                          MIMX9534XVTXN_cm7
**                          MIMX9534XVZXN_cm7
**
**     Compilers:           GNU C Compiler
**                          IAR ANSI C/C++ Compiler for ARM
**                          Keil ARM C/C++ Compiler
**
**     Reference manual:    iMX95RM rev1 draftM
**     Version:             rev. 2.0, 2024-10-29
**     Build:               b250522
**
**     Abstract:
**         CMSIS Peripheral Access Layer for MIMX9534_cm7
**
**     Copyright 1997-2016 Freescale Semiconductor, Inc.
**     Copyright 2016-2025 NXP
**     SPDX-License-Identifier: BSD-3-Clause
**
**     http:                 www.nxp.com
**     mail:                 support@nxp.com
**
**     Revisions:
**     - rev. 1.0 (2023-01-10)
**         Initial version.
**     - rev. 2.0 (2024-10-29)
**         Change the device header file from single flat file to multiple files based on peripherals,
**         each peripheral with dedicated header file located in periphN folder.
**
** ###################################################################
*/

/*!
 * @file MIMX9534_cm7.h
 * @version 2.0
 * @date 2024-10-29
 * @brief CMSIS Peripheral Access Layer for MIMX9534_cm7
 *
 * CMSIS Peripheral Access Layer for MIMX9534_cm7
 */

#if !defined(MIMX9534_cm7_H_)  /* Check if memory map has not been already included */
#define MIMX9534_cm7_H_

/* IP Header Files List */
#include "PERI_ADC.h"
#include "PERI_ALWAYS_ON_MAIN_RESILIENCEFAULTCONTROLLER.h"
#include "PERI_ANALOG_AGDET.h"
#include "PERI_ANALOG_FRO.h"
#include "PERI_ANALOG_OSC24M.h"
#include "PERI_ANALOG_PMRO.h"
#include "PERI_ANALOG_TCU.h"
#include "PERI_ANALOG_TRGMUX.h"
#include "PERI_ANALOG_VDET.h"
#include "PERI_AON_BLK_CTRL_NS_AONMIX.h"
#include "PERI_AON_BLK_CTRL_S_AONMIX.h"
#include "PERI_AON_CMU.h"
#include "PERI_AON_FCCU.h"
#include "PERI_AON_MCM.h"
#include "PERI_AON_ROMCP.h"
#include "PERI_AON_SYSPM.h"
#include "PERI_AON_TCU.h"
#include "PERI_AUDIO_XCVR.h"
#include "PERI_AUTOFOCUS.h"
#include "PERI_AXBS.h"
#include "PERI_BBNSM.h"
#include "PERI_BBSM_BLK_CTRL_BBSMMIX.h"
#include "PERI_BBSM_TCU.h"
#include "PERI_BLK_CTRL_CAMERAMIX.h"
#include "PERI_BLK_CTRL_NETCMIX.h"
#include "PERI_BLK_CTRL_WAKEUPMIX.h"
#include "PERI_BNR.h"
#include "PERI_CACHE_ECC_MCM.h"
#include "PERI_CAMERA_DSI_CAMID_CSR.h"
#include "PERI_CAMERA_DSI_MASTER_CSR.h"
#include "PERI_CAMERA_DSI_OR_CSI_PHY_CSR.h"
#include "PERI_CAMERA_DSI_PIXEL_FORMATTING.h"
#include "PERI_CAMERA_DSI_STREAM_CSR.h"
#include "PERI_CAMERA_MIPI_CSI2.h"
#include "PERI_CAMERA_TCU.h"
#include "PERI_CAN.h"
#include "PERI_CAS.h"
#include "PERI_CCM.h"
#include "PERI_CCMSRCGPC_TCU.h"
#include "PERI_CCONVMED.h"
#include "PERI_CM0_I_MAIN_QOSGENERATOR.h"
#include "PERI_CMU.h"
#include "PERI_COLOR_TEMP.h"
#include "PERI_COREMIX.h"
#include "PERI_CORE_CLK.h"
#include "PERI_CORE_PLATFORM.h"
#include "PERI_CORTEXA_TCU.h"
#include "PERI_CRCA.h"
#include "PERI_CSI.h"
#include "PERI_CSTCU.h"
#include "PERI_DDRC.h"
#include "PERI_DDR_BLK_CTRL_DDRMIX.h"
#include "PERI_DDR_TCU.h"
#include "PERI_DEMOSAIC.h"
#include "PERI_DF.h"
#include "PERI_DISPLAY_BLK_CTRL_DISPLAYMIX.h"
#include "PERI_DISPLAY_INTERLEAVER.h"
#include "PERI_DISPLAY_PIXEL_MAPPER.h"
#include "PERI_DISPLAY_SEERIS.h"
#include "PERI_DISPLAY_TCU.h"
#include "PERI_DMA.h"
#include "PERI_DMA5.h"
#include "PERI_DOORBELLS.h"
#include "PERI_DPU_IRQSTEER.h"
#include "PERI_DRC.h"
#include "PERI_EDMA_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_EDMA_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_EE.h"
#include "PERI_EIM.h"
#include "PERI_ENETC.h"
#include "PERI_ENETC_GLOBAL.h"
#include "PERI_ENETC_PCI_TYPE0.h"
#include "PERI_ENETC_PF_EMDIO.h"
#include "PERI_ENETC_PF_TMR.h"
#include "PERI_ENETC_SI.h"
#include "PERI_ENETC_VF_PCI_TYPE0.h"
#include "PERI_ENET_PHY.h"
#include "PERI_ENET_PHY_CTRL_EX.h"
#include "PERI_ENET_PHY_MAC_ADAPTER.h"
#include "PERI_ENET_PHY_PMA_MMD.h"
#include "PERI_ENET_PHY_VS_MII_MMD.h"
#include "PERI_ENET_PHY_XS_PCS_MMD.h"
#include "PERI_ERM.h"
#include "PERI_FLEXIO.h"
#include "PERI_FLEXSPI.h"
#include "PERI_GCM.h"
#include "PERI_GPC.h"
#include "PERI_GPC_GLOBAL.h"
#include "PERI_GPU_BLK_CTRL_GPUMIX.h"
#include "PERI_GPU_REGISTERS.h"
#include "PERI_GPU_TCU.h"
#include "PERI_HC.h"
#include "PERI_HDR_DECOMPRESS0.h"
#include "PERI_HDR_DECOMPRESS1.h"
#include "PERI_HDR_MERGE.h"
#include "PERI_HSIO_BLK_CTRL_HSIOMIX.h"
#include "PERI_HSIO_GHZ_LN_PLL.h"
#include "PERI_HSIO_TCU.h"
#include "PERI_I2S.h"
#include "PERI_I3C.h"
#include "PERI_IDBG1.h"
#include "PERI_IDBG2.h"
#include "PERI_IEPRC_IERB.h"
#include "PERI_IEPRC_PCI.h"
#include "PERI_IEPRC_PRB.h"
#include "PERI_INTM.h"
#include "PERI_IOMUXC.h"
#include "PERI_IOMUXC_GPR.h"
#include "PERI_IPA_CONTROL.h"
#include "PERI_IRQSTEER.h"
#include "PERI_IR_COMPRESS.h"
#include "PERI_ISI.h"
#include "PERI_ISI_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_ISI_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_ISI_WR_U_I_MAIN_QOSGENERATOR.h"
#include "PERI_ISI_WR_U_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_ISI_WR_V_I_MAIN_QOSGENERATOR.h"
#include "PERI_ISI_WR_V_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_ISI_WR_Y_I_MAIN_QOSGENERATOR.h"
#include "PERI_ISI_WR_Y_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_ISP.h"
#include "PERI_ISP_RD_0_I_MAIN_QOSGENERATOR.h"
#include "PERI_ISP_RD_0_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_ISP_RD_1_I_MAIN_QOSGENERATOR.h"
#include "PERI_ISP_RD_1_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_ISP_WR_0_I_MAIN_QOSGENERATOR.h"
#include "PERI_ISP_WR_0_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_ISP_WR_1_I_MAIN_QOSGENERATOR.h"
#include "PERI_ISP_WR_1_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_2D_BLITTER_FU_RD_0_I_MAIN_QOSGENERATOR.h"
#include "PERI_I_SEERIS_2D_BLITTER_FU_RD_0_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_2D_BLITTER_FU_RD_1_I_MAIN_QOSGENERATOR.h"
#include "PERI_I_SEERIS_2D_BLITTER_FU_RD_1_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_2D_BLITTER_FU_RD_2_I_MAIN_QOSGENERATOR.h"
#include "PERI_I_SEERIS_2D_BLITTER_FU_RD_2_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_2D_BLITTER_STORE_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_I_SEERIS_2D_BLITTER_STORE_WR_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_CMD_SEQ_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_CMD_SEQ_WR_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_DISPLAY_CTRL_FU_RD_0_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_DISPLAY_CTRL_FU_RD_1_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_DISPLAY_CTRL_FU_RD_2_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_DISPLAY_CTRL_FU_RD_3_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_DISPLAY_CTRL_FU_RD_4_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_DISPLAY_CTRL_FU_RD_5_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_DISPLAY_CTRL_FU_RD_6_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_DISPLAY_CTRL_FU_RD_7_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_I_SEERIS_DISPLAY_CTRL_FU_RD_8_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_JPEG_DEC.h"
#include "PERI_JPEG_DEC_WRAP.h"
#include "PERI_JPEG_ENC.h"
#include "PERI_LDB.h"
#include "PERI_LPI2C.h"
#include "PERI_LPIT.h"
#include "PERI_LPSPI.h"
#include "PERI_LPTMR.h"
#include "PERI_LPUART.h"
#include "PERI_LSTCU.h"
#include "PERI_M7_A7_APB_MCM.h"
#include "PERI_M7_TCU.h"
#include "PERI_MIPI_DSI.h"
#include "PERI_MMU_TBU0.h"
#include "PERI_MMU_TBU1.h"
#include "PERI_MMU_TBU2.h"
#include "PERI_MMU_TBU_ME10.h"
#include "PERI_MMU_TBU_ME11.h"
#include "PERI_MMU_TBU_ME3.h"
#include "PERI_MMU_TBU_ME4.h"
#include "PERI_MMU_TBU_ME5.h"
#include "PERI_MMU_TBU_ME6.h"
#include "PERI_MMU_TBU_ME7.h"
#include "PERI_MMU_TBU_ME9.h"
#include "PERI_MMU_TCU.h"
#include "PERI_MSGINTR.h"
#include "PERI_MU.h"
#include "PERI_M_E_0_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_0_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_0_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_0_WR_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_10_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_10_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_10_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_10_WR_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_11_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_11_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_11_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_11_WR_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_1A_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_1A_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_1B_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_1B_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_3_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_3_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_3_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_3_WR_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_4_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_4_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_4_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_4_WR_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_5_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_5_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_5_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_5_WR_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_6_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_6_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_7_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_7_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_7_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_7_WR_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_8_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_8_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_9_RD_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_9_RD_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_M_E_9_WR_I_MAIN_QOSGENERATOR.h"
#include "PERI_M_E_9_WR_I_MAIN_TRANSACTIONSTATFILTER.h"
#include "PERI_NETC_ENETC.h"
#include "PERI_NETC_ETH_LINK.h"
#include "PERI_NETC_IERB.h"
#include "PERI_NETC_PORT.h"
#include "PERI_NETC_PRIV.h"
#include "PERI_NETC_SW_ENETC.h"
#include "PERI_NETC_TCU.h"
#include "PERI_NEUTRON.h"
#include "PERI_NEUTRONS.h"
#include "PERI_NEUTRON_NPU.h"
#include "PERI_NOC_BLK_CTRL_NOCMIX.h"
#include "PERI_NOC_CMU.h"
#include "PERI_NOC_EIM.h"
#include "PERI_NOC_GICA.h"
#include "PERI_NOC_GICD.h"
#include "PERI_NOC_GICDA.h"
#include "PERI_NOC_GICP.h"
#include "PERI_NOC_GICRLPI0.h"
#include "PERI_NOC_GICRLPI1.h"
#include "PERI_NOC_GICRLPI2.h"
#include "PERI_NOC_GICRLPI3.h"
#include "PERI_NOC_GICRLPI4.h"
#include "PERI_NOC_GICRLPI5.h"
#include "PERI_NOC_GICRSGI0.h"
#include "PERI_NOC_GICRSGI1.h"
#include "PERI_NOC_GICRSGI2.h"
#include "PERI_NOC_GICRSGI3.h"
#include "PERI_NOC_GICRSGI4.h"
#include "PERI_NOC_GICRSGI5.h"
#include "PERI_NOC_GICT.h"
#include "PERI_NOC_GITS0.h"
#include "PERI_NOC_GITS0TRANSLATER.h"
#include "PERI_NOC_JPEG_DEC_MAIN_PROBE.h"
#include "PERI_NOC_JPEG_DEC_PROBE_XSTATPROFILER.h"
#include "PERI_NOC_JPEG_DEC_RD_I_XSTATFILTER.h"
#include "PERI_NOC_JPEG_DEC_WR_I_QOSGENERATOR.h"
#include "PERI_NOC_JPEG_DEC_WR_I_XSTATFILTER.h"
#include "PERI_NOC_JPEG_ENC_MAIN_PROBE.h"
#include "PERI_NOC_JPEG_ENC_PROBE_XSTATPROFILER.h"
#include "PERI_NOC_JPEG_ENC_RD_I_QOSGENERATOR.h"
#include "PERI_NOC_JPEG_ENC_RD_I_XSTATFILTER.h"
#include "PERI_NOC_JPEG_ENC_WR_I_XSTATFILTER.h"
#include "PERI_NOC_LSTCU.h"
#include "PERI_NOC_PCIE1_AXI_SLAVE_RD_I_XSTATFILTER.h"
#include "PERI_NOC_PCIE1_AXI_SLAVE_WR_I_XSTATFILTER.h"
#include "PERI_NOC_PCIE2_AXI_SLAVE_RD_I_XSTATFILTER.h"
#include "PERI_NOC_PCIE2_AXI_SLAVE_WR_I_XSTATFILTER.h"
#include "PERI_NOC_PROBE_TRANSACTION_XSTATPROFILER.h"
#include "PERI_NOC_RD_TRANSACTION_PROBE.h"
#include "PERI_NOC_SRAMCTL.h"
#include "PERI_NOC_SSI_MASTER_ERROR_ERRLOG_0.h"
#include "PERI_NOC_SSI_PRI_MAIN_PROBE.h"
#include "PERI_NOC_TCU.h"
#include "PERI_NOC_USB1_AXI_SLAVE_RD_I_XSTATFILTER.h"
#include "PERI_NOC_USB1_AXI_SLAVE_WR_I_XSTATFILTER.h"
#include "PERI_NOC_USB2_AXI_SLAVE_RD_I_XSTATFILTER.h"
#include "PERI_NOC_USB2_AXI_SLAVE_WR_I_XSTATFILTER.h"
#include "PERI_NOC_VPU_PRI_MAIN_PROBE.h"
#include "PERI_NOC_VPU_PRI_PROBE_XSTATPROFILER.h"
#include "PERI_NOC_VPU_PRI_RD_I_QOSGENERATOR.h"
#include "PERI_NOC_VPU_PRI_RD_I_XSTATFILTER.h"
#include "PERI_NOC_VPU_PRI_WR_I_QOSGENERATOR.h"
#include "PERI_NOC_VPU_PRI_WR_I_XSTATFILTER.h"
#include "PERI_NPU_TCU.h"
#include "PERI_NR.h"
#include "PERI_OB_WB0.h"
#include "PERI_OB_WB1.h"
#include "PERI_OB_WB2.h"
#include "PERI_OCRAM.h"
#include "PERI_OTFAD.h"
#include "PERI_PACKETIZER.h"
#include "PERI_PCIE_DMA_IATU.h"
#include "PERI_PCIE_EP.h"
#include "PERI_PCIE_RC.h"
#include "PERI_PCIE_SHADOW_EP.h"
#include "PERI_PDM.h"
#include "PERI_PIPE_CONF.h"
#include "PERI_PLL.h"
#include "PERI_POWER_MAIN_RESILIENCEFAULTCONTROLLER.h"
#include "PERI_PROBE1_MAIN_PROBE.h"
#include "PERI_PROBE1_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_ISI_MAIN_PROBE.h"
#include "PERI_PROBE_ISI_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_ISP_MAIN_PROBE.h"
#include "PERI_PROBE_ISP_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_MAIN_PROBE.h"
#include "PERI_PROBE_M_E_0_MAIN_PROBE.h"
#include "PERI_PROBE_M_E_0_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_M_E_10_MAIN_PROBE.h"
#include "PERI_PROBE_M_E_10_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_M_E_11_MAIN_PROBE.h"
#include "PERI_PROBE_M_E_11_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_M_E_3_MAIN_PROBE.h"
#include "PERI_PROBE_M_E_3_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_M_E_4_MAIN_PROBE.h"
#include "PERI_PROBE_M_E_4_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_M_E_5_MAIN_PROBE.h"
#include "PERI_PROBE_M_E_5_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_M_E_6_MAIN_PROBE.h"
#include "PERI_PROBE_M_E_6_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_M_E_7_MAIN_PROBE.h"
#include "PERI_PROBE_M_E_7_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_M_E_9_MAIN_PROBE.h"
#include "PERI_PROBE_M_E_9_MAIN_TRANSACTIONSTATPROFILER.h"
#include "PERI_PROBE_SSI_FWD_MAIN_PROBE.h"
#include "PERI_RGBIR.h"
#include "PERI_RGB_TO_YUV.h"
#include "PERI_RGPIO.h"
#include "PERI_SEMA42.h"
#include "PERI_SERDES_SS.h"
#include "PERI_SRC_GENERAL_REG.h"
#include "PERI_SRC_MEM.h"
#include "PERI_SRC_XSPR.h"
#include "PERI_STAT.h"
#include "PERI_SYS_CTR1.h"
#include "PERI_SYS_CTR_COMPARE.h"
#include "PERI_SYS_CTR_READ.h"
#include "PERI_TCM_ECC_MCM.h"
#include "PERI_TMPSNS.h"
#include "PERI_TPM.h"
#include "PERI_TRDC_MBC2.h"
#include "PERI_TSTMR.h"
#include "PERI_USB.h"
#include "PERI_USB3_CORE.h"
#include "PERI_USB3_GLUE.h"
#include "PERI_USB3_PHY_TCA.h"
#include "PERI_USBNC.h"
#include "PERI_USDHC.h"
#include "PERI_USER.h"
#include "PERI_VIGNETTING.h"
#include "PERI_VPU.h"
#include "PERI_VPU_BLK_CTRL_VPUMIX.h"
#include "PERI_VPU_JPEG_ENC_WRAP.h"
#include "PERI_VPU_TCU.h"
#include "PERI_WAKEUP_AHBRM.h"
#include "PERI_WAKEUP_ATU.h"
#include "PERI_WAKEUP_DMA_CRC.h"
#include "PERI_WAKEUP_ROMCP.h"
#include "PERI_WAKEUP_XSPI_RESPONDER.h"
#include "PERI_WDOG.h"
#include "PERI_XCACHE.h"

#endif  /* #if !defined(MIMX9534_cm7_H_) */
