/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN536TVPB/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN537VPB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: abed141e442e3ffb
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN536TVPB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN536TVPB_WRAPPER_

#include "MCXN537VPB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN536TVPB_WRAPPER_ */
