/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN546VNL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN547VKL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: e8fda37873eab0de
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN546VNL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN546VNL_WRAPPER_

#include "MCXN547VKL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN546VNL_WRAPPER_ */
