/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN947VPB/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXN947VDF-pinctrl.h with this part's differences applied
 * below (75 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 5c1d4a3d156c0945
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN947VPB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN947VPB_WRAPPER_

#include "MCXN947VDF-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_B20_PIO0_28
#undef ADC0_B21_PIO0_29
#undef ADC0_B22_PIO0_30
#undef ADC0_B23_PIO0_31
#undef ADC1_A20_PIO1_20
#undef ADC1_A21_PIO1_21
#undef ADC1_A22_PIO1_22
#undef ADC1_A23_PIO1_23
#undef CAN1_RXD_PIO1_21
#undef CAN1_TXD_PIO1_20
#undef CMP1_IN3_PIO1_20
#undef CMP2_IN3_PIO1_21
#undef CT2_MAT0_PIO3_18
#undef CT2_MAT1_PIO3_19
#undef CT3_MAT2_PIO1_20
#undef CT3_MAT3_PIO1_21
#undef CT_INP0_PIO0_28
#undef CT_INP14_PIO1_22
#undef CT_INP15_PIO1_23
#undef CT_INP1_PIO0_29
#undef CT_INP2_PIO0_30
#undef CT_INP3_PIO0_31
#undef ENET0_MDC_PIO1_20
#undef ENET0_MDIO_PIO1_21
#undef FC0_P4_PIO0_28
#undef FC0_P5_PIO0_29
#undef FC0_P6_PIO0_30
#undef FC1_P4_PIO0_28
#undef FC1_P5_PIO0_29
#undef FC1_P6_PIO0_30
#undef FC4_P0_PIO1_20
#undef FC4_P1_PIO1_21
#undef FC4_P2_PIO1_22
#undef FC4_P3_PIO1_23
#undef FC5_P4_PIO1_20
#undef FC5_P5_PIO1_21
#undef FC5_P6_PIO1_22
#undef FC6_P6_PIO3_18
#undef FC7_P6_PIO3_19
#undef FLEXIO0_D26_PIO3_18
#undef FLEXIO0_D27_PIO3_19
#undef FLEXIO0_D28_PIO1_20
#undef FLEXIO0_D29_PIO1_21
#undef FLEXIO0_D30_PIO1_22
#undef FLEXIO0_D31_PIO1_23
#undef PIO0_28
#undef PIO0_29
#undef PIO0_30
#undef PIO0_31
#undef PIO1_20
#undef PIO1_21
#undef PIO1_22
#undef PIO1_23
#undef PIO3_18
#undef PIO3_19
#undef PLU_OUT6_PIO1_20
#undef PLU_OUT7_PIO1_21
#undef PWM1_X0_PIO3_18
#undef PWM1_X1_PIO3_19
#undef SAI1_MCLK_PIO1_21
#undef SAI1_RX_BCLK_PIO3_18
#undef SAI1_RX_FS_PIO3_19
#undef SCT0_OUT4_PIO1_22
#undef SCT0_OUT5_PIO1_23
#undef SCT0_OUT8_PIO1_20
#undef SCT0_OUT9_PIO1_21
#undef SMARTDMA_PIO16_PIO1_20
#undef SMARTDMA_PIO17_PIO1_21
#undef SMARTDMA_PIO18_PIO1_22
#undef SMARTDMA_PIO18_PIO3_18
#undef SMARTDMA_PIO19_PIO1_23
#undef SMARTDMA_PIO19_PIO3_19
#undef TRIG_IN2_PIO1_20
#undef TRIG_IN3_PIO1_22
#undef TRIG_OUT2_PIO1_21

#endif /* _ZEPHYR_DTS_BINDING_MCXN947VPB_WRAPPER_ */
