/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN235VDF/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN236VDF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 1936228a352dbcb6
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN235VDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN235VDF_WRAPPER_

#include "MCXN236VDF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN235VDF_WRAPPER_ */
