/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN547TVDF/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN547VDF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 041f5fccacbf842f
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN547TVDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN547TVDF_WRAPPER_

#include "MCXN547VDF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN547TVDF_WRAPPER_ */
