/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN947VNL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN947VKL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: c6619f1a8803040b
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN947VNL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN947VNL_WRAPPER_

#include "MCXN947VKL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN947VNL_WRAPPER_ */
