/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN537TVKL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN537VKL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: eeb6272ba5a7fe53
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN537TVKL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN537TVKL_WRAPPER_

#include "MCXN537VKL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN537TVKL_WRAPPER_ */
