/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN235VPB/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN236VPB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 1d51bb588e5fe223
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN235VPB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN235VPB_WRAPPER_

#include "MCXN236VPB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN235VPB_WRAPPER_ */
