/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN946VDF/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXN947VDF-pinctrl.h with this part's differences applied
 * below (56 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 5c1d4a3d156c0945
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN946VDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN946VDF_WRAPPER_

#include "MCXN947VDF-pinctrl.h"

/* Signals not present on this part */
#undef PDM0_CLK_PIO0_16
#undef PDM0_CLK_PIO0_4
#undef PDM0_DATA0_PIO0_17
#undef PDM0_DATA0_PIO0_5
#undef PDM0_DATA1_PIO0_18
#undef PDM0_DATA1_PIO0_6
#undef SDHC0_CLK_PIO2_4
#undef SDHC0_CMD_PIO2_5
#undef SDHC0_D0_PIO2_3
#undef SDHC0_D1_PIO2_2
#undef SDHC0_D2_PIO2_7
#undef SDHC0_D3_PIO2_6
#undef SDHC0_D4_PIO2_1
#undef SDHC0_D5_PIO2_0
#undef SDHC0_D6_PIO2_9
#undef SDHC0_D7_PIO2_8
#undef SIM0_CLK_PIO3_10
#undef SIM0_CLK_PIO3_16
#undef SIM0_IO_PIO3_11
#undef SIM0_IO_PIO3_17
#undef SIM0_PD_PIO3_20
#undef SIM0_PD_PIO3_8
#undef SIM0_RST_PIO3_21
#undef SIM0_RST_PIO3_9
#undef SIM0_VCCEN_PIO3_22
#undef SIM0_VCCEN_PIO3_7
#undef SIM1_CLK_PIO3_4
#undef SIM1_IO_PIO3_5
#undef SIM1_PD_PIO3_2
#undef SIM1_RST_PIO3_3
#undef SIM1_VCCEN_PIO3_6
#undef TSI0_CH0_PIO1_0
#undef TSI0_CH10_PIO0_6
#undef TSI0_CH11_PIO0_16
#undef TSI0_CH12_PIO0_17
#undef TSI0_CH13_PIO0_18
#undef TSI0_CH14_PIO0_19
#undef TSI0_CH15_PIO0_20
#undef TSI0_CH16_PIO0_21
#undef TSI0_CH17_PIO1_8
#undef TSI0_CH18_PIO1_9
#undef TSI0_CH19_PIO1_10
#undef TSI0_CH1_PIO1_1
#undef TSI0_CH20_PIO1_11
#undef TSI0_CH21_PIO1_12
#undef TSI0_CH22_PIO1_13
#undef TSI0_CH23_PIO1_14
#undef TSI0_CH24_PIO1_15
#undef TSI0_CH2_PIO1_2
#undef TSI0_CH3_PIO1_3
#undef TSI0_CH4_PIO1_4
#undef TSI0_CH5_PIO1_5
#undef TSI0_CH6_PIO1_6
#undef TSI0_CH7_PIO1_7
#undef TSI0_CH8_PIO0_4
#undef TSI0_CH9_PIO0_5

#endif /* _ZEPHYR_DTS_BINDING_MCXN946VDF_WRAPPER_ */
