/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN947TVDF/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN947VDF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 5c1d4a3d156c0945
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN947TVDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN947TVDF_WRAPPER_

#include "MCXN947VDF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN947TVDF_WRAPPER_ */
