/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN547TVPB/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN547VPB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: f0497ef49bc0919c
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN547TVPB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN547TVPB_WRAPPER_

#include "MCXN547VPB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN547TVPB_WRAPPER_ */
