/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN946VDF/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXN947VDF-pinctrl.h with this part's differences applied
 * below (56 removed, 0 changed,
 * 64 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 00bf958128388a2e
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN946VDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN946VDF_WRAPPER_

#include "MCXN947VDF-pinctrl.h"

/* Signals not present on this part */
#undef PDM0_CLK_PIO0_16
#undef PDM0_CLK_PIO0_4
#undef PDM0_DATA0_PIO0_17
#undef PDM0_DATA0_PIO0_5
#undef PDM0_DATA1_PIO0_18
#undef PDM0_DATA1_PIO0_6
#undef SDHC0_CLK_PIO2_4
#undef SDHC0_CMD_PIO2_5
#undef SDHC0_D0_PIO2_3
#undef SDHC0_D1_PIO2_2
#undef SDHC0_D2_PIO2_7
#undef SDHC0_D3_PIO2_6
#undef SDHC0_D4_PIO2_1
#undef SDHC0_D5_PIO2_0
#undef SDHC0_D6_PIO2_9
#undef SDHC0_D7_PIO2_8
#undef SIM0_CLK_PIO3_10
#undef SIM0_CLK_PIO3_16
#undef SIM0_IO_PIO3_11
#undef SIM0_IO_PIO3_17
#undef SIM0_PD_PIO3_20
#undef SIM0_PD_PIO3_8
#undef SIM0_RST_PIO3_21
#undef SIM0_RST_PIO3_9
#undef SIM0_VCCEN_PIO3_22
#undef SIM0_VCCEN_PIO3_7
#undef SIM1_CLK_PIO3_4
#undef SIM1_IO_PIO3_5
#undef SIM1_PD_PIO3_2
#undef SIM1_RST_PIO3_3
#undef SIM1_VCCEN_PIO3_6
#undef TSI0_CH0_PIO1_0
#undef TSI0_CH10_PIO0_6
#undef TSI0_CH11_PIO0_16
#undef TSI0_CH12_PIO0_17
#undef TSI0_CH13_PIO0_18
#undef TSI0_CH14_PIO0_19
#undef TSI0_CH15_PIO0_20
#undef TSI0_CH16_PIO0_21
#undef TSI0_CH17_PIO1_8
#undef TSI0_CH18_PIO1_9
#undef TSI0_CH19_PIO1_10
#undef TSI0_CH1_PIO1_1
#undef TSI0_CH20_PIO1_11
#undef TSI0_CH21_PIO1_12
#undef TSI0_CH22_PIO1_13
#undef TSI0_CH23_PIO1_14
#undef TSI0_CH24_PIO1_15
#undef TSI0_CH2_PIO1_2
#undef TSI0_CH3_PIO1_3
#undef TSI0_CH4_PIO1_4
#undef TSI0_CH5_PIO1_5
#undef TSI0_CH6_PIO1_6
#undef TSI0_CH7_PIO1_7
#undef TSI0_CH8_PIO0_4
#undef TSI0_CH9_PIO0_5

/* Signals specific to this part */
#define EZH_PIO0_PIO1_4 N9X_MUX('1',4,7)
#define EZH_PIO0_PIO3_0 N9X_MUX('3',0,7)
#define EZH_PIO10_PIO1_14 N9X_MUX('1',14,7)
#define EZH_PIO10_PIO3_10 N9X_MUX('3',10,7)
#define EZH_PIO11_PIO1_15 N9X_MUX('1',15,7)
#define EZH_PIO11_PIO3_11 N9X_MUX('3',11,7)
#define EZH_PIO12_PIO1_16 N9X_MUX('1',16,7)
#define EZH_PIO12_PIO3_12 N9X_MUX('3',12,7)
#define EZH_PIO13_PIO1_17 N9X_MUX('1',17,7)
#define EZH_PIO13_PIO3_13 N9X_MUX('3',13,7)
#define EZH_PIO14_PIO1_18 N9X_MUX('1',18,7)
#define EZH_PIO14_PIO3_14 N9X_MUX('3',14,7)
#define EZH_PIO15_PIO1_19 N9X_MUX('1',19,7)
#define EZH_PIO15_PIO3_15 N9X_MUX('3',15,7)
#define EZH_PIO16_PIO1_20 N9X_MUX('1',20,7)
#define EZH_PIO16_PIO3_16 N9X_MUX('3',16,7)
#define EZH_PIO17_PIO1_21 N9X_MUX('1',21,7)
#define EZH_PIO17_PIO3_17 N9X_MUX('3',17,7)
#define EZH_PIO18_PIO1_22 N9X_MUX('1',22,7)
#define EZH_PIO18_PIO3_18 N9X_MUX('3',18,7)
#define EZH_PIO19_PIO1_23 N9X_MUX('1',23,7)
#define EZH_PIO19_PIO3_19 N9X_MUX('3',19,7)
#define EZH_PIO1_PIO1_5 N9X_MUX('1',5,7)
#define EZH_PIO1_PIO3_1 N9X_MUX('3',1,7)
#define EZH_PIO20_PIO2_0 N9X_MUX('2',0,7)
#define EZH_PIO20_PIO3_20 N9X_MUX('3',20,7)
#define EZH_PIO21_PIO2_1 N9X_MUX('2',1,7)
#define EZH_PIO21_PIO3_21 N9X_MUX('3',21,7)
#define EZH_PIO22_PIO2_2 N9X_MUX('2',2,7)
#define EZH_PIO22_PIO3_22 N9X_MUX('3',22,7)
#define EZH_PIO23_PIO2_3 N9X_MUX('2',3,7)
#define EZH_PIO23_PIO3_23 N9X_MUX('3',23,7)
#define EZH_PIO24_PIO2_4 N9X_MUX('2',4,7)
#define EZH_PIO24_PIO4_0 N9X_MUX('4',0,7)
#define EZH_PIO25_PIO2_5 N9X_MUX('2',5,7)
#define EZH_PIO25_PIO4_1 N9X_MUX('4',1,7)
#define EZH_PIO26_PIO2_6 N9X_MUX('2',6,7)
#define EZH_PIO26_PIO4_2 N9X_MUX('4',2,7)
#define EZH_PIO27_PIO2_7 N9X_MUX('2',7,7)
#define EZH_PIO27_PIO4_3 N9X_MUX('4',3,7)
#define EZH_PIO28_PIO2_8 N9X_MUX('2',8,7)
#define EZH_PIO28_PIO4_4 N9X_MUX('4',4,7)
#define EZH_PIO29_PIO2_9 N9X_MUX('2',9,7)
#define EZH_PIO29_PIO4_5 N9X_MUX('4',5,7)
#define EZH_PIO2_PIO1_6 N9X_MUX('1',6,7)
#define EZH_PIO2_PIO3_2 N9X_MUX('3',2,7)
#define EZH_PIO30_PIO2_11 N9X_MUX('2',11,7)
#define EZH_PIO30_PIO4_6 N9X_MUX('4',6,7)
#define EZH_PIO31_PIO2_10 N9X_MUX('2',10,7)
#define EZH_PIO31_PIO4_7 N9X_MUX('4',7,7)
#define EZH_PIO3_PIO1_7 N9X_MUX('1',7,7)
#define EZH_PIO3_PIO3_3 N9X_MUX('3',3,7)
#define EZH_PIO4_PIO1_8 N9X_MUX('1',8,7)
#define EZH_PIO4_PIO3_4 N9X_MUX('3',4,7)
#define EZH_PIO5_PIO1_9 N9X_MUX('1',9,7)
#define EZH_PIO5_PIO3_5 N9X_MUX('3',5,7)
#define EZH_PIO6_PIO1_10 N9X_MUX('1',10,7)
#define EZH_PIO6_PIO3_6 N9X_MUX('3',6,7)
#define EZH_PIO7_PIO1_11 N9X_MUX('1',11,7)
#define EZH_PIO7_PIO3_7 N9X_MUX('3',7,7)
#define EZH_PIO8_PIO1_12 N9X_MUX('1',12,7)
#define EZH_PIO8_PIO3_8 N9X_MUX('3',8,7)
#define EZH_PIO9_PIO1_13 N9X_MUX('1',13,7)
#define EZH_PIO9_PIO3_9 N9X_MUX('3',9,7)

#endif /* _ZEPHYR_DTS_BINDING_MCXN946VDF_WRAPPER_ */
