/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN556TCDF/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN557SCDF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 9639601b60e6654d
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN556TCDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN556TCDF_WRAPPER_

#include "MCXN557SCDF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN556TCDF_WRAPPER_ */
