/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN247TVKL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN247VKL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: c9a164b26d801af7
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN247TVKL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN247TVKL_WRAPPER_

#include "MCXN247VKL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN247TVKL_WRAPPER_ */
