/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN527TVDF/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN527VDF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 11c64edb8568378a
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN527TVDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN527TVDF_WRAPPER_

#include "MCXN527VDF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN527TVDF_WRAPPER_ */
