/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN546VAB/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN547VAB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: b156cc036e6a275b
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN546VAB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN546VAB_WRAPPER_

#include "MCXN547VAB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN546VAB_WRAPPER_ */
