/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN556TVAB/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN557TCAB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 7554c7464fc0b090
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN556TVAB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN556TVAB_WRAPPER_

#include "MCXN557TCAB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN556TVAB_WRAPPER_ */
