/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN546VNL/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN547VNL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 483f9065a7390f6e
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN546VNL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN546VNL_WRAPPER_

#include "MCXN547VNL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN546VNL_WRAPPER_ */
