/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN235VNL/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN236VNL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 2eae6c72a509d9a9
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN235VNL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN235VNL_WRAPPER_

#include "MCXN236VNL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN235VNL_WRAPPER_ */
