/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN247TVPB/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN247VPB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: de145d5876136f3a
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN247TVPB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN247TVPB_WRAPPER_

#include "MCXN247VPB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN247TVPB_WRAPPER_ */
