/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN557SCDF/signal_configuration.xml
 *
 * 
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXN947VDF-pinctrl.h with this part's differences applied
 * below (104 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 5c1d4a3d156c0945
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN557SCDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN557SCDF_WRAPPER_

#include "MCXN947VDF-pinctrl.h"

/* Signals not present on this part */
#undef CAN1_RXD_PIO1_12
#undef CAN1_RXD_PIO1_21
#undef CAN1_RXD_PIO1_7
#undef CAN1_RXD_PIO4_15
#undef CAN1_TXD_PIO1_13
#undef CAN1_TXD_PIO1_20
#undef CAN1_TXD_PIO1_6
#undef CAN1_TXD_PIO4_16
#undef CMP2_IN0_PIO1_2
#undef CMP2_IN1_PIO0_7
#undef CMP2_IN2_PIO0_23
#undef CMP2_IN3_PIO1_21
#undef CMP2_IN4N_PIO4_2
#undef CMP2_IN4P_PIO4_23
#undef CMP2_IN5N_PIO4_3
#undef HSCMP2_OUT_PIO0_11
#undef HSCMP2_OUT_PIO0_6
#undef OPAMP0_INP0_PIO4_12
#undef OPAMP0_INP1_PIO4_13
#undef OPAMP0_OUT_PIO4_15
#undef OPAMP1_INP0_PIO4_16
#undef OPAMP1_INP1_PIO4_17
#undef OPAMP1_OUT_PIO4_19
#undef OPAMP2_INP0_PIO4_20
#undef OPAMP2_INP1_PIO4_21
#undef OPAMP2_OUT_PIO4_23
#undef PLU_CLK_PIO1_7
#undef PLU_CLK_PIO4_6
#undef PLU_IN0_PIO1_10
#undef PLU_IN0_PIO4_0
#undef PLU_IN1_PIO1_11
#undef PLU_IN1_PIO4_1
#undef PLU_IN2_PIO1_14
#undef PLU_IN2_PIO4_2
#undef PLU_IN3_PIO1_15
#undef PLU_IN3_PIO4_3
#undef PLU_IN4_PIO1_18
#undef PLU_IN4_PIO4_4
#undef PLU_IN5_PIO1_19
#undef PLU_IN5_PIO4_5
#undef PLU_OUT0_PIO1_8
#undef PLU_OUT0_PIO4_12
#undef PLU_OUT1_PIO1_9
#undef PLU_OUT1_PIO4_13
#undef PLU_OUT2_PIO1_12
#undef PLU_OUT2_PIO4_14
#undef PLU_OUT3_PIO1_13
#undef PLU_OUT3_PIO4_15
#undef PLU_OUT4_PIO1_16
#undef PLU_OUT4_PIO4_16
#undef PLU_OUT5_PIO1_17
#undef PLU_OUT5_PIO4_17
#undef PLU_OUT6_PIO1_20
#undef PLU_OUT6_PIO4_18
#undef PLU_OUT7_PIO1_21
#undef PLU_OUT7_PIO4_19
#undef PWM1_A0_PIO2_6
#undef PWM1_A0_PIO3_12
#undef PWM1_A1_PIO2_4
#undef PWM1_A1_PIO3_14
#undef PWM1_A2_PIO2_2
#undef PWM1_A2_PIO3_16
#undef PWM1_A3_PIO2_0
#undef PWM1_A3_PIO3_20
#undef PWM1_B0_PIO2_7
#undef PWM1_B0_PIO3_13
#undef PWM1_B1_PIO2_5
#undef PWM1_B1_PIO3_15
#undef PWM1_B2_PIO2_3
#undef PWM1_B2_PIO3_17
#undef PWM1_B3_PIO2_1
#undef PWM1_B3_PIO3_21
#undef PWM1_X0_PIO2_8
#undef PWM1_X0_PIO3_18
#undef PWM1_X1_PIO2_9
#undef PWM1_X1_PIO3_19
#undef PWM1_X2_PIO2_10
#undef PWM1_X2_PIO3_22
#undef PWM1_X3_PIO2_11
#undef PWM1_X3_PIO3_23
#undef SINC0_MBIT0_PIO2_3
#undef SINC0_MBIT0_PIO4_13
#undef SINC0_MBIT1_PIO2_5
#undef SINC0_MBIT1_PIO4_17
#undef SINC0_MBIT2_PIO2_7
#undef SINC0_MBIT2_PIO4_21
#undef SINC0_MBIT3_PIO2_9
#undef SINC0_MBIT3_PIO4_2
#undef SINC0_MBIT4_PIO2_11
#undef SINC0_MBIT4_PIO4_5
#undef SINC0_MCLK0_PIO2_2
#undef SINC0_MCLK0_PIO4_12
#undef SINC0_MCLK1_PIO2_4
#undef SINC0_MCLK1_PIO4_16
#undef SINC0_MCLK2_PIO2_6
#undef SINC0_MCLK2_PIO4_20
#undef SINC0_MCLK3_PIO2_8
#undef SINC0_MCLK3_PIO4_0
#undef SINC0_MCLK4_PIO2_10
#undef SINC0_MCLK4_PIO4_4
#undef SINC0_MCLK_OUT0_PIO2_1
#undef SINC0_MCLK_OUT0_PIO4_15
#undef SINC0_MCLK_OUT1_PIO4_19
#undef SINC0_MCLK_OUT2_PIO4_23

#endif /* _ZEPHYR_DTS_BINDING_MCXN557SCDF_WRAPPER_ */
