/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN946TVAB/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN946VAB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 8f475b76ff1dc72f
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN946TVAB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN946TVAB_WRAPPER_

#include "MCXN946VAB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN946TVAB_WRAPPER_ */
