/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN947TVAB/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN947VAB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 8efa3ae61e09ab01
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN947TVAB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN947TVAB_WRAPPER_

#include "MCXN947VAB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN947TVAB_WRAPPER_ */
