/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN527TVKL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN527VKL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 984fa55c7a434066
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN527TVKL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN527TVKL_WRAPPER_

#include "MCXN527VKL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN527TVKL_WRAPPER_ */
