/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN946TVDF/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN946VDF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 579d5b540c35b828
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN946TVDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN946TVDF_WRAPPER_

#include "MCXN946VDF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN946TVDF_WRAPPER_ */
