/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN247TVDF/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN247VDF-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: b165be00b74a8e7f
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN247TVDF_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN247TVDF_WRAPPER_

#include "MCXN247VDF-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN247TVDF_WRAPPER_ */
