/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN235VKL/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN236VKL-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 0fccc76f7ac11fe2
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN235VKL_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN235VKL_WRAPPER_

#include "MCXN236VKL-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN235VKL_WRAPPER_ */
