/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN546VPB/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN547VPB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 55c5293969926beb
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN546VPB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN546VPB_WRAPPER_

#include "MCXN547VPB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN546VPB_WRAPPER_ */
