/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN527TVAB/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN527VAB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 1283433680aee6b3
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN527TVAB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN527TVAB_WRAPPER_

#include "MCXN527VAB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN527TVAB_WRAPPER_ */
