/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN235VPB/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN236VPB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 11fb916db7c0a3eb
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN235VPB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN235VPB_WRAPPER_

#include "MCXN236VPB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN235VPB_WRAPPER_ */
