/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXN246TVAB/signal_configuration.xml
 *
 * 
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXN247VAB-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 6cc1851067415125
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXN246TVAB_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXN246TVAB_WRAPPER_

#include "MCXN247VAB-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXN246TVAB_WRAPPER_ */
