/*--------------------------------------------------------------------------*/
/* Copyright 2021-2025 NXP                                                  */
/*                                                                          */
/* SPDX-License-Identifier: BSD-3-Clause                                    */
/*                                                                          */
/* Redistribution and use in source and binary forms, with or without       */
/* modification, are permitted provided that the following conditions are   */
/* met:                                                                     */
/*                                                                          */
/* 1. Redistributions of source code must retain the above copyright        */
/*    notice, this list of conditions and the following disclaimer.         */
/*                                                                          */
/* 2. Redistributions in binary form must reproduce the above copyright     */
/*    notice, this list of conditions and the following disclaimer in the   */
/*    documentation and/or other materials provided with the distribution.  */
/*                                                                          */
/* 3. Neither the name of the copyright holder nor the names of its         */
/*    contributors may be used to endorse or promote products derived from  */
/*    this software without specific prior written permission.              */
/*                                                                          */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  */
/* IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED    */
/* TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A          */
/* PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT       */
/* HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,   */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR   */
/* PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF   */
/* LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING     */
/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS       */
/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.             */
/*--------------------------------------------------------------------------*/

#include <mcuxCsslAnalysis.h>
#include <mcuxClCore_Platform.h>

#include <mcuxClHashModes_Constants.h> // hash output sizes
#include <internal/mcuxClHash_Internal.h>
#include <internal/mcuxClHashModes_Internal_Memory.h>

#define MCUXCLHASH_INTERNAL_AES_BLOCK_SIZE (16U)

MCUX_CSSL_ANALYSIS_START_PATTERN_OBJ_SIZES()
MCUX_CSSL_ANALYSIS_START_PATTERN_DESCRIPTIVE_IDENTIFIER()

/* Hash Cpu Workarea size generation */
volatile uint8_t mcuxClHash_compute_WaCpuSha1 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_C_SHA1)];
volatile uint8_t mcuxClHash_process_WaCpuSha1 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_C_SHA1)];
volatile uint8_t mcuxClHash_finish_WaCpuSha1 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_C_SHA1)];

volatile uint8_t mcuxClHash_compute_WaCpuSha2_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_224, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_224)];
volatile uint8_t mcuxClHash_process_WaCpuSha2_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_224, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_224)];
volatile uint8_t mcuxClHash_finish_WaCpuSha2_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_224, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_224)];

volatile uint8_t mcuxClHash_compute_WaCpuSha2_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_256, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_256)];
volatile uint8_t mcuxClHash_process_WaCpuSha2_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_256, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_256)];
volatile uint8_t mcuxClHash_finish_WaCpuSha2_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_256, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_256)];

volatile uint8_t mcuxClHash_compute_WaCpuSha2_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_384, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_384)];
volatile uint8_t mcuxClHash_process_WaCpuSha2_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_384, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_384)];
volatile uint8_t mcuxClHash_finish_WaCpuSha2_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_384, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_384)];

volatile uint8_t mcuxClHash_compute_WaCpuSha2_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512)];
volatile uint8_t mcuxClHash_process_WaCpuSha2_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512)];
volatile uint8_t mcuxClHash_finish_WaCpuSha2_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512)];

volatile uint8_t mcuxClHash_compute_WaCpuSha2_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512_224, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512_224)];
volatile uint8_t mcuxClHash_process_WaCpuSha2_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512_224, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512_224)];
volatile uint8_t mcuxClHash_finish_WaCpuSha2_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512_224, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512_224)];

volatile uint8_t mcuxClHash_compute_WaCpuSha2_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512_256, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512_256)];
volatile uint8_t mcuxClHash_process_WaCpuSha2_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512_256, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512_256)];
volatile uint8_t mcuxClHash_finish_WaCpuSha2_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512_256, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512_256)];

volatile uint8_t mcuxClHash_compute_nonblocking_WaCpuSha2_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_224)];
volatile uint8_t mcuxClHash_process_nonblocking_WaCpuSha2_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_224)];
volatile uint8_t mcuxClHash_finish_nonblocking_WaCpuSha2_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_224)];

volatile uint8_t mcuxClHash_compute_nonblocking_WaCpuSha2_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_256)];
volatile uint8_t mcuxClHash_process_nonblocking_WaCpuSha2_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_256)];
volatile uint8_t mcuxClHash_finish_nonblocking_WaCpuSha2_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_256)];

volatile uint8_t mcuxClHash_compute_nonblocking_WaCpuSha2_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_384)];
volatile uint8_t mcuxClHash_process_nonblocking_WaCpuSha2_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_384)];
volatile uint8_t mcuxClHash_finish_nonblocking_WaCpuSha2_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_384)];

volatile uint8_t mcuxClHash_compute_nonblocking_WaCpuSha2_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_512)];
volatile uint8_t mcuxClHash_process_nonblocking_WaCpuSha2_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_512)];
volatile uint8_t mcuxClHash_finish_nonblocking_WaCpuSha2_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_512)];

volatile uint8_t mcuxClHash_compute_nonblocking_WaCpuSha2_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_512_224)];
volatile uint8_t mcuxClHash_process_nonblocking_WaCpuSha2_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_512_224)];
volatile uint8_t mcuxClHash_finish_nonblocking_WaCpuSha2_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_512_224)];

volatile uint8_t mcuxClHash_compute_nonblocking_WaCpuSha2_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_512_256)];
volatile uint8_t mcuxClHash_process_nonblocking_WaCpuSha2_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_512_256)];
volatile uint8_t mcuxClHash_finish_nonblocking_WaCpuSha2_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_NONBLOCKING_SHA_512_256)];

volatile uint8_t mcuxClHash_compute_WaCpuSha3 [MCUXCLHASH_INTERNAL_WACPU_SIZE_SHA3_ONESHOT];
volatile uint8_t mcuxClHash_process_WaCpuSha3 [MCUXCLHASH_INTERNAL_WACPU_SIZE_SHA3_PROCESS];
volatile uint8_t mcuxClHash_finish_WaCpuSha3 [MCUXCLHASH_INTERNAL_WACPU_SIZE_SHA3_FINISH];

volatile uint8_t mcuxClHash_compute_WaCpuSecSha1 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA1)];
volatile uint8_t mcuxClHash_process_WaCpuSecSha1 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SECSHA1)];
volatile uint8_t mcuxClHash_finish_WaCpuSecSha1 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SECSHA1)];

volatile uint8_t mcuxClHash_compute_WaCpuSecSha2_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_224)];
volatile uint8_t mcuxClHash_process_WaCpuSecSha2_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_224)];
volatile uint8_t mcuxClHash_finish_WaCpuSecSha2_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_224)];

volatile uint8_t mcuxClHash_compute_WaCpuSecSha2_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_256)];
volatile uint8_t mcuxClHash_process_WaCpuSecSha2_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_256)];
volatile uint8_t mcuxClHash_finish_WaCpuSecSha2_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_256)];

volatile uint8_t mcuxClHash_compute_WaCpuSecSha2_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_384)];
volatile uint8_t mcuxClHash_process_WaCpuSecSha2_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_384)];
volatile uint8_t mcuxClHash_finish_WaCpuSecSha2_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_384)];

volatile uint8_t mcuxClHash_compute_WaCpuSecSha2_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512)];
volatile uint8_t mcuxClHash_process_WaCpuSecSha2_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512)];
volatile uint8_t mcuxClHash_finish_WaCpuSecSha2_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512)];

volatile uint8_t mcuxClHash_compute_WaCpuSecSha2_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512_224)];
volatile uint8_t mcuxClHash_process_WaCpuSecSha2_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512_224)];
volatile uint8_t mcuxClHash_finish_WaCpuSecSha2_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512_224)];

volatile uint8_t mcuxClHash_compute_WaCpuSecSha2_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_ONESHOT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512_256)];
volatile uint8_t mcuxClHash_process_WaCpuSecSha2_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_PROCESS(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512_256)];
volatile uint8_t mcuxClHash_finish_WaCpuSecSha2_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_FINISH(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512_256)];


volatile uint8_t mcuxClHash_compute_WaCpuSecSha3 [MCUXCLHASH_INTERNAL_WACPU_SIZE_SECSHA3SHAKE_ONESHOT];
volatile uint8_t mcuxClHash_process_WaCpuSecSha3 [MCUXCLHASH_INTERNAL_WACPU_SIZE_SECSHA3SHAKE_PROCESS];
volatile uint8_t mcuxClHash_finish_WaCpuSecSha3 [MCUXCLHASH_INTERNAL_WACPU_SIZE_SECSHA3SHAKE_FINISH];

/* Hash multipart context size generation */
volatile uint8_t mcuxClHash_Ctx_size_sha_1 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_C_SHA1)];

volatile uint8_t mcuxClHash_Ctx_size_sha_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_224, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_224)];
volatile uint8_t mcuxClHash_Ctx_size_sha_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_256, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_256)];
volatile uint8_t mcuxClHash_Ctx_size_sha_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_384, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_384)];
volatile uint8_t mcuxClHash_Ctx_size_sha_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512)];
volatile uint8_t mcuxClHash_Ctx_size_sha_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512_224, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512_224)];
volatile uint8_t mcuxClHash_Ctx_size_sha_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SGI_SHA_512_256, MCUXCLHASHMODES_DESCRIPTOR_C_SHA_512_256)];

volatile uint8_t mcuxClHash_Ctx_size_sha3_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_C_SHA3_224)];
volatile uint8_t mcuxClHash_Ctx_size_sha3_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_C_SHA3_256)];
volatile uint8_t mcuxClHash_Ctx_size_sha3_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_C_SHA3_384)];
volatile uint8_t mcuxClHash_Ctx_size_sha3_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_C_SHA3_512)];
volatile uint8_t mcuxClHash_Ctx_size_sha3_shake_128 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_C_SHA3_SHAKE_128)];
volatile uint8_t mcuxClHash_Ctx_size_sha3_shake_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_C_SHA3_SHAKE_256)];

volatile uint8_t mcuxClHash_Ctx_size_secsha_1 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA1)];

volatile uint8_t mcuxClHash_Ctx_size_secsha_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_224)];
volatile uint8_t mcuxClHash_Ctx_size_secsha_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_256)];
volatile uint8_t mcuxClHash_Ctx_size_secsha_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_384)];
volatile uint8_t mcuxClHash_Ctx_size_secsha_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512)];
volatile uint8_t mcuxClHash_Ctx_size_secsha_512_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512_224)];
volatile uint8_t mcuxClHash_Ctx_size_secsha_512_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA_512_256)];

volatile uint8_t mcuxClHash_Ctx_size_secsha3_224 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA3_224)];
volatile uint8_t mcuxClHash_Ctx_size_secsha3_256 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA3_256)];
volatile uint8_t mcuxClHash_Ctx_size_secsha3_384 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA3_384)];
volatile uint8_t mcuxClHash_Ctx_size_secsha3_512 [MCUXCLHASHMODES_COMPUTE_MEMORY_CONTEXT(MCUXCLHASHMODES_DESCRIPTOR_SECSHA3_512)];

/* Hash multipart state export size generation */
volatile uint8_t mcuxClHash_export_import_size_sha_1 [MCUXCLHASH_STATE_SIZE_SHA_1 + MCUXCLHASH_COUNTER_SIZE_SHA_1];
volatile uint8_t mcuxClHash_export_import_size_sha_256 [MCUXCLHASH_STATE_SIZE_SHA_256 + MCUXCLHASH_COUNTER_SIZE_SHA_256];
volatile uint8_t mcuxClHash_export_import_size_sha_512 [MCUXCLHASH_STATE_SIZE_SHA_512 + MCUXCLHASH_COUNTER_SIZE_SHA_512];
volatile uint8_t mcuxClHash_export_import_size_sha3 [MCUXCLHASH_STATE_SIZE_SHA3 + MCUXCLHASH_COUNTER_SIZE_SHA3];
volatile uint8_t mcuxClHash_export_import_size_secsha_1 [MCUXCLHASH_STATE_SIZE_SECSHA_1 + MCUXCLHASH_COUNTER_SIZE_SHA_1];
volatile uint8_t mcuxClHash_export_import_size_secsha_256 [MCUXCLHASH_STATE_SIZE_SECSHA_256 + MCUXCLHASH_COUNTER_SIZE_SHA_256];
volatile uint8_t mcuxClHash_export_import_size_secsha_512 [MCUXCLHASH_STATE_SIZE_SECSHA_512 + MCUXCLHASH_COUNTER_SIZE_SHA_512];
volatile uint8_t mcuxClHash_export_import_size_secsha3 [MCUXCLHASH_STATE_SIZE_SECSHA3 + MCUXCLHASH_COUNTER_SIZE_SHA3];


#if defined(MCUXCL_FEATURE_HASH_C_SHA3_SHAKE)
/* Algorithm descriptor sizes */
volatile uint8_t mcuxClHash_AlgorithmDescriptor_size [sizeof(mcuxClHash_AlgorithmDescriptor_t)];
#endif /* defined(MCUXCL_FEATURE_HASH_C_SHA3_SHAKE) */

MCUX_CSSL_ANALYSIS_STOP_PATTERN_DESCRIPTIVE_IDENTIFIER()
MCUX_CSSL_ANALYSIS_STOP_PATTERN_OBJ_SIZES()
