/*
 * Copyright 2026 NXP
 * SPDX-License-Identifier: Apache-2.0
 *
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXW70ADMFT/signal_configuration.xml
 *
 *
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXW70AAMFT-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: abb9ad706945fc38
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXW70ADMFT_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXW70ADMFT_WRAPPER_

#include "MCXW70AAMFT-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXW70ADMFT_WRAPPER_ */
