/*
 * Copyright 2024 NXP
 * SPDX-License-Identifier: Apache-2.0
 *
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXW716CMFPA/signal_configuration.xml
 *
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXW727CMFTA-pinctrl.h with this part's differences applied
 * below (66 removed, 2 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: e4e3f244538c7f47
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXW716CMFPA_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXW716CMFPA_WRAPPER_

#include "MCXW727CMFTA-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_A12_PTA16
#undef ADC0_A6_PTD2
#undef ADC0_A8_PTC6
#undef ADC0_B5_PTD1
#undef ADC0_B6_PTD3
#undef CAN0_RX_PTC1
#undef CAN0_TX_PTC0
#undef CAN1_RX_PTB0
#undef CAN1_RX_PTC2
#undef CAN1_RX_PTC6
#undef CAN1_TX_PTB1
#undef CAN1_TX_PTC3
#undef CAN1_TX_PTC7
#undef EWM0_OUT_b_PTA16
#undef FLEXIO0_D16_PTC0
#undef FLEXIO0_D17_PTC1
#undef FLEXIO0_D22_PTC6
#undef FLEXIO0_D5_PTA16
#undef I3C0_SCL_PTC1
#undef I3C0_SDA_PTC0
#undef LPI2C0_SCLS_PTA16
#undef LPI2C1_SCL_PTC0
#undef LPI2C1_SDA_PTC1
#undef LPSPI0_PCS0_PTA16
#undef LPSPI1_PCS1_PTC6
#undef LPSPI1_PCS2_PTC0
#undef LPSPI1_PCS3_PTC1
#undef LPTMR0_ALT3_PTD2
#undef LPTMR1_ALT3_PTD3
#undef LPUART0_CTS_b_PTA21
#undef LPUART0_RTS_b_PTA20
#undef LPUART0_RX_PTA16
#undef NMI_b_PTD1
#undef PTA16
#undef PTC0
#undef PTC1
#undef PTC6
#undef PTD1
#undef PTD2
#undef PTD3
#undef RF_GPO_4_PTD1
#undef RF_GPO_5_PTD2
#undef RF_GPO_6_PTD3
#undef RF_GPO_7_PTD1
#undef RF_GPO_8_PTA16
#undef RF_NOT_ALLOWED_PTA16
#undef RF_UART_CTS_b_PTC0
#undef RF_UART_CTS_b_PTD3
#undef RF_UART_RTS_b_PTC1
#undef RF_UART_RTS_b_PTD4
#undef SPC0_LPREQ_PTD1
#undef TAMPER0_PTD2
#undef TAMPER1_PTD3
#undef TPM0_CH4_PTA16
#undef TPM1_CH0_PTC0
#undef TPM1_CH1_PTC1
#undef TPM1_CH5_PTC6
#undef TPM2_CH0_PTD2
#undef TPM2_CH1_PTD3
#undef TRGMUX0_IN2_PTD3
#undef WUU0_P11_PTC6
#undef WUU0_P19_PTA16
#undef WUU0_P20_PTA18
#undef WUU0_P22_PTC5
#undef WUU0_P7_PTC0
#undef WUU0_P8_PTC1

/* Signals with different mux data on this part */
#undef KINETIS_MUX
#define KINETIS_MUX(port, pin, mux)		 (((((port) - 'A') & 0xF) << 28) |	 (((pin) & 0x3F) << 22) |		 (((mux) & 0x7) << 8))
#undef NMI_b_PTC7
#define NMI_b_PTC7 KINETIS_MUX('C',7,1)

#endif /* _ZEPHYR_DTS_BINDING_MCXW716CMFPA_WRAPPER_ */
