/*
 * Copyright 2026 NXP
 * SPDX-License-Identifier: Apache-2.0
 *
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXW70AAMFT/signal_configuration.xml
 *
 *
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXW70ACMFT-pinctrl.h with this part's differences applied
 * below (18 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 5934acf11f82d8d0
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXW70AAMFT_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXW70AAMFT_WRAPPER_

#include "MCXW70ACMFT-pinctrl.h"

/* Signals not present on this part */
#undef CAN0_RX_PTC1
#undef CAN0_RX_PTC5
#undef CAN0_TX_PTC0
#undef CAN0_TX_PTC4
#undef HDI_PTB0
#undef HDI_PTB1
#undef HDI_PTB2
#undef HDI_PTB3
#undef HDI_PTB4
#undef HDI_PTB5
#undef HDI_PTC0
#undef HDI_PTC1
#undef HDI_PTC2
#undef HDI_PTC3
#undef HDI_PTC4
#undef HDI_PTC5
#undef HDI_PTC6
#undef HDI_PTC7

#endif /* _ZEPHYR_DTS_BINDING_MCXW70AAMFT_WRAPPER_ */
