/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK80FN256VLQ15/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK82FN256VLQ15-pinctrl.h with this part's differences applied
 * below (0 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 77e791e77656b82e
 */

#ifndef _ZEPHYR_DTS_BINDING_MK80FN256VLQ15_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK80FN256VLQ15_WRAPPER_

#include "MK82FN256VLQ15-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK80FN256VLQ15_WRAPPER_ */
