/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXC243VFT/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXC244VFT-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: d45d01da16808415
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXC243VFT_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXC243VFT_WRAPPER_

#include "MCXC244VFT-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXC243VFT_WRAPPER_ */
