/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXC041VFG/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXC041VFK-pinctrl.h with this part's differences applied
 * below (31 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: a3a2435f0d232515
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXC041VFG_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXC041VFG_WRAPPER_

#include "MCXC041VFK-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE0_PTA12
#undef ADC0_SE2_PTA9
#undef ADC0_SE3_PTA8
#undef CLKOUT32K_PTB13
#undef CLKOUT_PTA12
#undef CMP0_IN0_PTA12
#undef I2C0_SCL_PTA8
#undef I2C0_SDA_PTA9
#undef LPTMR0_ALT2_PTA12
#undef LPTMR0_ALT3_PTB6
#undef PTA12
#undef PTA8
#undef PTA9
#undef PTB10
#undef PTB11
#undef PTB13
#undef PTB6
#undef PTB7
#undef RTC_CLKOUT_PTB13
#undef SPI0_MISO_PTB11
#undef SPI0_MOSI_PTA8
#undef SPI0_SCK_PTA9
#undef SPI0_SS_b_PTB10
#undef TPM0_CH0_PTB11
#undef TPM0_CH1_PTB10
#undef TPM1_CH0_PTA12
#undef TPM1_CH0_PTB7
#undef TPM1_CH1_PTB13
#undef TPM1_CH1_PTB6
#undef TPM_CLKIN0_PTA12
#undef TPM_CLKIN1_PTB6

#endif /* _ZEPHYR_DTS_BINDING_MCXC041VFG_WRAPPER_ */
