/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXC144VFM/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MCXC244VFM-pinctrl.h with this part's differences applied
 * below (1 removed, 0 changed,
 * 34 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 5d6c3ebd99fe3616
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXC144VFM_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXC144VFM_WRAPPER_

#include "MCXC244VFM-pinctrl.h"

/* Signals not present on this part */
#undef USB_SOF_OUT_PTC7

/* Signals specific to this part */
#define ADC0_DM1_PTE17 KINETIS_MUX('E',17,0)
#define ADC0_DM2_PTE19 KINETIS_MUX('E',19,0)
#define ADC0_DP1_PTE16 KINETIS_MUX('E',16,0)
#define ADC0_DP2_PTE18 KINETIS_MUX('E',18,0)
#define ADC0_SE1_PTE16 KINETIS_MUX('E',16,0)
#define ADC0_SE2_PTE18 KINETIS_MUX('E',18,0)
#define ADC0_SE5a_PTE17 KINETIS_MUX('E',17,0)
#define ADC0_SE6a_PTE19 KINETIS_MUX('E',19,0)
#define FXIO0_D0_PTE16 KINETIS_MUX('E',16,6)
#define FXIO0_D1_PTE17 KINETIS_MUX('E',17,6)
#define FXIO0_D2_PTE18 KINETIS_MUX('E',18,6)
#define FXIO0_D3_PTE19 KINETIS_MUX('E',19,6)
#define I2C0_SCL_PTE19 KINETIS_MUX('E',19,4)
#define I2C0_SDA_PTE18 KINETIS_MUX('E',18,4)
#define I2C1_SCL_PTE1 KINETIS_MUX('E',1,6)
#define LPTMR0_ALT3_PTE17 KINETIS_MUX('E',17,5)
#define LPUART1_RX_PTE1 KINETIS_MUX('E',1,3)
#define PTE1 KINETIS_MUX('E',1,1)
#define PTE16 KINETIS_MUX('E',16,1)
#define PTE17 KINETIS_MUX('E',17,1)
#define PTE18 KINETIS_MUX('E',18,1)
#define PTE19 KINETIS_MUX('E',19,1)
#define SPI0_MISO_PTE18 KINETIS_MUX('E',18,5)
#define SPI0_MISO_PTE19 KINETIS_MUX('E',19,2)
#define SPI0_MOSI_PTE18 KINETIS_MUX('E',18,2)
#define SPI0_MOSI_PTE19 KINETIS_MUX('E',19,5)
#define SPI0_SCK_PTE17 KINETIS_MUX('E',17,2)
#define SPI0_SS_PTE16 KINETIS_MUX('E',16,2)
#define SPI1_MISO_PTE1 KINETIS_MUX('E',1,5)
#define SPI1_MOSI_PTE1 KINETIS_MUX('E',1,2)
#define TPM_CLKIN0_PTE16 KINETIS_MUX('E',16,4)
#define TPM_CLKIN1_PTE17 KINETIS_MUX('E',17,4)
#define UART2_RX_PTE17 KINETIS_MUX('E',17,3)
#define UART2_TX_PTE16 KINETIS_MUX('E',16,3)

#endif /* _ZEPHYR_DTS_BINDING_MCXC144VFM_WRAPPER_ */
