/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MCXC143VFM/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MCXC144VFM-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 05ecc5f57df17e67
 */

#ifndef _ZEPHYR_DTS_BINDING_MCXC143VFM_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MCXC143VFM_WRAPPER_

#include "MCXC144VFM-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MCXC143VFM_WRAPPER_ */
