/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for K32L2B21VFM0A/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _ZEPHYR_DTS_BINDING_K32L2B21VFM0A_
#define _ZEPHYR_DTS_BINDING_K32L2B21VFM0A_

#define KINETIS_MUX(port, pin, mux)		\
	(((((port) - 'A') & 0xF) << 28) |	\
	(((pin) & 0x3F) << 22) |		\
	(((mux) & 0x7) << 8))

#define PTA0 KINETIS_MUX('A',0,1) /* PTA_0 */
#define TPM0_CH5_PTA0 KINETIS_MUX('A',0,3) /* PTA_0 */
#define SWD_CLK_PTA0 KINETIS_MUX('A',0,7) /* PTA_0 */
#define PTA1 KINETIS_MUX('A',1,1) /* PTA_1 */
#define LPUART0_RX_PTA1 KINETIS_MUX('A',1,2) /* PTA_1 */
#define TPM2_CH0_PTA1 KINETIS_MUX('A',1,3) /* PTA_1 */
#define PTA2 KINETIS_MUX('A',2,1) /* PTA_2 */
#define LPUART0_TX_PTA2 KINETIS_MUX('A',2,2) /* PTA_2 */
#define TPM2_CH1_PTA2 KINETIS_MUX('A',2,3) /* PTA_2 */
#define PTA3 KINETIS_MUX('A',3,1) /* PTA_3 */
#define I2C1_SCL_PTA3 KINETIS_MUX('A',3,2) /* PTA_3 */
#define TPM0_CH0_PTA3 KINETIS_MUX('A',3,3) /* PTA_3 */
#define SWD_DIO_PTA3 KINETIS_MUX('A',3,7) /* PTA_3 */
#define PTA4 KINETIS_MUX('A',4,1) /* PTA_4 */
#define I2C1_SDA_PTA4 KINETIS_MUX('A',4,2) /* PTA_4 */
#define TPM0_CH1_PTA4 KINETIS_MUX('A',4,3) /* PTA_4 */
#define NMI_b_PTA4 KINETIS_MUX('A',4,7) /* PTA_4 */
#define EXTAL0_PTA18 KINETIS_MUX('A',18,0) /* PTA_18 */
#define PTA18 KINETIS_MUX('A',18,1) /* PTA_18 */
#define LPUART1_RX_PTA18 KINETIS_MUX('A',18,3) /* PTA_18 */
#define TPM_CLKIN0_PTA18 KINETIS_MUX('A',18,4) /* PTA_18 */
#define XTAL0_PTA19 KINETIS_MUX('A',19,0) /* PTA_19 */
#define PTA19 KINETIS_MUX('A',19,1) /* PTA_19 */
#define LPUART1_TX_PTA19 KINETIS_MUX('A',19,3) /* PTA_19 */
#define TPM_CLKIN1_PTA19 KINETIS_MUX('A',19,4) /* PTA_19 */
#define LPTMR0_ALT1_PTA19 KINETIS_MUX('A',19,6) /* PTA_19 */
#define PTA20 KINETIS_MUX('A',20,1) /* PTA_20 */
#define RESET_b_PTA20 KINETIS_MUX('A',20,7) /* PTA_20 */
#define ADC0_SE8_PTB0 KINETIS_MUX('B',0,0) /* PTB_0 */
#define LLWU_P5_PTB0 KINETIS_MUX('B',0,1) /* PTB_0 */
#define PTB0 KINETIS_MUX('B',0,1) /* PTB_0 */
#define I2C0_SCL_PTB0 KINETIS_MUX('B',0,2) /* PTB_0 */
#define TPM1_CH0_PTB0 KINETIS_MUX('B',0,3) /* PTB_0 */
#define ADC0_SE9_PTB1 KINETIS_MUX('B',1,0) /* PTB_1 */
#define PTB1 KINETIS_MUX('B',1,1) /* PTB_1 */
#define I2C0_SDA_PTB1 KINETIS_MUX('B',1,2) /* PTB_1 */
#define TPM1_CH1_PTB1 KINETIS_MUX('B',1,3) /* PTB_1 */
#define ADC0_SE15_PTC1 KINETIS_MUX('C',1,0) /* PTC_1 */
#define RTC_CLKIN_PTC1 KINETIS_MUX('C',1,1) /* PTC_1 */
#define PTC1 KINETIS_MUX('C',1,1) /* PTC_1 */
#define LLWU_P6_PTC1 KINETIS_MUX('C',1,1) /* PTC_1 */
#define I2C1_SCL_PTC1 KINETIS_MUX('C',1,2) /* PTC_1 */
#define TPM0_CH0_PTC1 KINETIS_MUX('C',1,4) /* PTC_1 */
#define ADC0_SE11_PTC2 KINETIS_MUX('C',2,0) /* PTC_2 */
#define PTC2 KINETIS_MUX('C',2,1) /* PTC_2 */
#define I2C1_SDA_PTC2 KINETIS_MUX('C',2,2) /* PTC_2 */
#define TPM0_CH1_PTC2 KINETIS_MUX('C',2,4) /* PTC_2 */
#define LLWU_P7_PTC3 KINETIS_MUX('C',3,1) /* PTC_3 */
#define PTC3 KINETIS_MUX('C',3,1) /* PTC_3 */
#define SPI1_SCK_PTC3 KINETIS_MUX('C',3,2) /* PTC_3 */
#define LPUART1_RX_PTC3 KINETIS_MUX('C',3,3) /* PTC_3 */
#define TPM0_CH2_PTC3 KINETIS_MUX('C',3,4) /* PTC_3 */
#define CLKOUT_PTC3 KINETIS_MUX('C',3,5) /* PTC_3 */
#define LLWU_P8_PTC4 KINETIS_MUX('C',4,1) /* PTC_4 */
#define PTC4 KINETIS_MUX('C',4,1) /* PTC_4 */
#define SPI0_SS_PTC4 KINETIS_MUX('C',4,2) /* PTC_4 */
#define LPUART1_TX_PTC4 KINETIS_MUX('C',4,3) /* PTC_4 */
#define TPM0_CH3_PTC4 KINETIS_MUX('C',4,4) /* PTC_4 */
#define LLWU_P9_PTC5 KINETIS_MUX('C',5,1) /* PTC_5 */
#define PTC5 KINETIS_MUX('C',5,1) /* PTC_5 */
#define SPI0_SCK_PTC5 KINETIS_MUX('C',5,2) /* PTC_5 */
#define LPTMR0_ALT2_PTC5 KINETIS_MUX('C',5,3) /* PTC_5 */
#define CMP0_OUT_PTC5 KINETIS_MUX('C',5,6) /* PTC_5 */
#define CMP0_IN0_PTC6 KINETIS_MUX('C',6,0) /* PTC_6 */
#define PTC6 KINETIS_MUX('C',6,1) /* PTC_6 */
#define LLWU_P10_PTC6 KINETIS_MUX('C',6,1) /* PTC_6 */
#define SPI0_MOSI_PTC6 KINETIS_MUX('C',6,2) /* PTC_6 */
#define EXTRG_IN_PTC6 KINETIS_MUX('C',6,3) /* PTC_6 */
#define SPI0_MISO_PTC6 KINETIS_MUX('C',6,5) /* PTC_6 */
#define CMP0_IN1_PTC7 KINETIS_MUX('C',7,0) /* PTC_7 */
#define PTC7 KINETIS_MUX('C',7,1) /* PTC_7 */
#define SPI0_MISO_PTC7 KINETIS_MUX('C',7,2) /* PTC_7 */
#define USB_SOF_OUT_PTC7 KINETIS_MUX('C',7,3) /* PTC_7 */
#define SPI0_MOSI_PTC7 KINETIS_MUX('C',7,5) /* PTC_7 */
#define PTD4 KINETIS_MUX('D',4,1) /* PTD_4 */
#define LLWU_P14_PTD4 KINETIS_MUX('D',4,1) /* PTD_4 */
#define SPI1_SS_PTD4 KINETIS_MUX('D',4,2) /* PTD_4 */
#define UART2_RX_PTD4 KINETIS_MUX('D',4,3) /* PTD_4 */
#define TPM0_CH4_PTD4 KINETIS_MUX('D',4,4) /* PTD_4 */
#define FXIO0_D4_PTD4 KINETIS_MUX('D',4,6) /* PTD_4 */
#define ADC0_SE6b_PTD5 KINETIS_MUX('D',5,0) /* PTD_5 */
#define PTD5 KINETIS_MUX('D',5,1) /* PTD_5 */
#define SPI1_SCK_PTD5 KINETIS_MUX('D',5,2) /* PTD_5 */
#define UART2_TX_PTD5 KINETIS_MUX('D',5,3) /* PTD_5 */
#define TPM0_CH5_PTD5 KINETIS_MUX('D',5,4) /* PTD_5 */
#define FXIO0_D5_PTD5 KINETIS_MUX('D',5,6) /* PTD_5 */
#define ADC0_SE7b_PTD6 KINETIS_MUX('D',6,0) /* PTD_6 */
#define LLWU_P15_PTD6 KINETIS_MUX('D',6,1) /* PTD_6 */
#define PTD6 KINETIS_MUX('D',6,1) /* PTD_6 */
#define SPI1_MOSI_PTD6 KINETIS_MUX('D',6,2) /* PTD_6 */
#define LPUART0_RX_PTD6 KINETIS_MUX('D',6,3) /* PTD_6 */
#define SPI1_MISO_PTD6 KINETIS_MUX('D',6,5) /* PTD_6 */
#define FXIO0_D6_PTD6 KINETIS_MUX('D',6,6) /* PTD_6 */
#define PTD7 KINETIS_MUX('D',7,1) /* PTD_7 */
#define SPI1_MISO_PTD7 KINETIS_MUX('D',7,2) /* PTD_7 */
#define LPUART0_TX_PTD7 KINETIS_MUX('D',7,3) /* PTD_7 */
#define SPI1_MOSI_PTD7 KINETIS_MUX('D',7,5) /* PTD_7 */
#define FXIO0_D7_PTD7 KINETIS_MUX('D',7,6) /* PTD_7 */
#define CLKOUT32K_PTE0 KINETIS_MUX('E',0,1) /* PTE_0 */
#define PTE0 KINETIS_MUX('E',0,1) /* PTE_0 */
#define SPI1_MISO_PTE0 KINETIS_MUX('E',0,2) /* PTE_0 */
#define LPUART1_TX_PTE0 KINETIS_MUX('E',0,3) /* PTE_0 */
#define RTC_CLKOUT_PTE0 KINETIS_MUX('E',0,4) /* PTE_0 */
#define CMP0_OUT_PTE0 KINETIS_MUX('E',0,5) /* PTE_0 */
#define I2C1_SDA_PTE0 KINETIS_MUX('E',0,6) /* PTE_0 */
#define CMP0_IN4_PTE30 KINETIS_MUX('E',30,0) /* PTE_30 */
#define DAC0_OUT_PTE30 KINETIS_MUX('E',30,0) /* PTE_30 */
#define ADC0_SE23_PTE30 KINETIS_MUX('E',30,0) /* PTE_30 */
#define PTE30 KINETIS_MUX('E',30,1) /* PTE_30 */
#define TPM0_CH3_PTE30 KINETIS_MUX('E',30,3) /* PTE_30 */
#define TPM_CLKIN1_PTE30 KINETIS_MUX('E',30,4) /* PTE_30 */
#define LPUART1_TX_PTE30 KINETIS_MUX('E',30,5) /* PTE_30 */
#define LPTMR0_ALT1_PTE30 KINETIS_MUX('E',30,6) /* PTE_30 */
#endif
