/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for K32L2A41VLH1A/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on K32L2A41VLL1A-pinctrl.h with this part's differences applied
 * below (121 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 66a08a8ec9279aa8
 */

#ifndef _ZEPHYR_DTS_BINDING_K32L2A41VLH1A_WRAPPER_
#define _ZEPHYR_DTS_BINDING_K32L2A41VLH1A_WRAPPER_

#include "K32L2A41VLL1A-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_DM1_PTE17
#undef ADC0_DM2_PTE19
#undef ADC0_DP1_PTE16
#undef ADC0_DP2_PTE18
#undef ADC0_SE18_PTE2
#undef ADC0_SE19_PTE3
#undef ADC0_SE1_PTE16
#undef ADC0_SE22_PTA17
#undef ADC0_SE2_PTE18
#undef ADC0_SE5a_PTE17
#undef ADC0_SE6a_PTE19
#undef CMP0_OUT_PTB20
#undef CMP1_OUT_PTB21
#undef EMVSIM0_CLK_PTC14
#undef EMVSIM0_IO_PTC17
#undef EMVSIM0_PD_PTC18
#undef EMVSIM0_RST_PTC15
#undef EMVSIM0_VCCEN_PTC16
#undef FXIO0_D0_PTE16
#undef FXIO0_D12_PTB8
#undef FXIO0_D13_PTB9
#undef FXIO0_D14_PTB10
#undef FXIO0_D15_PTB11
#undef FXIO0_D1_PTE17
#undef FXIO0_D2_PTE18
#undef FXIO0_D3_PTE19
#undef LLWU_P16_PTE6
#undef LLWU_P19_PTE17
#undef LLWU_P1_PTE2
#undef LLWU_P20_PTE18
#undef LLWU_P2_PTE4
#undef LPI2C0_SCLS_PTE26
#undef LPI2C0_SCL_PTE19
#undef LPI2C0_SDA_PTE18
#undef LPI2C1_SCLS_PTC12
#undef LPI2C1_SCLS_PTE3
#undef LPI2C1_SDAS_PTC13
#undef LPI2C1_SDAS_PTE2
#undef LPI2C2_SCL_PTA14
#undef LPI2C2_SDAS_PTA7
#undef LPSPI0_PCS0_PTA14
#undef LPSPI0_PCS0_PTE16
#undef LPSPI0_PCS2_PTC18
#undef LPSPI0_PCS3_PTA7
#undef LPSPI0_PCS3_PTC17
#undef LPSPI0_SCK_PTA15
#undef LPSPI0_SCK_PTE17
#undef LPSPI0_SIN_PTA17
#undef LPSPI0_SIN_PTE19
#undef LPSPI0_SOUT_PTA16
#undef LPSPI0_SOUT_PTE18
#undef LPSPI1_PCS0_PTB10
#undef LPSPI1_PCS0_PTB8
#undef LPSPI1_PCS0_PTE4
#undef LPSPI1_PCS1_PTB7
#undef LPSPI1_PCS1_PTE5
#undef LPSPI1_PCS2_PTE6
#undef LPSPI1_PCS3_PTE16
#undef LPSPI1_SCK_PTB11
#undef LPSPI1_SCK_PTB9
#undef LPSPI1_SCK_PTE2
#undef LPSPI1_SIN_PTE3
#undef LPSPI2_PCS0_PTB20
#undef LPSPI2_SCK_PTB21
#undef LPSPI2_SIN_PTB23
#undef LPSPI2_SOUT_PTB22
#undef LPTMR0_ALT3_PTE17
#undef LPTMR1_ALT3_PTE17
#undef LPUART0_CTS_b_PTA16
#undef LPUART0_RTS_b_PTA17
#undef LPUART0_RX_PTA15
#undef LPUART0_TX_PTA14
#undef LPUART1_CTS_b_PTE2
#undef LPUART1_RTS_b_PTE3
#undef LPUART2_CTS_b_PTE18
#undef LPUART2_RTS_b_PTE19
#undef LPUART2_RX_PTE17
#undef LPUART2_TX_PTE16
#undef PTA14
#undef PTA15
#undef PTA16
#undef PTA17
#undef PTA6
#undef PTA7
#undef PTB10
#undef PTB11
#undef PTB20
#undef PTB21
#undef PTB22
#undef PTB23
#undef PTB7
#undef PTB8
#undef PTB9
#undef PTC12
#undef PTC13
#undef PTC14
#undef PTC15
#undef PTC16
#undef PTC17
#undef PTC18
#undef PTE16
#undef PTE17
#undef PTE18
#undef PTE19
#undef PTE2
#undef PTE26
#undef PTE3
#undef PTE4
#undef PTE5
#undef PTE6
#undef RTC_CLKOUT_PTE26
#undef TPM0_CH3_PTA6
#undef TPM0_CH4_PTA7
#undef TPM0_CH5_PTE26
#undef TPM0_CLKIN_PTC12
#undef TPM0_CLKIN_PTE16
#undef TPM1_CLKIN_PTC13
#undef TPM1_CLKIN_PTE17
#undef TPM2_CLKIN_PTB11
#undef USB_CLKIN_PTE26
#undef USB_SOF_OUT_PTE6

#endif /* _ZEPHYR_DTS_BINDING_K32L2A41VLH1A_WRAPPER_ */
