/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for K32L2A31VLL1A/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to K32L2A41VLL1A-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 66a08a8ec9279aa8
 */

#ifndef _ZEPHYR_DTS_BINDING_K32L2A31VLL1A_WRAPPER_
#define _ZEPHYR_DTS_BINDING_K32L2A31VLL1A_WRAPPER_

#include "K32L2A41VLL1A-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_K32L2A31VLL1A_WRAPPER_ */
