/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK02FN128VLH10/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKV31F512VLH12-pinctrl.h with this part's differences applied
 * below (71 removed, 0 changed,
 * 10 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 71eb1e070a33e712
 */

#ifndef _ZEPHYR_DTS_BINDING_MK02FN128VLH10_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK02FN128VLH10_WRAPPER_

#include "MKV31F512VLH12-pinctrl.h"

/* Signals not present on this part */
#undef ADC1_SE4a_PTE0
#undef ADC1_SE4b_PTC8
#undef ADC1_SE5a_PTE1
#undef ADC1_SE5b_PTC9
#undef ADC1_SE6b_PTC10
#undef ADC1_SE7b_PTC11
#undef ADC1_SE8_PTB0
#undef ADC1_SE9_PTB1
#undef CMP0_OUT_PTA1
#undef CMP1_OUT_PTA2
#undef EWM_IN_PTA0
#undef EWM_IN_PTB1
#undef EWM_OUT_b_PTA3
#undef FTM0_CH0_PTE24
#undef FTM0_CH1_PTE25
#undef FTM0_CH6_PTA1
#undef FTM0_CH6_PTD6
#undef FTM0_CH7_PTA2
#undef FTM0_CH7_PTD7
#undef FTM0_FLT0_PTA19
#undef FTM0_FLT1_PTB2
#undef FTM0_FLT1_PTC0
#undef FTM0_FLT2_PTB1
#undef FTM0_FLT3_PTA4
#undef FTM1_CH0_PTA2
#undef FTM1_CH1_PTA1
#undef FTM2_FLT0_PTA3
#undef FTM2_QD_PHA_PTA1
#undef FTM2_QD_PHB_PTA2
#undef FTM3_CH0_PTD0
#undef FTM3_CH1_PTD1
#undef FTM3_CH2_PTD2
#undef FTM3_CH3_PTD3
#undef FTM3_CH4_PTC8
#undef FTM3_CH5_PTC9
#undef FTM3_CH6_PTC10
#undef FTM3_CH7_PTC11
#undef I2C0_SCL_PTC6
#undef I2C0_SDA_PTC7
#undef I2C1_SCL_PTC10
#undef I2C1_SCL_PTE1
#undef I2C1_SDA_PTC11
#undef I2C1_SDA_PTE0
#undef LPUART0_CTS_b_PTC2
#undef LPUART0_CTS_b_PTD1
#undef LPUART0_RTS_b_PTC1
#undef LPUART0_RTS_b_PTD0
#undef LPUART0_RX_PTC3
#undef LPUART0_RX_PTD2
#undef LPUART0_TX_PTC4
#undef LPUART0_TX_PTD3
#undef SPI0_PCS0_PTC0
#undef SPI1_PCS0_PTD4
#undef SPI1_PCS1_PTE0
#undef SPI1_SCK_PTD5
#undef SPI1_SIN_PTB17
#undef SPI1_SIN_PTD7
#undef SPI1_SIN_PTE1
#undef SPI1_SOUT_PTB16
#undef SPI1_SOUT_PTD6
#undef SPI1_SOUT_PTE1
#undef UART0_RX_PTB0
#undef UART0_TX_PTB1
#undef UART2_CTS_b_PTD1
#undef UART2_CTS_b_PTE18
#undef UART2_RTS_b_PTD0
#undef UART2_RTS_b_PTE19
#undef UART2_RX_PTD2
#undef UART2_RX_PTE17
#undef UART2_TX_PTD3
#undef UART2_TX_PTE16

/* Signals specific to this part */
#define ADC0_DM1_PTE17 KINETIS_MUX('E',17,0)
#define ADC0_DM2_PTE19 KINETIS_MUX('E',19,0)
#define ADC0_DP1_PTE16 KINETIS_MUX('E',16,0)
#define ADC0_DP2_PTE18 KINETIS_MUX('E',18,0)
#define FTM0_CH0_PTD6 KINETIS_MUX('D',6,4)
#define FTM0_CH1_PTD7 KINETIS_MUX('D',7,4)
#define UART1_CTS_b_PTE18 KINETIS_MUX('E',18,3)
#define UART1_RTS_b_PTE19 KINETIS_MUX('E',19,3)
#define UART1_RX_PTE17 KINETIS_MUX('E',17,3)
#define UART1_TX_PTE16 KINETIS_MUX('E',16,3)

#endif /* _ZEPHYR_DTS_BINDING_MK02FN128VLH10_WRAPPER_ */
