/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK22FN256CAH12/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKV31F512VLH12-pinctrl.h with this part's differences applied
 * below (61 removed, 0 changed,
 * 19 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 71eb1e070a33e712
 */

#ifndef _ZEPHYR_DTS_BINDING_MK22FN256CAH12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK22FN256CAH12_WRAPPER_

#include "MKV31F512VLH12-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE17_PTE24
#undef ADC0_SE18_PTE25
#undef ADC0_SE4a_PTE16
#undef ADC0_SE5a_PTE17
#undef ADC0_SE6a_PTE18
#undef ADC0_SE7a_PTE19
#undef CLKOUT32K_PTE0
#undef CMP0_OUT_PTA1
#undef CMP1_OUT_PTA2
#undef EWM_IN_PTA0
#undef EWM_IN_PTB1
#undef EWM_IN_PTE25
#undef EWM_OUT_b_PTA3
#undef EWM_OUT_b_PTE24
#undef FTM0_CH0_PTE24
#undef FTM0_CH1_PTE25
#undef FTM0_FLT0_PTA19
#undef FTM0_FLT1_PTB2
#undef FTM0_FLT1_PTC0
#undef FTM0_FLT2_PTB1
#undef FTM0_FLT3_PTA4
#undef FTM0_FLT3_PTE16
#undef FTM1_CH0_PTA2
#undef FTM1_CH1_PTA1
#undef FTM2_FLT0_PTA3
#undef FTM2_QD_PHA_PTA1
#undef FTM2_QD_PHB_PTA2
#undef FTM3_CH0_PTD0
#undef FTM3_CH1_PTD1
#undef FTM3_CH2_PTD2
#undef FTM3_CH3_PTD3
#undef FTM3_CH4_PTC8
#undef FTM3_CH5_PTC9
#undef FTM3_CH6_PTC10
#undef FTM3_CH7_PTC11
#undef FTM_CLKIN0_PTE16
#undef FTM_CLKIN1_PTE17
#undef I2C0_SCL_PTC6
#undef I2C0_SCL_PTE19
#undef I2C0_SCL_PTE24
#undef I2C0_SDA_PTC7
#undef I2C0_SDA_PTE18
#undef I2C0_SDA_PTE25
#undef LPTMR0_ALT3_PTE17
#undef PTE16
#undef PTE17
#undef PTE18
#undef PTE19
#undef PTE24
#undef PTE25
#undef SPI0_PCS0_PTC0
#undef SPI0_PCS0_PTE16
#undef SPI0_SCK_PTE17
#undef SPI0_SIN_PTE19
#undef SPI0_SOUT_PTE18
#undef UART0_RX_PTB0
#undef UART0_TX_PTB1
#undef UART2_CTS_b_PTE18
#undef UART2_RTS_b_PTE19
#undef UART2_RX_PTE17
#undef UART2_TX_PTE16

/* Signals specific to this part */
#define I2S0_MCLK_PTC6 KINETIS_MUX('C',6,6)
#define I2S0_MCLK_PTC8 KINETIS_MUX('C',8,4)
#define I2S0_RXD0_PTC5 KINETIS_MUX('C',5,4)
#define I2S0_RX_BCLK_PTC6 KINETIS_MUX('C',6,4)
#define I2S0_RX_BCLK_PTC9 KINETIS_MUX('C',9,4)
#define I2S0_RX_FS_PTC10 KINETIS_MUX('C',10,4)
#define I2S0_RX_FS_PTC7 KINETIS_MUX('C',7,4)
#define I2S0_TXD0_PTA12 KINETIS_MUX('A',12,6)
#define I2S0_TXD0_PTC1 KINETIS_MUX('C',1,6)
#define I2S0_TX_BCLK_PTA5 KINETIS_MUX('A',5,6)
#define I2S0_TX_BCLK_PTB18 KINETIS_MUX('B',18,4)
#define I2S0_TX_BCLK_PTC3 KINETIS_MUX('C',3,6)
#define I2S0_TX_FS_PTA13 KINETIS_MUX('A',13,6)
#define I2S0_TX_FS_PTB19 KINETIS_MUX('B',19,4)
#define I2S0_TX_FS_PTC2 KINETIS_MUX('C',2,6)
#define RTC_CLKOUT_PTE0 KINETIS_MUX('E',0,7)
#define USB_CLKIN_PTA5 KINETIS_MUX('A',5,2)
#define USB_SOF_OUT_PTC0 KINETIS_MUX('C',0,4)
#define USB_SOF_OUT_PTC7 KINETIS_MUX('C',7,3)

#endif /* _ZEPHYR_DTS_BINDING_MK22FN256CAH12_WRAPPER_ */
