/*
 * NOTE: Autogenerated file by kinetis_cfg_utils.py
 * for MK22FX512VMD12/signal_configuration.xml
 *
 * Copyright 2023 Daniel DeGrasse
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MK22FX512VLQ12-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 29050f3dbe8c1de2
 */

#ifndef _ZEPHYR_DTS_BINDING_MK22FX512VMD12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK22FX512VMD12_WRAPPER_

#include "MK22FX512VLQ12-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK22FX512VMD12_WRAPPER_ */
