/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK22FN256VMP12/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MK22FN256CAH12-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: b0e18d214376f869
 */

#ifndef _ZEPHYR_DTS_BINDING_MK22FN256VMP12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK22FN256VMP12_WRAPPER_

#include "MK22FN256CAH12-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK22FN256VMP12_WRAPPER_ */
