/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK22FN128VMP10/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MK22FN128VLH10-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 8449222c0a3e84a1
 */

#ifndef _ZEPHYR_DTS_BINDING_MK22FN128VMP10_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK22FN128VMP10_WRAPPER_

#include "MK22FN128VLH10-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK22FN128VMP10_WRAPPER_ */
