/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MK22FN512VMP12/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MK22FN512VLH12-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: e5ec8e10de1d7557
 */

#ifndef _ZEPHYR_DTS_BINDING_MK22FN512VMP12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK22FN512VMP12_WRAPPER_

#include "MK22FN512VLH12-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK22FN512VMP12_WRAPPER_ */
