/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK24FN1M0VLQ12/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK64FX512VLQ12-pinctrl.h with this part's differences applied
 * below (36 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 05c4b096a0287829
 */

#ifndef _ZEPHYR_DTS_BINDING_MK24FN1M0VLQ12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK24FN1M0VLQ12_WRAPPER_

#include "MK64FX512VLQ12-pinctrl.h"

/* Signals not present on this part */
#undef ENET0_1588_TMR0_PTB2
#undef ENET0_1588_TMR0_PTC16
#undef ENET0_1588_TMR1_PTB3
#undef ENET0_1588_TMR1_PTC17
#undef ENET0_1588_TMR2_PTB4
#undef ENET0_1588_TMR2_PTC18
#undef ENET0_1588_TMR3_PTB5
#undef ENET0_1588_TMR3_PTC19
#undef ENET_1588_CLKIN_PTE26
#undef MII0_COL_PTA29
#undef MII0_CRS_PTA27
#undef MII0_MDC_PTB1
#undef MII0_MDIO_PTB0
#undef MII0_RXCLK_PTA11
#undef MII0_RXD0_PTA13
#undef MII0_RXD1_PTA12
#undef MII0_RXD2_PTA10
#undef MII0_RXD3_PTA9
#undef MII0_RXDV_PTA14
#undef MII0_RXER_PTA5
#undef MII0_TXCLK_PTA25
#undef MII0_TXD0_PTA16
#undef MII0_TXD1_PTA17
#undef MII0_TXD2_PTA24
#undef MII0_TXD3_PTA26
#undef MII0_TXEN_PTA15
#undef MII0_TXER_PTA28
#undef RMII0_CRS_DV_PTA14
#undef RMII0_MDC_PTB1
#undef RMII0_MDIO_PTB0
#undef RMII0_RXD0_PTA13
#undef RMII0_RXD1_PTA12
#undef RMII0_RXER_PTA5
#undef RMII0_TXD0_PTA16
#undef RMII0_TXD1_PTA17
#undef RMII0_TXEN_PTA15

#endif /* _ZEPHYR_DTS_BINDING_MK24FN1M0VLQ12_WRAPPER_ */
