/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK27FN2M0VMI15/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MK28FN2M0VMI15-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: bbc2b26d7386f233
 */

#ifndef _ZEPHYR_DTS_BINDING_MK27FN2M0VMI15_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK27FN2M0VMI15_WRAPPER_

#include "MK28FN2M0VMI15-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK27FN2M0VMI15_WRAPPER_ */
