/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK63FN1M0VMD12/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK64FX512VLQ12-pinctrl.h with this part's differences applied
 * below (18 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 05c4b096a0287829
 */

#ifndef _ZEPHYR_DTS_BINDING_MK63FN1M0VMD12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK63FN1M0VMD12_WRAPPER_

#include "MK64FX512VLQ12-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE17_PTE24
#undef ADC0_SE18_PTE25
#undef ENET_1588_CLKIN_PTE26
#undef EWM_IN_PTE25
#undef EWM_OUT_b_PTE24
#undef I2C0_SCL_PTE24
#undef I2C0_SDA_PTE25
#undef PTE24
#undef PTE25
#undef PTE26
#undef PTE27
#undef PTE28
#undef RTC_CLKOUT_PTE26
#undef UART4_CTS_b_PTE26
#undef UART4_RTS_b_PTE27
#undef UART4_RX_PTE25
#undef UART4_TX_PTE24
#undef USB_CLKIN_PTE26

#endif /* _ZEPHYR_DTS_BINDING_MK63FN1M0VMD12_WRAPPER_ */
