/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MK64FN1M0VLL12/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK64FX512VLQ12-pinctrl.h with this part's differences applied
 * below (110 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 05c4b096a0287829
 */

#ifndef _ZEPHYR_DTS_BINDING_MK64FN1M0VLL12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK64FN1M0VLL12_WRAPPER_

#include "MK64FX512VLQ12-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE10_PTA7
#undef ADC0_SE11_PTA8
#undef ADC1_SE10_PTB4
#undef ADC1_SE11_PTB5
#undef ADC1_SE12_PTB6
#undef ADC1_SE13_PTB7
#undef CLKOUT_PTA6
#undef ENET0_1588_TMR2_PTB4
#undef ENET0_1588_TMR3_PTB5
#undef ENET0_1588_TMR3_PTC19
#undef FTM0_CH3_PTA6
#undef FTM0_CH4_PTA7
#undef FTM1_CH0_PTA8
#undef FTM1_CH1_PTA9
#undef FTM1_FLT0_PTB4
#undef FTM1_QD_PHA_PTA8
#undef FTM1_QD_PHB_PTA9
#undef FTM2_CH0_PTA10
#undef FTM2_CH1_PTA11
#undef FTM2_FLT0_PTB5
#undef FTM2_QD_PHA_PTA10
#undef FTM2_QD_PHB_PTA11
#undef FTM3_CH2_PTE7
#undef FTM3_CH3_PTE8
#undef FTM3_CH4_PTE9
#undef FTM3_CH5_PTE10
#undef FTM3_CH6_PTE11
#undef FTM3_CH7_PTE12
#undef FTM3_FLT0_PTD12
#undef I2C0_SCL_PTD8
#undef I2C0_SDA_PTD9
#undef I2C2_SDA_PTA11
#undef I2S0_RXD0_PTE7
#undef I2S0_RXD1_PTE8
#undef I2S0_RX_BCLK_PTE9
#undef I2S0_RX_FS_PTE8
#undef I2S0_TXD0_PTE10
#undef I2S0_TXD1_PTE9
#undef I2S0_TX_BCLK_PTE12
#undef I2S0_TX_FS_PTE11
#undef MII0_COL_PTA29
#undef MII0_CRS_PTA27
#undef MII0_RXCLK_PTA11
#undef MII0_RXD2_PTA10
#undef MII0_RXD3_PTA9
#undef MII0_TXCLK_PTA25
#undef MII0_TXD2_PTA24
#undef MII0_TXD3_PTA26
#undef MII0_TXER_PTA28
#undef PTA10
#undef PTA11
#undef PTA24
#undef PTA25
#undef PTA26
#undef PTA27
#undef PTA28
#undef PTA29
#undef PTA6
#undef PTA7
#undef PTA8
#undef PTA9
#undef PTB4
#undef PTB5
#undef PTB6
#undef PTB7
#undef PTB8
#undef PTC19
#undef PTD10
#undef PTD11
#undef PTD12
#undef PTD13
#undef PTD14
#undef PTD15
#undef PTD8
#undef PTD9
#undef PTE10
#undef PTE11
#undef PTE12
#undef PTE27
#undef PTE28
#undef PTE7
#undef PTE8
#undef PTE9
#undef SDHC0_CLKIN_PTD11
#undef SDHC0_D4_PTD12
#undef SDHC0_D5_PTD13
#undef SDHC0_D6_PTD14
#undef SDHC0_D7_PTD15
#undef SPI2_PCS0_PTD11
#undef SPI2_PCS1_PTD15
#undef SPI2_SCK_PTD12
#undef SPI2_SIN_PTD14
#undef SPI2_SOUT_PTD13
#undef TRACE_CLKOUT_PTA6
#undef TRACE_D0_PTA10
#undef TRACE_D1_PTA9
#undef TRACE_D2_PTA8
#undef TRACE_D3_PTA7
#undef UART3_CTS_b_PTC19
#undef UART3_RTS_b_PTB8
#undef UART3_RTS_b_PTE7
#undef UART4_RTS_b_PTE27
#undef UART5_CTS_b_PTD11
#undef UART5_CTS_b_PTE10
#undef UART5_RTS_b_PTD10
#undef UART5_RTS_b_PTE11
#undef UART5_RX_PTD8
#undef UART5_RX_PTE9
#undef UART5_TX_PTD9
#undef UART5_TX_PTE8

#endif /* _ZEPHYR_DTS_BINDING_MK64FN1M0VLL12_WRAPPER_ */
