/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK64FX512VDC12/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK64FX512VLQ12-pinctrl.h with this part's differences applied
 * below (64 removed, 0 changed,
 * 10 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 05c4b096a0287829
 */

#ifndef _ZEPHYR_DTS_BINDING_MK64FX512VDC12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK64FX512VDC12_WRAPPER_

#include "MK64FX512VLQ12-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE10_PTA7
#undef ADC0_SE11_PTA8
#undef ADC1_SE10_PTB4
#undef ADC1_SE11_PTB5
#undef CLKOUT_PTA6
#undef ENET0_1588_TMR2_PTB4
#undef ENET0_1588_TMR3_PTB5
#undef FTM0_CH3_PTA6
#undef FTM0_CH4_PTA7
#undef FTM1_CH0_PTA8
#undef FTM1_CH1_PTA9
#undef FTM1_FLT0_PTB4
#undef FTM1_QD_PHA_PTA8
#undef FTM1_QD_PHB_PTA9
#undef FTM2_FLT0_PTB5
#undef FTM3_CH2_PTE7
#undef FTM3_CH3_PTE8
#undef FTM3_CH4_PTE9
#undef FTM3_CH5_PTE10
#undef FTM3_CH6_PTE11
#undef FTM3_CH7_PTE12
#undef I2S0_RXD0_PTE7
#undef I2S0_RXD1_PTE8
#undef I2S0_RX_BCLK_PTE9
#undef I2S0_RX_FS_PTE8
#undef I2S0_TXD0_PTE10
#undef I2S0_TXD1_PTE9
#undef I2S0_TX_BCLK_PTE12
#undef I2S0_TX_FS_PTE11
#undef MII0_CRS_PTA27
#undef MII0_RXD3_PTA9
#undef MII0_TXCLK_PTA25
#undef MII0_TXD2_PTA24
#undef MII0_TXD3_PTA26
#undef MII0_TXER_PTA28
#undef PTA24
#undef PTA25
#undef PTA26
#undef PTA27
#undef PTA28
#undef PTA6
#undef PTA7
#undef PTA8
#undef PTA9
#undef PTB4
#undef PTB5
#undef PTE10
#undef PTE11
#undef PTE12
#undef PTE27
#undef PTE28
#undef PTE7
#undef PTE8
#undef PTE9
#undef TRACE_CLKOUT_PTA6
#undef TRACE_D1_PTA9
#undef TRACE_D2_PTA8
#undef TRACE_D3_PTA7
#undef UART3_RTS_b_PTE7
#undef UART4_RTS_b_PTE27
#undef UART5_CTS_b_PTE10
#undef UART5_RTS_b_PTE11
#undef UART5_RX_PTE9
#undef UART5_TX_PTE8

/* Signals specific to this part */
#define FTM0_CH4_PTB12 KINETIS_MUX('B',12,4)
#define FTM0_CH5_PTB13 KINETIS_MUX('B',13,4)
#define FTM1_CH0_PTB12 KINETIS_MUX('B',12,3)
#define FTM1_CH1_PTB13 KINETIS_MUX('B',13,3)
#define FTM1_QD_PHA_PTB12 KINETIS_MUX('B',12,6)
#define FTM1_QD_PHB_PTB13 KINETIS_MUX('B',13,6)
#define PTB12 KINETIS_MUX('B',12,1)
#define PTB13 KINETIS_MUX('B',13,1)
#define UART3_CTS_b_PTB13 KINETIS_MUX('B',13,2)
#define UART3_RTS_b_PTB12 KINETIS_MUX('B',12,2)

#endif /* _ZEPHYR_DTS_BINDING_MK64FX512VDC12_WRAPPER_ */
