/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MK64FN1M0VLQ12/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK64FX512VLQ12-pinctrl.h with this part's differences applied
 * below (0 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 05c4b096a0287829
 */

#ifndef _ZEPHYR_DTS_BINDING_MK64FN1M0VLQ12_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK64FN1M0VLQ12_WRAPPER_

#include "MK64FX512VLQ12-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK64FN1M0VLQ12_WRAPPER_ */
