/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MK66FX1M0VMD18/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MK66FX1M0VLQ18-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: bdb46e0732c24d0f
 */

#ifndef _ZEPHYR_DTS_BINDING_MK66FX1M0VMD18_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK66FX1M0VMD18_WRAPPER_

#include "MK66FX1M0VLQ18-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MK66FX1M0VMD18_WRAPPER_ */
