/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MK82FN256CAx15/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MK82FN256VLQ15-pinctrl.h with this part's differences applied
 * below (75 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 77e791e77656b82e
 */

#ifndef _ZEPHYR_DTS_BINDING_MK82FN256CAX15_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MK82FN256CAX15_WRAPPER_

#include "MK82FN256VLQ15-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE10_PTA7
#undef ADC0_SE11_PTA8
#undef ADC0_SE4a_PTE16
#undef ADC0_SE5a_PTE17
#undef ADC0_SE6a_PTE18
#undef ADC0_SE7a_PTE19
#undef CLKOUT_PTA6
#undef EMVSIM0_CLK_PTA24
#undef EMVSIM0_IO_PTA25
#undef EMVSIM0_PD_PTA26
#undef EMVSIM0_RST_PTA27
#undef EMVSIM0_VCCEN_PTA28
#undef EMVSIM1_CLK_PTA6
#undef EMVSIM1_IO_PTA7
#undef EMVSIM1_PD_PTA8
#undef EMVSIM1_RST_PTA9
#undef FTM0_CH3_PTA6
#undef FTM0_CH4_PTA7
#undef FTM0_FLT3_PTE16
#undef FTM1_CH0_PTA8
#undef FTM1_CH1_PTA9
#undef FTM1_QD_PHA_PTA8
#undef FTM1_QD_PHB_PTA9
#undef FTM3_CH7_PTE12
#undef FTM_CLKIN0_PTE16
#undef FTM_CLKIN1_PTE17
#undef FXIO0_D2_PTE12
#undef FXIO0_D3_PTE13
#undef FXIO0_D4_PTE16
#undef FXIO0_D5_PTE17
#undef FXIO0_D6_PTE18
#undef FXIO0_D7_PTE19
#undef I2C0_SCL_PTE19
#undef I2C0_SDA_PTE18
#undef I2C2_SCL_PTA6
#undef I2C2_SDA_PTA7
#undef I2S0_TX_BCLK_PTE12
#undef LLWU_P19_PTE17
#undef LLWU_P20_PTE18
#undef LPTMR0_ALT3_PTE17
#undef LPTMR1_ALT3_PTE17
#undef LPUART2_CTS_b_PTE18
#undef LPUART2_RTS_b_PTE19
#undef LPUART2_RX_PTE13
#undef LPUART2_RX_PTE17
#undef LPUART2_TX_PTE12
#undef LPUART2_TX_PTE16
#undef PTA24
#undef PTA25
#undef PTA26
#undef PTA27
#undef PTA28
#undef PTA6
#undef PTA7
#undef PTA8
#undef PTA9
#undef PTE12
#undef PTE13
#undef PTE16
#undef PTE17
#undef PTE18
#undef PTE19
#undef QSPI0B_DQS_PTE12
#undef QSPI0B_SS1_B_PTE13
#undef SDHC0_CLKIN_PTE13
#undef SPI0_PCS0_PTE16
#undef SPI0_SCK_PTE17
#undef SPI0_SIN_PTE19
#undef SPI0_SOUT_PTE18
#undef TPM1_CH0_PTA8
#undef TPM1_CH1_PTA9
#undef TRACE_CLKOUT_PTA6
#undef TRACE_D1_PTA9
#undef TRACE_D2_PTA8
#undef TRACE_D3_PTA7

#endif /* _ZEPHYR_DTS_BINDING_MK82FN256CAX15_WRAPPER_ */
