/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MKE18F512VLH16/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKE18F512VLL16-pinctrl.h with this part's differences applied
 * below (115 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: f219a321f9d17b88
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE18F512VLH16_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE18F512VLH16_WRAPPER_

#include "MKE18F512VLL16-pinctrl.h"

/* Signals not present on this part */
#undef ACMP1_IN5_PTD9
#undef ACMP2_IN3_PTE14
#undef ADC1_SE12_PTA15
#undef ADC1_SE13_PTA16
#undef ADC1_SE14_PTB15
#undef ADC1_SE15_PTB16
#undef ADC1_SE9_PTB14
#undef ADC2_SE10_PTB9
#undef ADC2_SE11_PTB8
#undef ADC2_SE3_PTB17
#undef ADC2_SE8_PTB11
#undef ADC2_SE9_PTB10
#undef ADC2_SE9_PTB14
#undef BUSOUT_PTA14
#undef CLKOUT_PTD14
#undef EWM_IN_PTA14
#undef EWM_OUT_b_PTA17
#undef FTM0_CH2_PTB14
#undef FTM0_CH3_PTB15
#undef FTM0_CH4_PTB16
#undef FTM0_CH5_PTB17
#undef FTM0_CH6_PTA17
#undef FTM0_FLT0_PTA14
#undef FTM0_FLT1_PTE14
#undef FTM0_FLT2_PTD17
#undef FTM0_FLT3_PTE12
#undef FTM1_CH2_PTA15
#undef FTM1_CH3_PTA16
#undef FTM1_CH4_PTD8
#undef FTM1_CH5_PTD9
#undef FTM1_FLT0_PTA14
#undef FTM1_FLT3_PTA9
#undef FTM2_CH0_PTD10
#undef FTM2_CH1_PTD11
#undef FTM2_CH2_PTD12
#undef FTM2_CH4_PTD13
#undef FTM2_CH5_PTD14
#undef FTM2_CH6_PTC12
#undef FTM2_CH6_PTE15
#undef FTM2_CH7_PTC13
#undef FTM2_CH7_PTE16
#undef FTM2_FLT0_PTE13
#undef FTM2_FLT1_PTE14
#undef FTM2_FLT2_PTD8
#undef FTM2_FLT3_PTD9
#undef FTM2_QD_PHA_PTD11
#undef FTM2_QD_PHB_PTD10
#undef FTM3_CH0_PTB8
#undef FTM3_CH1_PTB9
#undef FTM3_CH2_PTB10
#undef FTM3_CH3_PTB11
#undef FTM3_CH4_PTC10
#undef FTM3_CH5_PTC11
#undef FTM3_CH6_PTC12
#undef FTM3_CH7_PTC13
#undef FTM3_FLT0_PTA17
#undef FTM3_FLT1_PTA14
#undef FTM3_FLT2_PTA9
#undef FTM3_FLT3_PTA8
#undef FXIO_D2_PTE15
#undef FXIO_D3_PTE16
#undef FXIO_D6_PTA8
#undef FXIO_D7_PTA9
#undef LPI2C0_HREQ_PTB11
#undef LPI2C0_SCLS_PTB9
#undef LPI2C0_SDAS_PTB10
#undef LPI2C1_HREQ_PTD12
#undef LPI2C1_SCL_PTD9
#undef LPI2C1_SDA_PTD8
#undef LPSPI0_PCS3_PTA15
#undef LPSPI1_PCS2_PTA16
#undef LPSPI1_PCS3_PTB17
#undef LPSPI1_SCK_PTB14
#undef LPSPI1_SIN_PTB15
#undef LPSPI1_SOUT_PTB16
#undef LPUART2_CTS_PTD11
#undef LPUART2_RTS_PTD12
#undef LPUART2_RX_PTD17
#undef LPUART2_TX_PTE12
#undef PTA14
#undef PTA15
#undef PTA16
#undef PTA17
#undef PTA8
#undef PTA9
#undef PTB10
#undef PTB11
#undef PTB14
#undef PTB15
#undef PTB16
#undef PTB17
#undef PTB8
#undef PTB9
#undef PTC10
#undef PTC11
#undef PTC12
#undef PTC13
#undef PTD10
#undef PTD11
#undef PTD12
#undef PTD13
#undef PTD14
#undef PTD17
#undef PTD8
#undef PTD9
#undef PTE12
#undef PTE13
#undef PTE14
#undef PTE15
#undef PTE16
#undef RTC_CLKOUT_PTD13
#undef TRGMUX_OUT6_PTE15
#undef TRGMUX_OUT6_PTE15_PTE15_PTE15_PTE15_PTE15_PTE15_PTE15_PTE15
#undef TRGMUX_OUT7_PTE16
#undef TRGMUX_OUT7_PTE16_PTE16_PTE16_PTE16_PTE16_PTE16_PTE16_PTE16

#endif /* _ZEPHYR_DTS_BINDING_MKE18F512VLH16_WRAPPER_ */
