/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKE15Z64VLD4/signal_configuration.xml
 *
 * Copyright 2025, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKE16Z64VLF4-pinctrl.h with this part's differences applied
 * below (17 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 0b4f3cd430edffa7
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE15Z64VLD4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE15Z64VLD4_WRAPPER_

#include "MKE16Z64VLF4-pinctrl.h"

/* Signals not present on this part */
#undef ACMP0_IN3_PTE8
#undef CAN0_RX_PTC6
#undef CAN0_RX_PTE4
#undef CAN0_TX_PTC7
#undef CAN0_TX_PTE5
#undef CLKOUT_PTE10
#undef LPSPI0_PCS2_PTE6
#undef LPTMR0_ALT1_PTE11
#undef LPUART1_RTS_PTE6
#undef PTE10
#undef PTE11
#undef PTE6
#undef PTE8
#undef PWT_IN1_PTE11
#undef TSI0_CH11_PTE8
#undef TSI0_CH2_PTE10
#undef TSI0_CH3_PTE11

#endif /* _ZEPHYR_DTS_BINDING_MKE15Z64VLD4_WRAPPER_ */
