/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKE14Z256VLL7/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKE18F512VLL16-pinctrl.h with this part's differences applied
 * below (97 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: f219a321f9d17b88
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE14Z256VLL7_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE14Z256VLL7_WRAPPER_

#include "MKE18F512VLL16-pinctrl.h"

/* Signals not present on this part */
#undef ACMP0_IN6_PTE6
#undef ACMP1_IN6_PTD4
#undef ACMP2_IN0_PTD16
#undef ACMP2_IN1_PTD15
#undef ACMP2_IN2_PTE9
#undef ACMP2_IN3_PTE14
#undef ACMP2_IN4_PTC15
#undef ACMP2_IN5_PTC14
#undef ACMP2_IN6_PTE7
#undef ACMP2_OUT_PTE3
#undef ADC1_SE12_PTA15
#undef ADC1_SE13_PTA16
#undef ADC1_SE14_PTB0
#undef ADC1_SE14_PTB15
#undef ADC1_SE15_PTB1
#undef ADC1_SE15_PTB16
#undef ADC2_SE0_PTD0
#undef ADC2_SE10_PTB9
#undef ADC2_SE11_PTB8
#undef ADC2_SE12_PTE10
#undef ADC2_SE13_PTE11
#undef ADC2_SE14_PTC8
#undef ADC2_SE15_PTC9
#undef ADC2_SE1_PTD1
#undef ADC2_SE2_PTE7
#undef ADC2_SE3_PTB17
#undef ADC2_SE4_PTA13
#undef ADC2_SE5_PTA12
#undef ADC2_SE6_PTE1
#undef ADC2_SE7_PTE0
#undef ADC2_SE8_PTB11
#undef ADC2_SE8_PTB13
#undef ADC2_SE9_PTB10
#undef ADC2_SE9_PTB14
#undef CAN0_RX_PTC2
#undef CAN0_RX_PTE4
#undef CAN0_TX_PTC3
#undef CAN0_TX_PTE5
#undef CAN1_RX_PTA12
#undef CAN1_RX_PTC6
#undef CAN1_TX_PTA13
#undef CAN1_TX_PTC7
#undef FTM1_CH4_PTA10
#undef FTM1_CH4_PTD8
#undef FTM1_CH5_PTA11
#undef FTM1_CH5_PTD9
#undef FTM1_CH6_PTA12
#undef FTM1_CH6_PTC0
#undef FTM1_CH7_PTA13
#undef FTM1_CH7_PTC1
#undef FTM1_FLT0_PTA14
#undef FTM1_FLT0_PTC8
#undef FTM1_FLT1_PTC9
#undef FTM1_FLT1_PTE1
#undef FTM2_CH4_PTD13
#undef FTM2_CH4_PTE10
#undef FTM2_CH5_PTD14
#undef FTM2_CH5_PTE11
#undef FTM2_CH6_PTC12
#undef FTM2_CH6_PTE15
#undef FTM2_CH7_PTC13
#undef FTM2_CH7_PTE16
#undef FTM2_FLT0
#undef FTM2_FLT0_PTE13
#undef FTM2_FLT0_PTE3
#undef FTM2_FLT1
#undef FTM2_FLT1_PTE14
#undef FTM3_CH0_PTA2
#undef FTM3_CH0_PTB8
#undef FTM3_CH1_PTA3
#undef FTM3_CH1_PTB9
#undef FTM3_CH2_PTB10
#undef FTM3_CH2_PTC6
#undef FTM3_CH3_PTB11
#undef FTM3_CH3_PTC7
#undef FTM3_CH4_PTC10
#undef FTM3_CH4_PTD2
#undef FTM3_CH5_PTC11
#undef FTM3_CH5_PTD3
#undef FTM3_CH6_PTC12
#undef FTM3_CH6_PTE2
#undef FTM3_CH7_PTC13
#undef FTM3_CH7_PTE6
#undef FTM3_FLT0_PTA17
#undef FTM3_FLT0_PTE7
#undef FTM3_FLT1_PTA14
#undef FTM3_FLT1_PTB13
#undef FTM3_FLT2_PTA9
#undef FTM3_FLT2_PTB12
#undef FTM3_FLT3_PTA8
#undef FTM3_FLT3_PTD4
#undef JTAG_TCLK_PTC4
#undef JTAG_TDI_PTC5
#undef JTAG_TDO_PTA10
#undef JTAG_TMS_PTA4
#undef JTAG_TRST_b_PTA5
#undef noetm_Trace_SWO_PTA10

#endif /* _ZEPHYR_DTS_BINDING_MKE14Z256VLL7_WRAPPER_ */
