/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKE14Z64VFP4/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKE16Z64VLF4-pinctrl.h with this part's differences applied
 * below (47 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 0b4f3cd430edffa7
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE14Z64VFP4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE14Z64VFP4_WRAPPER_

#include "MKE16Z64VLF4-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_SE2_PTA6
#undef CAN0_RX_PTC6
#undef CAN0_RX_PTE4
#undef CAN0_TX_PTC7
#undef CAN0_TX_PTE5
#undef FTM0_FLT0_PTE3
#undef FTM0_FLT1_PTA6
#undef FTM0_FLT3_PTD4
#undef LPSPI0_PCS2_PTE6
#undef LPSPI0_SOUT_PTE2
#undef LPTMR0_ALT3_PTE2
#undef LPUART1_CTS_PTA6
#undef LPUART1_CTS_PTE2
#undef LPUART1_RTS_PTE6
#undef LPUART2_RTS_PTE3
#undef PTA6
#undef PTD2
#undef PTD4
#undef PTE2
#undef PTE3
#undef PTE6
#undef PWT_IN3_PTE2
#undef TSI0_CH0_PTE5
#undef TSI0_CH10_PTD7
#undef TSI0_CH11_PTE8
#undef TSI0_CH12_PTC5
#undef TSI0_CH13_PTE0
#undef TSI0_CH14_PTE1
#undef TSI0_CH15_PTC6
#undef TSI0_CH16_PTC7
#undef TSI0_CH17_PTA0
#undef TSI0_CH18_PTA1
#undef TSI0_CH19_PTE2
#undef TSI0_CH1_PTE4
#undef TSI0_CH20_PTB2
#undef TSI0_CH21_PTB3
#undef TSI0_CH22_PTC0
#undef TSI0_CH23_PTC1
#undef TSI0_CH24_PTE3
#undef TSI0_CH2_PTE10
#undef TSI0_CH3_PTE11
#undef TSI0_CH4_PTD0
#undef TSI0_CH5_PTD1
#undef TSI0_CH6_PTD5
#undef TSI0_CH7_PTD6
#undef TSI0_CH8_PTB4
#undef TSI0_CH9_PTB5

#endif /* _ZEPHYR_DTS_BINDING_MKE14Z64VFP4_WRAPPER_ */
