/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKE14Z128VLL7/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MKE14Z256VLL7-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 1d50013dff7dd1c0
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE14Z128VLL7_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE14Z128VLL7_WRAPPER_

#include "MKE14Z256VLL7-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MKE14Z128VLL7_WRAPPER_ */
