/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MKE16F512VLL16/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKE18F512VLL16-pinctrl.h with this part's differences applied
 * below (4 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: f219a321f9d17b88
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE16F512VLL16_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE16F512VLL16_WRAPPER_

#include "MKE18F512VLL16-pinctrl.h"

/* Signals not present on this part */
#undef CAN1_RX_PTA12
#undef CAN1_RX_PTC6
#undef CAN1_TX_PTA13
#undef CAN1_TX_PTC7

#endif /* _ZEPHYR_DTS_BINDING_MKE16F512VLL16_WRAPPER_ */
