/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKE15Z128VLL7/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKE18F512VLL16-pinctrl.h with this part's differences applied
 * below (97 removed, 0 changed,
 * 25 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: f219a321f9d17b88
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE15Z128VLL7_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE15Z128VLL7_WRAPPER_

#include "MKE18F512VLL16-pinctrl.h"

/* Signals not present on this part */
#undef ACMP0_IN6_PTE6
#undef ACMP1_IN6_PTD4
#undef ACMP2_IN0_PTD16
#undef ACMP2_IN1_PTD15
#undef ACMP2_IN2_PTE9
#undef ACMP2_IN3_PTE14
#undef ACMP2_IN4_PTC15
#undef ACMP2_IN5_PTC14
#undef ACMP2_IN6_PTE7
#undef ACMP2_OUT_PTE3
#undef ADC1_SE12_PTA15
#undef ADC1_SE13_PTA16
#undef ADC1_SE14_PTB0
#undef ADC1_SE14_PTB15
#undef ADC1_SE15_PTB1
#undef ADC1_SE15_PTB16
#undef ADC2_SE0_PTD0
#undef ADC2_SE10_PTB9
#undef ADC2_SE11_PTB8
#undef ADC2_SE12_PTE10
#undef ADC2_SE13_PTE11
#undef ADC2_SE14_PTC8
#undef ADC2_SE15_PTC9
#undef ADC2_SE1_PTD1
#undef ADC2_SE2_PTE7
#undef ADC2_SE3_PTB17
#undef ADC2_SE4_PTA13
#undef ADC2_SE5_PTA12
#undef ADC2_SE6_PTE1
#undef ADC2_SE7_PTE0
#undef ADC2_SE8_PTB11
#undef ADC2_SE8_PTB13
#undef ADC2_SE9_PTB10
#undef ADC2_SE9_PTB14
#undef CAN0_RX_PTC2
#undef CAN0_RX_PTE4
#undef CAN0_TX_PTC3
#undef CAN0_TX_PTE5
#undef CAN1_RX_PTA12
#undef CAN1_RX_PTC6
#undef CAN1_TX_PTA13
#undef CAN1_TX_PTC7
#undef FTM1_CH4_PTA10
#undef FTM1_CH4_PTD8
#undef FTM1_CH5_PTA11
#undef FTM1_CH5_PTD9
#undef FTM1_CH6_PTA12
#undef FTM1_CH6_PTC0
#undef FTM1_CH7_PTA13
#undef FTM1_CH7_PTC1
#undef FTM1_FLT0_PTA14
#undef FTM1_FLT0_PTC8
#undef FTM1_FLT1_PTC9
#undef FTM1_FLT1_PTE1
#undef FTM2_CH4_PTD13
#undef FTM2_CH4_PTE10
#undef FTM2_CH5_PTD14
#undef FTM2_CH5_PTE11
#undef FTM2_CH6_PTC12
#undef FTM2_CH6_PTE15
#undef FTM2_CH7_PTC13
#undef FTM2_CH7_PTE16
#undef FTM2_FLT0
#undef FTM2_FLT0_PTE13
#undef FTM2_FLT0_PTE3
#undef FTM2_FLT1
#undef FTM2_FLT1_PTE14
#undef FTM3_CH0_PTA2
#undef FTM3_CH0_PTB8
#undef FTM3_CH1_PTA3
#undef FTM3_CH1_PTB9
#undef FTM3_CH2_PTB10
#undef FTM3_CH2_PTC6
#undef FTM3_CH3_PTB11
#undef FTM3_CH3_PTC7
#undef FTM3_CH4_PTC10
#undef FTM3_CH4_PTD2
#undef FTM3_CH5_PTC11
#undef FTM3_CH5_PTD3
#undef FTM3_CH6_PTC12
#undef FTM3_CH6_PTE2
#undef FTM3_CH7_PTC13
#undef FTM3_CH7_PTE6
#undef FTM3_FLT0_PTA17
#undef FTM3_FLT0_PTE7
#undef FTM3_FLT1_PTA14
#undef FTM3_FLT1_PTB13
#undef FTM3_FLT2_PTA9
#undef FTM3_FLT2_PTB12
#undef FTM3_FLT3_PTA8
#undef FTM3_FLT3_PTD4
#undef JTAG_TCLK_PTC4
#undef JTAG_TDI_PTC5
#undef JTAG_TDO_PTA10
#undef JTAG_TMS_PTA4
#undef JTAG_TRST_b_PTA5
#undef noetm_Trace_SWO_PTA10

/* Signals specific to this part */
#define TSI0_CH0_PTE5 KINETIS_MUX('E',5,0)
#define TSI0_CH10_PTD7 KINETIS_MUX('D',7,0)
#define TSI0_CH11_PTE8 KINETIS_MUX('E',8,0)
#define TSI0_CH12_PTC5 KINETIS_MUX('C',5,0)
#define TSI0_CH13_PTE0 KINETIS_MUX('E',0,0)
#define TSI0_CH14_PTE1 KINETIS_MUX('E',1,0)
#define TSI0_CH15_PTC6 KINETIS_MUX('C',6,0)
#define TSI0_CH16_PTC7 KINETIS_MUX('C',7,0)
#define TSI0_CH17_PTA0 KINETIS_MUX('A',0,0)
#define TSI0_CH18_PTA1 KINETIS_MUX('A',1,0)
#define TSI0_CH19_PTE2 KINETIS_MUX('E',2,0)
#define TSI0_CH1_PTE4 KINETIS_MUX('E',4,0)
#define TSI0_CH20_PTB2 KINETIS_MUX('B',2,0)
#define TSI0_CH21_PTB3 KINETIS_MUX('B',3,0)
#define TSI0_CH22_PTC0 KINETIS_MUX('C',0,0)
#define TSI0_CH23_PTC1 KINETIS_MUX('C',1,0)
#define TSI0_CH24_PTE3 KINETIS_MUX('E',3,0)
#define TSI0_CH2_PTE10 KINETIS_MUX('E',10,0)
#define TSI0_CH3_PTE11 KINETIS_MUX('E',11,0)
#define TSI0_CH4_PTD0 KINETIS_MUX('D',0,0)
#define TSI0_CH5_PTD1 KINETIS_MUX('D',1,0)
#define TSI0_CH6_PTD5 KINETIS_MUX('D',5,0)
#define TSI0_CH7_PTD6 KINETIS_MUX('D',6,0)
#define TSI0_CH8_PTB4 KINETIS_MUX('B',4,0)
#define TSI0_CH9_PTB5 KINETIS_MUX('B',5,0)

#endif /* _ZEPHYR_DTS_BINDING_MKE15Z128VLL7_WRAPPER_ */
