/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKE14Z32VLD4/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MKE14Z64VLD4-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 35e1f3b2d9a9e171
 */

#ifndef _ZEPHYR_DTS_BINDING_MKE14Z32VLD4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKE14Z32VLD4_WRAPPER_

#include "MKE14Z64VLD4-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MKE14Z32VLD4_WRAPPER_ */
