/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MKL25Z128VFM4/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on K32L2B31VFM0A-pinctrl.h with this part's differences applied
 * below (22 removed, 0 changed,
 * 21 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: ebe8df82d1a83013
 */

#ifndef _ZEPHYR_DTS_BINDING_MKL25Z128VFM4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKL25Z128VFM4_WRAPPER_

#include "K32L2B31VFM0A-pinctrl.h"

/* Signals not present on this part */
#undef CLKOUT32K_PTE0
#undef CLKOUT_PTC3
#undef FXIO0_D4_PTD4
#undef FXIO0_D5_PTD5
#undef FXIO0_D6_PTD6
#undef FXIO0_D7_PTD7
#undef LPTMR0_ALT1_PTE30
#undef LPUART0_RX_PTA1
#undef LPUART0_RX_PTD6
#undef LPUART0_TX_PTA2
#undef LPUART0_TX_PTD7
#undef LPUART1_RX_PTA18
#undef LPUART1_RX_PTC3
#undef LPUART1_TX_PTA19
#undef LPUART1_TX_PTC4
#undef LPUART1_TX_PTE0
#undef LPUART1_TX_PTE30
#undef SPI0_SS_PTC4
#undef SPI1_MISO_PTE0
#undef SPI1_SCK_PTC3
#undef SPI1_SS_PTD4
#undef USB_SOF_OUT_PTC7

/* Signals specific to this part */
#define CLKOUTa_PTC3 KINETIS_MUX('C',3,5)
#define SPI0_PCS0_PTC4 KINETIS_MUX('C',4,2)
#define SPI1_PCS0_PTD4 KINETIS_MUX('D',4,2)
#define TSI0_CH0_PTB0 KINETIS_MUX('B',0,0)
#define TSI0_CH14_PTC1 KINETIS_MUX('C',1,0)
#define TSI0_CH15_PTC2 KINETIS_MUX('C',2,0)
#define TSI0_CH1_PTA0 KINETIS_MUX('A',0,0)
#define TSI0_CH2_PTA1 KINETIS_MUX('A',1,0)
#define TSI0_CH3_PTA2 KINETIS_MUX('A',2,0)
#define TSI0_CH4_PTA3 KINETIS_MUX('A',3,0)
#define TSI0_CH5_PTA4 KINETIS_MUX('A',4,0)
#define TSI0_CH6_PTB1 KINETIS_MUX('B',1,0)
#define UART0_RX_PTA1 KINETIS_MUX('A',1,2)
#define UART0_RX_PTD6 KINETIS_MUX('D',6,3)
#define UART0_TX_PTA2 KINETIS_MUX('A',2,2)
#define UART0_TX_PTD7 KINETIS_MUX('D',7,3)
#define UART1_RX_PTA18 KINETIS_MUX('A',18,3)
#define UART1_RX_PTC3 KINETIS_MUX('C',3,3)
#define UART1_TX_PTA19 KINETIS_MUX('A',19,3)
#define UART1_TX_PTC4 KINETIS_MUX('C',4,3)
#define UART1_TX_PTE0 KINETIS_MUX('E',0,3)

#endif /* _ZEPHYR_DTS_BINDING_MKL25Z128VFM4_WRAPPER_ */
