/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKL27Z64VMP4/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Content deduplicated by dedup_pinctrl.py:
 * the pin mux data of this part is identical to MKL27Z64VLH4-pinctrl.h.
 * Do not edit; edit the canonical file instead.
 * target-hash: 43eb5f35a2fc1155
 */

#ifndef _ZEPHYR_DTS_BINDING_MKL27Z64VMP4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKL27Z64VMP4_WRAPPER_

#include "MKL27Z64VLH4-pinctrl.h"

#endif /* _ZEPHYR_DTS_BINDING_MKL27Z64VMP4_WRAPPER_ */
