/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKL27Z256VFM4/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on K32L2B31VFM0A-pinctrl.h with this part's differences applied
 * below (0 removed, 0 changed,
 * 8 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: ebe8df82d1a83013
 */

#ifndef _ZEPHYR_DTS_BINDING_MKL27Z256VFM4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKL27Z256VFM4_WRAPPER_

#include "K32L2B31VFM0A-pinctrl.h"

/* Signals specific to this part */
#define I2S0_MCLK_PTC4 KINETIS_MUX('C',4,5)
#define I2S0_MCLK_PTC6 KINETIS_MUX('C',6,6)
#define I2S0_RXD0_PTC5 KINETIS_MUX('C',5,4)
#define I2S0_RX_BCLK_PTC6 KINETIS_MUX('C',6,4)
#define I2S0_RX_FS_PTC7 KINETIS_MUX('C',7,4)
#define I2S0_TXD0_PTC1 KINETIS_MUX('C',1,6)
#define I2S0_TX_BCLK_PTC3 KINETIS_MUX('C',3,6)
#define I2S0_TX_FS_PTC2 KINETIS_MUX('C',2,6)

#endif /* _ZEPHYR_DTS_BINDING_MKL27Z256VFM4_WRAPPER_ */
