/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MKL25Z128VFT4/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKL25Z128VLK4-pinctrl.h with this part's differences applied
 * below (80 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 691c1d44b0485dac
 */

#ifndef _ZEPHYR_DTS_BINDING_MKL25Z128VFT4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKL25Z128VFT4_WRAPPER_

#include "MKL25Z128VLK4-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_DM3_PTE23
#undef ADC0_DP3_PTE22
#undef ADC0_SE3_PTE22
#undef ADC0_SE7a_PTE23
#undef CMP0_IN2_PTC8
#undef CMP0_IN3_PTC9
#undef CMP0_OUT_PTE0
#undef EXTRG_IN_PTB8
#undef I2C0_SCL_PTC8
#undef I2C0_SDA_PTC9
#undef I2C1_SCL_PTC10
#undef I2C1_SCL_PTE1
#undef I2C1_SDA_PTC11
#undef I2C1_SDA_PTE0
#undef PTA12
#undef PTA13
#undef PTA14
#undef PTA15
#undef PTA16
#undef PTA17
#undef PTA5
#undef PTB10
#undef PTB11
#undef PTB18
#undef PTB19
#undef PTB8
#undef PTB9
#undef PTC10
#undef PTC11
#undef PTC12
#undef PTC13
#undef PTC16
#undef PTC17
#undef PTC8
#undef PTC9
#undef PTE0
#undef PTE1
#undef PTE2
#undef PTE22
#undef PTE23
#undef PTE3
#undef PTE31
#undef PTE4
#undef PTE5
#undef RTC_CLKOUT_PTE0
#undef SPI0_MISO_PTA16
#undef SPI0_MISO_PTA17
#undef SPI0_MOSI_PTA16
#undef SPI0_MOSI_PTA17
#undef SPI0_PCS0_PTA14
#undef SPI0_SCK_PTA15
#undef SPI1_MISO_PTE1
#undef SPI1_MISO_PTE3
#undef SPI1_MOSI_PTE1
#undef SPI1_MOSI_PTE3
#undef SPI1_PCS0_PTB10
#undef SPI1_PCS0_PTE4
#undef SPI1_SCK_PTB11
#undef SPI1_SCK_PTE2
#undef TPM0_CH2_PTA5
#undef TPM0_CH4_PTC8
#undef TPM0_CH4_PTE31
#undef TPM0_CH5_PTC9
#undef TPM1_CH0_PTA12
#undef TPM1_CH1_PTA13
#undef TPM2_CH0_PTB18
#undef TPM2_CH0_PTE22
#undef TPM2_CH1_PTB19
#undef TPM2_CH1_PTE23
#undef TPM_CLKIN0_PTC12
#undef TPM_CLKIN1_PTC13
#undef TSI0_CH11_PTB18
#undef TSI0_CH12_PTB19
#undef UART0_RX_PTA15
#undef UART0_TX_PTA14
#undef UART1_RX_PTE1
#undef UART1_TX_PTE0
#undef UART2_RX_PTE23
#undef UART2_TX_PTE22
#undef USB_CLKIN_PTA5

#endif /* _ZEPHYR_DTS_BINDING_MKL25Z128VFT4_WRAPPER_ */
