/*
 * NOTE: Autogenerated file by gen_soc_headers.py
 * for MKL27Z64VLH4/signal_configuration.xml
 *
 * Copyright 2024, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on K32L2B31VLH0A-pinctrl.h with this part's differences applied
 * below (76 removed, 0 changed,
 * 29 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 67cd35d41ddbc29c
 */

#ifndef _ZEPHYR_DTS_BINDING_MKL27Z64VLH4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKL27Z64VLH4_WRAPPER_

#include "K32L2B31VLH0A-pinctrl.h"

/* Signals not present on this part */
#undef DAC0_OUT_PTE30
#undef LCD_P0_Fault_PTB0
#undef LCD_P0_PTB0
#undef LCD_P12_Fault_PTB16
#undef LCD_P12_PTB16
#undef LCD_P13_Fault_PTB17
#undef LCD_P13_PTB17
#undef LCD_P14_Fault_PTB18
#undef LCD_P14_PTB18
#undef LCD_P15_Fault_PTB19
#undef LCD_P15_PTB19
#undef LCD_P1_Fault_PTB1
#undef LCD_P1_PTB1
#undef LCD_P20_Fault_PTC0
#undef LCD_P20_PTC0
#undef LCD_P21_Fault_PTC1
#undef LCD_P21_PTC1
#undef LCD_P22_Fault_PTC2
#undef LCD_P22_PTC2
#undef LCD_P23_Fault_PTC3
#undef LCD_P23_PTC3
#undef LCD_P24_Fault_PTC4
#undef LCD_P24_PTC4
#undef LCD_P25_Fault_PTC5
#undef LCD_P25_PTC5
#undef LCD_P26_Fault_PTC6
#undef LCD_P26_PTC6
#undef LCD_P27_Fault_PTC7
#undef LCD_P27_PTC7
#undef LCD_P2_Fault_PTB2
#undef LCD_P2_PTB2
#undef LCD_P39_Fault_PTC23
#undef LCD_P39_PTC23
#undef LCD_P3_Fault_PTB3
#undef LCD_P3_PTB3
#undef LCD_P40_Fault_PTD0
#undef LCD_P40_PTD0
#undef LCD_P41_Fault_PTD1
#undef LCD_P41_PTD1
#undef LCD_P42_Fault_PTD2
#undef LCD_P42_PTD2
#undef LCD_P43_Fault_PTD3
#undef LCD_P43_PTD3
#undef LCD_P44_Fault_PTD4
#undef LCD_P44_PTD4
#undef LCD_P45_Fault_PTD5
#undef LCD_P45_PTD5
#undef LCD_P46_Fault_PTD6
#undef LCD_P46_PTD6
#undef LCD_P47_Fault_PTD7
#undef LCD_P47_PTD7
#undef LCD_P48_Fault_PTE0
#undef LCD_P48_PTE0
#undef LCD_P49_Fault_PTE1
#undef LCD_P49_PTE1
#undef LCD_P4_Fault_PTC20
#undef LCD_P4_PTC20
#undef LCD_P59_Fault_PTE20
#undef LCD_P59_PTE20
#undef LCD_P5_Fault_PTC21
#undef LCD_P5_PTC21
#undef LCD_P60_Fault_PTE21
#undef LCD_P60_PTE21
#undef LCD_P6_Fault_PTC22
#undef LCD_P6_PTC22
#undef PTC20
#undef PTC21
#undef PTC22
#undef PTC23
#undef SPI0_SS_PTC4
#undef SPI0_SS_PTD0
#undef SPI1_SS_PTD4
#undef VCAP1_PTC23
#undef VCAP2_PTC22
#undef VLL1_PTC21
#undef VLL2_PTC20

/* Signals specific to this part */
#define ADC0_DP1_PTE16 KINETIS_MUX('E',16,0)
#define ADC0_SE1_PTE16 KINETIS_MUX('E',16,0)
#define CMP0_IN2_PTC8 KINETIS_MUX('C',8,0)
#define CMP0_IN3_PTC9 KINETIS_MUX('C',9,0)
#define FXIO0_D0_PTE16 KINETIS_MUX('E',16,6)
#define I2C0_SCL_PTC8 KINETIS_MUX('C',8,2)
#define I2C0_SDA_PTC9 KINETIS_MUX('C',9,2)
#define I2C1_SCL_PTC10 KINETIS_MUX('C',10,2)
#define I2C1_SCL_PTD7 KINETIS_MUX('D',7,4)
#define I2C1_SDA_PTC11 KINETIS_MUX('C',11,2)
#define I2C1_SDA_PTD6 KINETIS_MUX('D',6,4)
#define PTC10 KINETIS_MUX('C',10,1)
#define PTC11 KINETIS_MUX('C',11,1)
#define PTC8 KINETIS_MUX('C',8,1)
#define PTC9 KINETIS_MUX('C',9,1)
#define PTE16 KINETIS_MUX('E',16,1)
#define SPI0_PCS0_PTC4 KINETIS_MUX('C',4,2)
#define SPI0_PCS0_PTD0 KINETIS_MUX('D',0,2)
#define SPI0_PCS0_PTE16 KINETIS_MUX('E',16,2)
#define SPI1_MISO_PTB0 KINETIS_MUX('B',0,5)
#define SPI1_MISO_PTB1 KINETIS_MUX('B',1,4)
#define SPI1_MOSI_PTB0 KINETIS_MUX('B',0,4)
#define SPI1_MOSI_PTB1 KINETIS_MUX('B',1,5)
#define SPI1_PCS0_PTC4 KINETIS_MUX('C',4,5)
#define SPI1_PCS0_PTD4 KINETIS_MUX('D',4,2)
#define TPM0_CH4_PTC8 KINETIS_MUX('C',8,3)
#define TPM0_CH5_PTC9 KINETIS_MUX('C',9,3)
#define TPM_CLKIN0_PTE16 KINETIS_MUX('E',16,4)
#define UART2_TX_PTE16 KINETIS_MUX('E',16,3)

#endif /* _ZEPHYR_DTS_BINDING_MKL27Z64VLH4_WRAPPER_ */
