/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MKV58F1M0VLL24/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKV58F1M0VLQ24-pinctrl.h with this part's differences applied
 * below (166 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 705621ce65ab19f3
 */

#ifndef _ZEPHYR_DTS_BINDING_MKV58F1M0VLL24_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKV58F1M0VLL24_WRAPPER_

#include "MKV58F1M0VLQ24-pinctrl.h"

/* Signals not present on this part */
#undef ADC0_DM3_PTE12
#undef ADC0_DP3_PTE11
#undef ADC0_SE11_PTE12
#undef ADC0_SE3_PTE11
#undef ADC0_SE6b_PTB4
#undef ADC0_SE7b_PTB5
#undef CAN2_RX_PTB7
#undef CAN2_RX_PTE28
#undef CAN2_TX_PTB6
#undef CAN2_TX_PTE27
#undef CLKOUT_PTA6
#undef ENET0_1588_TMR2_PTB4
#undef ENET0_1588_TMR3_PTB5
#undef ENET0_1588_TMR3_PTC19
#undef FLEXPWM0_A0_PTD14
#undef FLEXPWM0_A1_PTD12
#undef FLEXPWM0_A2_PTD10
#undef FLEXPWM0_A3_PTD8
#undef FLEXPWM0_B0_PTD15
#undef FLEXPWM0_B1_PTD13
#undef FLEXPWM0_B2_PTD11
#undef FLEXPWM0_B3_PTD9
#undef FLEXPWM1_A1_PTE7
#undef FLEXPWM1_A2_PTE9
#undef FLEXPWM1_A3_PTE11
#undef FLEXPWM1_B1_PTE8
#undef FLEXPWM1_B2_PTE10
#undef FLEXPWM1_B3_PTC19
#undef FLEXPWM1_B3_PTE12
#undef FLEXPWM1_X0_PTB4
#undef FLEXPWM1_X1_PTB5
#undef FLEXPWM1_X2_PTB6
#undef FLEXPWM1_X3_PTB7
#undef FTM0_CH3_PTA6
#undef FTM0_CH4_PTA7
#undef FTM1_CH0_PTA8
#undef FTM1_CH1_PTA9
#undef FTM1_FLT0_PTB4
#undef FTM2_CH0_PTA10
#undef FTM2_CH0_PTE22
#undef FTM2_CH1_PTA11
#undef FTM2_CH1_PTE23
#undef FTM2_FLT0_PTB5
#undef FTM2_QD_PHA_PTA10
#undef FTM2_QD_PHA_PTE22
#undef FTM2_QD_PHB_PTA11
#undef FTM2_QD_PHB_PTE23
#undef FTM3_CH2_PTE7
#undef FTM3_CH3_PTE8
#undef FTM3_CH4_PTE9
#undef FTM3_CH5_PTE10
#undef FTM3_CH6_PTE11
#undef FTM3_CH7_PTE12
#undef FTM3_FLT0
#undef FTM3_FLT0_PTD12
#undef HSADC1A_CH12_PTB6
#undef HSADC1A_CH13_PTB7
#undef HSADC1A_CH6_PTE11
#undef HSADC1B_CH6_PTE12
#undef HSADC1B_CH8_PTA7
#undef HSADC1B_CH9_PTA8
#undef I2C0_SDA_PTA11
#undef I2C1_SCL_PTD8
#undef I2C1_SDA_PTD9
#undef LLWU_P17_PTE9
#undef LLWU_P18_PTE10
#undef LLWU_P22_PTA10
#undef LLWU_P23_PTA11
#undef LLWU_P24_PTD8
#undef LLWU_P25_PTD11
#undef MII0_COL_PTA29
#undef MII0_CRS_PTA27
#undef MII0_MDC_PTA8
#undef MII0_MDIO_PTA7
#undef MII0_RXCLK_PTA11
#undef MII0_RXD2_PTA10
#undef MII0_RXD3_PTA9
#undef MII0_TXCLK_PTA25
#undef MII0_TXD2_PTA24
#undef MII0_TXD3_PTA26
#undef MII0_TXER_PTA28
#undef PTA10
#undef PTA11
#undef PTA24
#undef PTA25
#undef PTA26
#undef PTA27
#undef PTA28
#undef PTA29
#undef PTA6
#undef PTA7
#undef PTA8
#undef PTA9
#undef PTB4
#undef PTB5
#undef PTB6
#undef PTB7
#undef PTB8
#undef PTC19
#undef PTD10
#undef PTD11
#undef PTD12
#undef PTD13
#undef PTD14
#undef PTD15
#undef PTD8
#undef PTD9
#undef PTE10
#undef PTE11
#undef PTE12
#undef PTE13
#undef PTE22
#undef PTE23
#undef PTE27
#undef PTE28
#undef PTE7
#undef PTE8
#undef PTE9
#undef RMII0_MDC_PTA8
#undef RMII0_MDIO_PTA7
#undef SPI2_PCS0_PTD11
#undef SPI2_PCS1_PTD15
#undef SPI2_SCK_PTD12
#undef SPI2_SIN_PTD14
#undef SPI2_SOUT_PTD13
#undef TRACE_CLKOUT_PTA6
#undef TRACE_D0_PTA10
#undef TRACE_D1_PTA9
#undef TRACE_D2_PTA8
#undef TRACE_D3_PTA7
#undef UART3_CTS_b_PTC19
#undef UART3_RTS_b_PTB8
#undef UART3_RTS_b_PTE7
#undef UART4_RTS_b_PTE27
#undef UART5_CTS_b_PTD11
#undef UART5_CTS_b_PTE10
#undef UART5_RTS_b_PTD10
#undef UART5_RTS_b_PTE11
#undef UART5_RX_PTD8
#undef UART5_RX_PTE9
#undef UART5_TX_PTD9
#undef UART5_TX_PTE8
#undef XB_IN11_PTD14
#undef XB_IN11_PTD14_PTD14
#undef XB_IN11_PTD14_PTD14_PTD14_PTD14
#undef XB_IN2_PTE22
#undef XB_IN2_PTE22_PTE22
#undef XB_IN2_PTE22_PTE22_PTE22_PTE22
#undef XB_IN3_PTE23
#undef XB_IN3_PTE23_PTE23
#undef XB_IN3_PTE23_PTE23_PTE23_PTE23
#undef XB_IN4_PTA24
#undef XB_IN4_PTA24_PTA24
#undef XB_IN4_PTA24_PTA24_PTA24_PTA24
#undef XB_IN5_PTA25
#undef XB_IN5_PTA25_PTA25
#undef XB_IN5_PTA25_PTA25_PTA25_PTA25
#undef XB_IN5_PTD12
#undef XB_IN5_PTD12_PTD12
#undef XB_IN5_PTD12_PTD12_PTD12_PTD12
#undef XB_IN7_PTD13
#undef XB_IN7_PTD13_PTD13
#undef XB_IN7_PTD13_PTD13_PTD13_PTD13
#undef XB_OUT11_PTD14
#undef XB_OUT5_PTD12
#undef XB_OUT7_PTD13

#endif /* _ZEPHYR_DTS_BINDING_MKV58F1M0VLL24_WRAPPER_ */
