/*
 * NOTE: Autogenerated file by kinetis_signal2dts.py
 *       for MKW41Z512VHT4/signal_configuration.xml
 *
 * Copyright (c) 2022, NXP
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Delta-deduplicated by dedup_pinctrl.py:
 * based on MKW41Z512CAT4-pinctrl.h with this part's differences applied
 * below (6 removed, 0 changed,
 * 0 added). Regenerate with dedup_pinctrl.py;
 * do not edit by hand.
 * target-hash: 722f1503f1573fea
 */

#ifndef _ZEPHYR_DTS_BINDING_MKW41Z512VHT4_WRAPPER_
#define _ZEPHYR_DTS_BINDING_MKW41Z512VHT4_WRAPPER_

#include "MKW41Z512CAT4-pinctrl.h"

/* Signals not present on this part */
#undef ANT_A_PTC0
#undef I2C0_SCL_PTC0
#undef LLWU_P9_PTC0
#undef PTC0
#undef TPM0_CH1_PTC0
#undef UART0_CTS_b_PTC0

#endif /* _ZEPHYR_DTS_BINDING_MKW41Z512VHT4_WRAPPER_ */
