/*
 * Copyright 2019-2022 NXP
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef UWBIOTVER_STR_VERSION_INFO_H_INCLUDED
#define UWBIOTVER_STR_VERSION_INFO_H_INCLUDED

/* clang-format off */
#define UWBIOTVER_STR_PROD_NAME          "UWBIOT"
#define UWBIOTVER_STR_VER_STRING_NUM     "v06.00.00"
#define UWBIOTVER_STR_PROD_NAME_VER_FULL "UWBIOT_v06.00.00"
#define UWBIOTVER_STR_VER_MAJOR          (6u)
#define UWBIOTVER_STR_VER_MINOR          (00u)
#define UWBIOTVER_STR_VER_DEV            (00u)

/* v06.00 = 60000u */
#define UWBIOTVER_STR_VER_MAJOR_MINOR ( 0         \
    + (UWBIOTVER_STR_VER_MAJOR * 10000u)          \
    + (UWBIOTVER_STR_VER_MINOR))

/* v06.00.00 = 600000000ULL */
#define UWBIOTVER_STR_VER_MAJOR_MINOR_DEV ( 0          \
    + (UWBIOTVER_STR_VER_MAJOR * 10000ULL*10000ULL)    \
    + (UWBIOTVER_STR_VER_MINOR * 10000ULL)             \
    + (UWBIOTVER_STR_VER_DEV))

/* clang-format on */

/* Version Information:
 * Generated by:
 *     version_info.py (v2022.03.22_00)
 *
 * Do not edit this file. Update:
 *     ../version_info.txt instead.
 */

#endif /* UWBIOTVER_STR_VERSION_INFO_H_INCLUDED */
